### ISSUE TITLE
gc-ttl dose not work

### ISSUE THREAD

**Issue by mysteryHJJ** [argoproj/argo#1004]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**: I submit the gcc-ttl.yaml , but after the workflow finished, it did not delete the workflow and pods

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version: v2.2.0

**Comment by ywskycn** [comment]
Same to me. After checking the workflow-controller log, it shows 
`E0921 18:21:51.030059       1 ttlcontroller.go:124] error deleting 'default/gc-ttl-5mgg4': workflows.argoproj.io "gc-ttl-5mgg4" is forbidden: User "system:serviceaccount:argo:argo" cannot delete workflows.argoproj.io in the namespace "default"`.

@jessesuen so here we need to do another rolebinding?

**Comment by jessesuen** [comment]
Oops, yes the role needs to be expanded to perform delete:
```
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete # <<<< this needs to be added
```
