### ISSUE TITLE
Logging does not work after pod completes

### ISSUE THREAD

**Issue by strin** [argoproj/argo#1005]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report.

**What happened**:

We are running argo on Google Kubernetes Engine, with autoscaling enabled. Argo launched the container successfully, but after it completes the node gets deleted by autoscaler and the completed pod is no longer available.

**What you expected to happen**:

In Argo UI clicking on logs should reveal the container logs

![image](https://user-images.githubusercontent.com/2183232/45600418-6d1dc500-b9ca-11e8-8374-2c5865688218.png)

**How to reproduce it (as minimally and precisely as possible)**:

Launch a job on GKE with the following config enabled.

```
        resources:
          limits:
            nvidia.com/gpu: 1

```

**Anything else we need to know?**:

**Environment**:
- Argo version: v2.2.0
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```
```
clientVersion:
  buildDate: 2017-11-09T07:26:41Z
  compiler: gc
  gitCommit: f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd
  gitTreeState: clean
  gitVersion: v1.8.3
  goVersion: go1.9.2
  major: "1"
  minor: "8"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-08-02T23:42:40Z
  compiler: gc
  gitCommit: 9b635efce81582e1da13b35a7aa539c0ccb32987
  gitTreeState: clean
  gitVersion: v1.9.7-gke.5
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64

```
