### ISSUE TITLE
unknown field "artifactRepository" in io.k8s.api.core.v1.ConfigMap

### ISSUE THREAD

**Issue by jiuchongxiao** [argoproj/argo#1032]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
when add cepth to argo,display error message unknown field "artifactRepository" in io.k8s.api.core.v1.ConfigMap. and the method to add cepth to argo as below:
kubectl edit configmap workflow-controller-configmap -n ci
artifactRepository:
  s3:
  bucket: argo
  keyPrefix: prefix/in/bucket #optional
  endpoint: ceph-s3-front.cicd:7480
  insecure: true
  accessKeySecret:
    name: FUF5IS1XM27U81GT1J6B
    key: iJMRLzEqurCBthP7Tqeddd94eibvefaRqhfBTOdw
**What you expected to happen**:
i expected edit configmap success.
**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Argo version:

```
[root@node128 nexus]# argo version
argo: v2.2.0
  BuildDate: 2018-08-30T08:52:05Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
[root@node128 nexus]# kubectl version -o yaml
clientVersion:
  buildDate: 2018-08-07T23:17:28Z
  compiler: gc
  gitCommit: bb9ffb1654d4a729bb4cec18ff088eacc153c239
  gitTreeState: clean
  gitVersion: v1.11.2
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-09-09T17:53:03Z
  compiler: gc
  gitCommit: a4529464e4629c21224b3d52edfe0ea91b072862
  gitTreeState: clean
  gitVersion: v1.11.3
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64

```

**Other debugging information (if applicable)**:

```
- workflow-controller logs:
```
[root@node128 nexus]# kubectl logs -n ci $(kubectl get pods -l app=workflow-controller -n ci -o name)
time="2018-10-09T10:57:43Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\nnamespace: ci\n"
time="2018-10-09T10:57:43Z" level=info msg="Workflow Controller (version: v2.2.0) starting"
time="2018-10-09T10:57:43Z" level=info msg="Workers: workflow: 8, pod: 8"
time="2018-10-09T10:57:43Z" level=info msg="Watch Workflow controller config map updates"
time="2018-10-09T10:57:43Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2018-10-09T10:57:43Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2018-10-09T10:57:43Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\nnamespace: ci\n"
time="2018-10-09T10:57:43Z" level=info msg="Started workflow TTL worker"
time="2018-10-09T11:02:43Z" level=info msg="Alloc=3030 TotalAlloc=10794 Sys=10342 NumGC=7 Goroutines=62"
W1009 11:03:15.867684       1 reflector.go:341] github.com/argoproj/argo/workflow/controller/config.go:157: watch of *v1.ConfigMap ended with: too old resource version: 14221 (14494)
time="2018-10-09T11:07:43Z" level=info msg="Alloc=3039 TotalAlloc=10945 Sys=10342 NumGC=9 Goroutines=62"
W1009 11:10:50.884878       1 reflector.go:341] github.com/argoproj/argo/workflow/controller/config.go:157: watch of *v1.ConfigMap ended with: too old resource version: 14895 (15401)
time="2018-10-09T11:12:43Z" level=info msg="Alloc=3040 TotalAlloc=11031 Sys=10342 NumGC=12 Goroutines=62"
time="2018-10-09T11:17:43Z" level=info msg="Alloc=3060 TotalAlloc=11087 Sys=10342 NumGC=14 Goroutines=62"
W1009 11:19:43.902158       1 reflector.go:341] github.com/argoproj/argo/workflow/controller/config.go:157: watch of *v1.ConfigMap ended with: too old resource version: 15799 (16462)
time="2018-10-09T11:22:43Z" level=info msg="Alloc=3079 TotalAlloc=11208 Sys=10342 NumGC=17 Goroutines=62"
```

**Comment by alexmt** [comment]
The `artifactRepository` field supposed to be specified inside `config` field. E.g.

```
apiVersion: v1
data:
  config: |
    artifactRepository:
      ...
```
Error message is correct, ConfigMap does not have artifactRepository field
