### ISSUE TITLE
Workflow executor panic: workflows.argoproj.io/template workflows.argoproj.io/template not found in annotation file

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#1033]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

**What happened**:

Executor fails to following error:

```
time="2018-10-03T17:30:51Z" level=info msg="Creating a docker executor"
panic: Key workflows.argoproj.io/template not found in annotation file: /argo/podmetadata/annotations

goroutine 1 [running]:
github.com/argoproj/argo/cmd/argoexec/commands.initExecutor(0x12)
    /root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/root.go:94 +0x6ca
github.com/argoproj/argo/cmd/argoexec/commands.loadArtifacts(0x0, 0x0)
    /root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/init.go:25 +0x34
github.com/argoproj/argo/cmd/argoexec/commands.glob..func1(0x1ca0980, 0x1cc9c60, 0x0, 0x0)
    /root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/init.go:17 +0x22
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute(0x1ca0980, 0x1cc9c60, 0x0, 0x0, 0x1ca0980, 0x1cc9c60)
    /root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ca0e40, 0x10d6fd6, 0x138bcbb, 0xc420601f78)
    /root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute(0x1ca0e40, 0xc4203de4a0, 0xc4203b9350)
    /root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
    /root/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:15 +0x2d
```

**What you expected to happen**:

Workflow should be executed.

**Environment**:
- Argo version: v2.2.0

**Comment by mecampbellsoup** [comment]
Hi @alexmt I'm experiencing this issue in my local Argo installation (not production but very annoying to my dev workflow)...

```
(⎈ tenant-matt-user-tenant-matt-tenant-cluster.chi.atlanticcrypto.com:tenant-matt)➜  concierge-frontend git:(mc/fix-job-outputs-fetching) ✗ k logs analyze-blender-1606762257-168432976  -c init
time="2020-11-30T18:51:00.598Z" level=info msg="Starting Workflow Executor" version=v2.11.7
panic: Key workflows.argoproj.io/template not found in annotation file: /argo/podmetadata/annotations

goroutine 1 [running]:
github.com/argoproj/argo/cmd/argoexec/commands.checkErr(0x2178be0, 0xc0007e8630)
        /go/src/github.com/argoproj/argo/cmd/argoexec/commands/root.go:116 +0xee
```

Here are my k8s manifests related to Argo:

```
(⎈ tenant-admin@tenant-cluster:tenant-marcin)➜  concierge-frontend git:(mc/fix-job-outputs-fetching) ✗ k describe configmaps workflow-controller-configmap -n tenant-matt
Name:         workflow-controller-configmap
Namespace:    tenant-matt
Labels:       <none>
Annotations:  <none>

Data
====
config:
----
containerRuntimeExecutor: docker
featureFlags:
  resourcesDuration: true
metricsConfig:
  disableLegacy: true
  enabled: true
  path: /metrics
  port: 8080

Events:  <none>
```

```
(⎈ tenant-admin@tenant-cluster:tenant-marcin)➜  concierge-frontend git:(mc/fix-job-outputs-fetching) ✗ k get deployments.apps argo-server -n tenant-matt -o yaml | k neat
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: argo-server
  namespace: tenant-matt
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: argo-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.coreweave.cloud/class
                operator: In
                values:
                - control-plane
      containers:
      - args:
        - server
        - --namespaced
        image: argoproj/argocli:v2.11.7
        imagePullPolicy: IfNotPresent
        name: argo-server
        ports:
        - containerPort: 2746
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 2746
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: argo-server
      serviceAccountName: argo-server
      terminationGracePeriodSeconds: 30
```

```
(⎈ tenant-admin@tenant-cluster:tenant-marcin)➜  concierge-frontend git:(mc/fix-job-outputs-fetching) ✗ k get svc argo-server -n tenant-matt -o yaml | k neat
apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: tenant-matt
spec:
  clusterIP: 10.135.192.100
  ports:
  - name: api
    port: 2746
  selector:
    app: argo-server
```
