### ISSUE TITLE
Daemon pods are not reaped correctly

### ISSUE THREAD

**Issue by gaigepr** [argoproj/argo#1040]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:

When I run workflows with a daemon pod with `daemon: true`, this pod is not always reaped when the workflows enters a terminal state. 

**What you expected to happen**:

I would expect that when a workflow terminates, no matter the state, that all pods would be reaped. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a workflow with the following template:
```
  - name: couchdb
    daemon: true
    container:
      image: couchdb:2.2
      readinessProbe:
        httpGet:
          path: /
          port: 5984
        initialDelaySeconds: 2
        timeoutSeconds: 1
```

I am happy to provide more in the future, I think the bug is traceable to this function:

https://github.com/argoproj/argo/blob/3b52b26190163d1f72f3aef1a39f9f291378dafb/workflow/controller/exec_control.go#L67-L90

**Anything else we need to know?**:
I am still debugging this actively and am unsure if the end state changes whether pods are reaped or not. 

**Environment**:
```
$ argo version ;
argo: v2.2.0
  BuildDate: 2018-08-30T08:51:40Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```

- Kubernetes version : 1.10.7
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-08-20T10:09:03Z
  compiler: gc
  gitCommit: 0c38c362511b20a098d7cd855f1314dad92c2780
  gitTreeState: clean
  gitVersion: v1.10.7
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-10-02T17:32:01Z
  compiler: gc
  gitCommit: 06898a4d0f2b96f82b43d9e59fa2825bd3d616a2
  gitTreeState: clean
  gitVersion: v1.10.7-gke.6
  goVersion: go1.9.3b4
  major: "1"
  minor: 10+
  platform: linux/amd64
```
