### ISSUE TITLE
Minio - Default Artifact does not work

### ISSUE THREAD

**Issue by bappr** [argoproj/argo#1056]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
When setting up minio as a default artifact, it does not work.
No error with accessing the same minio as a non default artifact.

**What you expected to happen**:
Should work...

**How to reproduce it (as minimally and precisely as possible)**:
Require a minio cluster to be up and running.

##### Non default artifact -> works
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-s3-
spec:
  entrypoint: whalesay
  serviceAccountName: argo-build
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: message
        path: /tmp
        s3:
          endpoint: minio-dev:9000
          bucket: builds
          insecure: true
          key: hello_world.txt.tgz
          accessKeySecret:
            name: minio-credentials
            key: accessKey
          secretKeySecret:
            name: minio-credentials
            key: secretKey
```

##### Default artifact -> does not work
Add artifactRepo in `workflow-controller-configmap` configmap.
```
data:
  config: |
    artifactRepository:
      s3:
        bucket: builds
        endpoint: minio-dev:9000
        insecure: true
        accessKeySecret:
          name: minio-credentials
          key: accessKey
        secretKeySecret:
          name: minio-credentials
          key: secretKey
```
Run the workflow
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-s3-
spec:
  entrypoint: whalesay
  serviceAccountName: argo-build
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: message
        path: /tmp
        s3:
          key: hello_world.txt.tgz
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-27T22:29:25Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-08-16T21:33:47Z
  compiler: gc
  gitCommit: 9b635efce81582e1da13b35a7aa539c0ccb32987
  gitTreeState: clean
  gitVersion: v1.9.7-gke.6
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by RXminuS** [comment]
We've run into the same problem, it still seems to exist on the Master branch. I think adding to this problem is that errors aren't fully logged. Maybe this can be change here? https://github.com/argoproj/argo/blob/eaaad7d47257302f203bab24bce1b7d479453351/workflow/artifacts/s3/s3.go#L91

**Comment by sarabala1979** [comment]
This is a workflow configuration issue. if the workflow has an archive location like (s3/hdfs/etc..). Controller will not apply the common artifact repository config which as per the design and expected behavior.

if you remove the s3 on the artifacts, the workflow will work.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-s3-
spec:
  entrypoint: whalesay
  serviceAccountName: argo-build
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: message
        path: /tmp
```
