### ISSUE TITLE
Invalid conditional statement causes panic of workflow-controller

### ISSUE THREAD

**Issue by WeiTang114** [argoproj/argo#1057]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: 
Invalid conditional statement causes panic of workflow-controller.

**What you expected to happen**: 
It returns error message about the invalid statement.

**How to reproduce it (as minimally and precisely as possible)**:

I modified `example/conditionals.yaml` by changing the `when` statement of the `heads` step.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-
spec:
  entrypoint: coinflip
  templates:
  - name: coinflip
    steps:
    # flip a coin
    - - name: flip-coin
        template: flip-coin
    # evaluate the result in parallel
    - - name: heads
        template: heads                 #invoke heads template if "heads"

        # ** note that I add "a - " to make this statement invalid **
        when: "a - {{steps.flip-coin.outputs.result}} != ''"

      - name: tails
        template: tails                 #invoke tails template if "tails"
        when: "{{steps.flip-coin.outputs.result}} == tails"

  # Return heads or tails based on a random number
  - name: flip-coin
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)

  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]

  - name: tails
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was tails\""]
```

The below is the log of workflow-controller. 

The first line is added by me to see what happened. It seems the `shouldExecute()` function returns an error that says this statement is invalid. After that, another error occurs in `markNodeError()` because it tries to mark a non-existing node with the error.

```
time="2018-10-24T08:43:32Z" level=error msg="shouldExecute a - heads != '', proceed: false, error: Failed to evaluate 'when' expresion 'a - heads != ''': Value 'a' cannot be used with the modifier '-', it
 is not a number" namespace=default workflow=coinflip-znqp4

time="2018-10-24T08:43:32Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=coinflip-znqp4
time="2018-10-24T08:43:32Z" level=info msg="Updated message  -> node coinflip-znqp4[1].heads uninitialized" namespace=default workflow=coinflip-znqp4
time="2018-10-24T08:43:32Z" level=info msg="Marking workflow completed" namespace=default workflow=coinflip-znqp4
time="2018-10-24T08:43:32Z" level=error msg="Recovered from panic: node coinflip-znqp4[1].heads uninitialized\ngoroutine 83 [running]:\nruntime/debug.Stack(0xc4253c8960, 0x1249690, 0x5)\n\t/usr/local/go/s
rc/runtime/debug/stack.go:24 +0xa7\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate.func1(0xc4253c8960)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:114
+0xb5\npanic(0x1092e80, 0xc423f23c80)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markNodePhase(0xc4253c8960, 0xc422a616a0, 0x17, 0x124
9690, 0x5, 0xc4251b5ac8, 0x1, 0x1, 0x0)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1092 +0x8e5\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markNodeError(0
xc4253c8960, 0xc422a616a0, 0x17, 0x1345220, 0xc423f30240, 0x3)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1117 +0xaa\ngithub.com/argoproj/argo/workflow/controller.(*wfOperati
onCtx).executeStepGroup(0xc4253c8960, 0xc4208ebb00, 0x2, 0x4, 0xc422a611e0, 0x11, 0xc4251b67d8, 0xc422ce9c50)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/steps.go:179 +0x152f\ngithub.com/
argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc4253c8960, 0xc422ce9970, 0xe, 0xc4262857c0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/steps.go:73 +0xa
69\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc4253c8960, 0xc422ce99e0, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc422ce9970, ...)\n\t/root/go/src/github.com/argoproj/arg
o/workflow/controller/operator.go:965 +0xd84\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc4253c8960)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:
155 +0x372\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc42013af00, 0xc420424d00)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:235 +0
x435\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc42013af00)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:191 +0x2b\ngithub.com/argoproj/a
rgo/workflow/controller.(*WorkflowController).(github.com/argoproj/argo/workflow/controller.runWorker)-fm()\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:156 +0x2a\ngithub.com
/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4207f3dd0)\n\t/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54\ngithub.com/argo
proj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4207f3dd0, 0x3b9aca00, 0x0, 0x1, 0xc4200964e0)\n\t/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:1
34 +0xbd\ngithub.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4207f3dd0, 0x3b9aca00, 0xc4200964e0)\n\t/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/
wait.go:88 +0x4d\ncreated by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:156 +0x6a8\n" namespace=defau
lt workflow=coinflip-znqp4
time="2018-10-24T08:43:32Z" level=info msg="Workflow update successful" namespace=default workflow=coinflip-znqp4
time="2018-10-24T08:43:33Z" level=info msg="Labeled pod default/coinflip-znqp4-3816441204 completed"
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.2.0
  BuildDate: 2018-08-30T08:51:40Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-09-10T11:44:26Z
  compiler: gc
  gitCommit: a4529464e4629c21224b3d52edfe0ea91b072862
  gitTreeState: clean
  gitVersion: v1.11.3
  goVersion: go1.11
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-09-13T22:19:55Z
  compiler: gc
  gitCommit: 8d9503f982872112eb283f78cefc6944af640427
  gitTreeState: clean
  gitVersion: v1.10.7-gke.2
  goVersion: go1.9.3b4
  major: "1"
  minor: 10+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>

Name:                coinflip-znqp4
Namespace:           default
ServiceAccount:      default
Status:              Error
Message:             node coinflip-znqp4[1].heads uninitialized
Created:             Wed Oct 24 16:43:28 +0800 (1 minute ago)
Started:             Wed Oct 24 16:43:28 +0800 (1 minute ago)
Finished:            Wed Oct 24 16:43:32 +0800 (1 minute ago)
Duration:            4 seconds

STEP               PODNAME                    DURATION  MESSAGE
 ● coinflip-znqp4
 ├---✔ flip-coin   coinflip-znqp4-3816441204  4s

```

- workflow-controller logs:
At the above.
