### ISSUE TITLE
Signature error with GCS upgrade to 2.2.x

### ISSUE THREAD

**Issue by mlarrousse** [argoproj/argo#1060]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
Upgraded to 2.2.1, workflows began failing with
`time="2018-10-16T21:52:37Z" level=info msg="Updating node structure-assembler-4sm9s[0].run-structure-assembler-script(0) (structure-assembler-4sm9s-967368689) message: failed to load artifacts: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method."`

**What you expected to happen**:
No breaking changes for artifact storage.

**How to reproduce it (as minimally and precisely as possible)**:
Try to run version 2.2 with GCS storage

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.2.0
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-06-22T05:40:33Z
  compiler: gc
  gitCommit: 32ac1c9073b132b8ba18aa830f46b77dcceb0723
  gitTreeState: clean
  gitVersion: v1.10.5
  goVersion: go1.9.7
  major: "1"
  minor: "10"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-10-02T17:32:01Z
  compiler: gc
  gitCommit: 06898a4d0f2b96f82b43d9e59fa2825bd3d616a2
  gitTreeState: clean
  gitVersion: v1.10.7-gke.6
  goVersion: go1.9.3b4
  major: "1"
  minor: 10+
  platform: linux/amd64
```
