### ISSUE TITLE
Cannot create workflow with Kubernetes Resoruces

### ISSUE THREAD

**Issue by soolaugust** [argoproj/argo#1068]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Maybe a BUG REPORT I think.

**What happened**:

> When I try to create a workflow with Kubernetes REsources. I got following error message

``` bash
from server for: "/tmp/manifest.yaml": namespaces "rook-ceph-system" is forbidden: User "system:serviceaccount:default:default" cannot get resource "namespaces" in API group "" in the namespace "rook-ceph-system"
```

**What you expected to happen**:

> Workflow create successfully as expect

**How to reproduce it (as minimally and precisely as possible)**:

> using following yaml file

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: rook-operator-
spec:
  entrypoint: rook-operator-templates
  templates:
  - name: rook-operator-templates
    steps:
    - - name: rook-operator-namespace-job
        template: rook-operator-namespace-job
  - name: rook-operator-namespace-job
    resource:
      action: apply
      manifest: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: rook-ceph-system
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-10-05T16:46:06Z
  compiler: gc
  gitCommit: 4ed3216f3ec431b140b1d899130a69fc671678f4
  gitTreeState: clean
  gitVersion: v1.12.1
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-10-05T16:36:14Z
  compiler: gc
  gitCommit: 4ed3216f3ec431b140b1d899130a69fc671678f4
  gitTreeState: clean
  gitVersion: v1.12.1
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                rook-operator-95w6w
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             child 'rook-operator-95w6w-3240803918' failed
Created:             Thu Nov 01 00:58:02 -0700 (7 minutes ago)
Started:             Thu Nov 01 00:58:02 -0700 (7 minutes ago)
Finished:            Thu Nov 01 00:58:04 -0700 (7 minutes ago)
Duration:            2 seconds

STEP                                PODNAME                         DURATION  MESSAGE
 ✖ rook-operator-95w6w                                                        child 'rook-operator-95w6w-3240803918' failed
 └---✖ rook-operator-namespace-job  rook-operator-95w6w-3240803918  2s        Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "rook-ceph-system", Namespace: ""
Object: &{map["apiVersion":"v1" "kind":"Namespace" "metadata":map["name":"rook-ceph-system" "namespace":"" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]]]}
from server for: "/tmp/manifest.yaml": namespaces "rook-ceph-system" is forbidden: User "system:serviceaccount:default:default" cannot get resource "namespaces" in API group "" in the namespace "rook-ceph-system"

```
- executor logs:
```
Error from server (BadRequest): container init is not valid for pod rook-operator-95w6w-3240803918
```

```
Error from server (BadRequest): container wait is not valid for pod rook-operator-95w6w-3240803918
```
- workflow-controller logs:
```
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples.

```

**Comment by soolaugust** [comment]
I fix this, for **_default_** serviceaccount, it doesn't have **_create_** permission for **_namespace_**, add this rule to **_default_** serviceaccount will fix this.

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-namespaces-admin-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-namespaces-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-namespaces-admin-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```
