### ISSUE TITLE
Containers/logs not available if failed with DeadlineExceeded

### ISSUE THREAD

**Issue by SeriousSem** [argoproj/argo#1093]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
 Argo step exceeded deadline and workflow failed
```
status:
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  reason: DeadlineExceeded
  startTime: 2018-11-14T12:34:36Z
```
Failed container is not reachable and it is not possible to see logs in the pods which workflows failed with DeadlineExceeded, 
```
container "main" in pod "timeouts-cftlp" is not available
```
**What you expected to happen**:
I expect container/logs still be available after execution failed.

**How to reproduce it (as minimally and precisely as possible)**:
```
echo 'apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   generateName: timeouts-
> spec:
>   entrypoint: sleep
>   templates:
>   - name: sleep
>     container:
>       image: alpine:latest
>       command: [sh, -c]
>       args: ["echo sleeping for 1m; sleep 60; echo done"]
>     activeDeadlineSeconds: 10' | kubectl create -n argo -f -
```

```
kubectl logs -n argo pod-name main
```
**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version 2.2.0
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-10-30T21:39:16Z
  compiler: gc
  gitCommit: 17c77c7898218073f14c8d573582e8d2313dc740
  gitTreeState: clean
  gitVersion: v1.12.2
  goVersion: go1.11.1
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-11-08T20:06:00Z
  compiler: gc
  gitCommit: 42df8ec7aef509caba40b6178616dcffca9d7355
  gitTreeState: clean
  gitVersion: v1.10.6-gke.11
  goVersion: go1.9.3b4
  major: "1"
  minor: 10+
  platform: linux/amd64
```
