### ISSUE TITLE
Delete K8s resources by label

### ISSUE THREAD

**Issue by epa095** [argoproj/argo#1100]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request
I would like to be able to use Kubernetes Resources template to delete some deployments based on their label. E.g. I would be able to execute the equivalent of 
```bash
kubectl delete deployment -l applications.my-app/project-name=a-name,applications.my-app/project-version!="1542720"
```
It is possible that this is possible using the action: delete and a clever kubernetes manifest, but I did not find any way to do it. 

**Environment**:
- Argo version:
```
argo: v2.2.0
  BuildDate: 2018-08-30T08:52:05Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-03-26T16:55:54Z
  compiler: gc
  gitCommit: fc32d2f3698e36b93322a3465f63a14e9f0eaead
  gitTreeState: clean
  gitVersion: v1.10.0
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-06-29T01:07:01Z
  compiler: gc
  gitCommit: 57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a
  gitTreeState: clean
  gitVersion: v1.9.9
  goVersion: go1.9.3
  major: "1"
  minor: "9"
  platform: linux/amd64
```

**Comment by epa095** [comment]
To "answer" my own question, a work-around is to run a `script`  with an image with `kubectl` installed, and then just do the delete in there.

**Comment by Joibel** [comment]
This has been supported since v2.8.0 via the `flags` field on `resource` templates, which passes arguments straight through to `kubectl`. A manifest is not required for `delete`/`get` when flags are given, so a label-selector delete looks like:

```yaml
- name: delete-resource
  resource:
    action: delete
    flags: ["deployment", "--selector", "applications.my-app/project-name=a-name,applications.my-app/project-version!=1542720"]
```

See `examples/resource-delete-with-flags.yaml` for a full runnable example. The `script` + `kubectl` workaround you found is no longer necessary.

Closing as implemented. The walk-through docs don't currently mention `flags`, so a docs PR pointing at that example would be welcome.
