### ISSUE TITLE
Unable to load workflows

### ISSUE THREAD

**Issue by ashishkoho** [argoproj/argo#1114]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened**:
Installed using, https://github.com/argoproj/argo/blob/master/manifests/namespace-install.yaml
Argo UI errors: Unable to show data Internal server error
![screen shot 2018-12-05 at 4 11 35 pm](https://user-images.githubusercontent.com/3905922/49552384-25f7ef80-f8a8-11e8-8ed2-3bc7a642a732.png)

**What you expected to happen**:
UI shows the workflows with no issues.
**How to reproduce it (as minimally and precisely as possible)**:
Just install namespace-install.yml above
**Anything else we need to know?**:

**Environment**:
- Argo version:2.2.1
```
$ argo version
```
- Kubernetes version :1.9
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- argo-ui logs error:
```
error: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-ui" cannot list workflows.argoproj.io at the cluster scope {"code":403,"timestamp":"2018-12-06T00:08:45.055Z"}
```

**Comment by ashishkoho** [comment]
Update,
Argo version:2.2.0

**Comment by alexmt** [comment]
Issue fixed in master but still exists in v2.2.1. UI tries to load workflows from all namespaces and fails if argo-ui account does not have permissions.  Only workaround for now is to use pre-release image `argoproj/argoui:v2.2.1-37808b1` and manually add `FORCE_NAMESPACE_ISOLATION` env variable in `argo-ui` deployment:

```yaml
   spec:
      containers:
      - env:
        - name: FORCE_NAMESPACE_ISOLATION
          value: "true"
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: IN_CLUSTER
          value: "true"
        - name: ENABLE_WEB_CONSOLE
          value: "false"
        - name: BASE_HREF
          value: /
        image: argoproj/argoui:v2.2.1-37808b1
```
