### ISSUE TITLE
Loop support for output params from other steps

### ISSUE THREAD

**Issue by gaoning777** [argoproj/argo#1118]
**FEATURE REQUEST?**:

**What happened**:
Loop feature is not supported when the param is output parameters from other container steps.

**What you expected to happen**:
Argo loop can iterate through the items in the list, which is the output parameter from other container steps.

**How to reproduce it (as minimally and precisely as `possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-flip-coin-loop-
spec:
  arguments:
    parameters: []
  entrypoint: pipeline-flip-coin-loop
  serviceAccountName: pipeline-runner
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: flip-output
            value: '{{inputs.parameters.flip-output}}'
        name: generateloop
        template: generateloop
      - arguments:
          parameters:
          - name: flip-output
            value: '{{inputs.parameters.flip-output}}'
          - name: generateloop-output
            value: '{{tasks.generateloop.outputs.parameters.generateloop-output}}'
        dependencies:
        - generateloop
        name: print
        template: print
        withParams: '{{tasks.generateloop.outputs.parameters.generateloop-output}}'
    inputs:
      parameters:
      - name: flip-output
    name: condition-1
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: flip-output
            value: '{{inputs.parameters.flip-output}}'
        name: print2
        template: print2
    inputs:
      parameters:
      - name: flip-output
    name: condition-2
  - container:
      args:
      - python -c "import random; result = 'heads' if random.randint(0,1) == 0 else
        'tails'; print(result)" | tee /tmp/output
      command:
      - sh
      - -c
      image: python:alpine3.6
    name: flip
    outputs:
      parameters:
      - name: flip-output
        valueFrom:
          path: /tmp/output
  - container:
      args:
      - python -c "import json; import sys; json.dump([i for i in range(0,7)], sys.stdout)"
        | tee /tmp/output
      command:
      - sh
      - -c
      image: python:alpine3.6
    name: generateloop
    outputs:
      parameters:
      - name: generateloop-output
        valueFrom:
          path: /tmp/output
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: flip-output
            value: '{{tasks.flip.outputs.parameters.flip-output}}'
        dependencies:
        - flip
        name: condition-1
        template: condition-1
        when: '{{tasks.flip.outputs.parameters.flip-output}} == heads'
      - arguments:
          parameters:
          - name: flip-output
            value: '{{tasks.flip.outputs.parameters.flip-output}}'
        dependencies:
        - flip
        name: condition-2
        template: condition-2
        when: '{{tasks.flip.outputs.parameters.flip-output}} == tails'
      - name: flip
        template: flip
    name: pipeline-flip-coin-loop
  - container:
      args:
      - looping
      command:
      - echo
      image: alpine:3.6
    inputs:
      parameters:
      - name: generateloop-output
    name: print
  - container:
      args:
      - tails
      command:
      - echo
      image: alpine:3.6
    name: print2
```
**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:39:36Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2018-12-03T21:04:45Z"
  compiler: gc
  gitCommit: ddf47ac13c1a9483ea035a79cd7c10005ff21a6d
  gitTreeState: clean
  gitVersion: v1.13.0
  goVersion: go1.11.2
  major: "1"
  minor: "13"
  platform: linux/amd64
serverVersion:
  buildDate: "2018-11-10T20:22:02Z"
  compiler: gc
  gitCommit: dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c
  gitTreeState: clean
  gitVersion: v1.9.7-gke.11
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
Name:                pipeline-flip-coin-loop-2g2qg
Namespace:           kubeflow
ServiceAccount:      pipeline-runner
Status:              Succeeded
Created:             Thu Dec 06 14:36:57 -0800 (7 minutes ago)
Started:             Thu Dec 06 14:36:57 -0800 (7 minutes ago)
Finished:            Thu Dec 06 14:37:11 -0800 (7 minutes ago)
Duration:            14 seconds

STEP                              PODNAME                                   DURATION  MESSAGE
 ✔ pipeline-flip-coin-loop-2g2qg                                                      
 ├-✔ flip                         pipeline-flip-coin-loop-2g2qg-2606161201  3s        
 ├-✔ condition-1                                                                      
 | ├-✔ generateloop               pipeline-flip-coin-loop-2g2qg-3735441020  4s        
 | └-✔ print                      pipeline-flip-coin-loop-2g2qg-2770744276  4s        
 └-○ condition-2                                                                      when 'heads == tails' evaluated false

```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```
