### ISSUE TITLE
Volume spec does not need to be lowercased 

### ISSUE THREAD

**Issue by abhinavdas** [argoproj/argo#112]
```
volumes:
   SOMENAME:
      size_gb: 10
      storage_class: ssd
```
Will be flagged by argo yaml validate as error as earlier version of volume provisioner required this to be lowercase. This is not a restriction anymore and we should allow uppercase to fit with our convention of defining reference vars as uppercase.
