### ISSUE TITLE
Resource Template: 'get' action fails, resource not found

### ISSUE THREAD

**Issue by captainkerk** [argoproj/argo#1123]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug report

**What happened**:

I think I found a bug with the resource template type and the 'get' action. This doesn't work outside of the default namespace. 

That step runs two kubectl commands (see log lines below), and the second `kubectl get` is missing the namespace arg. The first one works because the namespace is in the manifest file.

**What you expected to happen**:

the resource template with `action: get` should return details about a particular object

**How to reproduce it (as minimally and precisely as possible)**:

1. have an existing object running (e.g. deployment), lets call the example deployment blah in namespace blahblah

2. run this template:

```
- name: get-previous-release
  outputs:
    parameters:
    - name: previous-commit-hash
      valueFrom:
        jsonPath: '{.metadata.labels.commit-hash}'
  resource:
    action: get
    successCondition: status.succeeded == 1
    failureCondition: status.failed == 1
    manifest: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: blah
        namespace: blahblah
```

workflow step logs:
```
time="2018-12-10T18:40:33Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
time="2018-12-10T18:40:33Z" level=info msg="kubectl get -f /tmp/manifest.yaml -o name"
time="2018-12-10T18:40:34Z" level=info msg=deployment.apps/blah
time="2018-12-10T18:40:34Z" level=info msg="Waiting for conditions: status.succeeded==1"
time="2018-12-10T18:40:34Z" level=info msg="Failing for conditions: status.failed==1"
time="2018-12-10T18:40:34Z" level=info msg="kubectl get deployment.apps/blah -w -o json"
time="2018-12-10T18:40:34Z" level=warning msg="Json reader returned error EOF. Calling kill (usually superfluous)"
time="2018-12-10T18:40:34Z" level=warning msg="Command for kubectl get -w for deployment.apps/blah exited. Getting return value using Wait"
time="2018-12-10T18:40:34Z" level=warning msg="cmd.Wait for kubectl get -w command for resource deployment.apps/blah returned error exit status 1"
```

It looks like argo does the lookup twice: first time using the manifest, then takes the name and passes it into another get request. The problem is the second get doesnt have the namespace specified:

> time="2018-12-10T18:40:34Z" level=info msg="kubectl get deployment.apps/blah -w -o json"

`kubectl get deployment.apps/blah -w -o json -n blahblah` works.

**Anything else we need to know?**:

The first lookup succeeds because the namespace is in the manifest. I've exec'ed into the pod running this step, and verified the get from /tmp/manifest works. 

It seems like the second lookup is redundant, you can get everything you need from the first get, with a slight modification: `kubectl get -f /tmp/manifest.yaml -o json`

I've ensured rbac is set correctly to allow this get action. 

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-09-28T15:20:58Z
  compiler: gc
  gitCommit: 0ed33881dc4355495f623c6f22e7dd0b7632b7c0
  gitTreeState: clean
  gitVersion: v1.12.0
  goVersion: go1.11
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-11-26T14:25:46Z
  compiler: gc
  gitCommit: 637c7e288581ee40ab4ca210618a89a555b6e7e9
  gitTreeState: clean
  gitVersion: v1.10.11
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

Thanks!
