### ISSUE TITLE
Wait container fails when some file is used both as output parameter and artifact

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#1124]
**BUG REPORT**:

**What happened**:

Wait container fails when some file is used both as output parameter and artifact.
I want to make a piece of data available as parameter argument, but I also want to store it in the artifact store. The execution fails after the main container finishes when I try doing that.

**What you expected to happen**:
I expect Argo to handle this without crashing.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-parameter-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: message-artifact
        path: /tmp/hello_world.txt
      parameters:
      - name: message-param
        valueFrom:
          path: /tmp/hello_world.txt
```

**Environment**:
- Argo version:
```
argo: v2.2.0
  BuildDate: 2018-08-30T08:52:05Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
kubectl version -o yaml
clientVersion:
  buildDate: 2018-09-09T18:02:47Z
  compiler: gc
  gitCommit: a4529464e4629c21224b3d52edfe0ea91b072862
  gitTreeState: clean
  gitVersion: v1.11.3
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-11-10T20:22:02Z
  compiler: gc
  gitCommit: dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c
  gitTreeState: clean
  gitVersion: v1.9.7-gke.11
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- executor logs (wait):

"No sidecars"
"Saving output artifacts"
"Annotations monitor stopped"
"Saving artifact: mlpipeline-ui-metadata"
"Archiving 60ed2e641ef6e5380d0c74183ef8b47896bf52b2f7ee0f0d35d1eb4b95f3a463:/mlpipeline-ui-metadata.json to /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz"
"sh -c docker cp -a 60ed2e641ef6e5380d0c74183ef8b47896bf52b2f7ee0f0d35d1eb4b95f3a463:/mlpipeline-ui-metadata.json - | gzip > /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz"
"Archiving completed"
"Creating minio client minio-service.kubeflow:9000 using static credentials"
"Saving from /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz to s3 (endpoint: minio-service.kubeflow:9000, bucket: mlpipeline, key: runs/fc650e6f-fda2-11e8-a7c1-42010a800147/pipeline-tfjob-6g4kg-1301404659/mlpipeline-ui-metadata.tgz)"
"Successfully saved file: /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz"
"Saving artifact: mlpipeline-metrics"
"Archiving 60ed2e641ef6e5380d0c74183ef8b47896bf52b2f7ee0f0d35d1eb4b95f3a463:/mlpipeline-metrics.json to /argo/outputs/artifacts/mlpipeline-metrics.tgz"
"sh -c docker cp -a 60ed2e641ef6e5380d0c74183ef8b47896bf52b2f7ee0f0d35d1eb4b95f3a463:/mlpipeline-metrics.json - | gzip > /argo/outputs/artifacts/mlpipeline-metrics.tgz"
"Archiving completed"
"Creating minio client minio-service.kubeflow:9000 using static credentials"
"Saving from /argo/outputs/artifacts/mlpipeline-metrics.tgz to s3 (endpoint: minio-service.kubeflow:9000, bucket: mlpipeline, key: runs/fc650e6f-fda2-11e8-a7c1-42010a800147/pipeline-tfjob-6g4kg-1301404659/mlpipeline-metrics.tgz)"
"Successfully saved file: /argo/outputs/artifacts/mlpipeline-metrics.tgz"
"Saving output parameters"
"Saving path output parameter: confusion-matrix-metrics"
"[sh -c docker cp -a 60ed2e641ef6e5380d0c74183ef8b47896bf52b2f7ee0f0d35d1eb4b95f3a463:/mlpipeline-metrics.json - | tar -ax -O]"
"`[sh -c docker cp -a 60ed2e641ef6e5380d0c74183ef8b47896bf52b2f7ee0f0d35d1eb4b95f3a463:/mlpipeline-metrics.json - | tar -ax -O]` stderr:\nError: No such container:path: 60ed2e641ef6e5380d0c74183ef8b47896bf52b2f7ee0f0d35d1eb4b95f3a463:/mlpipeline-metrics.json\ntar: This does not look like a tar archive\ntar: Exiting with failure status due to previous errors\n"
"Alloc=4389 TotalAlloc=12061 Sys=9830 NumGC=4 Goroutines=10"
"exit status 2\ngithub.com/argoproj/argo/errors.Wrap\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:87\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:70\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).GetFileContents\n\t/root/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:40\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveParameters\n\t/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:343\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:49\ngithub.com/argoproj/argo/cmd/argoexec/commands.glob..func4\n\t/root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:19\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:766\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/root/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:15\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2361"
- workflow-controller logs:
```
