### ISSUE TITLE
Memory Configurations for Argo Operator

### ISSUE THREAD

**Issue by daixiang0** [argoproj/argo#1139]
In `docs/workflow-controller-configmap.yaml`:
```
    # executorResources specifies the resource requirements that will be used for the executor
    # sidecar/init container. This is useful in clusters which require resources to be specified as
    # part of admission control.
    executorResources:
      requests:
        cpu: 0.1 
        memory: 64Mi
      limits:
        cpu: 0.5 
        memory: 512Mi
```
Do those resource settings work for almost scenes, right?
Also, above setting is for executor, not operator.
Is there any practice about resource setting for operator?
Or for ~100 jobs, how much resources need i set for operator?
