### ISSUE TITLE
HostPath volume won't work

### ISSUE THREAD

**Issue by marcadella** [argoproj/argo#1153]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Using a hostPath volume causes workflow to be stuck in ContainerCreating step.

**How to reproduce it (as minimally and precisely as possible)**:
Here is the yaml file (just replace XXX with a path on your system)
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  entrypoint: test
  volumes:
  - name: inputvol
    hostPath:
      path: XXX
      type: Directory

  templates:
  - name: test
    container:
      image: alpine:latest
      command: [sh]
      args: ["-c", "ls"]
      volumeMounts:
      - mountPath: /home
        name: inputvol
```

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2018-12-13T10:39:04Z"
  compiler: gc
  gitCommit: eec55b9ba98609a46fee712359c7b5b365bdd920
  gitTreeState: clean
  gitVersion: v1.13.1
  goVersion: go1.11.2
  major: "1"
  minor: "13"
  platform: linux/amd64
serverVersion:
  buildDate: "2018-12-14T06:59:37Z"
  compiler: gc
  gitCommit: f49fa022dbe63faafd0da106ef7e05a29721d3f1
  gitTreeState: clean
  gitVersion: v1.12.4
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                test-vnm2s
Namespace:           default
ServiceAccount:      default
Status:              Running
Created:             Fri Jan 04 12:12:05 +0100 (17 minutes ago)
Started:             Fri Jan 04 12:12:05 +0100 (17 minutes ago)
Duration:            17 minutes 36 seconds

STEP           PODNAME     DURATION  MESSAGE
 ◷ test-vnm2s  test-vnm2s  17m       ContainerCreating

```
- executor logs:
```
Error from server (BadRequest): container "main" in pod "test-vnm2s" is waiting to start: ContainerCreating
Error from server (BadRequest): container "wait" in pod "test-vnm2s" is waiting to start: ContainerCreating
```
