### ISSUE TITLE
fake outputs don't notify and task completes successfully

### ISSUE THREAD

**Issue by alexfrieden** [argoproj/argo#1165]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Seems like a bug but I would put it as a feature request
**What happened**:
When defining outputs that don't exist, the stage exists properly.  No notification is sent.   
**What you expected to happen**:
I expected the stage to crash as something that doesn't exist is being saved.  
**How to reproduce it (as minimally and precisely as possible)**:
```
script:
  image: alpine:latest
  command: [bash]
  source: |
     echo 'this is real' > /real.txt
outputs:
  artifacts:
    - name: real
       path: /real.txt
    - name: fake
       path /fake/path/to.txt
```
**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-11-27T01:15:02Z
  compiler: gc
  gitCommit: 435f92c719f279a3a67808c80521ea17d5715c66
  gitTreeState: clean
  gitVersion: v1.12.3
  goVersion: go1.11.2
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-11-26T14:25:46Z
  compiler: gc
  gitCommit: 637c7e288581ee40ab4ca210618a89a555b6e7e9
  gitTreeState: clean
  gitVersion: v1.10.11
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```
