### ISSUE TITLE
Unable to use aggregate output parameters in script step

### ISSUE THREAD

**Issue by smartnose** [argoproj/argo#1195]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request
**What happened**:
When the output parameters are in a `script` step, it cannot be properly interpreted in other steps.

**What you expected to happen**:

The output parameters for `script` should be properly interpreted just as `container` step as well

**How to reproduce it (as minimally and precisely as possible)**:

run `argo submit` on the following workflow definition. The interpretation will fail to find `steps.backtesting-split.outputs.parameters.task-id`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata: {generateName: dom-backtesting}
spec:
  entrypoint: backtesting
  templates:
  - name: backtesting
    steps:
    - - arguments:
          parameters:
          - {name: task-id, value: 94f3572bf53d41438dbc3317cb257d21}
        name: backtesting-split
        template: task-tpl
    - - arguments:
          parameters:
          - {name: task-id, value: '{{item.task-id}}'}
        name: backtesting-process
        template: task-tpl
        withParam: '{{steps.backtesting-split.outputs.parameters.task-id}}'
    - - arguments:
          parameters:
          - {name: task-id, value: 27fefb0dea324700928fe47aa668961d}
        name: backtesting-converge
        template: task-tpl
  - name: task-tpl
    script:
      command: [sh]
      image: 551896635143.dkr.ecr.us-west-2.amazonaws.com/zoml-zmlflow:op-int3
      imagePullPolicy: Always
      source: /opt/program/argo_entry {{inputs.parameters.task-id}}
    inputs:
      parameters:
      - {name: task-id}
    outputs:
      parameters:
      - name: task-id
        valueFrom: {path: /tmp/zmlflow_task_ids}
   
```
**Anything else we need to know?**:
Chatted with jesse in Slack channel and he confirmed this is something useful

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-09-28T15:19:47Z
  compiler: gc
  gitCommit: 0ed33881dc4355495f623c6f22e7dd0b7632b7c0
  gitTreeState: clean
  gitVersion: v1.12.0
  goVersion: go1.11
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-12-04T13:33:10Z
  compiler: gc
  gitCommit: 6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0
  gitTreeState: clean
  gitVersion: v1.10.11-eks
  goVersion: go1.9.3
  major: "1"
  minor: 10+
  platform: linux/amd64
<img width="483" alt="screen shot 2019-01-25 at 3 53 06 pm" src="https://user-images.githubusercontent.com/7807664/51779017-b6d59500-20b9-11e9-857d-29056ce3893a.png">

```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by delwaterman** [comment]
I have a workflow that demonstrates this problem with script output parameters:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameter-aggregation-bug-
spec:
  entrypoint: aggregate-params-bug
  templates:
    - name: generate-strings
      script:
        image: ruby:2.6.4-buster
        command: [ruby]
        source: |
          require 'json'

          def rand_str(number)
            charset = Array('A'..'Z') + Array('a'..'z')
            Array.new(number) { charset.sample }.join
          end

          values = 2.times.map { rand_str(5) }
          puts JSON.pretty_generate(values)

    - name: script-echo-to-result
      inputs:
        parameters:
        - name: message
      script:
        image: debian:9.4
        command: [bash]
        source: |
          echo "{{inputs.parameters.message}}"

    - name: script-echo-to-param
      inputs:
        parameters:
        - name: message
      outputs:
        parameters:
          - name: output-message
            valueFrom:
              path: /tmp/output-message
      script:
        image: debian:9.4
        command: [bash]
        source: |
          echo "{{inputs.parameters.message}}" | tee /tmp/output-message

    - name: container-echo-to-param
      inputs:
        parameters:
          - name: message
      outputs:
        parameters:
          - name: output-message
            valueFrom:
              path: /tmp/output-message
      container:
        image: debian:9.4
        args:
          - /bin/bash
          - "-c"
          - "echo {{inputs.parameters.message}} > /tmp/output-message"

    - name: aggregate-values
      inputs:
        parameters:
          - name: values
      script:
        image: ruby:2.6.4-buster
        command: [ruby]
        source: |
          require 'json'
          input = %q({{inputs.parameters.values}})
          puts "RAW INPUT: #{input.inspect}"
          values = JSON.parse(input)
          puts JSON.pretty_generate(values)

    - name: combine-results-from-script-templates
      inputs:
        parameters:
        - name: strings
      steps:
        - - name: script-echo-to-result
            template: script-echo-to-result
            arguments:
              parameters:
              - name: message
                value: "{{item}}"
            withParam: "{{inputs.parameters.strings}}"
        - - name: combine-results
            template: aggregate-values
            arguments:
              parameters:
                - name: values
                  value: "{{steps.script-echo-to-result.outputs.result}}"

    - name: combine-params-from-script-templates
      inputs:
        parameters:
        - name: strings
      steps:
        - - name: script-echo-to-param
            template: script-echo-to-param
            arguments:
              parameters:
              - name: message
                value: "{{item}}"
            withParam: "{{inputs.parameters.strings}}"
        - - name: combine-params-from-scripts
            template: aggregate-values
            arguments:
              parameters:
                - name: values
                  value: "{{steps.script-echo-to-param.outputs.parameters.output-message}}"
                  # value: "{{steps.echo-param.outputs.parameters}}"

    - name: combine-params-from-container-templates
      inputs:
        parameters:
        - name: strings
      steps:
        - - name: container-echo-to-param
            template: container-echo-to-param
            arguments:
              parameters:
              - name: message
                value: "{{item}}"
            withParam: "{{inputs.parameters.strings}}"
        - - name: combine-params-from-containers
            template: aggregate-values
            arguments:
              parameters:
                - name: values
                  value: "{{steps.container-echo-to-param.outputs.parameters}}"

    - name: aggregate-params-bug
      dag:
        tasks:
        - name: prep
          template: generate-strings
        - name: combine-results-from-script-templates
          dependencies: [prep]
          template: combine-results-from-script-templates
          arguments:
            parameters:
              - name: strings
                value: "{{tasks.prep.outputs.result}}"
        - name: combine-params-from-script-templates
          dependencies: [prep]
          template: combine-params-from-script-templates
          arguments:
            parameters:
              - name: strings
                value: "{{tasks.prep.outputs.result}}"
        - name: combine-params-from-container-templates
          dependencies: [prep]
          template: combine-params-from-container-templates
          arguments:
            parameters:
              - name: strings
                value: "{{tasks.prep.outputs.result}}"
```
