### ISSUE TITLE
Script output gets '\n' appended

### ISSUE THREAD

**Issue by pheymann** [argoproj/argo#1202]
**BUG REPORT**

**What happened**:
When using script outputs in another step they get a newline character `\n` appended.

**What you expected to happen**:
I expect to get exactly the same `String` as input which was produced as output. This unexpected newline character forces me to clean up script outputs everytime they are used.

**How to reproduce it (as minimally and precisely as possible)**:
Run the following workflow and check the logs:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-bug-
spec:
  entrypoint: script-out-bug
  templates:
  - name: script-out-bug
    steps:
    - - name: send-output
        template: send-output-templ
    - - name: receive-output
        template: receive-output-templ
        arguments:
          parameters:
          - name: received-output
            value: "{{steps.send-output.outputs.result}}"

  - name: send-output-templ
    script:
      image: debian:latest
      resources:
        requests:
          cpu: "50m"
          memory: "50Mi"
      command: [bash]
      source: 
        echo "hello world"

  - name: receive-output-templ
    inputs:
      parameters:
      - name: received-output
    script:
      image: debian:latest
      resources:
        requests:
          cpu: "50m"
          memory: "50Mi"
      command: [bash]
      source: 
        printf "{{inputs.parameters.received-output}}broken"
```

Log output:

```bash
$ argo ... logs <pod id>
hello world
broken
```

Expected output would be `hello worldbroken`.

**Environment**:
- Argo version: **master** branch : commit `f07b5afeaf950f49f87cdffb5116e82c8b0d43a1`
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-10-30T21:39:38Z
  compiler: gc
  gitCommit: 17c77c7898218073f14c8d573582e8d2313dc740
  gitTreeState: clean
  gitVersion: v1.12.2
  goVersion: go1.11.1
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-11-26T14:25:46Z
  compiler: gc
  gitCommit: 637c7e288581ee40ab4ca210618a89a555b6e7e9
  gitTreeState: clean
  gitVersion: v1.10.11
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```
