### ISSUE TITLE
Wait container fails to extract large artifacts from workflow step

### ISSUE THREAD

**Issue by seichten** [argoproj/argo#1203]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
A single-step workflow completes successfully when creating artifacts on smaller size (~200Mb) but fails when the wait container attempts to extract larger (~6.7Gb) artifacts. Main container shows success of its step, but pod fails out with wait container showing Exit Code 2 leading to `failed to save outputs: verify serviceaccount argo:default has necessary privileges`. Pod appears to have ample disk space and memory and manual extraction of artifacts can successfully occur via local docker container use outside of argo/k8s.

**What you expected to happen**:
The workflow should complete successfully and extract the expected artifacts

**How to reproduce it (as minimally and precisely as possible)**:

The workflow takes a single argument of a [NCBI SRA run identifier](https://trace.ncbi.nlm.nih.gov/Traces/sra/):

 `SRR000001` should complete successfully creating artifacts ~200Mb
` SRR7460726` fails as it creates artifacts ~6.7Gb in size

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sra-fasterq-dump-workflow-
spec:
  entrypoint: sra-fasterq-dump
  arguments:
    parameters:
      - name: srrid
        value: SRR7460726  # passing identifier 'SRR000001' is a working state with ~200Mb artifacts
  templates:
    - name: sra-fasterq-dump
      inputs:
        parameters:
          - name: srrid
      steps:
        - - name: fasterq-dump
            template: fasterq-dump
            arguments:
              parameters:
                - name: srrid
                  value: "{{inputs.parameters.srrid}}"
    - name: fasterq-dump
      inputs:
        parameters:
          - name: srrid
      script:
        image: inutano/sra-toolkit:latest
        command: [bash]
        resources:
          requests:
            memory: 2G
            cpu: 0.5
        source: |
          cd /
          fasterq-dump {{inputs.parameters.srrid}}
          du -sh "/{{inputs.parameters.srrid}}_1.fastq"
          du -sh "/{{inputs.parameters.srrid}}_2.fastq"
          df -h
      outputs:
        artifacts:
          - name: fastq1
            path: "/{{inputs.parameters.srrid}}_1.fastq"
          - name: fastq2
            path: "/{{inputs.parameters.srrid}}_2.fastq"
```
**Anything else we need to know?**:

Initially thought that the issue was similar to https://github.com/argoproj/argo/issues/724, however editing the `workflow-controller-configmap` to confirm more resources does not solve the issue.
 
main log for `SRR000001`:
```
spots read      : 470,985
reads read      : 1,883,940
reads written   : 707,026
reads 0-length  : 468,635
technical reads : 708,279
209M	/SRR000001_1.fastq
76M	/SRR000001_2.fastq
```

main log for `SRR7460726_1`:
```
spots read      : 17,834,614
reads read      : 35,669,228
reads written   : 35,669,228
6.7G	/SRR7460726_1.fastq
6.7G	/SRR7460726_2.fastq
```

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-11-26T14:38:32Z
  compiler: gc
  gitCommit: 637c7e288581ee40ab4ca210618a89a555b6e7e9
  gitTreeState: clean
  gitVersion: v1.10.11
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-11-26T14:25:46Z
  compiler: gc
  gitCommit: 637c7e288581ee40ab4ca210618a89a555b6e7e9
  gitTreeState: clean
  gitVersion: v1.10.11
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                sra-fasterq-dump-workflow-kvq74
Namespace:           argo
ServiceAccount:      default
Status:              Failed
Message:             child 'sra-fasterq-dump-workflow-kvq74-770089820' failed
Created:             Thu Jan 31 11:30:20 -0500 (10 minutes ago)
Started:             Thu Jan 31 11:30:20 -0500 (10 minutes ago)
Finished:            Thu Jan 31 11:36:01 -0500 (4 minutes ago)
Duration:            5 minutes 41 seconds
Parameters:
  srrid:             SRR7460726

STEP                                PODNAME                                    DURATION  MESSAGE
 ✖ sra-fasterq-dump-workflow-kvq74                                                       child 'sra-fasterq-dump-workflow-kvq74-770089820' failed
 └---⚠ fasterq-dump                 sra-fasterq-dump-workflow-kvq74-770089820  5m        failed to save outputs: verify serviceaccount argo:default has necessary privileges
```
- executor logs:

init:
```
time="2019-01-31T16:30:22Z" level=info msg="Creating a docker executor"
time="2019-01-31T16:30:22Z" level=info msg="Executor (version: v2.2.1, build_date: 2018-10-11T16:27:29Z) initialized with template:\narchiveLocation:\n  s3:\n    accessKeySecret:\n      key: \"\"\n    bucket: sra-tester-bucket\n    endpoint: s3.amazonaws.com\n    key: sra-fasterq-dump-workflow-kvq74/sra-fasterq-dump-workflow-kvq74-770089820\n    secretKeySecret:\n      key: \"\"\ninputs:\n  parameters:\n  - name: srrid\n    value: SRR7460726\nmetadata: {}\nname: fasterq-dump\noutputs:\n  artifacts:\n  - name: fastq1\n    path: /SRR7460726_1.fastq\n  - name: fastq2\n    path: /SRR7460726_2.fastq\nscript:\n  command:\n  - bash\n  image: inutano/sra-toolkit:latest\n  name: \"\"\n  resources:\n    requests:\n      cpu: 500m\n      memory: 2G\n  source: |\n    cd /\n    fasterq-dump SRR7460726\n    du -sh \"/SRR7460726_1.fastq\"\n    du -sh \"/SRR7460726_2.fastq\"\n    df -h\n"
time="2019-01-31T16:30:22Z" level=info msg="Loading script source to /argo/staging/script"
time="2019-01-31T16:30:22Z" level=info msg="Start loading input artifacts..."
time="2019-01-31T16:30:22Z" level=info msg="Alloc=3150 TotalAlloc=9472 Sys=9030 NumGC=3 Goroutines=3"
```

wait:
```
time="2019-01-31T16:30:23Z" level=info msg="Creating a docker executor"
time="2019-01-31T16:30:23Z" level=info msg="Executor (version: v2.2.1, build_date: 2018-10-11T16:27:29Z) initialized with template:\narchiveLocation:\n  s3:\n    accessKeySecret:\n      key: \"\"\n    bucket: sra-tester\n    endpoint: s3.amazonaws.com\n    key: sra-fasterq-dump-workflow-kvq74/sra-fasterq-dump-workflow-kvq74-770089820\n    secretKeySecret:\n      key: \"\"\ninputs:\n  parameters:\n  - name: srrid\n    value: SRR7460726\nmetadata: {}\nname: fasterq-dump\noutputs:\n  artifacts:\n  - name: fastq1\n    path: /SRR7460726_1.fastq\n  - name: fastq2\n    path: /SRR7460726_2.fastq\nscript:\n  command:\n  - bash\n  image: inutano/sra-toolkit:latest\n  name: \"\"\n  resources:\n    requests:\n      cpu: 500m\n      memory: 2G\n  source: |\n    cd /\n    fasterq-dump SRR7460726\n    du -sh \"/SRR7460726_1.fastq\"\n    du -sh \"/SRR7460726_2.fastq\"\n    df -h\n"
time="2019-01-31T16:30:23Z" level=info msg="Waiting on main container"
time="2019-01-31T16:30:24Z" level=info msg="main container started with container ID: 257fc8f6a8a11936702ff63d8a47e27167f07caea53f18658de9b376b0c0fb77"
time="2019-01-31T16:30:24Z" level=info msg="Starting annotations monitor"
time="2019-01-31T16:30:24Z" level=info msg="docker wait 257fc8f6a8a11936702ff63d8a47e27167f07caea53f18658de9b376b0c0fb77"
time="2019-01-31T16:30:24Z" level=info msg="Starting deadline monitor"
time="2019-01-31T16:34:56Z" level=info msg="Main container completed"
time="2019-01-31T16:34:56Z" level=info msg="No sidecars"
time="2019-01-31T16:34:56Z" level=info msg="Saving output artifacts"
time="2019-01-31T16:34:56Z" level=info msg="Annotations monitor stopped"
time="2019-01-31T16:34:56Z" level=info msg="Saving artifact: fastq1"
time="2019-01-31T16:34:56Z" level=info msg="Archiving 257fc8f6a8a11936702ff63d8a47e27167f07caea53f18658de9b376b0c0fb77:/SRR7460726_1.fastq to /argo/outputs/artifacts/fastq1.tgz"
time="2019-01-31T16:34:56Z" level=info msg="sh -c docker cp -a 257fc8f6a8a11936702ff63d8a47e27167f07caea53f18658de9b376b0c0fb77:/SRR7460726_1.fastq - | gzip > /argo/outputs/artifacts/fastq1.tgz"
time="2019-01-31T16:34:56Z" level=info msg="Deadline monitor stopped"
time="2019-01-31T16:35:23Z" level=info msg="Alloc=2998 TotalAlloc=11024 Sys=10342 NumGC=6 Goroutines=8"
```
- workflow-controller logs:
```
time="2019-01-31T16:29:53Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2019-01-31T16:29:53Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\nartifactRepository:\n  s3:\n    bucket: sra-tester\n    endpoint:  s3.amazonaws.com\nexecutorResources:\n  requests:\n    cpu: 1\n    memory: 6G\n  limits:\n    cpu: 1\n    memory: 8G\n"
time="2019-01-31T16:30:20Z" level=info msg="Processing workflow" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:20Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:20Z" level=info msg="Steps node sra-fasterq-dump-workflow-kvq74 (sra-fasterq-dump-workflow-kvq74) initialized Running" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:20Z" level=info msg="StepGroup node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) initialized Running" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:20Z" level=info msg="Created pod: sra-fasterq-dump-workflow-kvq74[0].fasterq-dump (sra-fasterq-dump-workflow-kvq74-770089820)" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:20Z" level=info msg="Pod node sra-fasterq-dump-workflow-kvq74[0].fasterq-dump (sra-fasterq-dump-workflow-kvq74-770089820) initialized Pending" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:20Z" level=info msg="Workflow step group node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) not yet completed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:20Z" level=info msg="Workflow update successful" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:21Z" level=info msg="Processing workflow" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:21Z" level=info msg="Updating node sra-fasterq-dump-workflow-kvq74[0].fasterq-dump (sra-fasterq-dump-workflow-kvq74-770089820) message: PodInitializing"
time="2019-01-31T16:30:21Z" level=info msg="Workflow step group node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) not yet completed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:21Z" level=info msg="Workflow update successful" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:22Z" level=info msg="Processing workflow" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:23Z" level=info msg="Workflow step group node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) not yet completed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:23Z" level=info msg="Processing workflow" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:23Z" level=info msg="Workflow step group node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) not yet completed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:24Z" level=info msg="Processing workflow" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:24Z" level=info msg="Updating node sra-fasterq-dump-workflow-kvq74[0].fasterq-dump (sra-fasterq-dump-workflow-kvq74-770089820) status Pending -> Running"
time="2019-01-31T16:30:24Z" level=info msg="Workflow step group node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) not yet completed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:24Z" level=info msg="Workflow update successful" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:25Z" level=info msg="Processing workflow" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:30:25Z" level=info msg="Workflow step group node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) not yet completed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:31:42Z" level=info msg="Alloc=26902 TotalAlloc=1861482 Sys=58602 NumGC=1455 Goroutines=62"
time="2019-01-31T16:34:56Z" level=info msg="Processing workflow" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:34:56Z" level=info msg="Workflow step group node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) not yet completed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Processing workflow" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Updating node sra-fasterq-dump-workflow-kvq74[0].fasterq-dump (sra-fasterq-dump-workflow-kvq74-770089820) status Running -> Error"
time="2019-01-31T16:36:01Z" level=info msg="Updating node sra-fasterq-dump-workflow-kvq74[0].fasterq-dump (sra-fasterq-dump-workflow-kvq74-770089820) message: failed to save outputs: verify serviceaccount argo:default has necessary privileges"
time="2019-01-31T16:36:01Z" level=info msg="Step group node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) deemed failed: child 'sra-fasterq-dump-workflow-kvq74-770089820' failed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) phase Running -> Failed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) message: child 'sra-fasterq-dump-workflow-kvq74-770089820' failed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="node sra-fasterq-dump-workflow-kvq74[0] (sra-fasterq-dump-workflow-kvq74-4011225137) finished: 2019-01-31 16:36:01.52175359 +0000 UTC" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="step group sra-fasterq-dump-workflow-kvq74-4011225137 was unsuccessful: child 'sra-fasterq-dump-workflow-kvq74-770089820' failed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Outbound nodes of sra-fasterq-dump-workflow-kvq74-770089820 is [sra-fasterq-dump-workflow-kvq74-770089820]" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Outbound nodes of sra-fasterq-dump-workflow-kvq74 is [sra-fasterq-dump-workflow-kvq74-770089820]" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="node sra-fasterq-dump-workflow-kvq74 (sra-fasterq-dump-workflow-kvq74) phase Running -> Failed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="node sra-fasterq-dump-workflow-kvq74 (sra-fasterq-dump-workflow-kvq74) message: child 'sra-fasterq-dump-workflow-kvq74-770089820' failed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="node sra-fasterq-dump-workflow-kvq74 (sra-fasterq-dump-workflow-kvq74) finished: 2019-01-31 16:36:01.521814137 +0000 UTC" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Checking deamoned children of sra-fasterq-dump-workflow-kvq74" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Updated message  -> child 'sra-fasterq-dump-workflow-kvq74-770089820' failed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Marking workflow completed" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:01Z" level=info msg="Workflow update successful" namespace=argo workflow=sra-fasterq-dump-workflow-kvq74
time="2019-01-31T16:36:02Z" level=info msg="Labeled pod argo/sra-fasterq-dump-workflow-kvq74-770089820 completed"
time="2019-01-31T16:36:42Z" level=info msg="Alloc=25496 TotalAlloc=1862269 Sys=58602 NumGC=1458 Goroutines=62"
```

**Comment by GiantToast** [comment]
I've investigated this issue myself for several days to no avail, so any input from the Argo team would be greatly appreciated.

**Comment by alexfrieden** [comment]
Has anyone tried moving very large data through argo and also gotten hit by this limitation?

**Comment by maxkramer** [comment]
@alexfrieden @GiantToast I ran into this issue myself when attempting to upload data of around 1.5Gb as an artifact. From debugging, it seemed to be an issue with the docker cp command which extracts items from the `main` container into the `wait` sidecar where argo will go ahead and upload them to S3/some other file store.

The docker cp command was also preventing us from gathering logs from the container because it creates a lock around it while the file transfer is in progress. From what I understand, @jessesuen is currently working on a solution as part of https://github.com/argoproj/argo/pull/1214, which will prevent the need to run this command, by simply allowing the sidecar to share the same process and volume as the main container.

I received more or less the same log messages as you from the wait sidecar, however an incomplete tarball was being uploaded instead of the whole thing failing. Seemed to be because the docker cp ...  | gzip` command was timing out.

**Comment by jessesuen** [comment]
This should be fixed as part of PNS. The implementation has been changed to upload artifacts directly from a mirrored volume from the wait container. This bypasses the `docker cp | tar` logic entirely

However, there still potential for large artifacts to fail the `docker cp | tar` when copying files from the base image layer. But for this case, the recommendation is to use an emptyDir to hold the output artifacts so that copying can be done directly. This will additionally improve the performance by removing the `docker cp` step.

**Comment by TekTimmy** [comment]
> This should be fixed as part of PNS. The implementation has been changed to upload artifacts directly from a mirrored volume from the wait container. This bypasses the `docker cp | tar` logic entirely
> 
> However, there still potential for large artifacts to fail the `docker cp | tar` when copying files from the base image layer. But for this case, the recommendation is to use an emptyDir to hold the output artifacts so that copying can be done directly. This will additionally improve the performance by removing the `docker cp` step.

Hey @jessesuen, could you give an example how I specify an emptyDir volume as workflow output?

**Comment by sarabala1979** [comment]
```
# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  volumes:
    - name: workdir
      emptyDir: {}
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 10; cowsay hello world | tee /mnt/vol/hello_world.txt"]
      volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
    outputs:
      artifacts:
      - name: hello-art
        path: /mnt/vol/hello_world.txt

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```
