### ISSUE TITLE
Execute Argo Workflow as CRON

### ISSUE THREAD

**Issue by DaspawnW** [argoproj/argo#1229]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

**What happened**:
Execute Workflows as Cron

**What you expected to happen**:
I would like to use Argo Workflow to create Database Backups in Kubernetes.
The process first generates a Backup of a Postgres DB, then it encrypts the Backup and in last step it uploads the backup. (This is maybe something were I don't need Argo, but...)
We also maintain Oracle Databases and there a backup is a bit more tricky:
1. I ask Oracle to create a backup and wait that it is finished
2. I download the Backup from Oracle File Storage
3. I encrypt the Backup
4. I upload the backup
5. I delete the Backup on Oracle File Storage

To make this continuous it would be nice to have a cron in a Workflow. Like the Kubernetes CronJob with a CRON Pattern.

**Comment by DaspawnW** [comment]
Read first then write, sorry for this!

**Comment by Shimi** [comment]
@DaspawnW or anyone else, can you post the link

**Comment by igor47** [comment]
i think @DaspawnW might be referring to either:
* instructions, described [here](https://github.com/argoproj/data-pipeline#how-to-run-the-example), for using a kubernetes cronjob which runs a container where `argo submit` is executed to kick off the workflow

or
* using [argo-events](https://argoproj.github.io/argo-events) and a [calendar gateway](https://argoproj.github.io/argo-events/gateways/calendar/)

i don't like the second option because it seems to require inlining my workflow into the sensor definition as a string -- not sure why i can't just specify it as *data* since i'm just putting a yaml file inside a yaml file.

maybe there's some other way to have a workflow run regularly, but i haven't found it by reading the docs and googling for the last hour or so

**Comment by Sturgelose** [comment]
Following this, we ended creating a new project that simply fetches a Git repository and triggers the Argo Workflow using a K8s Cronjob. 
Benefits are the control over the concurrency of workflows and that is quite simple to configure!

https://github.com/bitphy/argo-cron

How we can help in this community then!

**Comment by xianlubird** [comment]
@jessesuen @sarabala1979 Should we support this cron workflow native ?

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  schedule: "*/5 * * * *"
  entrypoint: whalesay          # invoke the whalesay template
  templates:
  - name: whalesay              # name of the template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
```

**Comment by Shimi** [comment]
I think I understand the reason for decouple the execution of a workflow using argo-events.
But I think scheduling is a concept that very basic in terms of workflows. It is not intuitive for users when you tell them that they need to define the scheduling somewhere else. Also, if you want to be able to schedule and also run it on demand, you will need to write it twice (inline/config-map in the sensor or a workflow file) which is not so good.

I think it will be very useful to define the scheduling as part of the workflow and allow to create a workflow from a scheduled workflow, similar to the way it is done in CronJob 
`kubectl create job --from=cronjob/<cronjob-name> <job-name>`

**Comment by xianlubird** [comment]
@Shimi Yep, I agree. 

I will try to implement this feature in the future.

**Comment by jessesuen** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  schedule: "*/5 * * * *"
```

@xianlubird, I think a separate CronWorkflow CRD makes more sense than adding this functionality directly to Argo Workflows. It is a more a proper separation of concerns (following the same pattern of CronJob vs. Job). I also think feel this should be a separate controller and project. 

Would you be interested in starting this off as an https://github.com/argoproj-labs project?

**Comment by xianlubird** [comment]
Yep, just like the `CronJob vs Job`, I think we should provide a separate CronWorkflow CRD makes sense.   But for the `CronJob and Job`, the controller is the same `kube-controller-manager`. 

Can we just provide a new `CronWorkflow CRD` in the argo workflow project and use the same controller ?    In that case, we can reuse `argo command`, like `argo cron list` or `argo cron submit`, a sub command will much more convenience and we can reuse much more code. User can also just deploy argo once, and they can use cron or normal workflow in the same env. 

@jessesuen    WDYT  ?

**Comment by Sharathmk99** [comment]
@xianlubird I'm happy to help to implement this feature. If you have started the implementation, let me know I'm ready to work on this.

**Comment by xianlubird** [comment]
@Sharathmk99   Will you implement this in argo-controller ?

**Comment by Sharathmk99** [comment]
@xianlubird yes sure with you guidance. I'll get started.

**Comment by tigerwings** [comment]
@xianlubird , @Sharathmk99 , when you implement this CronWorkflow, can you please include these features similar to k8s CronJob: `successfulJobsHistoryLimit`, `failedJobsHistoryLimit` and `.spec.concurrencyPolicy`. Thanks.

**Comment by jaygorrell** [comment]
This was closed immediately after opening but has a lot of good discussion after. Can it be re-opened so it better reflects the current state?

**Comment by dtaniwaki** [comment]
I’m going to create a general crown resource which allows you to schedule any resource including Workflow. Maybe it can be helpful.

**Comment by jackywu** [comment]
@dtaniwaki cool

**Comment by ananthu1834** [comment]
@dtaniwaki Thanks. Waiting for this

**Comment by llimon** [comment]
@dtaniwaki I have something for this. Ping me next week.

**Comment by sarabala1979** [comment]
@simster7 is working CRONWorkflow. He almost through.

**Comment by llimon** [comment]
@sarabala1979 I guess great minds think a like.

**Comment by simster7** [comment]
@llimon @dtaniwaki I've been working on this for the last couple of days internally. Feel free to ping me on the slack channel (`@simon`) if there's anything you guys want to discuss

**Comment by dtaniwaki** [comment]
@llimon @simster7 Thank you for implementing the feature. My progress is not so big because I was quite busy with other things. Please feel free to go ahead discussing about it between you guys.

**Comment by llimon** [comment]
My POC was demoed to the internally with good feedback.
This is what I have all working:

Workflow scheduler and orchestration engine for Kubernetes.
Is targeted to ETL, Batch Processing, ML and where work needs to be orchestrated.

In its basic mode It runs on a cronSpec, What makes a difference is Workflows are sourced from GitHub. Allowing to have a version, PR, etc. Keeping GitOps & infrastructure as code.
```
apiVersion: workflowscheduler.argoproj.io/v1alpha1
kind: WorkflowScheduler
metadata:
  name: example-foo
spec:
  cronSpec: "*/1 * * * *"
  workflow:
    sourceType: github
    scheme: https
    repo: https://github.com/llimon/workflowscheduler-examples.git
    branch: master
    path: "workflows/hello-world.yaml"
```

The more interesting mode adds "FileWatchers". This is the ability to monitor for file patterns in repositories. Once it is detected a workflow will be initiated, This allows us to "chain" workflows and create complex Execution patterns and combining workflows. It allows controlling how frequently to verify for trigger files.


```
kind: WorkflowScheduler
metadata:
  name: workflow-load-db
spec:
  workflow:
    sourceType: github
    scheme: https
    repo: https://github.com/llimon/workflowscheduler-examples.git
    branch: master
    path: "workflows/bye-world.yaml"
  fileWatcher:
    type: s3
    bucket: argoscheduler-sample
    region: us-east-1
    AWSKeys:
      secret: example-aws-s3-secret
      accessKeyID: accessKey
      secretKeyID: secretKey
    path: transformed-file.dat
    launchExt:  ready
    finishExt:  done
    processingExt: processing
    renameOnStart: true
    renameOnFinish: true
    frequency: "@every 1m"
```
PS. * I defined AWSKeys with different format than ArgoWorkflows, I think it makes a little more sence and Does not require to lookup for multiple k8s Secret objects.
* I got feedback about possibly grouping launchExt, processingExt, finishExt and true false flags.

Current status: All POC features are functional, running locally. This week I'll be refactoring the resource name, work on travis and running inside k8s.
