### ISSUE TITLE
BUG: DAG nodes are deleted on workflow retry

### ISSUE THREAD

**Issue by CristianPop** [argoproj/argo#1242]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
DAG nodes are deleted on workflow retry and then recreated without adding the already completed children. As a result, the argo-ui ends up showing two disjoint graphs, one containing the DAG node and one containing its children.
**What you expected to happen**:
The DAG node has all children appropriately set.
**How to reproduce it (as minimally and precisely as possible)**:
Create the following workflow that always fails and retry it:
```yml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-2
spec:
  entrypoint: dag
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: "false"
    container:
      image: alpine:3.7
      command: ["false"]
  - name: dag
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: "false"
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

```
**Anything else we need to know?**:
Although it does not appear to affect the retry functionality, applications such as argo-ui and other 3rd party apps cannot rely solely on the status to recompose the DAG, but they must rely on the spec of the workflow and match the templates to the nodes. 

 I've changed the RetryWorkflow behavior to not delete DAG nodes, but to change their status to running, delete the finished timestamps and messages (similar to what happens to the workflows) and it seems to work properly. If it's not intended behavior, and the proposed solution is considered proper, I can contribute with a fix.
**Environment**:
- Argo version:
```
master branch
```
