### ISSUE TITLE
how to set host ipc in argo?

### ISSUE THREAD

**Issue by sys520084** [argoproj/argo#1244]
see title

**Comment by segabond** [comment]
```
    - name: step-1
      podSpecPatch: '{"hostIPC": true}'
      container:
        image: docker/whalesay
```

You're welcome
