### ISSUE TITLE
Support the {{inputs.artifacts.<art-name>.path}} and {{outputs.artifacts.<art-name>.path}} placeholders

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#1257]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

It's not a good practice to repeat any constant in several places. When there is a single source of truth, everything is consistent by design. When something is specified in multiple places, there is always a risk of things going out or sync and breaking.
Currently it's common to specify each artifact path in two places: One in the `inputs.artifacts[*].path` property. Another one in the command-line.

I propose adding a placeholder that allows referring to the input/output artifact path instead of copy/pasting the path. Then there's be just a single place where the path is specified. This will also allow in future to automatically generate the paths.

Example:

```
 - name: producer
    outputs:
      artifacts:
      - name: out-art
        path: /argo/outputs/out-art/data
    container:
      image: docker/whalesay:latest
      command: [sh, -c]

      #Current usage: Path has to be copy-pasted:
      args: ["cowsay hello world | tee /argo/outputs/out-art/data"]

      #Proposed usage: Path is referenced:
      args: ["cowsay hello world | tee {{outputs.artifacts.out-art.path}}"]
```
