### ISSUE TITLE
Argo incorrectly buffers logging from containerized Python

### ISSUE THREAD

**Issue by thundergolfer** [argoproj/argo#1259]
**Is this a BUG REPORT or FEATURE REQUEST?**:

_BUG REPORT_

**What happened**:

1. Deployed a simple containerized Python [subpar](https://github.com/google/subpar) with `argo submit workflow.yaml` (subpar aspect is probably irrelevant)
2. Ran `argo logs -f <OUTPUT NAME>`
3. Ran `kubectl logs -f <OUTPUT NAME> main` 

**What you expected to happen**:

Argo would stream the log output of my workflow while it was running, as `kubectl logs -f` does.

**How to reproduce it (as minimally and precisely as possible)**:

Containerize this script:

```
from loguru import logger

for _ in range(10):
    logger.info('A log line')
    sleep(1)

exit(0)
```

and invoke it in a `workflow.yaml` like: 

```
container:
        command: [python3, "script.py"]
        image: blah.dkr.ecr.us-east-1.amazonaws.com/my-image:release-xxxxx
```

**Anything else we need to know?**:

**Environment**:
- Argo version: `argo-2.2.1`
- Kubernetes version :
```
clientVersion:
  buildDate: "1970-01-01T00:00:01Z"
  compiler: gc
  gitCommit: 721bfa751924da8d1680787490c54b9179b1fed0
  gitTreeState: archive
  gitVersion: v1.13.3
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-03-01T22:49:39Z"
  compiler: gc
  gitCommit: 7c34c0d2f2d0f11f397d55a46945193a0e22d8f3
  gitTreeState: clean
  gitVersion: v1.11.8-eks-7c34c0
  goVersion: go1.10.8
  major: "1"
  minor: 11+
  platform: linux/amd64
```

**Note:** I'll try come back and add better reproducibility details. It's quite late here and I need to head off.
