### ISSUE TITLE
"wait" container cannot copy output parameter timely

### ISSUE THREAD

**Issue by vincent-pli** [argoproj/argo#1267]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:
I try to use argo in kubeflow for model training and serving.
I use the "output parameter" to deliver information to next step, like this:
```
outputs:
      parameters:
      - name: training-export
        valueFrom:
          path: /export.txt
      - name: training-model
        valueFrom:
          path: /model.txt
```
and I add below code at the end of my mode.py file in training container(first step):
```
  with open('/export.txt', 'w') as f:
    f.write(args.tf_export_dir)

  with open('/model.txt', 'w') as f:
    f.write(args.tf_model_dir)
```

But the first step always failed, and I find something like this in the "wait" container:
[sh -c docker cp -a 60ed2e641ef6e5380d0c74183ef8b47896bf52b2f7ee0f0d35d1eb4b95f3a463:/model.txt' - | tar -ax -O] stderr:\nError: No such container:path: 

**Anything else we need to know?**:
I guess the issue caused by the scenario:
when the "wait" try to copy the output parameter the "main" has already complete, so I add 
`time.sleep(600)`
at the end of model.py, then everything works.

I really want to know what exactly happen in that process, thanks
