### ISSUE TITLE
Support mounting ssh_known_hosts in init container

### ISSUE THREAD

**Issue by discordianfish** [argoproj/argo#1281]
**FEATURE REQUEST**:
Now that argo verifies host keys when, e.g checking out artefacts via ssh, we need a good way to configure known hosts.

This could be supported by allowing a user to mount a volume in the init container.

**Comment by pplavetzki** [comment]
@discordianfish not sure that this would work for you, but what I did was use the alpine/git image to clone the repo to a persistent volume.  I used a secret that contained both the ssh private key and a config file.  The config file sets UserHostsKnownFile to /dev/null.  I'm sure if you'd rather add a legitimate known_hosts file you could do that in the same way...
```
Host github.com
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
```
**Simple Workflow Example**
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: automation-install-
spec:
  entrypoint: hello-world
  volumeClaimTemplates:
  - metadata:
      name: project-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 200Mi
  volumes:
    - name: ssh-git-creds
      secret:
        defaultMode: 0600
        secretName: ssh-git-creds
        items:
          - key: ssh-privatekey
            path: id_rsa
          - key: ssh-config
            path: config
  templates:
    - name: hello-world
      steps:
        - - name: run-get-project
            template: get-project
    - name: get-project
      container:
        image: alpine/git
        command: ["git"]
        args: ["clone", "git@github.com:repo-name.git", "/var/data"]
        volumeMounts:
        - name: project-data
          mountPath: /var/data
        - name: ssh-git-creds
          mountPath: /root/.ssh
```
