### ISSUE TITLE
Executor kubectl version is obsolete

### ISSUE THREAD

**Issue by xlucas** [argoproj/argo#1287]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Steps processing manifests are failing when the cluster is running kubernetes 1.14 with the following error message: 
```
error: SchemaError(io.k8s.api.policy.v1beta1.SupplementalGroupsStrategyOptions): invalid object doesn't have additional properties
```

**What you expected to happen**:
Steps should succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Run a workflow containing a step that looks like this:

```
 - name: manifest
    inputs:
      parameters:
      - name: apply
      - name: manifest
    resource:
      manifest: "{{inputs.parameters.manifest}}"
```

**Anything else we need to know?**:
The `kubectl` version in the executor image (1.13.4) is outdated now that Kubernetes 1.14.0 has been released. I guess it also raises the following question: how can we know the compatibility of the executor with regards to the Kubernetes version, and make sure the right one is being used when submitting a workflow?

**Environment**:
- Argo version:
```
$ argo version 2.2.1
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

```
clientVersion:
  buildDate: "2019-03-25T15:53:57Z"
  compiler: gc
  gitCommit: 641856db18352033a0d96dbc99153fa3b27298e5
  gitTreeState: clean
  gitVersion: v1.14.0
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-03-25T15:45:25Z"
  compiler: gc
  gitCommit: 641856db18352033a0d96dbc99153fa3b27298e5
  gitTreeState: clean
  gitVersion: v1.14.0
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: linux/amd64
```
