### ISSUE TITLE
Error: Failed to save output for parameter-aggregation-dag.yaml

### ISSUE THREAD

**Issue by devops-42** [argoproj/argo#1306]
**BUG REPORT**

**What happened**:
Tried to run example `parameter-aggregation-dag.yaml` by issuing:
`argo submit --serviceaccount argo --watch https://raw.githubusercontent.com/argoproj/argo/master/examples/parameter-aggregation-dag.yaml --namespace=foobar`

Result was:
```
Name:                parameter-aggregation-dag-fp2nj
Namespace:           foobar
ServiceAccount:      argo
Status:              Running
Created:             Thu Apr 04 11:36:28 +0200 (11 seconds ago)
Started:             Thu Apr 04 11:36:28 +0200 (11 seconds ago)
Duration:            11 seconds

STEP                                PODNAME                                     DURATION  MESSAGE
 ● parameter-aggregation-dag-fp2nj                                                        
 ├-⚠ odd-or-even(0:1)               parameter-aggregation-dag-fp2nj-3443100683  6s        failed to save outputs: container docker://193bbdfb6ddb92489d62323268fe1135509ce9c400e77031958302d855fb894e is terminated: &ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2019-04-04 09:36:32 +0000 UTC,FinishedAt:2019-04-04 09:36:32 +0000 UTC,ContainerID:docker://193bbdfb6ddb92489d62323268fe1135509ce9c400e77031958302d855fb894e,}
 ├-⚠ odd-or-even(1:2)               parameter-aggregation-dag-fp2nj-2085598665  8s        failed to save outputs: container docker://e0d492bcb023a779b265c1d1b512ec5f46ad07c10c6510223c78618c86312035 is terminated: &ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2019-04-04 09:36:34 +0000 UTC,FinishedAt:2019-04-04 09:36:34 +0000 UTC,ContainerID:docker://e0d492bcb023a779b265c1d1b512ec5f46ad07c10c6510223c78618c86312035,}
 ├-⚠ odd-or-even(2:3)               parameter-aggregation-dag-fp2nj-1525519675  9s        failed to save outputs: timeout after 0s
 └-● odd-or-even(3:4)               parameter-aggregation-dag-fp2nj-2100276621  11s       
```

**What you expected to happen**:
Example workflow should processed successfully.

**How to reproduce it (as minimally and precisely as possible)**:
- Install argo
- Run workflow

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-06-27T20:17:28Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.2
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2019-02-08T23:07:29Z
  compiler: gc
  gitCommit: d4cacc0
  gitTreeState: clean
  gitVersion: v1.11.0+d4cacc0
  goVersion: go1.10.3
  major: "1"
  minor: 11+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
see above
```
- executor logs (wait-Container of first pod:
```
...
time="2019-04-04T09:36:34Z" level=fatal msg="container docker://193bbdfb6ddb92489d62323268fe1135509ce9c400e77031958302d855fb894e is terminated: &ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2019-04-04 09:36:32 +0000 UTC,FinishedAt:2019-04-04 09:36:32 +0000 UTC,ContainerID:docker://193bbdfb6ddb92489d62323268fe1135509ce9c400e77031958302d855fb894e,}"
```
- workflow-controller logs:
no errors

Thanks and cheers
