### ISSUE TITLE
Error: Failed to resolve result output from Task A within a DAG

### ISSUE THREAD

**Issue by devops-42** [argoproj/argo#1307]
**BUG REPORT**

**What happened**:
Tried to create a workflow containing a DAG. Wanted to use the output of task A in task B. After submitting the workflow (template below):

`argo submit --serviceaccount argo --watch task-test.yml --namespace=foobar`

Argo returned an error message:
`2019/04/04 13:24:55 Failed to submit workflow: templates.say-hello.tasks.B failed to resolve {{tasks.A.outputs.result}}
`

**What you expected to happen**:
The workflow starts and uses the output of task A in task B.

**How to reproduce it (as minimally and precisely as possible)**:
- Install Argo
- Use the following template

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: say-hello-
spec:
  entrypoint: say-hello
  arguments:
    parameters:
      - name: greeting
        value: "{{inputs.parameters.greeting}}"
  templates:
  - name: say-hello
    dag:
      tasks:
        - name: A
          template: transform-greeting
          arguments:
            parameters:
              - name: greeting
                value: "{{workflow.parameters.greeting}}"
        - name: B
          template: print-greeting
          dependencies: [A]
          arguments:
            parameters:
              - name: agreeting
                value: "{{tasks.A.outputs.result}}"

  - name: transform-greeting
    steps:
      - - name: say-hello-1
          template: say-hello-1
          arguments:
            parameters:
              - name: greeting1
                value: "{{workflow.parameters.greeting}}"

  - name: print-greeting
    inputs:
      parameters:
        - name: agreeting
    steps:
      - - name: echo
          template: echo
          arguments:
            parameters:
              - name: agreeting
                value: "{{inputs.parameters.agreeting}}"

  - name: say-hello-1
    inputs:
      parameters:
        - name: greeting1
    script:
      image: bash:4
      command: ["bash"]
      source: |
        echo "First greeting: {{inputs.parameters.greeting1}}")

  - name: echo
    inputs:
      parameters:
        - name: agreeting
    script:
      image: bash:4
      command: ["bash"]
      source: |
        echo "Finally: {{inputs.parameters.agreeting}}")
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-06-27T20:17:28Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.2
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2019-02-08T23:07:29Z
  compiler: gc
  gitCommit: d4cacc0
  gitTreeState: clean
  gitVersion: v1.11.0+d4cacc0
  goVersion: go1.10.3
  major: "1"
  minor: 11+
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- workflow result:
```
see above
```
- executor logs:
```
not relevant, workflow has not submitted
```
- workflow-controller logs:
```
not relevant, workflow has not submitted
```

Thanks for your help!
