### ISSUE TITLE
Workflows fail if the name is longer than 63 characters

### ISSUE THREAD

**Issue by ian-howell** [argoproj/argo#1324]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
When a workflow is given a name which happens to be longer than 63 characters, the workflow fails.

**What you expected to happen**:
The workflow to not fail.

**How to reproduce it (as minimally and precisely as possible)**:
The following YAML will create a Workflow which will fail.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: arbitrarily-long-name-which-just-so-happens-to-be-longer-than-63-characters
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

**Anything else we need to know?**:
I'm pretty sure the root cause is because of the [limit on label lengths](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)
