### ISSUE TITLE
Workflow level artifact archive locations with configmap reference

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#1332]
Currently, with output artifacts, users are doing one of several things:

1. configuring a controller level artifact repository (in workflow-controller-configmap), and allowing outputs to go to the default location

2. specifying it at a template level:

```yaml
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    archiveLocation:
      s3:
        endpoint: s3.amazonaws.com
        bucket: my-bucket
        key: path/in/bucket/hello_world.txt.tgz
        accessKeySecret:
          name: my-s3-credentials
          key: accessKey
        secretKeySecret:
          name: my-s3-credentials
          key: secretKey
    outputs:
      artifacts:
      - name: message
        path: /tmp
```

3. hardwiring a location at an individual artifact level. e.g.

```yaml
    outputs:
      artifacts:
      - name: message
        path: /tmp
        s3:
          endpoint: s3.amazonaws.com
          bucket: my-bucket
          key: path/in/bucket/hello_world.txt.tgz
          accessKeySecret:
            name: my-s3-credentials
            key: accessKey
          secretKeySecret:
            name: my-s3-credentials
            key: secretKey
```

In multi-tenant clusters, a "default" archive repository will not be configured. In place of that, it would be useful for a workflow to reference a configmap to archive location. For example:

```yaml
kind: Workflow
metadata:
  generateName: output-artifact-s3-
spec:
  entrypoint: whalesay
  archiveLocationConfig:
    name: archive-location-configmap
    key: config
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: message
        path: /tmp
```
