### ISSUE TITLE
Workflow step showed running after pod got deleted, impossible to terminate

### ISSUE THREAD

**Issue by discordianfish** [argoproj/argo#1341]
**BUG REPORT**

**What happened**:
I saw a workflow step not finishing. Terminating the workflow didn't work. Investigation showed that the pod got deleted (yet unclear why, maybe autoscaling evicted it).

**What you expected to happen**:
- The workflow step should fail if the pod gets deleted/evicted
- Terminating the workflow should fail the step, no matter what happened with the pod

**How to reproduce it (as minimally and precisely as possible)**:
I don't know if it's reproducable like this, but I'd try to start a workflow and remove the pod from a running workflow step.

**Environment**:
- Argo version: v2.2.1
- Upgraded to 2.3.0-rc2 after this happened to see if it would fix this but it didn't

- Kubernetes version: v1.11.2 (server), v1.14.1 (client)

**Other debugging information (if applicable)**:
- workflow result: (sorry, didn't get the yaml so only describe output. Status field should be enough I hope:
```
Status:
  Finished At:  <nil>
  Nodes:
    Ci - xx - 8 W 9 Dg:
      Children:
        ci-XXX-8w9dg-1038100541
      Display Name:   ci-XXX-8w9dg
      Finished At:    <nil>
      Id:             ci-XXX-8w9dg
      Name:           ci-XXX-8w9dg
      Phase:          Running
      Started At:     2019-04-13T01:15:03Z
      Template Name:  ci
      Type:           DAG
    Ci - xx - 8 W 9 Dg - 1038100541:
      Boundary ID:  ci-XXX-8w9dg
      Children:
        ci-XXX-8w9dg-1961627753
      Display Name:  init
      Finished At:   2019-04-13T01:15:10Z
      Id:            ci-XXX-8w9dg-1038100541
      Inputs:
        Artifacts:
          Git:
            Repo:      git@yyy/XXX.git
            Revision:  b5e36001181e0776ac6dc96becb33d900d79075c
            Ssh Private Key Secret:
              Key:   id_rsa
              Name:  github-ssh-keys
          Name:      source
          Path:      /src
        Parameters:
          Name:       script
          Value:      ZZZ-ci-init
      Name:           ci-XXX-8w9dg.init
      Phase:          Succeeded
      Started At:     2019-04-13T01:15:03Z
      Template Name:  ci-tools
      Type:           Pod
    Ci - xx - 8 W 9 Dg - 1961627753:
      Boundary ID:  ci-XXX-8w9dg
      Children:
        ci-XXX-8w9dg-2181297783
      Display Name:  build
      Finished At:   2019-04-13T01:17:00Z
      Id:            ci-XXX-8w9dg-1961627753
      Inputs:
        Artifacts:
          Git:
            Repo:      git@yyy/XXX.git
            Revision:  b5e36001181e0776ac6dc96becb33d900d79075c
            Ssh Private Key Secret:
              Key:   id_rsa
              Name:  github-ssh-keys
          Name:      source
          Path:      /src
        Parameters:
          Name:       script
          Value:
      Name:           ci-XXX-8w9dg.build
      Phase:          Succeeded
      Started At:     2019-04-13T01:15:10Z
      Template Name:  build
      Type:           Pod
    Ci - xx - 8 W 9 Dg - 2181297783:
      Boundary ID:    ci-XXX-8w9dg
      Display Name:   test
      Finished At:    <nil>
      Id:             ci-XXX-8w9dg-2181297783
      Name:           ci-XXX-8w9dg.test
      Phase:          Running
      Started At:     2019-04-13T01:17:01Z
      Template Name:  test
      Type:           Pod
  Phase:              Running
  Started At:         2019-04-13T01:15:03Z
Events:               <none>
```
- executor logs: pod is gone, so can't say
- workflow-controller logs: Nothing I can find beside api request logging etc

**Comment by discordianfish** [comment]
@jessesuen I've got a similar issue. Should I open a new issue for that or do you think it's due to the same underlying issue?

In this case the pod is Errored (the main container exited with 1) but some sidecar containers are still running. Maybe similar to #879?

I see this `workflows.argoproj.io/node-message` annotation:

      Error response from daemon: Cannot kill container:
      20b3f1e602b3577e252ead6c55c1b4a73a69a48b0d50a549b5c14610398cc142: Container
      20b3f1e602b3577e252ead6c55c1b4a73a69a48b0d50a549b5c14610398cc142 is not running

Which is a sidecar that got restarted once but is currently running:
```
  - containerID: docker://78b1390fede02f47e8a97f17b7d4742551365e459b3655a7c78e39c9ee6e74dc
    image: postgres:9.5
    imageID: docker-pullable://postgres@sha256:5433865ca676081f1c8bf0998451273e8afc2a2ffa6cfc33fda6f396bdd6b526
    lastState:
      terminated:
        containerID: docker://20b3f1e602b3577e252ead6c55c1b4a73a69a48b0d50a549b5c14610398cc142
        exitCode: 0
        finishedAt: null
        startedAt: null
    name: postgres
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2019-05-07T02:51:15Z"
```

Maybe a race condition? e.g argo tried to kill it while it was terminated, so it failed - but it got restarted by k8s right after, preventing argo from cleaning up the remaining pods?

Deleting the pod manually manually worked though.
