### ISSUE TITLE
How to use default artifactory with input artifacts?

### ISSUE THREAD

**Issue by Kamforka** [argoproj/argo#1377]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Both

**What happened**: 
I wanted to access the default artifactory for  input artifacts.
When I set up a default artifactory (I'm using minio locally at the moment) it works fine with output artifacts, as I don't have to set anything else in the workflow to specify the output location.
However I couldn't figure out how to use the same pattern with input artifacts, so I had to use the `s3` section of the artifact schema and specify every detail about the artifactory I want to get the data from.
It works okay after that, but the workflow definition looks quite ugly and not really DRY as you can see below.

```yaml
artifacts: 
- name: model1
    s3:
    bucket: my-bucket
    key: model1.py
    endpoint: argo-artifacts-minio.default:9000
    insecure: true
    accessKeySecret:
        name: argo-artifacts-minio
        key: accesskey
    secretKeySecret:
        name: argo-artifacts-minio
        key: secretkey
- name: model1-input1
    s3:
    bucket: my-bucket
    key: model1_input1.csv
    endpoint: argo-artifacts-minio.default:9000
    insecure: true
    accessKeySecret:
        name: argo-artifacts-minio
        key: accesskey
    secretKeySecret:
        name: argo-artifacts-minio
        key: secretkey
- name: model1-input2
    path: model1_input2.csv
    s3:
    bucket: my-bucket
    key: model1_input2.csv
    endpoint: argo-artifacts-minio.default:9000
    insecure: true
    accessKeySecret:
        name: argo-artifacts-minio
        key: accesskey
    secretKeySecret:
        name: argo-artifacts-minio
        key: secretkey
```
**What you expected to happen**:

Instead I would love to see something similar to this when using the default artifactory for inputs:

```yaml
artifacts: 
- name: model1
  path: model1.py
- name: model1-input1
  path: model1_input1.csv
- name: model1-input2
  path: model1_input2.csv
```

The benefit is obvious, the artifact definitions become much concise.

However this schema is not yet supported as I get the following error message:

`2019/05/27 10:28:37 Failed to submit workflow: templates.sample-dag.tasks.model1-runner.arguments.model1-input2.from or artifact location is required`

**How to reproduce it (as minimally and precisely as possible)**:

You can see the full workflow definition below:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sample-dag-
spec:
  entrypoint: sample-dag
  templates:
  - name: sample-dag
    dag:
      tasks:
      - name: model1-runner 
        template: model1
        arguments:
          artifacts: 
            - name: model1
              s3:
                bucket: my-bucket
                key: model1.py
                endpoint: argo-artifacts-minio.default:9000
                insecure: true
                accessKeySecret:
                  name: argo-artifacts-minio
                  key: accesskey
                secretKeySecret:
                  name: argo-artifacts-minio
                  key: secretkey
            - name: model1-input1
              s3:
                bucket: my-bucket
                key: model1_input1.csv
                endpoint: argo-artifacts-minio.default:9000
                insecure: true
                accessKeySecret:
                  name: argo-artifacts-minio
                  key: accesskey
                secretKeySecret:
                  name: argo-artifacts-minio
                  key: secretkey
            - name: model1-input2
              path: model1_input2.csv
              s3:
                bucket: my-bucket
                key: model1_input2.csv
                endpoint: argo-artifacts-minio.default:9000
                insecure: true
                accessKeySecret:
                  name: argo-artifacts-minio
                  key: accesskey
                secretKeySecret:
                  name: argo-artifacts-minio
                  key: secretkey
 - name: model1
    container:
      image: python-generic 
      imagePullPolicy: Never
      command: [sh, -c]
      args: ["python /model1.py --input1 /model1_input1.csv --input2 /model1_input2.csv --output1 /model1_output1.csv"]
    inputs:
      artifacts:
      - name: model1
        path: /model1.py
      - name: model1-input1
        path: /model1_input1.csv
      - name: model1-input2
        path: /model1_input2.csv
    outputs:
      artifacts:
      - name: model1-output1 
        path: /model1_output1.csv
```

**Anything else we need to know?**:

Nope.

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-11-26T14:38:32Z
  compiler: gc
  gitCommit: 637c7e288581ee40ab4ca210618a89a555b6e7e9
  gitTreeState: clean
  gitVersion: v1.10.11
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-11-26T14:25:46Z
  compiler: gc
  gitCommit: 637c7e288581ee40ab4ca210618a89a555b6e7e9
  gitTreeState: clean
  gitVersion: v1.10.11
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```
