### ISSUE TITLE
Unable to resolve {{item.<fieldname>}} when using multiple steps with different withParam filters

### ISSUE THREAD

**Issue by djworth** [argoproj/argo#1379]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
```
Name:                argo-bug-f6bgs
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             failed to resolve {{item.firstdate}}
Created:             Thu May 23 19:43:29 -0400 (20 seconds ago)
Started:             Thu May 23 19:43:29 -0400 (20 seconds ago)
Finished:            Thu May 23 19:43:49 -0400 (now)
Duration:            20 seconds

STEP                                                        PODNAME                    DURATION  MESSAGE
 ✖ argo-bug-f6bgs                                                                                failed to resolve {{item.firstdate}}
 ├---✔ step0                                                argo-bug-f6bgs-328698384   8s
 ├---✔ step1(0:first_date:1970-01-01,last_date:2019-05-23)  argo-bug-f6bgs-2424513170  4s
 ├---✔ step2(0:first_date:1970-01-01,last_date:2019-05-23)  argo-bug-f6bgs-941670032   5s
```

**What you expected to happen**:
I expected step3 to execute as expected and not report a failure.

**How to reproduce it (as minimally and precisely as possible)**:
argo submit --watch bug.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-bug-
spec:
  entrypoint: start
  templates:
  - name: start
    steps:
    - - name: step0
        template: fetch-dates
    - - name: step1
        template: data-pull
        arguments:
          parameters:
          - name: lastdate
            value: "{{item.last_date}}"
        withParam: "{{steps.step0.outputs.result}}"
    - - name: step2
        template: gen-cohorts
        arguments:
          parameters:
          - name: firstdate
            value: "{{item.first_date}}"
          - name: lastdate
            value: "{{item.last_date}}"
        withParam: "{{steps.step0.outputs.result}}"

    - - name: step3
        template: cohort-processing
        arguments:
          parameters:
          - name: lastdate
            value: "{{item.lastdate}}"
          - name: cohort
            value: "{{item.cohort}}"
          - name: firstdate
            value: "{{item.firstdate}}"
        withParam: "{{steps.step2.outputs.result}}"

  - name: fetch-dates
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json, sys
        json.dump([{'first_date': '1970-01-01', 'last_date': '2019-05-23'}], sys.stdout)


  - name: gen-cohorts
    inputs:
      parameters:
      - name: firstdate
      - name: lastdate
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import os, json, sys
        cohorts = ['cohort_01', 'cohort_02', 'cohort_03', 'cohort_04', 'cohort_05']
        json.dump([{'cohort': cohort, 'firstdate': '{{inputs.parameters.firstdate}}', 'lastdate': '{{inputs.parameters.lastdate}}'} for cohort in cohorts], sys.stdout)

  - name: data-pull
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        print("do stuff that pulls data...")

  - name: cohort-processing
    inputs:
      parameters:
      - name: cohort
      - name: firstdate
      - name: lastdate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.cohort}} {{inputs.parameters.firstdate}} {{inputs.parameters.lastdate}}" ]
```

**Anything else we need to know?**:
I reported this bug in the slack channel as well.
https://argoproj.slack.com/archives/C8J6SGN12/p1558645558444000

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2019-03-25T02:52:13Z
  compiler: gc
  gitCommit: 6f482974b76db3f1e0f5d24605a9d1d38fad9a2b
  gitTreeState: clean
  gitVersion: v1.12.7
  goVersion: go1.10.8
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2019-04-03T01:27:32Z
  compiler: gc
  gitCommit: 035e49d66342c7c6ac569c68721f0a821d2df6f5
  gitTreeState: clean
  gitVersion: v1.12.6-gke.11
  goVersion: go1.10.8b4
  major: "1"
  minor: 12+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```
