### ISSUE TITLE
Retry resource template on apply + AlreadyExists error

### ISSUE THREAD

**Issue by epa095** [argoproj/argo#1380]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Both?

**What happened**:
Have several steps/workflows which all use resource template to *apply* the same resource (a service in my case). Sometimes, if they all happen at the same time, one can get a 
error `"executor error: Error from server (AlreadyExists): error when creating \"/tmp/manifest.yaml\":... `
This is probably because of [this](https://github.com/kubernetes/kubernetes/issues/44165) kubernetes issue, essentially that `kubectl apply` is not as declarative as one would think, and that it is prone to race conditions. In cases like that it should be safe for Argo to retry the apply. #1370 would help a bit, but this issue here is more specific, and I think it is safe to retry these steps in general.

**What you expected to happen**:
The resource to be applied.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version :
```
clientVersion:
  buildDate: 2018-11-26T12:57:14Z
  compiler: gc
  gitCommit: 435f92c719f279a3a67808c80521ea17d5715c66
  gitTreeState: clean
  gitVersion: v1.12.3
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
serverVersion:
  buildDate: 2019-03-25T15:19:22Z
  compiler: gc
  gitCommit: 2166946f41b36dea2c4626f90a77706f426cdea2
  gitTreeState: clean
  gitVersion: v1.13.5
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64

```
