### ISSUE TITLE
Running Argo on hybrid Kubernetes cluster

### ISSUE THREAD

**Issue by mkfp** [argoproj/argo#1383]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST?
I couldn't find a way to solve.

**What happened**:
I want to run argo on a hybrid Kubernetes Linux/Windows cluster.
When I run it on windows node, I got an error on mounting /var/run/docker.sock,
or running an image argoproj/argoexec:v2.3.0.
Does argo support Windows?
If not, are there any plans for future support?

**Environment**:
- Argo version:
```
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:09Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
(on Windows worker node)
```
clientVersion:
  buildDate: "2019-04-08T17:11:31Z"
  compiler: gc
  gitCommit: b7394102d6ef778017f2ca4046abbaa23b88c290
  gitTreeState: clean
  gitVersion: v1.14.1
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: windows/amd64
serverVersion:
  buildDate: "2019-04-08T17:02:58Z"
  compiler: gc
  gitCommit: b7394102d6ef778017f2ca4046abbaa23b88c290
  gitTreeState: clean
  gitVersion: v1.14.1
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: linux/amd64
```
