### ISSUE TITLE
Specify copies of generic worker

### ISSUE THREAD

**Issue by jjsentian** [argoproj/argo#1385]
Is it possible to specify that 5 copies of x should run after y is done?
I want to run multiple workers that get tasks from an external queue.

Right now I'm doing this but can I specify that I want 5 workers instead?

```
    - - name: worker
        template: worker
        withItems:
          - a
          - b
          - c
```
