### ISSUE TITLE
Delete Calls should return a 404 when resource does not exist

### ISSUE THREAD

**Issue by samkeet** [argoproj/argo#1398]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE

**What happened**:
When deleting Argo application programmatically with REST calls, if the application is not found the response is a 500 Server Error

**What you expected to happen**:
Delete calls to Argo application should return a 404 Not Found if the application does not exist

**How to reproduce it (as minimally and precisely as possible)**:
Make a curl request to delete an Argo application which does not exist.

**Environment**:
- Argo version:
```
$ argo version 
```
`v2.2.1`

- Kubernetes version :
```
$ kubectl version -o yaml
```
```
clientVersion:
  buildDate: "2019-04-19T22:12:47Z"
  compiler: gc
  gitCommit: b7394102d6ef778017f2ca4046abbaa23b88c290
  gitTreeState: clean
  gitVersion: v1.14.1
  goVersion: go1.12.4
  major: "1"
  minor: "14"
  platform: darwin/amd64
```
