### ISSUE TITLE
Workflow with daemon does not proceed to next steps

### ISSUE THREAD

**Issue by Duske** [argoproj/argo#1410]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
When I apply any daemon-example from `examples/`, only the first pod - the daemon - gets created. The workflow itself gets stuck there and never proceeds to the following steps.
It does not make a difference if its dag- or step-based.

The systems runs with **k3s** with **containerd** and **PNS** enabled

**What you expected to happen**:
The daemon keeps running until the workflow finishes while the other steps are executed.

**How to reproduce it (as minimally and precisely as possible)**:
Use PNS and apply the following minimal workflow:
```
apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: daemon-nginx-
spec:
  entrypoint: daemon-nginx-example

  templates:
  - name: daemon-nginx-example
    steps:
    - - name: nginx-server
        template: nginx-server
    - - name: nginx-client
        template: nginx-client
        arguments:
          parameters:
          - name: server-ip
            value: "{{steps.nginx-server.ip}}"

  - name: nginx-server
    daemon: true
    container:
      image: nginx:1.13

  - name: nginx-client
    inputs:
      parameters:
      - name: server-ip
    container:
      image: appropriate/curl:latest
      command: ["/bin/sh", "-c"]
      args: ["echo curl --silent -G http://{{inputs.parameters.server-ip}}:80/ && curl --silent -G http://{{inputs.parameters.server-ip}}:80/"]

```

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.3.0
```
$ argo version
```
- Kubernetes version : k3s 0.5.0
```
clientVersion:
  buildDate: "2019-03-26T00:04:52Z"
  compiler: gc
  gitCommit: 641856db18352033a0d96dbc99153fa3b27298e5
  gitTreeState: clean
  gitVersion: v1.14.0
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: 2019-04-15T22:13+00:00Z
  compiler: gc
  gitCommit: 52f3b42401c93c36467f1fd6d294a3aba26c7def
  gitTreeState: clean
  gitVersion: v1.14.1-k3s.4
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                daemon-nginx-zlr22
Namespace:           default
ServiceAccount:      default
Status:              Running
Created:             Mon Jun 10 20:03:40 +0200 (9 minutes ago)
Started:             Mon Jun 10 20:03:41 +0200 (9 minutes ago)
Duration:            9 minutes 9 seconds

STEP                   PODNAME                        DURATION  MESSAGE
 ● daemon-nginx-zlr22                                           
 └---◷ nginx-server    daemon-nginx-zlr22-2200222121  9m        ContainerCreating
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
wait:

time="2019-06-10T18:03:42Z" level=info msg="Creating PNS executor (namespace: default, pod: daemon-nginx-zlr22-2200222121, pid: 7, hasOutputs: false)"
time="2019-06-10T18:03:42Z" level=info msg="Executor (version: v2.3.0, build_date: 2019-05-20T22:10:54Z) initialized (pod: default/daemon-nginx-zlr22-2200222121) with template:\n{\"name\":\"nginx-server\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"daemon\":true,\"container\":{\"name\":\"\",\"image\":\"nginx:1.13\",\"resources\":{}}}"
time="2019-06-10T18:03:42Z" level=info msg="Waiting on main container"
time="2019-06-10T18:03:42Z" level=error msg="executor error: Failed to establish pod watch: unknown (get pods)\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapErrorf\n\t/go/src/github.com/argoproj/argo/errors/errors.go:78\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).waitMainContainerStart\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:885\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).Wait\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:856\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:32\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
time="2019-06-10T18:03:42Z" level=info msg="No sidecars"
time="2019-06-10T18:03:42Z" level=info msg="No output parameters"
time="2019-06-10T18:03:42Z" level=info msg="No output artifacts"
time="2019-06-10T18:03:42Z" level=info m
```
- workflow-controller logs:
```
time="2019-06-10T18:03:41Z" level=info msg="Processing workflow" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:41Z" level=info msg="Updated phase  -> Running" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:41Z" level=info msg="Steps node daemon-nginx-zlr22 (daemon-nginx-zlr22) initialized Running" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:41Z" level=info msg="StepGroup node daemon-nginx-zlr22[0] (daemon-nginx-zlr22-1130168961) initialized Running" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:41Z" level=info msg="Created pod: daemon-nginx-zlr22[0].nginx-server (daemon-nginx-zlr22-2200222121)" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:41Z" level=info msg="Pod node daemon-nginx-zlr22[0].nginx-server (daemon-nginx-zlr22-2200222121) initialized Pending" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:41Z" level=info msg="Workflow step group node daemon-nginx-zlr22[0] (daemon-nginx-zlr22-1130168961) not yet completed" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:41Z" level=info msg="Workflow update successful" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:42Z" level=info msg="Processing workflow" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:42Z" level=info msg="Updating node daemon-nginx-zlr22[0].nginx-server (daemon-nginx-zlr22-2200222121) message: ContainerCreating"
time="2019-06-10T18:03:42Z" level=info msg="Workflow step group node daemon-nginx-zlr22[0] (daemon-nginx-zlr22-1130168961) not yet completed" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:42Z" level=info msg="Workflow update successful" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:43Z" level=info msg="Processing workflow" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:43Z" level=info msg="Workflow step group node daemon-nginx-zlr22[0] (daemon-nginx-zlr22-1130168961) not yet completed" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:54Z" level=info msg="Processing workflow" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:03:54Z" level=info msg="Workflow step group node daemon-nginx-zlr22[0] (daemon-nginx-zlr22-1130168961) not yet completed" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:05:31Z" level=info msg="Alloc=4209 TotalAlloc=46203 Sys=70590 NumGC=50 Goroutines=80"
time="2019-06-10T18:10:31Z" level=info msg="Alloc=4153 TotalAlloc=46239 Sys=70590 NumGC=53 Goroutines=80"
time="2019-06-10T18:10:31Z" level=info msg="Processing workflow" namespace=default workflow=daemon-nginx-zlr22
time="2019-06-10T18:10:31Z" level=info msg="Workflow step group node daemon-nginx-zlr22[0] (daemon-nginx-zlr22-1130168961) not yet completed" namespace=default workflow=daemon-nginx-zlr22

```
