### ISSUE TITLE
Script attribute does not properly read script contents

### ISSUE THREAD

**Issue by jbmcfarlin31** [argoproj/argo#1418]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**:
I am writing an argo workflow that runs a script and outputs that result into another template step. For testing, I am simply writing a quick file on the fly. The following is my yaml:
```
 - name: kustomize
    inputs:
      parameters:
      - name: kustomized
    script:
      image: myimage
      command: [bash]
      source: |
        echo '{{inputs.parameters.kustomized}}' > /tmp/kompose.yaml && cd /tmp

        cat <<EOF > kustomization.yaml
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        namespace: default
        resources:
        - kompose.yaml
        EOF

        kustomize build -o kustomized.yaml
        cat kustomized.yaml
```

The part of the script that fails is when it reaches the `cat ...` part. The pod that runs this part outputs the following error in the logs:
```
cat: can't open 'apiVersion:': No such file or directory
cat: can't open 'v1': No such file or directory
sh: kind:: not found
sh: metadata:: not found
sh: annotations:: not found
sh: kompose.cmd:: not found
sh: kompose.service.type:: not found
sh: syntax error: unexpected "("
```

**What you expected to happen**:
I expected that the script block would have read it like a normal bash prompt and cat'd those lines into a file.

**How to reproduce it (as minimally and precisely as possible)**:
Create an argo workflow that utilizes a script block, enter in:
```script:
     image: busybox
     command: [bash]
     source: | 
          cat <<EOF > test.yaml
          hello world
          EOF
```

**Anything else we need to know?**: The `cat` command works fine on every linux terminal I tried it on so I don't think it is a syntax issue.

**Environment**: Ubuntu 16.04 in Azure Stack
- Argo version: 2.2.1
```
$ argo version
```
- Kubernetes version : 1.13.5
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result: Failed
