### ISSUE TITLE
Variable substitution in envrionment

### ISSUE THREAD

**Issue by hnykda** [argoproj/argo#1432]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST/Question

**What happened**:
I need to get workflow ID (worfklow.uid) inside the pod of a step, but it seems that the variable is not expanding in `env` spec block.

**What you expected to happen**:
I would be able to have `{{wofklow.label...}` or `{{worfklow.uid}}` in the environment variable inside the pod.

**How to reproduce it (as minimally and precisely as possible)**:
I would like to do something like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      env:
        - name: WORKFLOW_UID
          value: "{{worfklow.uid}}"
          # or even the below, but that doesn't even serialize to json
          # value: "{{workflow.labels.workflows.argoproj.io/controller-instanceid}}"
```
but it doesn't resolve, ie. its present as `"WORKFLOW_UUID": "{{worfklow.uid}}"` inside the pod. Is there any way how to get some of these global variables into env variables, or are the input parameters the only way?

It's quite unclear in what context the [variables](https://github.com/argoproj/argo/blob/master/docs/variables.md) can be used. It seems that it [should](https://github.com/argoproj/argo/blob/master/examples/README.md#parameters) be supported, but I can't make it work with global parameters

**Environment**:
- Argo version: 
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:09Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version : 1.13
