### ISSUE TITLE
unable to clone repositories using git

### ISSUE THREAD

**Issue by mohbilly** [argoproj/argo#1434]
**Bug Report **:

**What happened**:
I tried using the example posted using git artifacts and it didn't work producing an **exit error 128**
I tried with git clone 
      command: [sh, -c]
      args: ["mkdir /src && cd /src &&
              git clone -v https://github.com/argoproj/argo.git"]
and it gave me this error: 
Cloning into 'argo'...
fatal: unable to access 'https://github.com/argoproj/argo.git/': Could not resolve host: github.com
**What you expected to happen**:
I expected the repo to be cloned and I tried 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
<img width="385" alt="Screen Shot 2019-06-19 at 7 58 47 AM" src="https://user-images.githubusercontent.com/34221965/59764388-ae007e00-9269-11e9-93e6-0b7b2a60909d.png">

- Kubernetes version :
<img width="392" alt="Screen Shot 2019-06-19 at 7 59 07 AM" src="https://user-images.githubusercontent.com/34221965/59764414-ba84d680-9269-11e9-989b-2665dd37325e.png">

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
<img width="871" alt="Screen Shot 2019-06-19 at 8 11 26 AM" src="https://user-images.githubusercontent.com/34221965/59764486-df794980-9269-11e9-8fb6-3d7a5ea4aaac.png">
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
<img width="1656" alt="Screen Shot 2019-06-19 at 8 13 55 AM" src="https://user-images.githubusercontent.com/34221965/59764678-44cd3a80-926a-11e9-82c3-7b34b2c9b807.png">

$ kubectl logs <failedpodname> -c wait
<img width="1654" alt="Screen Shot 2019-06-19 at 8 13 24 AM" src="https://user-images.githubusercontent.com/34221965/59764669-3ed75980-926a-11e9-8af5-27e670a45e6d.png">

**Comment by sarabala1979** [comment]
I am not able to reproduce this issue. Can you provide more information to reproduce it?
Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: git-clone-
spec:
  entrypoint: git-clone-example
  templates:
  - name: git-clone-example
    steps:
    - - name: clone
        template: clone-message

  - name: clone-message
    container:
      image: alpine/git:latest
      command: [sh, -c]
      args: ["mkdir /src && cd /src &&
      git clone -v https://github.com/argoproj/argo.git"]
```
output:

![image](https://user-images.githubusercontent.com/33908564/61238141-e8d2c600-a6f0-11e9-9845-fa64988cb75e.png)
