### ISSUE TITLE
Accessing `metadata.selfLink` Variable

### ISSUE THREAD

**Issue by Azza292** [argoproj/argo#1448]
I would like to access `metadata.selfLink` when providing an argument to a pod - Is this possible?

**eg.**
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ['<command>', `{{worfklow.selfLink}}`]
```

Also, Is there a list containing every global variable accessible from within the workflow?
Edit: Found it - https://github.com/argoproj/argo/blob/master/docs/variables.md
