### ISSUE TITLE
Forwarding of the value of the loop parameter in a nested workflow

### ISSUE THREAD

**Issue by clementrey** [argoproj/argo#1491]
Hello 

**Is this a BUG REPORT or FEATURE REQUEST?**:
I am not sure but  I would classify it as a bug

**What happened**:

I am trying to run a nested workflow inside a loop but unfortunately the value of the loop parameter is not forward to the nested workflow

**What you expected to happen**:

I would to forward the value my loop argument to my nested workflow; use it as in an input of my producer, and then use the result in my consumer.

**How to reproduce it (as minimally and precisely as possible)**:
workflow descrition :
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
 generateName: loop-with-nested-worflow-
spec:
 entrypoint: loop-with-nested-worflow
 templates:  
 - name: loop-with-nested-worflow
   steps:
   - - name: nested-workflow
       template: nested-workflow
       arguments:
         parameters:
         - name: message
           value: "{{item}}"
       withItems:
       - world
       - linux
       - docker
 - name: nested-workflow
   inputs:
     parameters:
     - name: message
   steps:
   - - name: producer
       template: producer
       arguments:
        parameters:
        - name : message 
          value: "{{inputs.parameters.message}}"
   - - name: consumer
       template: consumer
       arguments:
         parameters:
         - name: generated-message
           value: "{{steps.producer.outputs.parameters.generated-message}}"
 - name: producer
   inputs:
     parameters:
     - name: message
   outputs:
     parameters:
     - name: generated-message
       valueFrom:
         path: /tmp/file.txt
   container:
    image: alpine
    imagePullPolicy: Always
    command: ["sh"]
    args: ["-c","echo hello {{inputs.parameters.message}};echo hello {{inputs.parameters.message}} > /tmp/file.txt"]  
 - name: consumer
   inputs:
     parameters:
      - name: generated-message
   container:
     image: alpine
     command: ["sh"]
     args: ["-c","echo my generated message is {{inputs.parameters.generated-message}}"]

```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:09Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-06-19T16:40:16Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-03-25T15:19:22Z"
  compiler: gc
  gitCommit: 2166946f41b36dea2c4626f90a77706f426cdea2
  gitTreeState: clean
  gitVersion: v1.13.5
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- workflow result:
I can submit that workflow:
```
$ argo submit loop-with-nested-workflow.yaml 
Name:                loop-with-nested-worflow-4v5hh
Namespace:           default
ServiceAccount:      default
Status:              Pending
Created:             Fri Jul 19 08:23:42 +0200 (now)
```

Then I got :
```
$ argo get loop-with-nested-worflow-4v5hh
Name:                loop-with-nested-worflow-4v5hh
Namespace:           default
ServiceAccount:      default
Status:              Succeeded
Created:             Fri Jul 19 08:23:42 +0200 (23 seconds ago)
Started:             Fri Jul 19 08:23:42 +0200 (23 seconds ago)
Finished:            Fri Jul 19 08:24:05 +0200 (now)
Duration:            23 seconds

STEP                               PODNAME                                    DURATION  MESSAGE
 ✔ loop-with-nested-worflow-4v5hh                                                       
 └-·-✔ nested-workflow(0:world)                                                         
   | ├---✔ producer                loop-with-nested-worflow-4v5hh-4103167869  9s        
   | └---✔ consumer                loop-with-nested-worflow-4v5hh-2663109320  9s        
   ├-✔ nested-workflow(1:linux)                                                         
   | ├---✔ producer                loop-with-nested-worflow-4v5hh-2070960326  6s        
   | └---✔ consumer                loop-with-nested-worflow-4v5hh-105746203   8s        
   └-✔ nested-workflow(2:docker)                                                        
     ├---✔ producer                loop-with-nested-worflow-4v5hh-833034627   9s        
     └---✔ consumer                loop-with-nested-worflow-4v5hh-2069507746  9s 
```
then if I displayed the logs for the linux iteration I got the following output:
```
$ argo logs loop-with-nested-worflow-4v5hh-2070960326
hello world
```
I was expecting "hello linux"

Is it possible to run a nested workflow inside and to the forward the value of the loop parameter into the most inner template ?

Thank you very much
