### ISSUE TITLE
How to access an artifact from sibling's nested step?

### ISSUE THREAD

**Issue by raftAtGit** [argoproj/argo#1497]
**Is this a BUG REPORT or FEATURE REQUEST?**: Not sure

Considering a workflow like below, how to access an artifact created by A from B1 or B2?

`{{steps.A.outputs.artifacts.artifact}}` is not working in this case, both CLI and controller are complaining about it's not resolved.

```
templates:
- name: entry
  steps:
  - - name: A
      template: A
  - - name: B
      template: B
  - name: B
    steps:
    - - name: B1
        template: B1
		arguments:
          artifacts:
          - name: artifact
            from: "{{steps.A.outputs.artifacts.artifact}}"
    - - name: B2
        template: B2

- name: A
  container: ..
  outputs:
    artifacts:
    - name: artifact
      path: ..
- name: B1
  container: ..
- name: B2
  container: ..
```

**Comment by samath117** [comment]
You need to pass it from A to B1 via B. Here's what that looks like:

```
templates:
- name: entry
  steps:
  - - name: A
      template: A
  - - name: B
      template: B
      arguments:
        artifacts:
        - name: artifact
          from: "{{steps.A.outputs.artifacts.artifact}}"
  - name: B
    inputs:
      artifacts:
      - name: artifact
    steps:
    - - name: B1
        template: B1
		arguments:
          artifacts:
          - name: artifact
            from: "{{inputs.artifacts.artifact}}"
    - - name: B2
        template: B2

- name: A
  container: ..
  outputs:
    artifacts:
    - name: artifact
      path: ..
- name: B1
  container: ..
- name: B2
  container: ..
```

**Comment by raftAtGit** [comment]
Thanks, but this didnt work for me. 

In my case, **A** and **B** are not top level templates but nested ones. In the original question I omitted that for brevity. Maybe this is the reason?

How to access artifact created by A from B1 or B2 in this case?

**Comment by sarabala1979** [comment]
Take a look below example.

```
# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```

**Comment by raftAtGit** [comment]
Thanks, but looks like that only works when artifact producer and consumer are steps under the same parent.

**Comment by samath117** [comment]
It's strange that the solution I posted didn't work for you. Did you make sure to include the `inputs.artifacts` field like I posted right below `name: B`?

It shouldn't matter if A and B are also nested templates. Just make sure to always have `arguments` when the template is invoked and corresponding `inputs` in the template definition. Trace the artifact as it's passed up and down the chains and between steps.

**Comment by raftAtGit** [comment]
@samath117 himm, I guess I messed it up somehow. Now I tried it with a simpler flow and it worked. Thanks!

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: entry
  templates:
  - name: entry
    steps:
    - - name: Parent
        template: Parent
  - name: Parent
    steps:
    - - name: A
        template: A
    - - name: B
        template: B
        arguments:
          artifacts:
          - name: artifact
            from: "{{steps.A.outputs.artifacts.artifact}}"
  - name: B
    inputs:
      artifacts:
      - name: artifact
    steps:
    - - name: B1
        template: B1
        arguments:
          artifacts:
          - name: artifact
            from: "{{inputs.artifacts.artifact}}"
    - - name: B2
        template: B2

  - name: A
    outputs:
      artifacts:
      - name: artifact
        path: /artifact
    container:
      image: alpine:latest
      command: [sh, -c, "echo hey dude > /artifact"]
  - name: B1
    inputs:
      artifacts:
      - name: artifact
        path: /artifact
    container:
      image: alpine:latest
      command: [sh, -c, "echo hey dude"]
  - name: B2
    container:
      image: alpine:latest
      command: [sh, -c, "echo hey dude"]
```
