### ISSUE TITLE
Input artifact optionality cannot be nested

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#1499]
**False alarm. This actually works as intended! I was using the wrong Argo version.**

~~**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT~~

I work with nested Argo templates, and want to use the new optional artifact feature from Argo 2.3.0 in order to build general-purpose templates for processes which may or may not have an input artifact. However, if the lowest-level template has an optional artifact, there is no way to pass this optionality up the nested chain. Here is a minimal example:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: minimal-nested-optional-artifact-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: subplan
        template: subplan
        # No input artifact supplied at this level.
  - name: subplan
    inputs:
      artifacts:
      - name: optional-nested-in-artifact
        optional: true
    steps:
    - - name: subsubplan
        template: subsubplan
        arguments:
          artifacts:
          - name: optional-nested-in-artifact
            from: "{{inputs.artifacts.optional-nested-in-artifact}}"
            # This line fails.
  - name: subsubplan
    inputs:
      artifacts:
        - name: optional-nested-in-artifact
          path: /input
          optional: true
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo hello"]
```

~~**What happened**: I got the following error message: `invalid spec: templates.subplan inputs.artifacts.optional-nested-in-artifact was not supplied`~~

~~**What you expected to happen**: If an optional artifact which is not provided is referenced as the value for another optional artifact argument, that artifact argument should simply be removed, so that this optionality can be passed up a nested workflow.~~
