### ISSUE TITLE
Optional input artifact appears as empty directory

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#1503]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: When an optional input artifact is not supplied, an empty directory is still placed at the given path. This causes unexpected errors if that optional artifact is usually a file.

**What you expected to happen**: The empty directory should simply not be created if the input artifact is not supplied.

**How to reproduce it (as minimally and precisely as possible)**:
Here is a minimal example:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: minimal-optional-directory-appears-example-
spec:
  entrypoint: plan
  templates:
  - name: plan
    inputs:
      artifacts:
      - name: opt
        path: /file.yaml
        optional: true
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ['ls']
```
The logs of this example show file.yaml as a directory.

I'm working on Argo v2.3.0.
