### ISSUE TITLE
Unable to run example with `continueOn`: Unknown field `continueOn`

### ISSUE THREAD

**Issue by CermakM** [argoproj/argo#1518]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
```
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "continueOn"
```

**What you expected to happen**:
I am able to include `continueOn` in my Workflow.

**How to reproduce it (as minimally and precisely as possible)**:
```
argo submit https://raw.githubusercontent.com/argoproj/argo/master/examples/continue-on-fail.yaml
```

**Anything else we need to know?**:
Doesn't work for either of `steps` and `dag`

**Environment**:

- Argo version:
```
$ argo version
```
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```

- Kubernetes version :
```
$ kubectl version -o yaml
```
```
clientVersion:
  buildDate: 2018-10-10T16:38:01Z
  compiler: gc
  gitCommit: d4cacc0
  gitTreeState: clean
  gitVersion: v1.11.0+d4cacc0
  goVersion: go1.10.3
  major: "1"
  minor: 11+
  platform: linux/amd64
serverVersion:
  buildDate: 2019-08-01T13:19:47Z
  compiler: gc
  gitCommit: d4cacc0
  gitTreeState: clean
  gitVersion: v1.11.0+d4cacc0
  goVersion: go1.10.8
  major: "1"
  minor: 11+
  platform: linux/amd64


```

**Other debugging information (if applicable)**:
```
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "continueOn"
```
