### ISSUE TITLE
How to use artifacts with `resource`?

### ISSUE THREAD

**Issue by CermakM** [argoproj/argo#1519]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What you expected to happen**:
I'd like to use artifact value directly in my Kubernetes resource definition as such:
```
spec:
  templates:
    - name: build
      inputs:
        artifacts:
          - name: dockerfile  # path cannot be specified, how do I use artifacts w/o it?
      resource:
        action: create
        manifest: |
          kind: BuildConfig
          apiVersion: build.openshift.io/v1
          metadata:
            name: "{{workflow.parameters.inspection-id}}"
            labels:
              app: myapp
          spec:
            output:
              to:
                kind: ImageStreamTag
                name: "{{workflow.parameters.inspection-id}}:latest"
            source:
              dockerfile: "{{inputs.artifacts.dockerfile}}"  # <--- how to retrieve the value of the artifact?
              type: Dockerfile
            strategy:
              type: Docker
```

**Environment**:

- Argo version:
```
$ argo version
```
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```

- Kubernetes version :
```
$ kubectl version -o yaml
```
```
clientVersion:
  buildDate: 2018-10-10T16:38:01Z
  compiler: gc
  gitCommit: d4cacc0
  gitTreeState: clean
  gitVersion: v1.11.0+d4cacc0
  goVersion: go1.10.3
  major: "1"
  minor: 11+
  platform: linux/amd64
serverVersion:
  buildDate: 2019-08-01T13:19:47Z
  compiler: gc
  gitCommit: d4cacc0
  gitTreeState: clean
  gitVersion: v1.11.0+d4cacc0
  goVersion: go1.10.8
  major: "1"
  minor: 11+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by Downchuck** [comment]
Your template does not signal where it would pick up the Dockerfile -- Where is your Dockerfile located? If it's on HTTP or S3, you can specify that -- if it's simply on your local machine, you're going to want to add that in before running your submit - such as through a parameter.

**Comment by CermakM** [comment]
@Downchuck thanks for the quick reply,

The default artifact repository is s3, now I am having trouble retrieving the value with the `resource` spec. To illustrate:
I have a step which generates the Dockerfile artifact from another artifect -- the mock Dockerfile:
```yaml
templates:
    - name: create-dockerfile
      inputs:
        artifacts:
        - name: dockerfile-mock
          path: "/tmp/Dockerfile.mock"
          raw:
            data: 'FROM alpine:latest\nENTRYPOINT [\"bash\"]'
      outputs:
        artifacts:
          - name: dockerfile
            path: "/tmp/Dockerfile"
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          from pathlib import Path
          ...  # some code left out for brevity
          with open("/tmp/Dockerfile", "w") as f:
            dockerfile = Path("/tmp/Dockerfile.mock").read_text()
            f.write(dockerfile)
```

Now I wanna use that to create `BuildConfig` using the `resource` specification in the following step and consume that artifact, however, I cannot do simply 

```yaml
inputs:
   artifacts:
   - name: dockerfile
     path: "/tmp/Dockerfile"  # <--- not allowed with `resource`
```

I wouldn't be able to read the file anyway.

So I feed the artifact to the step as follows:
```yaml
arguments:
   artifacts:
   - name: dockerfile
     from: "{{steps.create-dockerfile.outputs.artifacts.dockerfile}}"
```

And in this step:
```yaml
source:
   dockerfile: "{{inputs.artifacts.dockerfile}}"
```

I expect the resulting yaml to be populated as such (according to the Dockerfile mock)

```yaml
source:
   dockerfile: "FROM alpine:latest\nENTRYPOINT [\"bash\"]"
```

The `dockerfile` variable, however, is not populated with the content of the artifact (i.e, the `Dockerfile`)


Hope that clears things out and thanks for any help!

Cheers,
Marek
