### ISSUE TITLE
Openshift 3.11: Workflow variables not being resolved in some cases

### ISSUE THREAD

**Issue by amalic** [argoproj/argo#1558]
It looks like placeholders for variables are not being resolved properly. 

When running [example/coinflip.yaml](https://github.com/argoproj/argo/blob/master/examples/coinflip.yaml) I am getting following error message on the step where it fails:
**Output:** `Invalid 'when' expression '{{steps.flip-coin.outputs.result}} == heads': Invalid token: '{{'`

When running [daemon-nginx.yaml](https://github.com/argoproj/argo/blob/master/examples/daemon-nginx.yaml) I am getting following output on the last step.
**Output:** `curl --silent -G http://{{steps.nginx-server.ip}}:80/`

For the daemon example to work at all, I had to change the readiness probe into a liveness-probe. Otherwise the workflow would have been stuck waiting. I guess this is another bug.

```
apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: daemon-nginx-
spec:
  entrypoint: daemon-nginx-example

  templates:
  - name: daemon-nginx-example
    steps:
    - - name: nginx-server
        template: nginx-server
    - - name: nginx-client
        template: nginx-client
        arguments:
          parameters:
          - name: server-ip
            value: "{{steps.nginx-server.ip}}"

  - name: nginx-server
    daemon: true
    container:
      image: nginx:1.13
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 1
        timeoutSeconds: 1
#      readinessProbe:
#        httpGet:
#          path: /
#          port: 80
#        initialDelaySeconds: 2
#        timeoutSeconds: 1

  - name: nginx-client
    inputs:
      parameters:
      - name: server-ip
    container:
      image: appropriate/curl:latest
      command: ["/bin/sh", "-c"]
      args: ["echo curl --silent -G http://{{inputs.parameters.server-ip}}:80/ && curl --silent -G http://{{inputs.parameters.server-ip}}:80/"]
```

I tested with Argo v2.2.0, v2.2.1, v2.3.0, and 2.4.0rc1

Strangely other workflows using Workflow variables seem to work: e.g. [loops-maps](https://raw.githubusercontent.com/argoproj/argo/master/examples/loops-maps.yaml)

**Comment by amalic** [comment]
yes i was.

**Comment by pavel-mikhalchuk** [comment]
same issue on GKE cluster 1.14.6-gke.13

**Comment by pavel-mikhalchuk** [comment]
some logs:

`level=error msg="Mark error node coinflip-49bqx[1].heads: Invalid 'when' expression '{{steps.flip-coin.outputs.result}} == heads': Invalid token: '{{'\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/errors.Errorf\n\t/go/src/github.com/argoproj/argo/errors/errors.go:55\ngithub.com/argoproj/argo/workflow/controller.shouldExecute\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:258\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:195\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:77\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1210\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:212\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:304\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:230\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker-fm\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333" namespace=default workflow=coinflip-49bqx`

**Comment by strump** [comment]
I got same error on GKE. Pod logs also have error:

```
time="2019-11-07T11:40:54Z" level=warning msg="Failed to get pod 'coinflip-wg68x-673904296': pods \"coinflip-wg68x-673904296\" is forbidden: User \"system:serviceaccount:argo:default\" cannot get resource \"pods\" in API group \"\" in the namespace \"argo\""        time="2019-11-07T11:40:54Z" level=error msg="Failed to kill sidecars: pods \"coinflip-wg68x-673904296\" is forbidden: User \"system:serviceaccount:argo:default\" cannot get resource \"pods\" in API group \"\" in the namespace \"argo\""
time="2019-11-07T11:40:54Z" level=info msg="Alloc=4805 TotalAlloc=9990 Sys=69822 NumGC=3 Goroutines=7"
```

Looks like Argo can't get POD output. My workaround is to grant roles:

```
kubectl create rolebinding argo-admin --clusterrole=admin --serviceaccount=argo:default
```

**Comment by rushtehrani** [comment]
Also getting the `Invalid 'when' expression '{{steps.flip-coin.outputs.result}} == heads': Invalid token: '{{'` error with both `1.14.8-gke.12` and `1.15.4-gke.18`.

**Comment by rushtehrani** [comment]
In my case, the fix was to grant roles to `default` service account in each namespace that workflows are run (example below). Is there a better way to handle this? In the `wait` container logs, it looks like the namespace's `default` service account is always used to make API calls.

```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: argo
  name: argo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: argo
  name: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo
subjects:
- kind: ServiceAccount
  name: default
  namespace: <workflow-namespace>
```

**Comment by saisankargochhayat** [comment]
I seem to face the same issue, the value of result was not being assigned properly-
I changed the conditional example a little and finally it worked - 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-
spec:
  serviceAccountName: argo
  entrypoint: coinflip
  
  volumes:
  - name: outputdir
    emptyDir: {}


  templates:
  - name: coinflip
    steps:
    # flip a coin
    - - name: flip-coin
        template: flip-coin
    # evaluate the result in parallel
    - - name: heads
        template: heads                 # call heads template if "heads"
        when: "{{steps.flip-coin.outputs.parameters.answer}} == heads"
      - name: tails
        template: tails                 # call tails template if "tails"
        when: "{{steps.flip-coin.outputs.parameters.answer}} == tails"

  # Return heads or tails based on a random number
  - name: flip-coin
    script:
      image: python:alpine3.6
      volumeMounts:
      - mountPath: /mnt/output
        name: outputdir
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)
        with open("/mnt/output/output.txt", "w") as text_file:
            print(result, file=text_file)
    outputs:
      parameters:
      - name: answer	# name of output parameter
        valueFrom:
          path: /mnt/output/output.txt	# set the value of hello-param to the contents of this hello-world.txt

  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]

  - name: tails
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was tails\""]
```
