### ISSUE TITLE
[FEATURE REQUEST] support `Workflow.spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution`

### ISSUE THREAD

**Issue by hidekuro** [argoproj/argo#1559]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
```yaml
# example.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-
spec:

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - "worker"

  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

```bash
argo submit example.yaml
```

```
2019/08/16 21:56:36 Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field NodeAffinity.preferredDuringSchedulingIgnoredDuringExecution of type []v1.PreferredSchedulingTer
```

**What you expected to happen**:
submit succeed and scheduled on node which has label "role: worker".

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-08-05T16:54:35Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-08-05T09:15:22Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: linux/amd64
```
