### ISSUE TITLE
Executor fails to capture output artifact that is same directory as input dir

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#1566]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:

When collecting artifacts where the path is the same (e.g. example below)

```yaml
  - name: collect
    inputs:
      artifacts:
      - name: samedir
        path: /outer
    container:
      image: alpine:3.8
      command: [sh, -c]
      args: ["sleep 1"]
    outputs:
      artifacts:
      - name: outer
        path: /outer
```

it fails on the PNS executor because the PNS executor attempts to capture the file from the base image layer instead of the shared volumeMount.
