### ISSUE TITLE
Sidecar not terminated when main container completes

### ISSUE THREAD

**Issue by knkski** [argoproj/argo#1570]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:

I created a sidecar container from `tensorflow/serving:1.14.0` to serve a model for the main container to run some tests against. After the main container completed, the serving sidecar was not terminated, and left the pipeline stuck in a running state.

**What you expected to happen**:

I expected the sidecar to get terminated after the main container completed.

**How to reproduce it (as minimally and precisely as possible)**:

This is the workflow step in question, generated with Kubeflow pipelines' Python DSL:

```yaml
- container:
    args:
      - '--endpoint'
      - '{{inputs.parameters.storage-endpoint}}'
      - '----output-paths'
      - /tmp/outputs/done/data
    command:
      - python3
      - '-u'
      - '-c'
      - >
        from typing import NamedTuple


        def test_task(endpoint: str) -> NamedTuple('Done', [('done', str)]):
            """Connects to served model"""

            import requests
            import time

            for _ in range(24):
                try:
                    response = requests.get('http://localhost:9001/v1/models/mnist/versions/1')
                    response.raise_for_status()
                    break
                except requests.RequestException as err:
                    print(f'Got error: {err}')
                    print('Waiting for model to get served...')
                    time.sleep(5)
            else:
                raise Exception("Waited too long for model to boot up!")

            return 'done',

        import argparse

        _parser = argparse.ArgumentParser(prog='Test task',
        description='Connects to served model\n')

        _parser.add_argument("--endpoint", dest="endpoint", type=str,
        required=True, default=None)

        _parser.add_argument("----output-paths", dest="_output_paths",
        type=str, nargs=1)

        _parsed_args = vars(_parser.parse_args())

        _output_files = _parsed_args.pop("_output_paths")


        _outputs = test_task(**_parsed_args)


        if not hasattr(_outputs, '__getitem__') or isinstance(_outputs,
        str):
            _outputs = [_outputs]

        from pathlib import Path

        for idx, filename in enumerate(_output_files):
            _output_path = Path(filename)
            _output_path.parent.mkdir(parents=True, exist_ok=True)
            _output_path.write_text(str(_outputs[idx]))
    image: 'tensorflow/tensorflow:1.14.0-py3'
    volumeMounts:
      - mountPath: /output
        name: volume
      - mountPath: /tmp/outputs
        name: outputs
      - mountPath: /secrets
        name: minio-secrets
  inputs:
    parameters:
      - name: storage-endpoint
  name: test-task
  outputs:
    artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /output/mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /output/mlpipeline-metrics.json
    parameters:
      - name: test-task-done
        valueFrom:
          path: /tmp/outputs/done/data
  sidecars:
    - args:
        - '-c'
        - |-
          apt update && apt install -y python3 && python3 -c "import os
          import signal
          import subprocess
          import time

          p = subprocess.Popen([
              '/usr/bin/tensorflow_model_server',
              '--model_name=mnist',
              '--model_base_path=/output/mnist',
              '--port=9000',
              '--rest_api_port=9001',
          ])

          def verbose_exit(signum, frame):
              print(f'Got exit: {signum} {frame}')
              os.kill(p.pid, signal.SIGKILL)

          signal.signal(signal.SIGINT, verbose_exit)
          signal.signal(signal.SIGTERM, verbose_exit)

          try:
              while p.poll() is None:
                  time.sleep(0.1)
          except BaseException as err:
              print(f'Got {err}, hard killing server')
              os.kill(p.pid, signal.SIGKILL)
              raise
              "
      command:
        - sh
      image: 'tensorflow/serving:1.14.0'
      mirrorVolumeMounts: true
      name: tensorflow-serve
```

Note that I wrapped the serving command in a python script for debugging purposes that watches for any signals and hard kills the serving command, in case it's an issue with the signals somehow getting ignored, but the wrapper script doesn't print anything out.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argoproj/workflow-controller:v2.3.0, with the `kubelet` executor
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-05T17:09:13Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-08-05T17:06:39Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- executor logs:
```
time="2019-08-20T19:28:02Z" level=info msg="Main container completed"
time="2019-08-20T19:28:02Z" level=info msg="Killing sidecars"
time="2019-08-20T19:28:02Z" level=info msg="Annotations monitor stopped"
time="2019-08-20T19:28:02Z" level=info msg="Killing sidecar tensorflow-serve (5e9895c2925da51a5c29a09d6c0b5c993e650330083faf048b90fb1cfeb9579e)"
time="2019-08-20T19:28:02Z" level=info msg="SIGTERM containerID \"5e9895c2925da51a5c29a09d6c0b5c993e650330083faf048b90fb1cfeb9579e\": terminated"
time="2019-08-20T19:28:02Z" level=info msg="Starting to wait completion of containerID 5e9895c2925da51a5c29a09d6c0b5c993e650330083faf048b90fb1cfeb9579e ..."
time="2019-08-20T19:28:03Z" level=info msg="Deadline monitor stopped"
time="2019-08-20T19:28:12Z" level=info msg="SIGKILL containerID \"5e9895c2925da51a5c29a09d6c0b5c993e650330083faf048b90fb1cfeb9579e\": killed"
time="2019-08-20T19:28:12Z" level=info msg="Starting to wait completion of containerID 5e9895c2925da51a5c29a09d6c0b5c993e650330083faf048b90fb1cfeb9579e ..."
time="2019-08-20T19:28:22Z" level=error msg="executor error: timeout after 10s" 
```

**Comment by arbakker** [comment]
I experience the same, sidecar not terminated when main container completes leaving the workflow in a running state. 

#### How to reproduce it (as minimally and precisely as possible):

```yml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sidecar-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: load-data
        template: load-data
  - name: load-data
    container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["
          apk update &&
          apk add postgresql-client &&
          until pg_isready -h 127.0.0.1 -p 5432 ; do sleep .5; echo sleep; done &&
          PGPASSWORD=postgres psql -h 127.0.0.1 -p 5432 -U postgres -c 'CREATE TABLE films (code char(5) CONSTRAINT firstkey PRIMARY KEY);';
          PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -p 5432 -c 'SELECT table_schema,table_name FROM information_schema.tables ORDER BY table_schema,table_name;';
        "]
    sidecars:
    - name: postgres
      image: postgres:9-alpine
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
```

#### Environment

- Argo version

```
argoproj/workflow-controller:v2.4.2
```

- Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
