### ISSUE TITLE
Ability to interface with S3 using assumed roles (session tokens)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#1571]
In addition to IAM role authentication and access key/secret key authentication, Argo should be able to use assumed roles to download/upload to and from s3.

The syntax should look something like:

```yaml
  templates:
  - name: input-artifact-s3-example
    inputs:
      artifacts:
      - name: my-art
        path: /my-artifact
        s3:
          endpoint: s3.amazonaws.com
          bucket: my-bucket-name
          key: path/in/bucket
          roleARN: arn:aws:iam::123456789012:role/xaccounts3access
```

This would be equivalent to first doing:

```
aws sts assume-role --role-arn arn:aws:iam::123456789012:role/xaccounts3access
```

and using the generated credentials to upload/download the artifacts.

**Comment by kollurukailash** [comment]
@jessesuen Can you help me with configuring the IAM role for s3 artifact?

**Comment by calvinx408** [comment]
> @jessesuen Can you help me with configuring the IAM role for s3 artifact?

example:
```
        artifacts:
          - name: terraform_tfstate_output
            path: /state
            s3:
              region: us-west-2
              endpoint: s3.amazonaws.com
              bucket: example-bucket
              key: test/terraform.tfstate
              roleARN: arn:aws:iam::2232322222:role/test
```
