### ISSUE TITLE
Workflow step fails with "failed to save outputs: timeout after 0s"

### ISSUE THREAD

**Issue by knkski** [argoproj/argo#1573]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:

A workflow step failed with the error `failed to save outputs: timeout after 0s`, even though the container successfully completed.

**What you expected to happen**:

The workflow step to properly reflect the successful container completion

**How to reproduce it (as minimally and precisely as possible)**:

This is the pipeline that I'm trying to run:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-workflow-
spec:
  arguments:
    parameters:
      - name: storage-endpoint
        value: 'minio:9000'
      - name: bucket
        value: mnist
  entrypoint: test-workflow
  serviceAccountName: pipeline-runner
  templates:
    - container:
        args:
          - '--endpoint'
          - '{{inputs.parameters.storage-endpoint}}'
          - '--bucket'
          - '{{inputs.parameters.bucket}}'
          - '----output-paths'
          - /tmp/outputs/Output/data
        command:
          - python3
          - '-u'
          - '-c'
          - >
            def ensure_bucket_task(endpoint: str, bucket: str) -> str:
                from minio import Minio
                from minio.error import BucketAlreadyOwnedByYou, BucketAlreadyExists

                mclient = Minio(
                    endpoint,
                    access_key=...,
                    secret_key=...,
                )

                try:
                    mclient.make_bucket(bucket)
                except (BucketAlreadyExists, BucketAlreadyOwnedByYou):
                    pass

            import argparse

            _parser = argparse.ArgumentParser(prog='Ensure bucket task',
            description='Ensures that the data bucket has been created.\n')

            _parser.add_argument("--endpoint", dest="endpoint", type=str,
            required=True, default=None)

            _parser.add_argument("--bucket", dest="bucket", type=str,
            required=True, default=None)

            _parser.add_argument("----output-paths", dest="_output_paths",
            type=str, nargs=1)

            _parsed_args = vars(_parser.parse_args())

            _output_files = _parsed_args.pop("_output_paths")


            _outputs = ensure_bucket_task(**_parsed_args)


            if not hasattr(_outputs, '__getitem__') or isinstance(_outputs,
            str):
                _outputs = [_outputs]

            from pathlib import Path

            for idx, filename in enumerate(_output_files):
                _output_path = Path(filename)
                _output_path.parent.mkdir(parents=True, exist_ok=True)
                _output_path.write_text(str(_outputs[idx]))
        image: 'tensorflow/tensorflow:1.14.0-py3'
        volumeMounts:
          - mountPath: /output
            name: volume
          - mountPath: /tmp/outputs
            name: outputs
          - mountPath: /secrets
            name: minio-secrets
      inputs:
        parameters:
          - name: bucket
          - name: storage-endpoint
      name: ensure-bucket-task
      outputs:
        artifacts:
          - name: mlpipeline-ui-metadata
            optional: true
            path: /output/mlpipeline-ui-metadata.json
          - name: mlpipeline-metrics
            optional: true
            path: /output/mlpipeline-metrics.json
        parameters:
          - name: ensure-bucket-task-output
            valueFrom:
              path: /tmp/outputs/Output/data
    - dag:
        tasks:
          - arguments:
              parameters:
                - name: bucket
                  value: '{{inputs.parameters.bucket}}'
                - name: storage-endpoint
                  value: '{{inputs.parameters.storage-endpoint}}'
            name: ensure-bucket-task
            template: ensure-bucket-task
      inputs:
        parameters:
          - name: bucket
          - name: storage-endpoint
      name: test-workflow
  volumes:
    - name: minio-secrets
      secret:
        secretName: mlpipeline-minio-artifact
    - emptyDir: {}
      name: outputs
    - emptyDir: {}
      name: volume
```

**Anything else we need to know?**:

This only happens periodically, to reproduce it for opening this bug, I had to rerun the pipeline several dozens of times. It seems to happen more frequently on some steps than others.

My guess is that it's related to the fact that the minio library uses threading internally, and there's some threads hanging around causing issues, but I'm not sure how to turn off minio's threading to test that.

If it makes a difference, this was generated with `func_to_container_op` from the Kubeflow pipelines SDK.

**Environment**:
- Argo version:
```
argoproj/workflow-controller:v2.3.0, with `kubelet` executor
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-05T17:09:13Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-08-05T17:06:39Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- executor logs:
```
 time="2019-08-21T16:52:41Z" level=info msg="Creating a kubelet executor"
time="2019-08-21T16:52:41Z" level=info msg="Non configured envvar ARGO_KUBELET_PORT, defaulting the kubelet port to 10250"
time="2019-08-21T16:52:41Z" level=warning msg="Loading service account ca.crt as certificate authority to reach the kubelet api"
time="2019-08-21T16:52:41Z" level=info msg="Executor (version: v2.3.0, build_date: 2019-05-20T22:10:54Z) initialized (pod: kubeflow/mnist-cnn-example-66dwv-4224359274) with template:\n..."
time="2019-08-21T16:52:41Z" level=info msg="Waiting on main container"
time="2019-08-21T16:52:42Z" level=info msg="main container started with container ID: 2a76a541030adcbbf9437cf93e937cf8278f76dbe7530bdbc92ff8da9544dff4"
time="2019-08-21T16:52:42Z" level=info msg="Starting annotations monitor"
time="2019-08-21T16:52:42Z" level=info msg="Starting to wait completion of containerID 2a76a541030adcbbf9437cf93e937cf8278f76dbe7530bdbc92ff8da9544dff4 ..."
time="2019-08-21T16:52:42Z" level=error msg="executor error: timeout after 0s"
time="2019-08-21T16:52:42Z" level=info msg="No sidecars"
time="2019-08-21T16:52:42Z" level=info msg="Saving output parameters"
time="2019-08-21T16:52:42Z" level=info msg="Saving path output parameter: ensure-bucket-task-output"
time="2019-08-21T16:52:42Z" level=info msg="Copying /tmp/outputs/Output/data from from volume mount"
time="2019-08-21T16:52:42Z" level=error msg="executor error: open /mainctrfs/tmp/outputs/Output/data: no such file or directory"
time="2019-08-21T16:52:42Z" level=info msg="Annotations monitor stopped"
time="2019-08-21T16:52:42Z" level=info msg="Alloc=4337 TotalAlloc=11091 Sys=70590 NumGC=4 Goroutines=9"
time="2019-08-21T16:52:42Z" level=info msg="Starting deadline monitor"
time="2019-08-21T16:52:42Z" level=info msg="Deadline monitor stopped"
time="2019-08-21T16:52:42Z" level=fatal msg="open /mainctrfs/tmp/outputs/Output/data: no such file or directory" ```
