### ISSUE TITLE
Linter does not detect arguments which do not match inputs

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#1574]
In short, I provided arguments to a step which did not have corresponding inputs, and the linter did not catch this inconsistency.

Here is a minimal example illustrating this for both artifacts and parameters:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ghost-arguments-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: step
        template: whalesay
        arguments:
          parameters:
          - name: ghost-parameter
            value: wooooooo
          artifacts:
          - name: ghost-artifact
            raw:
              data: |
                woooooooooooooo

  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: [hello]
```
Running `argo lint` on this yields `Workflow manifests validated`. Running `argo submit` does not cause an error and succeeds. However, if there is a more complicated downstream effect depending on the presence of the artifacts which are passed as arguments, this will cause an error only then.

Are there actually use cases where we want to provide arguments to templates which have no ability to use them? If not, this seems like an opportunity to reduce confusion and help users catch mistakes.
