### ISSUE TITLE
Restart job at workflow level

### ISSUE THREAD

**Issue by huikang** [argoproj/argo#1578]
I have an argo workflow that is triggered through argo-event, If anyone of the steps in the workflow failed, how could the workflow be retried automatically. Is there any way to setup a retry strategy at the workflow level? Thanks.

https://argoproj.slack.com/archives/C8J6SGN12/p1566439599263600

**Comment by dtaniwaki** [comment]
I think this feature is very useful for me too. May I implement it?

**Comment by dtaniwaki** [comment]
How about allowing `retryStrategy` in templates other than container templates?

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-retry-workflow-
spec:
  entrypoint: retry-workflow
  templates:
  - name: random-fail-template
    container:
      image: python:alpine3.6
      command: [python, -c]
      # fail with a 66% probability
      args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]
  - name: retry-workflow
    template: steps
    retryStrategy:
      limit: 10
  - name: steps
    steps:
    - - name: hello1
        template: random-fail-template
    - - name: hello2a
        template: random-fail-template
      - name: hello2b
        template: random-fail-template
```
