### ISSUE TITLE
WorkflowTemplate doesn't render parameters in resource manifest

### ISSUE THREAD

**Issue by Devatoria** [argoproj/argo#1594]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report.

**What happened**:
When creating a `WorkflowTemplate` resource containing a resource creation, parameters used in this resource manifests aren't rendered.

**What you expected to happen**:
Parameters should be rendered in the resource manifest as well.

**How to reproduce it (as minimally and precisely as possible)**:
Let's say we have a `WorkflowTemplate` creating a `ConfigMap` resource as:
```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fake-template
spec:
  templates:
    - name: configmap
      inputs:
        parameters:
          - name: namespace
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ workflow.name }}"
            namespace: "{{ inputs.parameters.namespace }}"
          data:
            game.properties: |
              enemies=aliens
```

And a `Workflow` using this template as:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-
spec:
  serviceAccountName: argo-workflow
  entrypoint: whalesay
  templates:
  - name: whalesay
    templateRef:
      name: fake-template
      template: configmap
    arguments:
      parameters:
      - name: namespace
        value: foo
```

When submitting this workflow, here's the result of the resource creation:
```
Error from server (NotFound): error when creating "/tmp/manifest.yaml": namespaces "{{ inputs.parameters.namespace }}" not found
```

The namespace parameter is not rendered in the configmap manifest probably because the `manifest` field expects a multiline plain text value (see the `|`):
```
        manifest: |
          apiVersion: v1
          kind: ConfigMap
```

**Anything else we need to know?**:
No.

**Environment**:
- Argo version:
```
argo: v2.4.0-rc1
  BuildDate: 2019-08-08T22:59:35Z
  GitCommit: 6131721f43545196399d7ffe3a72c1b9dc04df87
  GitTreeState: clean
  GitTag: v2.4.0-rc1
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-09-28T15:20:58Z
  compiler: gc
  gitCommit: 0ed33881dc4355495f623c6f22e7dd0b7632b7c0
  gitTreeState: clean
  gitVersion: v1.12.0
  goVersion: go1.11
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-11-26T14:25:46Z
  compiler: gc
  gitCommit: 637c7e288581ee40ab4ca210618a89a555b6e7e9
  gitTreeState: clean
  gitVersion: v1.10.11
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Status:              Failed
Message:             Error from server (NotFound): error when creating "/tmp/manifest.yaml": namespaces "{{ inputs.parameters.namespace }}" not found
Created:             Wed Sep 04 18:30:11 +0200 (4 minutes ago)
Started:             Wed Sep 04 18:30:18 +0200 (4 minutes ago)
Finished:            Wed Sep 04 18:30:22 +0200 (4 minutes ago)
Duration:            4 seconds

STEP                                   PODNAME                  DURATION  MESSAGE
 ✖ workflow-template-kmzb8 (whalesay)  workflow-template-kmzb8  2s        Error from server (NotFound): error when creating "/tmp/manifest.yaml": namespaces "{{ inputs.parameters.namespace }}" not found
```
- executor logs:
```
time="2019-09-04T16:30:21Z" level=fatal msg="Error from server (NotFound): error when creating \"/tmp/manifest.yaml\": namespaces \"{{ inputs.parameters.namespace }}\" not found\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).ExecResource\n\t/go/src/github.com/argoproj/argo/workflow/executor/resource.go:63\ngithub.com/argoproj/argo/cmd/argoexec/commands.execResource\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/resource.go:44\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewResourceCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/resource.go:21\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
```
- workflow-controller logs:
nothing specific, just info logs about resources creation and update.
