### ISSUE TITLE
Input artifact from s3 directory fails due to tempArtPath not existing.

### ISSUE THREAD

**Issue by comron** [argoproj/argo#1602]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
When specifying an s3 input artifact that is a directory, downloading fails due to the ".tmp" directory not being created before downloading begins. When minio starts to download the items in the s3 directory a call to stat the potential location fails because the parent directory defined by tempArtPath does not exist. Maybe it should be created before attempting to call FGetObject here: https://github.com/argoproj/pkg/blob/master/s3/s3.go#L186

**What you expected to happen**:
The directory is downloaded from s3.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: get-s3-dir-
spec:
  entrypoint: get-directory
  templates:
  - name: get-directory
    inputs:
      artifacts:
      - name: s3dir
        path: /var/run/data/dir/
        archive:
          none: {}
        s3: 
          endpoint: s3.us-east-2.amazonaws.com
          bucket: argo-test-3de5c31dbece632481fed860a6581e3b
          key: "argo/ea4938c66f72d4ea955d31187ca311c9"
          accessKeySecret:
            name: my-s3-credentials
            key: accessKey
          secretKeySecret:
            name: my-s3-credentials
            key: secretKey
    container:
      image: busybox
      args: ["ls -al /var/run/data/dir"]
```
**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-06-07T09:57:54Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: clean
  gitVersion: v1.14.3
  goVersion: go1.12.5
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-08-20T22:39:46Z"
  compiler: gc
  gitCommit: 5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1
  gitTreeState: clean
  gitVersion: v1.13.10-eks-5ac0f1
  goVersion: go1.11.13
  major: "1"
  minor: 13+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- executor logs:
```
$ kubectl logs <failedpodname> -c init
time="2019-09-08T23:06:34Z" level=info msg="Creating a docker executor"
time="2019-09-08T23:06:34Z" level=info msg="Executor (version: v2.3.0, build_date: 2019-05-20T22:10:54Z) initialized (pod: argo-work/get-s3-dir-gcrnf) with template:\n{\"name\":\"get-directory\",\"inputs\":{\"artifacts\":[{\"name\":\"s3dir\",\"path\":\"/var/run/data/dir/\",\"s3\":{\"endpoint\":\"s3.us-east-2.amazonaws.com\",\"bucket\":\"argo-test-3de5c31dbece632481fed860a6581e3b\",\"accessKeySecret\":{\"name\":\"my-s3-credentials\",\"key\":\"accessKey\"},\"secretKeySecret\":{\"name\":\"my-s3-credentials\",\"key\":\"secretKey\"},\"key\":\"argo/ea4938c66f72d4ea955d31187ca311c9\"},\"archive\":{\"none\":{}}}]},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"busybox\",\"args\":[\"ls -al /var/run/data/dir\"],\"resources\":{}}}"
time="2019-09-08T23:06:34Z" level=info msg="Start loading input artifacts..."
time="2019-09-08T23:06:34Z" level=info msg="Downloading artifact: s3dir"
time="2019-09-08T23:06:34Z" level=info msg="S3 Load path: /argo/inputs/artifacts/s3dir.tmp, key: argo/ea4938c66f72d4ea955d31187ca311c9"
time="2019-09-08T23:06:34Z" level=info msg="Creating minio client s3.us-east-2.amazonaws.com using static credentials"
time="2019-09-08T23:06:34Z" level=info msg="Getting from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:06:34Z" level=info msg="Getting directory from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:06:34Z" level=warning msg="Failed get directory: stat /argo/inputs/artifacts/s3dir.tmp/original: not a directory"
time="2019-09-08T23:06:36Z" level=info msg="S3 Load path: /argo/inputs/artifacts/s3dir.tmp, key: argo/ea4938c66f72d4ea955d31187ca311c9"
time="2019-09-08T23:06:36Z" level=info msg="Creating minio client s3.us-east-2.amazonaws.com using static credentials"
time="2019-09-08T23:06:36Z" level=info msg="Getting from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:06:36Z" level=info msg="Getting directory from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:06:36Z" level=warning msg="Failed get directory: stat /argo/inputs/artifacts/s3dir.tmp/original: not a directory"
time="2019-09-08T23:06:40Z" level=info msg="S3 Load path: /argo/inputs/artifacts/s3dir.tmp, key: argo/ea4938c66f72d4ea955d31187ca311c9"
time="2019-09-08T23:06:40Z" level=info msg="Creating minio client s3.us-east-2.amazonaws.com using static credentials"
time="2019-09-08T23:06:40Z" level=info msg="Getting from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:06:40Z" level=info msg="Getting directory from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:06:40Z" level=warning msg="Failed get directory: stat /argo/inputs/artifacts/s3dir.tmp/original: not a directory"
time="2019-09-08T23:06:49Z" level=info msg="S3 Load path: /argo/inputs/artifacts/s3dir.tmp, key: argo/ea4938c66f72d4ea955d31187ca311c9"
time="2019-09-08T23:06:49Z" level=info msg="Creating minio client s3.us-east-2.amazonaws.com using static credentials"
time="2019-09-08T23:06:49Z" level=info msg="Getting from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:06:49Z" level=info msg="Getting directory from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:06:49Z" level=warning msg="Failed get directory: stat /argo/inputs/artifacts/s3dir.tmp/original: not a directory"
time="2019-09-08T23:07:05Z" level=info msg="S3 Load path: /argo/inputs/artifacts/s3dir.tmp, key: argo/ea4938c66f72d4ea955d31187ca311c9"
time="2019-09-08T23:07:05Z" level=info msg="Creating minio client s3.us-east-2.amazonaws.com using static credentials"
time="2019-09-08T23:07:05Z" level=info msg="Getting from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:07:05Z" level=info msg="Getting directory from s3 (endpoint: s3.us-east-2.amazonaws.com, bucket: argo-test-3de5c31dbece632481fed860a6581e3b, key: argo/ea4938c66f72d4ea955d31187ca311c9) to /argo/inputs/artifacts/s3dir.tmp"
time="2019-09-08T23:07:05Z" level=warning msg="Failed get directory: stat /argo/inputs/artifacts/s3dir.tmp/original: not a directory"
time="2019-09-08T23:07:05Z" level=error msg="executor error: timed out waiting for the condition"
time="2019-09-08T23:07:05Z" level=info msg="Alloc=5516 TotalAlloc=23179 Sys=70846 NumGC=8 Goroutines=10"
time="2019-09-08T23:07:05Z" level=fatal msg="timed out waiting for the condition"
```
