### ISSUE TITLE
Argo lint tolerates empty workflow template steps

### ISSUE THREAD

**Issue by JayThomason** [argoproj/argo#1605]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: A bug in my code that generates Argo workflows created a workflow spec where one of the workflow templates had a completely empty step. This workflow was accepted by Argo and ran fine, simply skipping this empty step, however it crashed the Argo UI.

**What you expected to happen**: I expect that either the Argo API and linter should reject this workflow specification, or that the Argo UI should handle it without crashing.

**How to reproduce it (as minimally and precisely as possible)**:
In the workflow yaml spec:
```
...
spec:
  templates:
  - name: test-workflow
    steps:
    - - name: StepOne
        template: StepOne
    - []
    - - name: StepTwo
        template: StepTwo
   ...
```

**Anything else we need to know?**: My guess is that this should be fixed in Argo itself, but let me know if I should move this issue over to the Argo UI repo.

**Environment**:
Argo v2.3.0

**Other debugging information (if applicable)**:
In the Argo UI it is failing here:
``` const steps = (entryPointTemplate.steps || []).map((group) => group[0]).map((step) => ({ name: step.name, isSucceeded, isFailed, isRunning })).slice(0, 3);```
because the `step` has no name.
```
