### ISSUE TITLE
Using dockerSockPath changes mountPath of docker.sock

### ISSUE THREAD

**Issue by jw3** [argoproj/argo#1606]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:

> This step is in Error state with this message: failed to save outputs: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

The wait container cannot find the docker.sock at the expected location.

This is because when setting an alternate **host** docker.sock with `dockerSockPath` results in the **pod** docker.sock being mounted to the specified `dockerSockPath` inside the container.

**What you expected to happen**:

The docker.sock should be mounted to the expected `/var/run/docker.sock`.

There is no additional configuration that I see that moves where the wait container is looking for the sock, and there would not seem to be much advantage to provide that.

It would seem that just leaving the mountPath to the default location is ideal.

**How to reproduce it (as minimally and precisely as possible)**:

Set `dockerSockPath` on a workflow controller and observe the `docker-sock` `mountPath` on the workflow pod.

**Anything else we need to know?**:

Reference #1419 and #901

My Argo deployment is through Kubeflow 0.5.1 via Microk8s 1.13.6, and using the `dockerSockPath` to point Argo to the Microk8s `docker.sock`

Kubeflow parameters have been set to the `v2.4.0-rc1` Argo components.

**Environment**:
- Argo version:
```
ubuntu@vm:~/mykubeflow/ks_app$ ks param list | grep argoproj
argo                executorImage                         'argoproj/argoexec:v2.4.0-rc1'
argo                uiImage                               'argoproj/argoui:v2.4.0-rc1'
argo                workflowControllerImage               'argoproj/workflow-controller:v2.4.0-rc1'
```

- Kubernetes version :
```
ubuntu@host:~/mykubeflow/ks_app$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-05-08T13:53:53Z"
  compiler: gc
  gitCommit: abdda3f9fefa29172298a2e42f5102e777a8ec25
  gitTreeState: clean
  gitVersion: v1.13.6
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-05-08T13:46:28Z"
  compiler: gc
  gitCommit: abdda3f9fefa29172298a2e42f5102e777a8ec25
  gitTreeState: clean
  gitVersion: v1.13.6
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

Snipping output here, can produce more if needed....

```
ubuntu@host:~$ k -n kubeflow get cm workflow-controller-configmap -o yaml
apiVersion: v1
data:
  config: |
    {
    executorImage: argoproj/argoexec:v2.4.0-rc1,
    dockerSockPath: /var/snap/microk8s/current/docker.sock,
```

```
ubuntu@host:~$ kubectl -n kubeflow logs exit-handler-proxy-9l9th-1617829 wait
...
time="2019-09-13T15:09:19Z" level=info msg="Starting annotations monitor"
time="2019-09-13T15:09:19Z" level=info msg="Starting deadline monitor"
time="2019-09-13T15:09:19Z" level=info msg="docker wait abd637384efd645ea9b5089adab60b6ed78e1eaa45b5750a91e4780ce59ad94a"
time="2019-09-13T15:09:19Z" level=error msg="`docker wait abd637384efd645ea9b5089adab60b6ed78e1eaa45b5750a91e4780ce59ad94a` failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n"
time="2019-09-13T15:09:19Z" level=error msg="executor error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

...

```

```
ubuntu@host:~$ kubectl -n kubeflow get pod exit-handler-proxy-9l9th-1617829 -o yaml
...
spec:
...
 containers:
...

    volumeMounts:
    - mountPath: /var/snap/microk8s/current/docker.sock
      name: docker-sock
      readOnly: true

...

  volumes:
  - hostPath:
      path: /var/snap/microk8s/current/docker.sock
      type: Socket
    name: docker-sock
```
