### ISSUE TITLE
Terminate does not work well with retries.

### ISSUE THREAD

**Issue by gaoning777** [argoproj/argo#1620]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

**What happened**:
The workflow continues to retry after I send terminate commands.

**What you expected to happen**:
The terminate should stop the argo from retrying.

**How to reproduce it (as minimally and precisely as possible)**:
Run the following workflow and run argo terminate command.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "The pipeline includes
      two steps which fail randomly. It shows how to use ContainerOp(...).set_retry(...).",
      "name": "Retry random failures"}'
  generateName: retry-random-failures-
spec:
  arguments:
    parameters: []
  entrypoint: retry-random-failures
  serviceAccountName: pipeline-runner
  templates:
  - container:
      args:
      - import random; import sys; exit_code = random.choice(sys.argv[1].split(","));
        print(exit_code); sys.exit(exit_code)
      - 0,1,2,3
      command:
      - python
      - -c
      image: python:alpine3.6
    name: random-failure
    retryStrategy:
      limit: 10
  - container:
      args:
      - import random; import sys; exit_code = random.choice(sys.argv[1].split(","));
        print(exit_code); sys.exit(exit_code)
      - 0,1
      command:
      - python
      - -c
      image: python:alpine3.6
    name: random-failure-2
    retryStrategy:
      limit: 5
  - dag:
      tasks:
      - name: random-failure
        template: random-failure
      - name: random-failure-2
        template: random-failure-2
    name: retry-random-failures
```

**Anything else we need to know?**:

**Environment**:
- Argo version: v2.3.0
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```
