### ISSUE TITLE
Unable to resolve artifact when dag/tasks includes withItems parameter

### ISSUE THREAD

**Issue by Itfly** [argoproj/argo#1625]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Not sure, I guess this is a bug
**What happened**:
I use a DAG template with two tasks, one task with `withItems` parameter and outputs text to artifact, and second one use this artifact as input. However, the second task is failed with error 
` Unable to resolve: {{tasks.generate-artifact.outputs.artifacts.hello-art}}`.

I also use a globalName in artifact, in this case the second task gets not content.

Here's my yaml file:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    parallelism: 4
    dag:
      tasks:
      - name: generate-artifact
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems: [0,1,2]

      - name: consume-artifact
        dependencies: [generate-artifact]
        template: print-message
        arguments:
          artifacts:
          - name: message
            #from: "{{tasks.generate-artifact.outputs.artifacts.hello-art}}"
            from: "{{workflow.outputs.artifacts.my-global-art}}"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [bash, -c]
      args: ["sleep 1; if [ {{inputs.parameters.message}} == '0' ]; then cowsay hello world | tee /tmp/hello_world.txt; fi"]
      #args: ["sleep 1; cowsay hello world {{inputs.parameters.message}}| tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
        optional: true
        globalName: my-global-art

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```
 
**What you expected to happen**:
The next task can read the artifact from previous task's output artifact

**How to reproduce it (as minimally and precisely as possible)**:
Run the yaml file

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
2.3.0
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-05T16:54:35Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-08-05T09:15:22Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Comment by simster7** [comment]
Checking this

**Comment by madhuresh04** [comment]
@simster7 any update on this?

**Comment by simster7** [comment]
This should be resolved in [`2.4.3`](https://github.com/argoproj/argo/releases/tag/v2.4.3). Could you please check? If the issue still exists please reopen.

**Comment by Itfly** [comment]
@simster7 The issue is resolved in `v2.4.3` if i use global artifiacts. However it still can not resolve artifact without `globalName` field. Here's workflow yaml content:

```
# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    parallelism: 4
    dag:
      tasks:
      - name: generate-artifact
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems: [0,1,2]

      - name: consume-artifact
        dependencies: [generate-artifact]
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{tasks.generate-artifact.outputs.artifacts.hello-art}}"
            #from: "{{workflow.outputs.artifacts.my-global-art}}"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [bash, -c]
      args: ["sleep 1; if [ {{inputs.parameters.message}} == '0' ]; then cowsay hello world | tee /tmp/hello_world.txt; fi"]
      #args: ["sleep 1; cowsay hello world {{inputs.parameters.message}}| tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
        optional: true
        #globalName: my-global-art

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
      #args: ["ls /tmp/message"]
```
