### ISSUE TITLE
passing a list as a workflow parameter

### ISSUE THREAD

**Issue by GAHila** [argoproj/argo#1633]
**Is this a BUG REPORT or FEATURE REQUEST?**:
A request for help at first and if not possible then feature request.

**What happened**:

Below is a workflow with a workflow parameter that is a list of templates that should run. 
The task at hand is using a webhook to run workflow but under some conditions skip certain DAG steps.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coinflip-dag-workflow
  namespace: eim
data:
  wf: |
    apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      generateName: dag-diamond-coinflip-
      labels:
        rerun-timestamp:  
    spec:
      entrypoint: diamond
      arguments:
        parameters:
        - name: transformations
          value: ("dimension1,dimension2,fact1")
      serviceAccountName: argo
      templates:
      - name: diamond
        dag:
          tasks:
          - name: dimension-workflow
            template: dimension-workflow
          - name: fact-workflow
            dependencies: [dimension-workflow]
            template: fact-workflow

      - name: dimension-workflow
        dag:
          tasks:
          - name: transform-dimension1
            template: check-transformation
            arguments:
              parameters:
                - name: transformation
                  value: "dimension1"
                - name: name
                  value: "dim1-name"
          - name: transform-dimension2
            template: check-transformation
            arguments:
              parameters:
                - name: transformation
                  value: "dimension2"
                - name: name
                  value: "dim2-name"
          - name: transform-dimension3
            template: check-transformation
            arguments:
              parameters:
                - name: transformation
                  value: "dimension3"
                - name: name
                  value: "dim3-name"

      - name: fact-workflow
        dag:
          tasks: 
          - name: transform-fact1
            template: check-transformation
            arguments:
              parameters:
                - name: transformation
                  value: "fact1"
                - name: name
                  value: "fact1-name"
          - name: transform-fact2
            template: check-transformation
            arguments:
              parameters:
                - name: transformation
                  value: "fact2"
                - name: name
                  value: "fact2-name"

      - name: check-transformation
        inputs:
          parameters:
            - name: transformation
            - name: name
        steps: 
        - - name: transform-task
            template: transform-task
            arguments:
              parameters:
                - name: transformation
                  value: "{{inputs.parameters.transformation}}"
                - name: name
                  value: "{{inputs.parameters.name}}"
            when: "{{inputs.parameters.transformation}} in {{workflow.parameters.transformations}}"

      - name: transform-task
        inputs:
          parameters:
            - name: transformation
            - name: name
        container:
          image: alpine:3.6
          command: [sh, -c]
          args: ["sleep 2 && echo \"For transformation {{inputs.parameters.transformation}} name was {{inputs.parameters.name}}\""]
```

**What you expected to happen**:

Through a webhook, I would like to pass a list of values as argument parameter.

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: "coinflip-sensor"
  namespace: eim
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor:v0.9.3"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "coinflip-gateway:coinflip-webhook"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: coinflip-workflow-trigger
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          configmap:
            name: "coinflip-dag-workflow"
            # name: eim-pdm-workflow
            namespace: eim
            key: wf
      resourceParameters:
        - src:
            event: "coinflip-gateway:coinflip-webhook"
            path: timestamp
          dest: metadata.labels.rerun-timestamp
          operation: overwrite
        - src:
            event: "coinflip-gateway:coinflip-webhook"
            path: dimensions
          dest: spec.arguments.parameters.0.value
          operation: overwrite

```

The json passed through a webhook is like below:

`_{"dimensions": ["dimension2","dimension3","fact1","fact2"]}_`

I was expecting that passing a json array would be translated as a list into the workflow parameter but that does not seem to be the case.

Is this even possible at all currently? Otherwise can we use a conditional to see if a certain value is part of an array?  Condition `_when dimension1 in ("dimension1","dimension2")_` works but `_when dimension1 in ["dimension1","dimension2"]_` does not work.

**Environment**:
- Argo version:
```
$ argo version
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-03-26T00:04:52Z"
  compiler: gc
  gitCommit: 641856db18352033a0d96dbc99153fa3b27298e5
  gitTreeState: clean
  gitVersion: v1.14.0
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-08-20T22:39:46Z"
  compiler: gc
  gitCommit: 5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1
  gitTreeState: clean
  gitVersion: v1.13.10-eks-5ac0f1
  goVersion: go1.11.13
  major: "1"
  minor: 13+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
 
Name:                dag-diamond-coinflip-bvzlf
Namespace:           eim
ServiceAccount:      argo
Status:              Failed
Created:             Tue Oct 01 16:55:50 -0400 (35 minutes ago)
Started:             Tue Oct 01 16:55:50 -0400 (35 minutes ago)
Finished:            Tue Oct 01 16:55:50 -0400 (35 minutes ago)
Duration:            0 seconds
Parameters:
  transformations:   ["dimension2","dimension3","fact1","fact2"]

STEP                           PODNAME  DURATION  MESSAGE
 ✖ dag-diamond-coinflip-bvzlf
 └-✖ dimension-workflow
   ├-✖ transform-dimension1                       Failed to evaluate 'when' expresion 'dimension1 in ["dimension2","dimension3","fact1","fact2"]': Value '"dimension2","dimension3","fact1","fact2"' cannot be used with the comparator 'in', it is not a number
   | └---⚠ transform-task                         Failed to evaluate 'when' expresion 'dimension1 in ["dimension2","dimension3","fact1","fact2"]': Value '"dimension2","dimension3","fact1","fact2"' cannot be used with the comparator 'in', it is not a number
   ├-✖ transform-dimension2                       Failed to evaluate 'when' expresion 'dimension2 in ["dimension2","dimension3","fact1","fact2"]': Value '"dimension2","dimension3","fact1","fact2"' cannot be used with the comparator 'in', it is not a number
   | └---⚠ transform-task                         Failed to evaluate 'when' expresion 'dimension2 in ["dimension2","dimension3","fact1","fact2"]': Value '"dimension2","dimension3","fact1","fact2"' cannot be used with the comparator 'in', it is not a number
   └-✖ transform-dimension3                       Failed to evaluate 'when' expresion 'dimension3 in ["dimension2","dimension3","fact1","fact2"]': Value '"dimension2","dimension3","fact1","fact2"' cannot be used with the comparator 'in', it is not a number
     └---⚠ transform-task                         Failed to evaluate 'when' expresion 'dimension3 in ["dimension2","dimension3","fact1","fact2"]': Value '"dimension2","dimension3","fact1","fact2"' cannot be used with the comparator 'in', it is not a number
```

**Comment by GAHila** [comment]
It appears that if the list is passed as a string:

```
      entrypoint: diamond
      arguments:
        parameters:
        - name: transformations
          value: "dimension1,dimension2,fact1"
```
And it can be consumed as 

`when: "someValue in ({{workflow.parameters.transformations}})"`


However this approach works only if the value supplied is is a comma separated list. 

If the value is a single value it fails.

Actually when condition fails when with one parameter only like below without using parameters at all and that is a bug as it should be able to translate it into a list of one item.

`when: "someValue in (someValue)"`
