### ISSUE TITLE
templatizing workflow parameters

### ISSUE THREAD

**Issue by GAHila** [argoproj/argo#1635]
I need to be able to pass a group of parameters to a workflow. Since our DAG workflow will have about 30 steps and each of this steps has 7 parameters that will need to be passed in, if each one of them is passed on its own we will have a workflow that has 210 parameters.

If we can group these and maybe pass in 30 groups of parameters, it will be much easier to read. 

So I attempted something like the following:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-parameters-
spec:
  entrypoint: hello-goodbye
  arguments:
    parameters:
    - name: param1
      value: "{name: message, value: \"hello\"},{name: secondmessage, value: \"goodbye\"}"
  templates:
    - name: hello-goodbye
      steps:
        - - name: hello
            template: whalesay
            arguments:
              parameters: ["{{workflow.parameters.param1}}"]

    - name: whalesay
      inputs:
        parameters:
          - name: message
          - name: secondmessage
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{user.username}}"]
```
But when I run argo submit I get the error:

**`Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Arguments.parameters of type v1alpha1.Parameter`**

Is there any way to pass groups of parameters to a workflow or json objects?
