### ISSUE TITLE
[BUG] pod.name within retry does not match actual container

### ISSUE THREAD

**Issue by c-dante** [argoproj/argo#1646]
**BUG REPORT**:

**What happened**:
Using `{{pod.name}}` inside a retry gave the retry's node for each retry instance, not the individual instance's pod name. It prints:

```
MY_KUBE_NAME=pod-name-b9gvx-1810249896
MY_ARGO_NAME=pod-name-b9gvx
```

**What you expected to happen**:
I expect to get the actual pod name in each instance, IE both print the pod in kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-name-
spec:
  entrypoint: pod-name
  templates:
  - name: pod-name
    retryStrategy:
        limit: 1
    container:
      image: docker/whalesay
      env:
        - name: MY_ARGO_NAME
          value: "{{pod.name}}"
        - name: MY_KUBE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      command: ["/bin/sh"]
      args: ["-c", "env | grep MY_; exit 1"]
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```yaml
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```yaml
clientVersion:
  buildDate: "2019-09-18T14:51:13Z"
  compiler: gc
  gitCommit: 67d2fcf276fcd9cf743ad4be9a9ef5828adc082f
  gitTreeState: clean
  gitVersion: v1.15.4
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-06-19T20:48:40Z"
  compiler: gc
  gitCommit: f53039cc1e5295eed20969a4f10fb6ad99461e37
  gitTreeState: clean
  gitVersion: v1.12.8-gke.10
  goVersion: go1.10.8b4
  major: "1"
  minor: 12+
  platform: linux/amd64
```
