### ISSUE TITLE
argo lint requires kubeconfig

### ISSUE THREAD

**Issue by groodt** [argoproj/argo#1662]
**BUG REPORT**:

**What happened**:
argo lint failed in my CI environment

**What you expected to happen**:
argo lint to succeed

**How to reproduce it (as minimally and precisely as possible)**:
Fails:
```
curl --silent https://raw.githubusercontent.com/argoproj/argo/master/examples/coinflip.yaml > wf.yaml ; argo lint wf.yaml ; rm wf.yaml
```

Succeeds:
```
curl --silent https://raw.githubusercontent.com/argoproj/argo/master/examples/coinflip.yaml > wf.yaml ; argo --kubeconfig=config lint wf.yaml ; rm wf.yaml
```

**Environment**:
- Argo version:
2.4.1
- Kubernetes version :
```
clientVersion:
  buildDate: "1970-01-01T00:00:01Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: archive
  gitVersion: v1.14.3
  goVersion: go1.12.7
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-08-21T22:32:40Z"
  compiler: gc
  gitCommit: 5047edce664593832e9b889e447ac75ab104f527
  gitTreeState: clean
  gitVersion: v1.14.6-eks-5047ed
  goVersion: go1.12.9
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Context**:
I understand the difficulty in linting Workflows which have been decomposed into WorkflowTemplates, but I'm not sure a `lint` should attempt to resolve Kubernetes resources. 

Perhaps an additional command that does a full `validate` or an option to `lint` to prevent it from connecting to a cluster would be more appropriate.

A `lint` in my opinion should purely validate the structure or schema of the individual files, not the entire graph if it happens to contain remote resources in a cluster.
