### ISSUE TITLE
generate artifact via script failed when mounted emptyDir

### ISSUE THREAD

**Issue by dove-young** [argoproj/argo#1667]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:

I want generate a file under `/home/output` directory, I mounted an emptyDir to `/home/output` in my template, but it still failed 

```
[root@Argo]# argo submit -n argo artifact-volume.yaml
Name:                build-image-zf8t5
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Thu Oct 10 22:40:53 -0700 (now)
[root@Argo]# argo get -n argo build-image-zf8t5
Name:                build-image-zf8t5
Namespace:           argo
ServiceAccount:      default
Status:              Failed
Message:             invalid spec: templates.build-image-src.outputs.artifacts.hello-art: kubelet executor does not support outputs from base image layer. must use emptyDir
Created:             Thu Oct 10 22:40:53 -0700 (9 seconds ago)
Started:             Thu Oct 10 22:40:53 -0700 (9 seconds ago)
Finished:            Thu Oct 10 22:40:53 -0700 (9 seconds ago)
Duration:            0 seconds
[root@agentavtone-masterone Argo]#
```

**What you expected to happen**:

Docker file would be created in `/tmp/output/Dockerfile`

**How to reproduce it (as minimally and precisely as possible)**:

Submit an argo workflow like this 

```
[root@Argo]# cat artifact-volume.yaml
kind: Workflow
metadata:
  generateName: build-image-
spec:
  entrypoint: artifact-example
  volumes:
  - name: vol
    emptyDir: {}
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: build-image-src
  - name: build-image-src
    script:
      image: alpine:latest
      command: [sh, -c]
      source: |
        cat > /home/output/Dockerfile <<EOF
        FROM alpine
        RUN apk update && apk add curl
        EOF
      volumeMounts:
      - name: vol
        mountPath: /home/output
    outputs:
      artifacts:
      - name: hello-art
        path: /home/output/Dockerfile
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-10-02T17:01:15Z"
  compiler: gc
  gitCommit: d647ddbd755faf07169599a625faf302ffc34458
  gitTreeState: clean
  gitVersion: v1.16.1
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-05-08T02:18:32Z"
  compiler: gc
  gitCommit: eb4df6c6fb47f5b4fd1ed8bfbfe2d0ed5ea636e1
  gitTreeState: clean
  gitVersion: v1.13.5+icp-ee
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>

mentioned above
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by dove-young** [comment]
Generate K8S resource with output parameter also hit this problem. 

```
argo get artifact-cm-npl77
Name:                artifact-cm-npl77
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             invalid spec: templates.dockerfile-cm.outputs.parameters.cm-name: kubelet executor does not support outputs from base image layer. must use emptyDir
Created:             Fri Oct 11 01:56:49 -0700 (7 seconds ago)
Started:             Fri Oct 11 01:56:49 -0700 (7 seconds ago)
Finished:            Fri Oct 11 01:56:49 -0700 (7 seconds ago)
Duration:            0 seconds
```

Here is my workflow definition

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-cm-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-dockerfile
        template: dockerfile-cm
  - name: dockerfile-cm
    resource:                   # indicates that this is a resource template
      action: create            # can be any kubectl action (e.g. create, delete, apply, patch)
      successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |               #put your kubernetes spec here
        apiVersion: v1
        kind: ConfigMap
        metadata:
          generateName: alpine-
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            blockOwnerDeletion: true
            kind: Workflow
            name: "{{workflow.name}}"
            uid: "{{workflow.uid}}"
        data:
          Dockerfile: |
            FROM alpine
            RUN apk update && apk add curl 
    outputs:
      parameters:
      - name: cm-name
        valueFrom:
          jsonPath: '{.metadata.name}'
```
