### ISSUE TITLE
Feature request: Ability to assume role

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo#1668]
Feature request

Ability to Assume role by default by main container.

This would be equivalent to first doing:

`aws sts assume-role --role-arn arn:aws:iam::123456789012:role/xaccounts3access`

and using the generated credentials to use aws resources.

**Comment by jessesuen** [comment]
It wouldn't be feasible to have workflows act as the aws metadata server for the main container (similar to KIAM). I think the best we can do is to have a convenience input artifact type, `awsCredentials`, which will perform the sts-assume-role and place the generated credentials in file which is easily consumed by AWS SDKs like boto. Example below:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aws-assume-role-
spec:
  entrypoint: aws-assume-role
  templates:
  - name: aws-assume-role
    inputs:
      artifacts:
      - name: my-aws-credentials
        path: /root/.aws/credentials
        awsCredentials:
          assumeRoleARN: role:1l23123:1231312312
    container:
      image: debian:latest
      command: [sh, -c]
      args: ["ls -l /my-artifact"]

```

**Comment by thundergolfer** [comment]
@mehtadeepen We're moving to the new [IAM Roles for `serviceAccount`s](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) functionality. 

It's reasonably straightforward to associate a K8s `serviceAccount` with an AWS IAM role, and then you don't need to the `sts assume-role` at all _if_ you're application is using newer versions of AWS's SDKs that support it. 

Would this satisfy your needs?

**Comment by mehtadeepen** [comment]
> It wouldn't be feasible to have workflows act as the aws metadata server for the main container (similar to KIAM). I think the best we can do is to have a convenience input artifact type, `awsCredentials`, which will perform the sts-assume-role and place the generated credentials in file which is easily consumed by AWS SDKs like boto. Example below:
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   generateName: aws-assume-role-
> spec:
>   entrypoint: aws-assume-role
>   templates:
>   - name: aws-assume-role
>     inputs:
>       artifacts:
>       - name: my-aws-credentials
>         path: /root/.aws/credentials
>         awsCredentials:
>           assumeRoleARN: role:1l23123:1231312312
>     container:
>       image: debian:latest
>       command: [sh, -c]
>       args: ["ls -l /my-artifact"]
> ```



> It wouldn't be feasible to have workflows act as the aws metadata server for the main container (similar to KIAM). I think the best we can do is to have a convenience input artifact type, `awsCredentials`, which will perform the sts-assume-role and place the generated credentials in file which is easily consumed by AWS SDKs like boto. Example below:
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   generateName: aws-assume-role-
> spec:
>   entrypoint: aws-assume-role
>   templates:
>   - name: aws-assume-role
>     inputs:
>       artifacts:
>       - name: my-aws-credentials
>         path: /root/.aws/credentials
>         awsCredentials:
>           assumeRoleARN: role:1l23123:1231312312
>     container:
>       image: debian:latest
>       command: [sh, -c]
>       args: ["ls -l /my-artifact"]
> ```

Probably you will also need to add refresh time for long running steps. As `sts` can get you credentials just for 3600 seconds.

**Comment by thundergolfer** [comment]
> As sts can get you credentials just for 3600 seconds.

It can get you credentials for up to 12hrs, if the role you're getting creds for allows the full 12hrs. If not, you can get the max allowed by the role.

**Comment by simster7** [comment]
@sarabala1979 mentioned this possible solution. Would this work?

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aws-assume-role-
spec:
  entrypoint: aws-assume-role
  templates:
  - name: aws-assume-role
    inputs:
      artifacts:
      - name: aws-config
        path: /root/.aws/config
        raw:
          data: |
            [profile default]
            role_arn = role:1l23123:1231312312
    container:
      image: debian:latest
      command: [sh, -c]
      args: ["ls -l /my-artifact"]
```
