### ISSUE TITLE
Multiply memory on retry

### ISSUE THREAD

**Issue by bnouvelbmll** [argoproj/argo#1676]
FEATURE REQUEST

I am trying to run a parallel process which generally is low mem but occasionally requires a larger amount of memory. To increase parallelism it is tempting to put small memory requests on a large number of pods but if they fail they would need to retry, ideally with more memory.
It would be nice on retry to be able to tweak resource requests by adding providing a multiplicative factor like for exponetialDelay for backoffs.

**Comment by cmriprocan** [comment]
would love to see this one too

**Comment by simster7** [comment]
I agree that this would be a good enhancement. Before I share my ideas, have you considered a _workaround_ such as this?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-workaround-
spec:
  entrypoint: steps
  templates:
  - name: steps
    steps:
    - - name: base-try
        template: base-try
        continueOn:
          failed: true
    - - name: retry-1
        template: retry-1
        continueOn:
          failed: true
        when: "{{steps.base-try.status}} == Failed"
    - - name: retry-2
        template: retry-2
        when: "{{steps.retry-1.status}} == Failed"

  - name: base-try
    resource:
      # Resource with base memory (i.e. 100)

  - name: retry-1
    resource:
    # Resource with first retry memory (i.e. 200)

  - name: retry-2
    resource:
    # Resource with second retry memory (i.e. 300)
```
What do you think?

A nice way to solve this would be to expose the variable `{{step.retry.number}}` to the same step, then allow the user to be able to create an expression such as:
```
memoryRequest: [[100 + {{step.retry.number}} * 50]]MiB
```

However for this we would need to make two decisions:

1. To allow for expressions to be computed on a workflow (perhaps using https://github.com/Knetic/govaluate or https://github.com/antonmedv/expr (from #2356)). I could hear the argument of allowing commutable expressions being a slippery slope.
2. To allow self-reference in variables in general (i.e. self referencing a step using `{{step.[...]}}`. We are already going to add this within the context metrics emission only in #2254, but here we would need to add it in general.

I will try to bring this up at an internal meeting and get some opinions.
