### ISSUE TITLE
Parameter aggregation doesn't work when aggregating over a nested DAG output

### ISSUE THREAD

**Issue by ryan-maus** [argoproj/argo#1678]
Possible BUG REPORT

**What happened**:
Input workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nested-dag-param-aggregation-
spec:
  entrypoint: outer-dag
  templates:
  - name: outer-dag
    dag:
      tasks:
      # this version of parallel-outer-tasks works (when it's not using withItems/withParam)
      # - name: parallel-outer-tasks
      #   template: inner-dag
      #   arguments:
      #     parameters:
      #     - name: input-param
      #       value: hello world

      # this version of parallel-outer-tasks does not work
      - name: parallel-outer-tasks
        template: inner-dag
        arguments:
          parameters:
          - name: input-param
            value: "{{item}}"
        withItems:
        - hello world
        - goodbye world

      - name: echo-results
        dependencies: [parallel-outer-tasks]
        template: echo
        arguments:
          parameters:
          - name: message
            # I am expecting parameter aggregation here:
            #   ["hello world", "goodbye world"]
            # however I just get the literal value I've typed here:
            #   {{tasks.parallel-outer-tasks.outputs.parameters.inner-dag-output-param}}
            value: "{{tasks.parallel-outer-tasks.outputs.parameters.inner-dag-output-param}}"

  - name: inner-dag
    inputs:
      parameters:
      - name: input-param
    dag:
      tasks:
      - name: inner-echo-results
        template: echo
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.input-param}}"
    outputs:
      parameters:
      - name: inner-dag-output-param
        valueFrom:
          parameter: "{{tasks.inner-echo-results.outputs.parameters.output-param}}"

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}} | tee /tmp/output.txt "]
    outputs:
      parameters:
      - name: output-param
        valueFrom:
          path: /tmp/output.txt

```

**What you expected to happen**:
As noted in the YAML code above, I am expecting parameter aggregation in the outer DAG such that the 'echo-results' task would print ["hello world", "goodbye world"]

Instead it just prints the un-expanded parameter name it was given:  {{tasks.parallel-outer-tasks.outputs.parameters.inner-dag-output-param}}

If I mutate the parameter name in echo-results.arguments.parameters.value, the workflow fails to submit ("failed to resolve...") so it's seemingly wired together correctly but not inflating the variable as I'd expect.

Eliminating the withItems/withParams from the outer DAG resolves the issue (see YAML code), and "hello world" is printed as expected.

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-19T11:13:49Z"
  compiler: gc
  gitCommit: 96fac5cd13a5dc064f7d9f4f23030a6aeface6cc
  gitTreeState: clean
  gitVersion: v1.14.6
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-09-06T18:30:33Z"
  compiler: gc
  gitCommit: c9de33b5439df6e206d7ba646787c6ace92d737b
  gitTreeState: clean
  gitVersion: v1.14.6-gke.2
  goVersion: go1.12.9b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                nested-dag-param-aggregation-n29xv
Namespace:           default
ServiceAccount:      default
Status:              Succeeded
Created:             Tue Oct 15 16:49:54 -0500 (16 seconds ago)
Started:             Tue Oct 15 16:49:54 -0500 (16 seconds ago)
Finished:            Tue Oct 15 16:50:05 -0500 (5 seconds ago)
Duration:            11 seconds

STEP                                        PODNAME                                        DURATION  MESSAGE
 ✔ nested-dag-param-aggregation-n29xv                                                                
 ├-✔ parallel-outer-tasks(0:hello world)                                                             
 | └-✔ inner-echo-results                   nested-dag-param-aggregation-n29xv-2764457048  3s        
 ├-✔ parallel-outer-tasks(1:goodbye world)                                                           
 | └-✔ inner-echo-results                   nested-dag-param-aggregation-n29xv-3810644076  3s        
 └-✔ echo-results                           nested-dag-param-aggregation-n29xv-1735400932  3s 
```
```
$ argo logs nested-dag-param-aggregation-n29xv-1735400932
{{tasks.parallel-outer-tasks.outputs.parameters.inner-dag-output-param}}
```
