### ISSUE TITLE
`restartPolicy` does not work in workflow definition

### ISSUE THREAD

**Issue by brabster** [argoproj/argo#1701]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Unable to specify `restartPolicy` on a daemon container. On copying https://github.com/argoproj/argo/blob/master/examples/daemon-step.yaml and overwriting the daemon spec as shown in the [daemon container README](https://github.com/argoproj/argo/blob/master/examples/README.md#daemon-containers), the `argo` cli tool rejects the workflow, reporting:
```Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "restartPolicy"```

**What you expected to happen**:
Argo should have accepted the workflow, and should restart the daemon container if it fails.

**How to reproduce it (as minimally and precisely as possible)**:
Using this fairly minimal template, based on the README:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-step-
spec:
  entrypoint: daemon-example
  templates:
  - name: daemon-example
    steps:
    - - name: influx
        template: influxdb

  - name: influxdb
    daemon: true                        # start influxdb as a daemon
    container:
      image: influxdb:1.2
      restartPolicy: Always             # restart container if it fails
      readinessProbe:                   # wait for readinessProbe to succeed
        httpGet:
          path: /ping
          port: 8086
```

Submit to Argo as follows: `argo submit /path/to/the-above-definition.yml`

Error is
`Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "restartPolicy"`

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.4.1
  BuildDate: 2019-10-08T23:14:59Z
  GitCommit: d7f099992d8cf93c280df2ed38a0b9a1b2614e56
  GitTreeState: clean
  GitTag: v2.4.1
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-06-19T16:40:16Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-08-21T23:28:44Z"
  compiler: gc
  gitCommit: 569511c9540f78a94cc6a41d895c382d0946c11a
  gitTreeState: clean
  gitVersion: v1.13.10-gke.0
  goVersion: go1.11.13b4
  major: "1"
  minor: 13+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
N/A
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```
