### ISSUE TITLE
Nested steps run with incorrect parameters

### ISSUE THREAD

**Issue by mark9white** [argoproj/argo#1713]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:
If you execute the parallelism-nested.yaml example then the pods with a seq-id of b, c or d all have a parallel-id of 1

**What you expected to happen**:
pods with a seq-id of b, c or d all to have all parallel ids (1, 2, 3 and 4).

**How to reproduce it (as minimally and precisely as possible)**:
```argo submit parallelism-nested.yaml```
then:
```argo get <workflow-id> -o yaml```

There will be multiple pods in the Status section with seq-id of b and parallel id of 1, there should only be one.

**Anything else we need to know?**:
This looks to be related to https://github.com/argoproj/argo/pull/1552

storedTemplates contains the following, with seq-id hardcoded:
```
    /seq-worker:
      arguments: {}
      inputs: {}
      metadata: {}
      name: seq-worker
      outputs: {}
      parallelism: 1
      steps:
      - - arguments:
            parameters:
            - name: parallel-id
              value: "1"
            - name: seq-id
              value: '{{item}}'
          name: seq-step
          template: one-job
          withParam: |
            ["a","b","c","d"]
```

**Environment**:
- Argo version: master
```
$ argo version
```
- Kubernetes version : 1.12

**Comment by mark9white** [comment]
@dtaniwaki fyi, I think this relates to your PR

**Comment by NirvanaZA** [comment]
Hi sir, When this bug fix will release? Hope soon. Many thanks.

**Comment by sarabala1979** [comment]
@dtaniwaki is refactoring the store template feature. This will close most of the bugs.

**Comment by NirvanaZA** [comment]
I tried to downgrade the version to 2.4.0, from 2.4.2, and seems the retry feature has some bug as well.

**Comment by simster7** [comment]
@NirvanaZA could you elaborate on the bug with the retry feature?

**Comment by samath117** [comment]
Another minimal example to illustrate what appears to be the same problem:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: steps
  templates:
  - name: print
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}}"]
  - name: print-twice
    inputs:
      parameters:
      - name: message
    steps:
    - - name: print1
        template: print
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"
    - - name: print2
        template: print
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"
  - name: steps
    steps:
    - - name: hello
        template: print-twice
        arguments:
          parameters:
          - name: message
            value: hello
    - - name: goodbye
        template: print-twice
        arguments:
          parameters:
          - name: message
            value: goodbye
```

On Argo 2.3.0, this has the expected behavior. Workflow logs:
```
print1: hello
print2: hello
print1: goodbye
print2: goodbye
```

On Argo 2.4.2, the message for the last one is passed incorrectly:
```
print1: hello
print2: hello
print1: goodbye
print2: hello
```
