### ISSUE TITLE
Environment variables from parameter file are encapsulated in quotes

### ISSUE THREAD

**Issue by perbu** [argoproj/argo#1718]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: Environment variables from parameter file are encapsulated in quotes.

**What you expected to happen**: I expected the environment variable to be set to the correct value without adding quotes to the string.

**How to reproduce it (as minimally and precisely as possible)**:

Given the following workflow: 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: dump-env
  templates:
  - name: dump-env
    container:
      image: alpine:latest
      command: [env]
      env:
        - name: 'ENDPOINT'
          value:  '{{workflow.parameters.ENDPOINT}}'
```
with the following parameter file:
```
ENDPOINT: https://storage.googleapis.com/
```

Invoked like this:
```
➜  Argo argo submit --parameter-file minimal.yaml minimal-workflow.yaml 
Name:                hello-world-gzxzp
Namespace:           default
ServiceAccount:      default
Status:              Pending
Created:             Wed Oct 30 12:45:46 +0100 (now)
Parameters:          
  ENDPOINT:          "https://storage.googleapis.com/"
➜  Argo 
```
You see ENDPOINT is set with quotes within the environment variable itself. What I expected was this to be set to the content of the string, without quotes.

I now have to cleanup the environment variables before I can use them.

Note that _integer values_ are correctly set. 

**Anything else we need to know?**:

**Environment**:
```
➜  Argo argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
$ argo version
```
- Kubernetes version :
```
➜  Argo kubectl version -o yaml
clientVersion:
  buildDate: "2019-09-18T14:47:22Z"
  compiler: gc
  gitCommit: 8fca2ec50a6133511b771a11559e24191b1aa2b4
  gitTreeState: clean
  gitVersion: v1.14.7
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-09-18T14:39:02Z"
  compiler: gc
  gitCommit: 8fca2ec50a6133511b771a11559e24191b1aa2b4
  gitTreeState: clean
  gitVersion: v1.14.7
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: linux/amd64
```

PS: I'm otherwise super happy with Argo. It is a very useful tool for me and it sparks joy.
