### ISSUE TITLE
Workflow controller repeatedly attempts to create pods that already exist

### ISSUE THREAD

**Issue by Syps** [argoproj/argo#1720]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Workflow controller continually tries to create the same workflow pod, which counts against resource quotas.

**What you expected to happen**:
Workflow should create the workflow pod once, and not try again if it was successful the first time.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a single workflow that runs for a bit (I use 30 seconds here):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dulicate-pods-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      name: main
      image: alpine
      command: [bin/sh]
      args: [-c, sleep 30]
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 400m
          memory: 1Gi
```

2. Set up a resource quota in your namespace that limits the number of pods.
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-argo
  namespace: argo
spec:
  hard:
    cpu: '32'
    memory: 64Gi
    pods: '12'

```

3. Launch the workflow and monitor the workflow controller logs, and the resource quota status using `kubectl get quota quota-argo -o yaml --watch`.

4. You will see the workflow controller logs repeatedly outputting `Skipped pod <the pod name> (<the pod name>) creation: already exists`. Meanwhile, due to bugs in kubernetes regarding invalid pod requests counting towards resource quotas (see https://github.com/kubernetes/kubernetes/issues/70563 and https://github.com/kubernetes/kubernetes/issues/51476), these invalid duplicate requests count against the pod limit of our resource quota. Ultimately this results in the workflow failing if the quota is exceeded. 

**Anything else we need to know?**:
While this seems to involve a bug in kubernetes, it seems like there should be a way for the workflow controller to avoid repeatedly submitting the same pod creation request. I can see that this scenario is actually expected in the code (https://github.com/argoproj/argo/blob/master/workflow/controller/workflowpod.go#L271) though I'm not sure why. Hopefully there is a way to avoid this scenario completely. 

**Environment**:
- Argo version: `2.4.2`

- Kubernetes version : `1.14`

- workflow-controller logs:
```
time="2019-10-31T12:37:58Z" level=info msg="Skipped pod pod-spec-patch-wrvrr (pod-spec-patch-wrvrr) creation: already exists" namespace=argo workflow=pod-spec-patch-wrvrr
time="2019-10-31T12:37:58Z" level=info msg="Workflow update successful" namespace=argo workflow=pod-spec-patch-wrvrr
time="2019-10-31T12:37:59Z" level=info msg="Processing workflow" namespace=argo workflow=pod-spec-patch-wrvrr
time="2019-10-31T12:37:59Z" level=info msg="Skipped pod pod-spec-patch-wrvrr (pod-spec-patch-wrvrr) creation: already exists" namespace=argo workflow=pod-spec-patch-wrvrr
time="2019-10-31T12:38:01Z" level=info msg="Processing workflow" namespace=argo workflow=pod-spec-patch-wrvrr
time="2019-10-31T12:38:01Z" level=info msg="Skipped pod pod-spec-patch-wrvrr (pod-spec-patch-wrvrr) creation: already exists" namespace=argo workflow=pod-spec-patch-wrvrr
time="2019-10-31T12:38:07Z" level=info msg="Processing workflow" namespace=argo workflow=pod-spec-patch-wrvrr
time="2019-10-31T12:38:07Z" level=info msg="Skipped pod pod-spec-patch-wrvrr (pod-spec-patch-wrvrr) creation: already exists" namespace=argo workflow=pod-spec-patch-wrvrr
time="2019-10-31T12:38:11Z" level=info msg="Processing workflow" namespace=argo workflow=pod-spec-patch-wrvrr
```
