### ISSUE TITLE
Failed to wait for container executor error: Get https://worker-ip:10250/pods: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dove-young** [argoproj/argo#1723]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:

When executor set to `kubelet` and using artifacts outputs in a workflow, 

Get https://worker-ip:10250/pods: x509: certificate signed by unknown authority"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-example-
spec:
  entrypoint: argo-workflow-example
  volumes:
  - name: vol
    emptyDir: {}      
  templates:
  - name: argo-workflow-example
    steps:
    - - name: populate-data
#        templateRef:
#          name: container-s3-data-tmpl
        template: populate-s3-data
  - name: populate-s3-data   
    inputs:
      parameters:
      - name: agent-pkg-path
      - name: artifacts-path
      - name: test-pkg
      - name: dc-build
      - name: workspace
#      - name: image-utils
      - name: RELEASE_VERSION    
      artifacts:
      - name: agent-pkg
        path: "{{inputs.parameters.workspace}}/{{inputs.parameters.agent-pkg-path}}"
        s3:
          bucket: my-bucket
          endpoint: "{{workflow.parameters.minio-server}}"
          insecure: true
          key: "{{inputs.parameters.agent-pkg-path}}"
          accessKeySecret:
            name: "{{workflow.parameters.minio-access-secret}}"
            key: accesskey
          secretKeySecret:
            name: "{{workflow.parameters.minio-access-secret}}"
            key: secretkey
    script:
      image: "{{workflow.parameters.image-utils}}" 
      command: ["/bin/bash"]
      env:
      - name: WORKSPACE
        value: "{{inputs.parameters.workspace}}"
      - name: AGENT_PKG
        value: "{{inputs.parameters.agent-pkg-path}}"
      volumeMounts:
        - mountPath: "{{inputs.parameters.workspace}}/outputs"
          name: vol        
      source: |
        set -o xtrace
        find {{inputs.parameters.workspace}} -maxdepth 3
        cd ${WORKSPACE}

        do something
    outputs:
      artifacts:
      - name: nodejs-pets
        path: "{{inputs.parameters.workspace}}/outputs/something"

  - name: check-nodejs-pets
    inputs:
      artifacts:
      - name: nodejs-pets
        path: /src/nodejs-pets
      parameters:
      - name: docker-context
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:29Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml

clientVersion:
  buildDate: "2019-10-02T17:01:15Z"
  compiler: gc
  gitCommit: d647ddbd755faf07169599a625faf302ffc34458
  gitTreeState: clean
  gitVersion: v1.16.1
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-10-15T19:09:08Z"
  compiler: gc
  gitCommit: c97fe5036ef3df2967d086711e6c0c405941e14b
  gitTreeState: clean
  gitVersion: v1.16.2
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>

argo get argo-example-mfm2w
Name:                argo-example-mfm2w
Namespace:           argo
ServiceAccount:      default
Status:              Failed
Message:             child 'argo-example-mfm2w-3822881816' failed
Created:             Thu Oct 31 21:40:01 -0700 (1 minute ago)
Started:             Thu Oct 31 21:40:01 -0700 (1 minute ago)
Finished:            Thu Oct 31 21:40:45 -0700 (27 seconds ago)
Duration:            44 seconds
Parameters:
  docker-context:    images/alpine-utils/
  ... ...

STEP                                           PODNAME                        DURATION  MESSAGE
 ✖ argo-example-mfm2w (argo-workflow-example)                                           child 'argo-example-mfm2w-3822881816' failed
 └---⚠ populate-data (populate-s3-data)        argo-example-mfm2w-3822881816  42s       failed to save outputs: Get https://worker-ip:10250/pods: x509: certificate signed by unknown authority
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
time="2019-11-01T02:48:37Z" level=info msg="Waiting on main container"
time="2019-11-01T02:48:39Z" level=info msg="main container started with container ID: ecd8fa97268772375fd0c8409da22162cbcedd4b90098f610eb919e3f55678e1"
time="2019-11-01T02:48:39Z" level=info msg="Starting annotations monitor"
time="2019-11-01T02:48:39Z" level=info msg="Starting to wait completion of containerID ecd8fa97268772375fd0c8409da22162cbcedd4b90098f610eb919e3f55678e1 .
.."
time="2019-11-01T02:48:39Z" level=info msg="Starting deadline monitor"
time="2019-11-01T02:48:40Z" level=warning msg="Failed to wait for container id 'ecd8fa97268772375fd0c8409da22162cbcedd4b90098f610eb919e3f55678e1': Get ht
tps://9.46.74.222:10250/pods: x509: certificate signed by unknown authority"
time="2019-11-01T02:48:40Z" level=error msg="executor error: Get https://9.46.74.222:10250/pods: x509: certificate signed by unknown authority
github.com/argoproj/argo/errors.Wrap
/go/src/github.com/argoproj/argo/errors/errors.go:88
github.com/argoproj/argo/errors.InternalWrapError
/go/src/github.com/argoproj/argo/errors/errors.go:71
github.com/argoproj/argo/workflow/executor/kubelet.(*kubeletClient).GetContainerStatus
/go/src/github.com/argoproj/argo/workflow/executor/kubelet/client.go:171
github.com/argoproj/argo/workflow/executor/common.WaitForTermination
/go/src/github.com/argoproj/argo/workflow/executor/common/common.go:55
github.com/argoproj/argo/workflow/executor/kubelet.(*kubeletClient).WaitForTermination
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)

time="2019-11-01T04:40:38Z" level=debug msg="Setting s3 artifact repository information" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:38Z" level=info msg="Skipped pod argo-example-mfm2w[0].populate-data (argo-example-mfm2w-3822881816) creation: already exists" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:38Z" level=info msg="Workflow step group node argo-example-mfm2w[0] (argo-example-mfm2w-3481469823) not yet completed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=info msg="Processing workflow" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=debug msg="Evaluating node argo-example-mfm2w: template: *v1alpha1.Template (argo-workflow-example), boundaryID: " namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=debug msg="Executing node argo-example-mfm2w of Steps is Running" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=debug msg="Found a resolved template for node argo-example-mfm2w" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=debug msg="Evaluating node argo-example-mfm2w[0].populate-data: template: *v1alpha1.WorkflowStep (populate-s3-data), boundaryID: argo-example-mfm2w" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=debug msg="Executing node argo-example-mfm2w[0].populate-data of Pod is Running" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=debug msg="Found a resolved template for node argo-example-mfm2w[0].populate-data" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=debug msg="Creating Pod: argo-example-mfm2w[0].populate-data (argo-example-mfm2w-3822881816)" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=debug msg="Setting s3 artifact repository information" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=info msg="Skipped pod argo-example-mfm2w[0].populate-data (argo-example-mfm2w-3822881816) creation: already exists" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:39Z" level=info msg="Workflow step group node argo-example-mfm2w[0] (argo-example-mfm2w-3481469823) not yet completed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Processing workflow" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Updating node argo-example-mfm2w[0].populate-data (argo-example-mfm2w-3822881816) status Running -> Error"
time="2019-11-01T04:40:45Z" level=info msg="Updating node argo-example-mfm2w[0].populate-data (argo-example-mfm2w-3822881816) message: failed to save outputs: Get https://9.46.75.116:10250/pods: x509: certificate signed by unknown authority"
time="2019-11-01T04:40:45Z" level=debug msg="Evaluating node argo-example-mfm2w: template: *v1alpha1.Template (argo-workflow-example), boundaryID: " namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=debug msg="Executing node argo-example-mfm2w of Steps is Running" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=debug msg="Found a resolved template for node argo-example-mfm2w" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=debug msg="Evaluating node argo-example-mfm2w[0].populate-data: template: *v1alpha1.WorkflowStep (populate-s3-data), boundaryID: argo-example-mfm2w" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=debug msg="Node argo-example-mfm2w[0].populate-data already completed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Step group node argo-example-mfm2w[0] (argo-example-mfm2w-3481469823) deemed failed: child 'argo-example-mfm2w-3822881816' failed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="node argo-example-mfm2w[0] (argo-example-mfm2w-3481469823) phase Running -> Failed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="node argo-example-mfm2w[0] (argo-example-mfm2w-3481469823) message: child 'argo-example-mfm2w-3822881816' failed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="node argo-example-mfm2w[0] (argo-example-mfm2w-3481469823) finished: 2019-11-01 04:40:45.302128831 +0000 UTC" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="step group argo-example-mfm2w-3481469823 was unsuccessful: child 'argo-example-mfm2w-3822881816' failed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Outbound nodes of argo-example-mfm2w-3822881816 is [argo-example-mfm2w-3822881816]" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Outbound nodes of argo-example-mfm2w is [argo-example-mfm2w-3822881816]" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="node argo-example-mfm2w (argo-example-mfm2w) phase Running -> Failed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="node argo-example-mfm2w (argo-example-mfm2w) message: child 'argo-example-mfm2w-3822881816' failed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="node argo-example-mfm2w (argo-example-mfm2w) finished: 2019-11-01 04:40:45.30233349 +0000 UTC" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Checking daemoned children of argo-example-mfm2w" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Updated message  -> child 'argo-example-mfm2w-3822881816' failed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Marking workflow completed" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Checking daemoned children of " namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:45Z" level=info msg="Workflow update successful" namespace=argo workflow=argo-example-mfm2w
time="2019-11-01T04:40:46Z" level=info msg="Labeled pod argo/argo-example-mfm2w-3822881816 completed"
```
