### ISSUE TITLE
argo resubmit removes ownerReferences

### ISSUE THREAD

**Issue by epa095** [argoproj/argo#1736]
**Is this a BUG REPORT or FEATURE REQUEST?**:
I don't know, bug report maybe? I don't know what is expected behaviour in k8s, but I definitely did not expect the current behaviour. 
**What happened**:
I have a workflow with `metadata.ownerReferences` set. I resubmit it. The resubmitted job does not get `metadata.ownerReferences` set. 

**What you expected to happen**:
The resubmitted workflow to have the save `metadata.ownerReferences` as the original workflow.

**How to reproduce it (as minimally and precisely as possible)**:
Make a workflow with `metadata.ownerReferences` set, resubmit it, and see that the new workflow does not have `metadata.ownerReferences` set. 

**Anything else we need to know?**:
`metadata.ownerReferences` is used for deleting the workflow when the owning resource is deleted

**Environment**:
- Argo version:
```
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:09Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-19T11:13:54Z"
  compiler: gc
  gitCommit: 2d3c76f9091b6bec110a5e63777c332469e0cba2
  gitTreeState: clean
  gitVersion: v1.15.3
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-08-19T11:05:16Z"
  compiler: gc
  gitCommit: 96fac5cd13a5dc064f7d9f4f23030a6aeface6cc
  gitTreeState: clean
  gitVersion: v1.14.6
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: linux/amd64

```
