### ISSUE TITLE
Support for template-level volumeClaimTemplates

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo#1747]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

I'm trying to write a workflow that:
1. Queries an external storage system to get the size of a file
2. Generates a PVC big enough to fit the file
3. Downloads the file onto the volume
4. Processes it from there

Since PVCs are currently a workflow-level resource in Argo, my first thought for how to make this work was to use a `resource` template to directly allocate the `PersistentVolumeClaim`, then mount that PVC into each following step. From some (brief) experiments it looks like I can definitely create the claim, but the following `container` / `script` templates can't mount it because it doesn't appear in the workflow's list of volume claims. To work around _that_, I have to use raw k8s resources for the processing pods / jobs.

Another option could be to create an entire nested workflow as a raw k8s resource [like in this example](https://github.com/argoproj/argo/blob/master/examples/k8s-wait-wf.yaml), and pass in the file size as an argument. I'm going to try that next, but it's not ideal since it makes tracking the progress of a (conceptually) single workflow more difficult.

**What you expected to happen**:

It'd be awesome if Argo could support template-level `volumeClaimTemplates`. In my head, the workflow spec could look something like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dream-workflow-
spec:
  entrypoint: lookup-download-and-process-file
  templates:
  - name: lookup-download-and-process-file
    steps:
    - - name: get-file-size
        template: get-file-size
    - - name: download-and-process-file
        template: download-and-process-file
        arguments:
          parameters:
          - name: file-size
            value: '{{steps.get-file-size.outputs.result}}'

  - name: get-file-size
    container:
      image: alpine:3.10
      command: [echo]
      args: ["10Gi"]

  - name: download-and-process-file
    inputs:
      parameters:
      - name: file-size
    volumeClaimTemplates:
      - metadata:
          name: workdir
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: '{{inputs.parameters.file-size}}'
    steps:
    - - name: download-file
        template: download-file
        arguments:
          parameters:
            # Not super clear how this part would work
            volume-claim: '{{workdir.real-name}}'
    - - name: process-file
        template: process-file
        arguments:
          parameters:
            volume-claim: '{{workdir.real-name}}'

  - name: download-file
    inputs:
      parameters:
      - name: volume-claim
    volumes:
    - name: workdir
      mountPath: /out
      persistentVolumeClaim: '{{inputs.parameters.volume-claim}}'
    container:
      image: alpine:3.10
      command: [echo]
      args: [foo, >, /out/downloaded]

  - name: process-file
    inputs:
      parameters:
      - name: volume-claim
    volumes:
    - name: workdir
      mountPath: /in
      persistentVolumeClaim: '{{inputs.parameters.volume-claim}}'
    container:
      image: alpine:3.10
      command: [cat]
      args: [/in/downloaded]
```

**Comment by jessesuen** [comment]
> From some (brief) experiments it looks like I can definitely create the claim, but the following container / script templates can't mount it because it doesn't appear in the workflow's list of volume claims

Resource templates [can have output parameters](https://github.com/argoproj/argo/blob/master/examples/k8s-jobs.yaml#L50). 
The resource template which creates the PVC should make the name of the PVC as an output parameter, which is then used as an input parameter to the step which wants to use it.

**Comment by danxmoran** [comment]
@jessesuen getting the PVC name isn't tough, but I'm not sure how to use it in downstream steps. I'm trying to do something like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pvc-mid-workflow-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: create-volume
        template: create-volume
    - - name: check-volume
        template: check-volume
        arguments:
          parameters:
          - name: pvc-name
            value: '{{steps.create-volume.outputs.parameters.pvc-name}}'
  - name: create-volume
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          generateName: mid-workflow-pvc-
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    outputs:
      parameters:
      - name: pvc-name
        valueFrom:
          jsonPath: '{.metadata.name}'
  - name: check-volume 
    inputs:
      parameters:
      - name: pvc-name
    container:
      image: alpine:latest
      command: [sh, -c]
      args: [df, /mnt/vol]
      volumeMounts:
      - name: '{{inputs.parameters.pvc-name}}'
        mountPath: /mnt/vol
```
But that results in errors like `volume 'mid-workflow-pvc-pnz7s' not found in workflow spec`.

My current best guess at a workaround is to use `podSpecPatch` to inject all the configuration needed to mount the generated PVC into the `main` container of every pod that needs it. This wouldn't be awful since I'd still get to lean on the nice short-hand of `container` templates, but it still feels pretty brittle (and difficult for others not as familiar with argo / k8s to grok). Is there another approach you'd recommend?

**Comment by danxmoran** [comment]
@jessesuen I tried working around this limitation using `podSpecPatch`, but it's causing errors. For example, I have a workflow template:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: download-ftp-file
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: ftp-site
          - name: ftp-path
          - name: local-path
          - name: pvc-name
      podSpecPatch: |
        volumes:
          - name: state
            persistentVolumeClaim:
              claimName: {{inputs.parameters.pvc-name}}
        containers:
          - name: main
            volumeMounts:
              - name: state
                mountPath: /state
      container:
        image: cirrusci/wget
        command: [wget]
        args:
          # Restart from any state
          - --continue
          # Reset the download connection if it goes idle for > 30 seconds.
          - --read-timeout=30
          - --output-document=/state/{{inputs.parameters.local-path}}
          - ftp://{{inputs.parameters.ftp-site}}/{{inputs.parameters.ftp-path}}
```
The `pvc-name` input is generated by an earlier `resource` step in a DAG, and that plumbing works fine. When the template above attempts to execute I get this error:
```
Pod "ingest-clinvar-archive-ttbbz-2669865119" is invalid: [spec.volumes[0].downwarAPI: Forbidden: may not specify more than 1 volume type, spec.volumes[1].downwarAPI: Forbidden: may not specify more than 1 volume type, spec.containers[0].volumeMounts[0].name: Not found: "podmetadata", spec.containers[1].volumeMounts[0].name: Not found: "state"]
```
My team doesn't need this feature right now, but we'll have an urgent need next quarter. I'd be happy to contribute the feature if we can agree on the design. I can think of three ways to move forward:
1. Implement the full support for template-level volume specs, which might be useful for the "submittable templates" feature too
2. Add a new field somewhere in the `container` and `script` models for specifying "dynamic" or "raw" PVC names, which could be mounted without being validated against the workflow-level list of volume names
3. Figure out what's going wrong with the `podSpecPatch` approach, and fix it

Option 2 feels like the lowest-hanging fruit to me. What do you / others on the team think?
