### ISSUE TITLE
Output artifact in same location as optional input artifact is not saved

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#1750]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: When an output artifact location matches that of an optional input artifact which is not supplied, the output artifact fails to save properly. This is related to #1503 and #1660.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: optional-input-output-artifact-same-location-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:
    - - name: write
        template: file
    - - name: read
        template: file
        arguments:
          artifacts:
          - name: file
            from: "{{steps.write.outputs.artifacts.file}}"
  - name: file
    inputs:
      artifacts:
      - name: file
        path: /tmp/file1.txt
        optional: true
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'test' > /tmp/file1.txt"]
    outputs:
      artifacts:
      - name: file
        path: /tmp/file1.txt
```
When this is run, the `write` step passes, but the `read` step fails with this message: `inputs.artifacts.file was not supplied`. If the location of the optional input file is changed to `/tmp/file2.txt`, then both steps pass. This indicates that the output artifact is failing to save properly, but isn't raising an error in the process even though it isn't labeled as optional.

**Environment**: Argo version: 2.4.1
