### ISSUE TITLE
[Question] How to pass parameters to a workflow via http call?

### ISSUE THREAD

**Issue by ambarish510** [argoproj/argo#1757]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Question
**What happened**:
I'm able to make an api call to submit a workflow using the curl request below:-

curl -X POST  http://host/apis/argoproj.io/v1alpha1/namespaces/default/workflows   -H 'Authorization: Bearer TOKEN'   -H 'Content-Type: application/yaml'  -d"$(cat sample-pipeline.yaml)"

I've gone through many examples / documentations etc but I could find anything on passing parameters to workflow using api calls.

**What you expected to happen**:
A way to pass parameters using api call to submit workflows.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64

```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-19T12:36:28Z"
  compiler: gc
  gitCommit: 2d3c76f9091b6bec110a5e63777c332469e0cba2
  gitTreeState: clean
  gitVersion: v1.15.3
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-06-19T16:32:14Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: linux/amd64
```
