### ISSUE TITLE
Cannot reference multiple workflowtemplates in single workflow

### ISSUE THREAD

**Issue by nHurD** [argoproj/argo#1785]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**: 
I'm writing a workflow that references two separate `WorkflowTemplates` within my cluster and am receiving the following error:
```
2019/11/20 13:46:44 Failed to submit workflow: templates.main.steps[1].ending template reference workflow-template-whalesay-template-2.workflow-template-2 not found
```

**What you expected to happen**:
The workflows to run as expected

**How to reproduce it (as minimally and precisely as possible)**:
1.  Create two workflow templates within k8s:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template-2
spec:
  templates:
  - name: whalesay-template-2
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

```
2. Submit the following workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sample-
spec:
  serviceAccountName: argo
  entrypoint: main
  templates:
  - name: the-end
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["the end"]
  - name: main
    steps:
    - - name: echo-stuff
        templateRef:
          name: workflow-template-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
            - name: message
              value: "{{item}}"
        withItems:
          - this
          - is
          - a
          - test
    - - name: ending
        templateRef:
          name: workflow-template-whalesay-template-2
          template: workflow-template-2
        arguments:
          parameters:
            - name: message
              value: "ending"
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version

argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml

clientVersion:
  buildDate: "2019-09-18T14:47:22Z"
  compiler: gc
  gitCommit: 8fca2ec50a6133511b771a11559e24191b1aa2b4
  gitTreeState: clean
  gitVersion: v1.14.7
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-08-19T10:44:49Z"
  compiler: gc
  gitCommit: 37d169313237cb4ceb2cc4bef300f2ae3053c1a2
  gitTreeState: clean
  gitVersion: v1.13.10
  goVersion: go1.11.13
  major: "1"
  minor: "13"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)

time="2019-11-20T18:40:25Z" level=info msg="Persistence configuration disabled"
time="2019-11-20T18:40:25Z" level=info msg="Workflow Controller (version: v2.4.2) starting"
time="2019-11-20T18:40:25Z" level=info msg="Workers: workflow: 8, pod: 8"
time="2019-11-20T18:40:25Z" level=info msg="Watch Workflow controller config map updates"
time="2019-11-20T18:40:25Z" level=info msg="Starting prometheus metrics server at 0.0.0.0:8080/metrics"
time="2019-11-20T18:40:25Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2019-11-20T18:40:25Z" level=info msg="Starting prometheus metrics server at 0.0.0.0:8081/telemetry"
time="2019-11-20T18:40:25Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2019-11-20T18:40:25Z" level=info msg="Persistence configuration disabled"
time="2019-11-20T18:40:25Z" level=info msg="Started workflow TTL worker"
time="2019-11-20T18:45:25Z" level=info msg="Alloc=4031 TotalAlloc=12981 Sys=70590 NumGC=7 Goroutines=77"
time="2019-11-20T18:50:25Z" level=info msg="Alloc=4064 TotalAlloc=13091 Sys=70590 NumGC=9 Goroutines=77"
time="2019-11-20T18:55:25Z" level=info msg="Alloc=4052 TotalAlloc=13115 Sys=70590 NumGC=12 Goroutines=77"
W1120 18:57:40.140051       1 reflector.go:289] github.com/argoproj/argo/workflow/controller/config_controller.go:116: watch of *v1.ConfigMap ended with: too old resource version: 11611344 (11611877)
```
