### ISSUE TITLE
When script output contains "{{", it cannot be used in a "when" expression

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#1801]
Example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: brackets-test-
spec:
  entrypoint: brackets-test
  templates:
  - name: brackets-test
    steps:
    - - name: brackets
        template: brackets
      - name: no-brackets
        template: no-brackets
    - - name: no-brackets-test
        template: success
        when: "{{steps.no-brackets.outputs.result}} == true"
    - - name: brackets-test
        template: success
        when: "{{steps.brackets.outputs.result}} == {{true}}"

  - name: brackets
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        print("{{true}}")

  - name: no-brackets
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        print("true")

  - name: success
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"got here successfully\""]
```
Result:
```
Name:                brackets-test-rmk4w
Namespace:           argo
ServiceAccount:      default
Status:              Failed
Message:             Invalid 'when' expression '{{true}} == {{true}}': Invalid token: '{{'
Created:             Wed Nov 27 09:18:02 -0800 (12 seconds ago)
Started:             Wed Nov 27 09:18:02 -0800 (12 seconds ago)
Finished:            Wed Nov 27 09:18:14 -0800 (now)
Duration:            12 seconds

STEP                                    PODNAME                         DURATION  MESSAGE
 ✖ brackets-test-rmk4w (brackets-test)                                            Invalid 'when' expression '{{true}} == {{true}}': Invalid token: '{{'
 ├-·-✔ brackets (brackets)              brackets-test-rmk4w-560115208   5s
 | └-✔ no-brackets (no-brackets)        brackets-test-rmk4w-2219011512  7s
 ├---✔ no-brackets-test (success)       brackets-test-rmk4w-2596172140  3s
 └---⚠ brackets-test (success)                                                    Invalid 'when' expression '{{true}} == {{true}}': Invalid token: '{{'
```
Slightly related to https://github.com/argoproj/argo/issues/1792
