### ISSUE TITLE
Inputs to a task are evaluated even if the condition says it shouldn't run - failing the flow

### ISSUE THREAD

**Issue by perbu** [argoproj/argo#1807]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG, potentially this could be the desired behavior, but if so it should be reflected in docs or examples.

**What happened**:
Given a flow which looks like this:

```
     B -> B2 
   /        \
A - C - C2 - D
```
Where C2 depends on artifacts created by C. C isn't run so when the C2 container is evaluated it fails the entire workflow as it has inputs from C.

Note that the C and C2 tasks have a when-statement that would prohibit them from running. 

Perhaps it would be possible to evaluate the inputs to a task after the conditional has been evaluated?

**What you expected to happen**:

I expected the workflow to succeed and the inputs for the B2 container not to be evaluated.

**How to reproduce it (as minimally and precisely as possible)**:
Submit the following workflow:

https://gist.github.com/perbu/56b93c4a9cff0ea1472eb90a5a31191d

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.4.0+12b983f.dirty
```
k8s:
```
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cheers.

**Comment by simster7** [comment]
I tried this out and I agree it seems like buggy behavior. More specifically, it seems like we should evaluate a `when` clause _before_ trying to evaluate arguments.

I'll try to take a look at this next week. Here is the relevant code in case anyone wants to also take a look: https://github.com/argoproj/argo/blob/master/workflow/controller/dag.go#L357-L393

Here is the Workflow I used:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
      - name: B
        dependencies: [A]
        template: echo
      - name: C
        dependencies: [A]
        template: make-artifact
        when: "a == b"
      - name: C2
        dependencies: [C]
        when: "{{tasks.C.status}} == Succeeded"
        template: use-artifact
        arguments:
          artifacts:
            - name: message
              from: "{{tasks.C.outputs.artifacts.hello-art}}"
      - name: D
        dependencies: [B, C2]
        template: echo

  - name: echo
    container:
      image: alpine:3.7
      command: [echo, "Hello"]

  - name: make-artifact
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt

  - name: use-artifact
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["cat /tmp/message"]
```
With the following result:
```
Name:                dag-diamond-5xxjn
Namespace:           default
ServiceAccount:      default
Status:              Error
Created:             Sat Nov 30 10:47:17 -0800 (7 seconds ago)
Started:             Sat Nov 30 10:47:17 -0800 (7 seconds ago)
Finished:            Sat Nov 30 10:47:24 -0800 (now)
Duration:            7 seconds

STEP                            PODNAME                       DURATION  MESSAGE
 ⚠ dag-diamond-5xxjn (diamond)
 ├-✔ A (echo)                   dag-diamond-5xxjn-2918226225  3s
 ├-✔ B (echo)                   dag-diamond-5xxjn-2867893368  2s
 ├-○ C (make-artifact)                                                  when 'a == b' evaluated false
 └-⚠ C2 (use-artifact)                                                  Unable to resolve: {{tasks.C.outputs.artifacts.hello-art}}
```
