### ISSUE TITLE
Can't set different network policy to different pods in single workflow

### ISSUE THREAD

**Issue by zhangxiaohao** [argoproj/argo#1809]
I am using Argo to build CI pipeline, and I have two step (compile, test) in a workflow. I want using hostNetwork only in compile step pods.

**Comment by eduranf** [comment]
Hi, there is a way to specify hostNetwork PodSecurityPolicy for certain steps?
It would be a very useful enhancement

**Comment by alexec** [comment]
Could you simple labels the pods to set your net pol?

**Comment by Joibel** [comment]
Both parts of this are supported today.

Per-step pod labels, so a `NetworkPolicy` can select individual steps:

```yaml
- name: compile
  metadata:
    labels:
      step: compile
  container:
    image: golang
```

Per-step `hostNetwork`, via template-level `podSpecPatch` (added in v2.5.0):

```yaml
- name: compile
  podSpecPatch: |
    hostNetwork: true
  container:
    image: golang
```

`podSpecPatch` is a strategic merge patch against the whole pod spec and is applied per template, so only that step's pod gets `hostNetwork: true` while the `test` step keeps the workflow-level default.

The PodSecurityPolicy request in the earlier comment no longer applies — PSP was removed in Kubernetes v1.25; use Pod Security Admission or an admission policy keyed off the per-template labels above.

Closing as already supported. Please open a new issue if something specific still doesn't work on a supported version.
