### ISSUE TITLE
scripts-python.yaml example doesn't work

### ISSUE THREAD

**Issue by thundergolfer** [argoproj/argo#1812]
**Is this a BUG REPORT or FEATURE REQUEST?**: 🦟🐛

**What happened**:

Running this https://github.com/argoproj/argo/blob/master/examples/scripts-python.yaml

`argo -n argo logs -w scripts-python-9stwm`

```
generate:	27
print:	result was: {{steps.generate.outputs.result}}
```

It's not substituting anything.

**What you expected to happen**:

`argo -n argo logs -w scripts-python-9stwm`

```
generate:	27
print:	result was: 27
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version: `2.4.2`
- Kubernetes version :
```
clientVersion:
  buildDate: "1970-01-01T00:00:01Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: archive
  gitVersion: v1.14.3
  goVersion: go1.12.7
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-10-18T17:56:01Z"
  compiler: gc
  gitCommit: b7174db5ee0e30c94a0b9899c20ac980c0850fc8
  gitTreeState: clean
  gitVersion: v1.14.8-eks-b7174d
  goVersion: go1.12.10
  major: "1"
  minor: 14+
  platform: linux/amd64
```
