### ISSUE TITLE
Incomplete Installation Instructions

### ISSUE THREAD

**Issue by paguos** [argoproj/argo#1841]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
When installing `argo` using the release instructions workflows are not able to run with the `default ` service account.

**What you expected to happen**:
After following the installation instructions. Been able to successfully run some basic workflow examples.

**How to reproduce it (as minimally and precisely as possible)**:

```
minikube start
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.4.3/manifests/install.yaml

argo submit https://raw.githubusercontent.com/argoproj/argo/master/examples/hello-world.yaml --watch
```

**Anything else we need to know?**:
The problem is solved when specifying a new `serviceAccount` in the workflow-controller spec and also specifying the `serviceAccount` in the workflow.

This behavior was introduced in `v2.4.3`

**Environment**:
- Argo version:
```
argo: v2.4.3
  BuildDate: 2019-12-06T03:36:38Z
  GitCommit: cfe5f377bc3552fba90afe6db7a76edd92c753cd
  GitTreeState: clean
  GitTag: v2.4.3
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-11-14T04:24:29Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.13
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-13T11:11:50Z"
  compiler: gc
  gitCommit: 7015f71e75f670eb9e7ebd4b5749639d42e20079
  gitTreeState: clean
  gitVersion: v1.15.6
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                hello-world-vjjtq
Namespace:           argo
ServiceAccount:      default
Status:              Error
Message:             failed to save outputs: Failed to establish pod watch: unknown (get pods)
Created:             Thu Dec 12 22:25:29 +0100 (3 seconds ago)
Started:             Thu Dec 12 22:25:29 +0100 (3 seconds ago)
Finished:            Thu Dec 12 22:25:33 +0100 (now)
Duration:            4 seconds

STEP                             PODNAME            DURATION  MESSAGE
 ⚠ hello-world-vjjtq (whalesay)  hello-world-vjjtq  3s        failed to save outputs: Failed to establish pod watch: unknown (get pods)
```
