### ISSUE TITLE
Allow resources to pass arbitrary flags to kubectl

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#1857]
I think that this PR could become more generalized by allowing the user to pass arbitrary arguments to `kubectl`. If we merge this, other users could request a similar implementation for other flags, which could cause it to get cluttered.

Something like:
```yaml

  - name: create-route-without-validation
    resource:
      action: create
      flags: ["--validate=false"]  # validation will be turned off
```
could work.

Will open this as a new issue. @CermakM do you want to own this? 

(P.S. Not that this is slightly different from the open https://github.com/argoproj/argo/pull/1834 as that requires executor changes, so it still requires its own PR)

_Originally posted by @simster7 in https://github.com/argoproj/argo/pull/1779#issuecomment-566214900_
