### ISSUE TITLE
invalid spec templates not found using WorkflowTemplate and dag

### ISSUE THREAD

**Issue by dorsany** [argoproj/argo#1877]
**What happened**:
```
invalid spec: templates.workflow-template-core.tasks.core-example-migrator template reference workflow-template-core-example.core-example-migrator-pod-template not found" namespace=default workflow=workflow-core-d7zk4
```

**What you expected to happen**:
the core-example-migrator-pod-template should be exist

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-core-
spec:
  podgcstrategy: "delete pods when workflow is succeeded"
  #onExit: exit-handler (also not working but should be in a different issue)
  imagePullSecrets:
  - name: imagepullsecret
  entrypoint: workflow-template-core
  templates:
  - name: workflow-template-core
    dag:
      tasks:
      - name: core-example-migrator
        templateRef:
          name: workflow-template-core-example
          template: core-example-migrator-pod-template

---

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-core-example
spec:
  templates:
  - name: core-example-migrator-pod-template
    nodeSelector:
      backend: "true"
    container:
    image: "busybox"
    imagePullPolicy: IfNotPresent
    command: [sh, -c]
    args:
    - |
      echo hello


```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
v2.4.3
```
- Kubernetes version :
```
v1.14.8
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get workflow-core-d7zk4
Name:                workflow-core-d7zk4
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             invalid spec: templates.workflow-template-core.tasks.core-example-migrator template reference workflow-template-core-example.core-example-migrator-pod-template not found
Created:             Thu Dec 19 16:26:14 +0000 (29 minutes ago)
Started:             Thu Dec 19 16:26:14 +0000 (29 minutes ago)
Finished:            Thu Dec 19 16:26:14 +0000 (29 minutes ago)
Duration:            0 seconds
```

- workflow-controller logs:
```
time="2019-12-19T16:26:14Z" level=info msg="Processing workflow" namespace=default workflow=workflow-core-d7zk4
time="2019-12-19T16:26:14Z" level=info msg="Updated phase  -> Running" namespace=default workflow=workflow-core-d7zk4
time="2019-12-19T16:26:14Z" level=info msg="Updated phase Running -> Failed" namespace=default workflow=workflow-core-d7zk4
time="2019-12-19T16:26:14Z" level=info msg="Updated message  -> invalid spec: templates.workflow-template-core.tasks.core-example-migrator template reference workflow-template-core-example.core-example-migrator-pod-template not found" namespace=default workflow=workflow-core-d7zk4
time="2019-12-19T16:26:14Z" level=info msg="Marking workflow completed" namespace=default workflow=workflow-core-d7zk4
time="2019-12-19T16:26:14Z" level=info msg="Checking daemoned children of " namespace=default workflow=workflow-core-d7zk4
time="2019-12-19T16:26:14Z" level=info msg="Workflow update successful" namespace=default workflow=workflow-core-d7zk4
```

**Comment by simster7** [comment]
The `Workflow` and `WorkflowTemplate` you posted look malformed. It should be the following (note "`podgcstrategy`" field and indentation of `.spec.templates.container`):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-core-
spec:
  # podgcstrategy: "delete pods when workflow is succeeded" <- This is not a valid field
  # onExit: exit-handler (also not working but should be in a different issue)
  imagePullSecrets:
  - name: imagepullsecret
  entrypoint: workflow-template-core
  templates:
  - name: workflow-template-core
    dag:
      tasks:
      - name: core-example-migrator
        templateRef:
          name: workflow-template-core-example
          template: core-example-migrator-pod-template
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-core-example
spec:
  templates:
  - name: core-example-migrator-pod-template
    nodeSelector:
      backend: "true"
    container:
      image: "busybox"
      imagePullPolicy: IfNotPresent
      command: [sh, -c]
      args:
      - |
        echo hello
```

The following worked for me. Are you submitting using `argo {submit, template create}` or `kubectl apply`? `argo` should be catching the linting errors.
