### ISSUE TITLE
Unable to resolve artifact from one skipped step in another skipped step

### ISSUE THREAD

**Issue by jimdickinson** [argoproj/argo#1900]
We have a fairly complex workflow that we pass some variables into so we can skip steps that aren't needed during this execution. When we do that, it would seem like artifact inputs/outputs are validated before the `when` clause that lets job steps get skipped over.

Here's a snippet that illustrates what's going on. The job fails at runtime before checking whether `use-magic-files` needs to run.

```yaml
    - - name: generating-basic-files
        template: generate-normal
    - - name: generating-magic-files
        when: "{{workflow.parameters.magicNeeded}} == true"
        template: generate-magic
    - - name: use-magic-files
        template: use-magic
        when: "{{workflow.parameters.magicNeeded}} == true"
        arguments:
          parameters:  
          - name: summary
            value: "{{steps.generating-magic-files.outputs.parameters.summary}}"
          artifacts:
          - name: details
            from: "{{steps.generating-magic-files.outputs.artifacts.details}}"
    - - name: generating-verbose-files
        template: generate-verbose
```
