### ISSUE TITLE
QUESTION: best way for a reader of workflows to get output of individual steps

### ISSUE THREAD

**Issue by wreed4** [argoproj/argo#1901]
At a high level, my goal is to use argo workflows as a kubernetes-based task system for my company.  The main goal is to read argo workflows, and publish their status, potentially progress (X% complete), and some human-readable logs, that are not necessarily the logs of the individual steps to a company-wide message broker. My plan basically is to write a controller that `watch`es workflows, and publishes updates it sees.  I can get the overall status easily, percent complete I haven't figured out, but I could probably just figure out how many steps have executed in the status vs how many are in the spec.

It's the logs that I'm really having trouble with.  My initial plan was to have a small template that just `echo`ed a message.  I could then look through the `status` for any step that was of template name `log` or something special like that, and grab the output and append that to my messages.  However, I noticed that script results, are not captured unless they're referred to later.  As these messages have no use being in the workflow, I would rather not reference them there, that would just be confusing.  Is there some way to so say "for this step I want the output captured in the yaml even though I don't refer to it in the workflow later???"  

If not, is there a better practice I could be adopting? These logs are likely to be something like "copy files succeeded" or "git ref not found", not something worth uploading to s3 as an artifact.  (is my thought anyways)

**Comment by alexec** [comment]
Have you tried turning artifact collection for logs on?

```
apiVersion: v1
data:
  config: |
    artifactRepository:
      archiveLogs: true
```

That will always save your logs.

**Comment by wreed4** [comment]
Oh interesting.  Okay, so I did find another option I wanted to bring up.  Do you guys think the above suggestion would be a better idea, or the following:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  ttlSecondsAfterFinished: 300
  entrypoint: hello-world          # invoke the whalesay template
  templates:
  - name: hello-world
    steps:
    - - name: work1
        template: work
    - - name: log1
        template: log
        arguments:
          parameters:
          - name: msg
            value: "log 1"
          - name: out
            value: log1
    - - name: work2
        template: work
    - - name: log2
        template: log
        arguments:
          parameters:
          - name: msg
            value: "log 2"
          - name: out
            value: log2

  - name: work
    container:
      image: alpine
      command:
        - sleep
        - "10"
      resources:
        limits:
          memory: 16Mi
          cpu: 50m

  - name: log              # name of the template
    inputs:
      parameters:
      - name: msg
      - name: out
      - name: outfile
        value: /tmp/log_output.txt
    outputs:
      parameters:
      - name: msg
        valueFrom:
          path: "{{inputs.parameters.outfile}}"
        globalName: "{{inputs.parameters.out}}"
    container:
      image: alpine
      command: [sh, -c]
      args: ["sleep 1; echo -n {{inputs.parameters.msg}} > {{inputs.parameters.outfile}} "]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
```

What I don't like about this approach is it requires the writer of the workflow to provide some weird `out` param to the `log` template.  For context, this `log` template would be reused by many many Workflows, and the writers of these workflows don't need to know how "log" works.  So providing a weird out param is a little odd.  BUT, this does allow me to get the logs easily, and as the workflow progresses with `status.Outputs`.  

The downside I see with the above suggestion is simply the same reason logs were not aggregated by default in the first place: the object can get too large without the workflow writer knowing about it.  

Any thoughts?

**Comment by wreed4** [comment]
actually, update, I think I solved the "out" param issue.  

```yaml
  - name: log
    inputs:
      parameters:
      - name: msg
      - name: out
        value: "{{pod.name}}"
      - name: outfile
        value: /tmp/log_output.txt
    outputs:
      parameters:
      - name: msg
        valueFrom:
          path: "{{inputs.parameters.outfile}}"
        globalName: "{{inputs.parameters.out}}"
    container:
      image: alpine
      command: [sh, -c]
      args: ["sleep 1; echo -n {{inputs.parameters.msg}} > {{inputs.parameters.outfile}} "]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
```

Thoughts?
