### ISSUE TITLE
Specify port and network in argo yaml file.

### ISSUE THREAD

**Issue by DungLai** [argoproj/argo#1917]
# Summary

I created a server running inside a container and use argo to start the container,  however argo yaml template does not let me specify port and network like what docker-compose can do and now I am struggling with connecting the server inside the container from host machine. 

So my question is how to specify port and network in the `.yaml` file to connect to server running inside container?

Hope someone could help
# Motivation

**Comment by simster7** [comment]
How are you starting the container? Are you using the `resource` template? You can use the `resource` template to create K8s objects directly, such as a `Deployment` and a `Service`. Here is a toy example I got working.

(P.S. If you are deploying this server for a persistent amount of time (instead of just for the purposes of a workflow), consider using [Argo CD](https://github.com/argoproj/argo-cd))

Workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: server-
spec:
  entrypoint: start
  templates:
  - name: start
    steps:
      - - name: start-deploy
          template: start-deploy
        - name: start-service
          template: start-service
      - - name: test
          template: test

  - name: start-deploy
    resource:
      action: create
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: my-nginx
        spec:
          selector:
            matchLabels:
              run: my-nginx
          replicas: 2
          template:
            metadata:
              labels:
                run: my-nginx
            spec:
              containers:
              - name: my-nginx
                image: nginx
                ports:
                - containerPort: 80

  - name: start-service
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: my-nginx
          labels:
            run: my-nginx
        spec:
          ports:
          - port: 80
            protocol: TCP
          selector:
            run: my-nginx

  - name: test
    container:
      image: radial/busyboxplus:curl
      command: ["nslookup", "my-nginx"]
```

Output:
```
Name:                server-xhjjm
Namespace:           argo
ServiceAccount:      default
Status:              Succeeded
Created:             Wed Jan 08 09:21:32 -0800 (6 seconds ago)
Started:             Wed Jan 08 09:21:32 -0800 (6 seconds ago)
Finished:            Wed Jan 08 09:21:38 -0800 (now)
Duration:            6 seconds

STEP                                  PODNAME                  DURATION  MESSAGE
 ✔ server-xhjjm (start)
 ├-·-✔ start-deploy (start-deploy)    server-xhjjm-1584736676  1s
 | └-✔ start-service (start-service)  server-xhjjm-736667730   2s
 └---✔ test (test)                    server-xhjjm-740912455   2s

$  kubectl get svc my-nginx
NAME       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
my-nginx   ClusterIP   10.109.220.167   <none>        80/TCP    15s

$  kubectl get deploy my-nginx
NAME       READY   UP-TO-DATE   AVAILABLE   AGE
my-nginx   2/2     2            2           20s

$ kubectl logs server-xhjjm-740912455 -c main
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      my-nginx
Address 1: 10.109.220.167 my-nginx.argo.svc.cluster.local
```
