### ISSUE TITLE
Duplicate volumes when using input artifacts

### ISSUE THREAD

**Issue by tcolgate** [argoproj/argo#1969]
Version: 2.4.3 (likely anything > 2.3)

When using a git private key via an input artifact secret reference, argo adds an additional volume named after the secret being referenced. If a volume with that name already exists, then the resulting pods are invalid.

Ideally this work work, either by reusing the existing volume, or using a private, non-colliding, name for the mount added by the controller.

Example workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: list-secrets-
spec:
  entrypoint: list-secrets
  volumes:
  - name: ci-secrets
    secret:
      secretName: ci-secrets
  templates:
  - name: list-secrets
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ['
        ls -R /secret;
      ']
      volumeMounts:
      - name: ci-secrets
        mountPath: "/secret/maven"
    inputs:
      artifacts:
        - git: 
            repo: "git@github.com:someorg/repo.git"
            revision: 1111111111111111111111111111111111111111
            sshPrivateKeySecret:
              key: ssh-private-key
              name: ci-secrets
          name: code
          path: /src
```
log:
```
time="2020-01-14T16:54:42Z" level=error msg="Mark error node list-secrets-hrngk: Pod \"list-secrets-hrngk\" is invalid: spec.volumes[3].name: Duplicate value: \"ci-secrets\"\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argoerrors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).createWorkflowPod\n\t/go/src/github.com/argoproj/argo/workflow/controller/workflowpod.go:278\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeContainer\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1442\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1193\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:216\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:304\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:230\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker-fm\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333" namespace=argo workflow=list-secrets-hrngk
```

**Comment by evagonz** [comment]
FWIW I ran into this as well and can confirm the configuration worked in 2.2.0 and started failing with this error in 2.3.0., up to and including 2.7.4.

**Comment by evagonz** [comment]
Actually...we were able to get around this by changing the name of the volume to be different from the actual secret.

If you change it to 

```
spec:
  entrypoint: list-secrets
  volumes:
  - name: ci-secrets-volume
    secret:
      secretName: ci-secrets
```

or w/e, it should work for you too.
