### ISSUE TITLE
Managing multiple namespaces with the new version

### ISSUE THREAD

**Issue by naor2013** [argoproj/argo#2063]
# Summary
How do you suggest handling multiple namespaces that run Argo workflows in the new version?
The ways I’m thinking about right now are either:
a) workflow controller for each namespace and an Argo server for each namespace.
b) workflow controller for each namespace and a “managing” namespace which has a Argo server for each namespace with the “managed-namespace” patameter.

Is there a better way? Do you think it will be a good idea for you to implement an option to have one Argo server with multiple managed-namespaces for it?

# Motivation
We are the MLOps team and we want every DS team to have their own namespace with their own resource limitations and only show in the Argo UI their own workflows.

**Comment by maryoush** [comment]
Hi
what with the case for multi tenant spanned workflow ? 
https://github.com/argoproj/argo/issues/2042

**Comment by luozhaoyu** [comment]
I have similar issue: different team may want to create pods in different namespaces - their individual namespace would have different pods to interact with.
Currently `--managed-namespace` is a single string: https://github.com/argoproj/argo/blob/69179e72c0872cde9131cc9d68192d5c472d64c9/cmd/argo/commands/server.go#L35

**Comment by alexec** [comment]
See #3523

**Comment by dudicoco** [comment]
I was able to achieve this by using the following workaround:
1. Run workflow-controller and argo-server without the `--namespaced` flag
2. Create a cluster role for workflow-controller with read only permissions:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
```
3. Bind the cluster role to the workflow-controller service account.
4. Provide write access to specific namespaces by creating a role with the appropriate permissions in that namespace and binding it to the workflow-controller service account.
