### ISSUE TITLE
Allow parameters to be a dictionary as well as a list

### ISSUE THREAD

**Issue by mildewey** [argoproj/argo#2077]
# Summary

Allow for a parameters file to have fully nested yaml/json by allowing parameters to accept nested values.

# Motivation

This would be a direct method of allowing arbitrary yaml/json as input to a workflow.

# Proposal

Allow parameters to be defined as a dictionary IE:
```
arguments:
  parameters:
    data:
      field1: "something"
      field2: 
        subfield: "something else"
```

Conjointly, allow nested values in a --parameters-file IE:
```
data:
  field1: "overridden"
  field2: 
    subfield: "another value overridden"
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
