### ISSUE TITLE
[Bug] Workflow stays running even if the resource in the template is deleted

### ISSUE THREAD

**Issue by zhujl1991** [argoproj/argo#2078]
### Issue:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: pod-resource-wf
spec:
  entrypoint: pi-tmpl
  templates:
  - name: pi-tmpl
    resource:
      action: create
      setOwnerReference: true
      successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |
        apiVersion: v1
        kind: Pod
        metadata:
          generateName: pi-pod-
        spec:
          containers:
          - name: pi
            image: "perl"
            command: ["sh", "-c", "sleep 10000"]
```

Apply this yaml and manually delete the pod `pi-pod-xxx`, which is the resource in the template. This leaves the wf running. While I think the expected behavior should be the same as that when the `failureCondition` is satisfied.

### Fix Plan:
AFAIU, the fix should be here https://github.com/argoproj/argo/blob/master/workflow/executor/resource.go#L189, where we can  check the existence of the resource. The cost is to make another call to api server.

Any thought? @alexec @jessesuen

**Comment by nicorikken** [comment]
If I understand your issue correctly, a fix is already in the works on https://github.com/argoproj/argo/issues/1823

**Comment by simster7** [comment]
No this is a separate issue

**Comment by simster7** [comment]
Hi @zhujl1991, this seems like a great bug fix. However, I don't think you have to make an API call to the server. When a watch event comes, you can just check if it contains a set `metadata.deletionTimestamp` field. From the K8s docs:

> When the metadata.deletionTimestamp field is set, controllers watching the object execute any finalizers they handle, by polling update requests for that object. When all finalizers have been executed, the resource is deleted.

[_Source_](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/)

I.e., if that field is set, we know it's about to be deleted. At that time we can fail the step.

**Comment by zhujl1991** [comment]
> Hi @zhujl1991, this seems like a great bug fix. However, I don't think you have to make an API call to the server. When a watch event comes, you can just check if it contains a set `metadata.deletionTimestamp` field. From the K8s docs:
> 
> > When the metadata.deletionTimestamp field is set, controllers watching the object execute any finalizers they handle, by polling update requests for that object. When all finalizers have been executed, the resource is deleted.
> 
> [_Source_](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/)
> 
> I.e., if that field is set, we know it's about to be deleted. At that time we can fail the step.

This is not true for `Job` somehow. I tried this:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: zjl-k8s-jobs
spec:
  entrypoint: pi-tmpl
  templates:
  - name: pi-tmpl
    resource:
      action: create
      setOwnerReference: true
      successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: pi-job-
        spec:
          template:
            metadata:
              name: pi
            spec:
              containers:
              - name: pi
                image: "perl"
                # command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
                command: ["sh", "-c", "sleep 10000"]
              restartPolicy: Never
          backoffLimit: 4
```

When I delete this job manually, the only field that is different is `resourceVersion ` https://www.diffchecker.com/VSN5bWDs .
