### ISSUE TITLE
Artifact archive strategy of none still zips/unzips artifact

### ISSUE THREAD

**Issue by jamesgunnfiveai** [argoproj/argo#2132]
**What happened:**
With the artifact archive strategy set to none, the artifact is tarred and then untarred before upload to s3. For large artifacts (mine are 1-2Gb) these steps take a significant amount of time, in particular more than the S3 upload time of the unzipped artifact.

**What you expected to happen:**
No zipping of the artifact, direct upload to S3.

**How to reproduce it (as minimally and precisely as possible):**
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-disable-archive-
spec:
  entrypoint: artifact-disable-archive
  templates:
  - name: artifact-disable-archive
    steps:
    - - name: generate-artifact
        template: whalesay

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt ; sleep 1"]
    outputs:
      artifacts:
      - name: hello-txt
        path: /tmp/hello_world.txt
        archive:
          none: {}
```

This is a minimal example to demonstrate the redundant zip/unzip. Note that for this example the artifact is small, so the time penalty is not obvious.

Environment:

- Argo version:
```
$ argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:29Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version:
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-01-21T22:17:28Z"
  compiler: gc
  gitCommit: 59603c6e503c87169aea6106f57b9f242f64df89
  gitTreeState: clean
  gitVersion: v1.17.2
  goVersion: go1.13.5
  major: "1"
  minor: "17"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-10-15T19:09:08Z"
  compiler: gc
  gitCommit: c97fe5036ef3df2967d086711e6c0c405941e14b
  gitTreeState: clean
  gitVersion: v1.16.2
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: linux/amd64
```
**Other information:**

- executor logs:
```
$ kubectl logs artifact-disable-archive-dpn2s-978936219 --container wait
...
time="2020-02-01T18:12:08Z" level=info msg="Staging artifact: hello-txt"
time="2020-02-01T18:12:08Z" level=info msg="Copying /tmp/hello_world.txt from container base image layer to /tmp/argo/outputs/artifacts/hello-txt.tgz"
time="2020-02-01T18:12:08Z" level=info msg="Archiving 9859551e255b967fda4470a9626dcaa70feb5c086881b56ac39eb423213f6871:/tmp/hello_world.txt to /tmp/argo/outputs/artifacts/hello-txt.tgz"
time="2020-02-01T18:12:08Z" level=info msg="sh -c docker cp -a 9859551e255b967fda4470a9626dcaa70feb5c086881b56ac39eb423213f6871:/tmp/hello_world.txt - | gzip > /tmp/argo/outputs/artifacts/hello-txt.tgz"
time="2020-02-01T18:12:09Z" level=info msg="Archiving completed"
time="2020-02-01T18:12:09Z" level=info msg="Untaring /tmp/argo/outputs/artifacts/hello-txt.tgz archive before upload"
time="2020-02-01T18:12:09Z" level=info msg="tar -xf /tmp/argo/outputs/artifacts/hello-txt.tgz -C /tmp/argo/outputs/artifacts/hello-txt.tmpdir"
time="2020-02-01T18:12:09Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/hello_world.txt, key: artifact-disable-archive-dpn2s/artifact-disable-archive-dpn2s-978936219/hello_world.txt"
time="2020-02-01T18:12:09Z" level=info msg="Creating minio client 10.0.2.2:9000 using static credentials"
time="2020-02-01T18:12:09Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/hello_world.txt to s3 (endpoint: 10.0.2.2:9000, bucket: dev, key: artifact-disable-archive-dpn2s/artifact-disable-archive-dpn2s-978936219/hello_world.txt)"
time="2020-02-01T18:12:09Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/hello_world.txt"
...
```
In the above logs it is possible to see the artifact being copied from the container and zipped, before being unzipped and uploaded.

**Comment by whynowy** [comment]
@jamesgunnfiveai 

`archive: none: {}` only indicates to skip tar process and upload the files or directory tree as independent files to artifact repository, it does not mean during the process, zip/unzip is not used at all.

Current process of uploading artifact is:

1. Copy and zip files from `main` container to `wait` container (`docker cp -a {container_id}:{source_path} - | gzip > xxxx`);
2. Check the strategy of uploading, `tar` or `None` (default is `tar`), if it's `tar`, upload; else unzip and upload.

The reason doing copy and zip in step 1 is, it's much faster than docker cp to local and zip the file. And to simplify the logic, we don't want to have 2 methods `CopyFile` and `CopyAndZipFile`.

However there's an exception to avoid the issue you experienced - `docker cp` is not always expected to happen, if the `wait` container can `see` the files in the `main` container, there's no need to copy files. So, to solve your issue, you can add a shared volume to your workflow when you expect the files will be huge, and you don't want to zip them. An example spec looks like below.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-disable-archive-
spec:
  entrypoint: artifact-disable-archive
  volumes:
  - name: workdir
    emptyDir: {}
  templates:
  - name: artifact-disable-archive
    steps:
    - - name: generate-artifact
        template: whalesay

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /mnt/hello_world.txt ; sleep 1"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt
    outputs:
      artifacts:
      - name: hello-txt
        path: /mnt/hello_world.txt
        archive:
          none: {}
```

**Comment by jamesgunnfiveai** [comment]
Thanks for this @whynowy. I've tried your example and it does indeed avoid the `docker cp`. However, in my real workflow (not the minimal example I provided here) I already use a shared volume to store the large artifacts and yet it will still invoke the `docker cp`. I've checked, and the file permissions are the same in both the example you've provided and the one I'm using, and when I jump into the wait container I can see the artifact sitting in `/mainctrfs/mnt`. Despite this, it still ends up being zipped. Before I start digging into this, do you know of any other reason that the `docker cp` would be invoked, even if the wait container can see the artifact?

**Comment by jamesgunnfiveai** [comment]
Aha, it seems that if a script is being used then the `docker cp` is invoked even if the artifact is in a shared volume. For example:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-disable-archive-
spec:
  entrypoint: artifact-disable-archive
  volumes:
  - name: workdir
    emptyDir: {}
  templates:
  - name: artifact-disable-archive
    steps:
    - - name: generate-artifact
        template: whalesay

  - name: whalesay
    script:
      image: docker/whalesay:latest
      command: [sh]
      source: |
        cowsay hello world | tee /mnt/hello_world.txt
        sleep 1
      volumeMounts:
      - name: workdir
        mountPath: /mnt
    outputs:
      artifacts:
      - name: hello-txt
        path: /mnt/hello_world.txt
        archive:
          none: {}
```
