### ISSUE TITLE
apps/v1beta2 is deprecated in k8s 1.16, should use apps/v1 instead 

### ISSUE THREAD

**Issue by iMoses** [argoproj/argo#2162]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Trying to install argo according to the "Getting Started" documentation I get the following when trying to run command:
```
$ kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml

customresourcedefinition.apiextensions.k8s.io/workflows.argoproj.io unchanged
serviceaccount/argo unchanged
serviceaccount/argo-ui unchanged
clusterrole.rbac.authorization.k8s.io/argo-aggregate-to-admin unchanged
clusterrole.rbac.authorization.k8s.io/argo-aggregate-to-edit unchanged
clusterrole.rbac.authorization.k8s.io/argo-aggregate-to-view unchanged
clusterrole.rbac.authorization.k8s.io/argo-cluster-role unchanged
clusterrole.rbac.authorization.k8s.io/argo-ui-cluster-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/argo-binding unchanged
clusterrolebinding.rbac.authorization.k8s.io/argo-ui-binding unchanged
configmap/workflow-controller-configmap unchanged
service/argo-ui unchanged
unable to recognize "https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
unable to recognize "https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
```

**What you expected to happen**:

I'd expect the instructions under "Getting Started" to work without errors.

According to [this post](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) API version 1.16 no longer supports `apps/v1beta2` and it should be replaced with `apps/v1`.

**How to reproduce it (as minimally and precisely as possible)**:

Install minikube locally and run:
```
kubectl create ns argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-01-18T23:30:10Z"
  compiler: gc
  gitCommit: 59603c6e503c87169aea6106f57b9f242f64df89
  gitTreeState: clean
  gitVersion: v1.17.2
  goVersion: go1.13.5
  major: "1"
  minor: "17"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-10-15T19:09:08Z"
  compiler: gc
  gitCommit: c97fe5036ef3df2967d086711e6c0c405941e14b
  gitTreeState: clean
  gitVersion: v1.16.2
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: linux/amd64
```
