### ISSUE TITLE
Enhanced metrics to aggregate function

### ISSUE THREAD

**Issue by hanjunlee** [argoproj/argo#2199]
# Summary

 To aggregate metrics  by `generateName`, especially for `argo_workflow_info` and `argo_workflow_status_phase`, it would be helpful to add the `generate_name` label into  metrics. I think, at this moment, metrics doesn't has labels to distinguish by the field `generateName`.

# Motivation

 When I make a dashboard, I want to distinguish it by `generateName`. For example, I can use `generateName` in the variable of [Grafana](https://grafana.com/docs/grafana/latest/reference/templating/).

# Proposal

Simply append the label into `descWorkflowDefaultLabels` or some metrics,  such as `argo_workflow_info` and `argo_workflow_status_phase`,   in [collector.go](https://github.com/argoproj/argo/blob/master/workflow/metrics/collector.go). I think this enhancement to provide a nice option to users. And if i can take this issue, I will make you the PR.

Very thanks to Argo team  for implementing Argoproj.  

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by lyonsaj** [comment]
Any update on this? This would be very beneficial. Currently, if I am displaying metrics on workflows running/ran I have to add a custom query for each individual workflow name. It would be very nice to be able to aggregate by name/template.

**Comment by simster7** [comment]
Metrics have been refactored and now operate in a significantly different way. Please take a look at https://github.com/argoproj/argo/blob/master/docs/metrics.md

**Comment by lyonsaj** [comment]
@simster7 We are currently using some custom metrics.. I still have been unable to find a way to simply pull a workflow count. Or error count by workflow name without having to specifically state ```count(argo_workflow_info{name=~"flippity.*"})```. Is there a better way to accomplish this?

**Comment by simster7** [comment]
What version are you running?

**Comment by lyonsaj** [comment]
2.7.6

**Comment by simster7** [comment]
`argo_workflow_info` is now deprecated. If you want a workflow count you should deploy a custom metric. Something like 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: steps
  metrics:
    prometheus:
      - name: result_counter
        help: "Count of step execution by result status"
        labels:
          - key: name
            value: "workflow_name_here"
          - key: status
            value: "{{status}}"
        counter:
          value: "1"

...
```
