### ISSUE TITLE
Validation doesn't catch when `retryStrategy`  is in a `WorkflowStep` instead of a `Template`

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2204]
E.g. (invalid yaml):

```yaml
    entrypoint: crawl-then-generate-reports
    onExit: exit-handler
    parallelism: 2
    templates:
    # Create Reports
    - name: crawl-then-generate-reports
      steps:
      - - name: crawl-tables
          templateRef:
            name: wt-crawl-table
            template: crawl-table
          retryStrategy: # <-- incorrect place
            limit: 5
            retryOn: Always
            backoff:
              duration: 1m
              factor: 2
```

[See more on slack](https://argoproj.slack.com/archives/C8J6SGN12/p1581361388439800)
