### ISSUE TITLE
Is there a place to specify `securityContext` in a workflow so that it's applied at the `podSpec` level?

### ISSUE THREAD

**Issue by uipo78** [argoproj/argo#2238]
# Summary

I'd like to be able to specify a `securityContext` at the pod level so that both the `main` and `wait` containers within a workflow-generated pod receive that `securityContext`.

# Motivation

Example of something that I ran into&mdash;

Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
I submitted [this workflow](https://github.com/argoproj/argo/blob/master/examples/dag-diamond.yaml) to a kubernetes cluster with pod security policies enabled. Since that image runs with root by default, I change added this to the container spec section: `securityContext.runAsUser: 999`. The pod associated with the first task in this workflow spun up and completed successfully (the main container inherited the `securityContext` that I provided); however, argo reported the following message: `CreateContainerConfigError: container has runAsNonRoot and image will run as root`. The subsequent jobs in the DAG were never spun up.

Is there a place to specify `securityContext` in a workflow so that it's applied at the `podSpec` level?

**What you expected to happen**:

I expected the workflow to finish successfully.

**How to reproduce it (as minimally and precisely as possible)**:

1. `kubectl apply` the following pod security policy:
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: argo-workflow
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  - hostPath
```
2. `kubectl create sa my-argo-workflow`
3. `kubectl apply` the following role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-argo-workflow
rules:
- apiGroups:
  - extensions
  resourceNames:
  - argo-workflow
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
```
4. `kubectl create rolebinding my-argo-workflow --role my-argo-workflow --serviceaccount=$my_namespace:my-argo-workflow`

5. `argo submit` the following workflow
```
# The following workflow executes a diamond workflow
# 
#   A
#  / \
# B   C
#  \ /
#   D
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  serviceAccountName: my-argo-workflow
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
      securityContext:
        runAsUser: 999
```

**Environment**:
- Argo version:
```
$ argo version
argo: v2.4.3
  BuildDate: 2019-12-06T03:36:01Z
  GitCommit: cfe5f377bc3552fba90afe6db7a76edd92c753cd
  GitTreeState: clean
  GitTag: v2.4.3
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-11-13T11:23:11Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.12
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-01-31T20:09:49Z"
  compiler: gc
  gitCommit: c83d931fb9bece427bc63a02349755e0f8696d3e
  gitTreeState: clean
  gitVersion: v1.15.7
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Logs**
- workflow result:
```
argo get dag-diamond-$SOMETHING
Name:                dag-diamond-wddzd
Namespace:           default
ServiceAccount:      test
Status:              Running
Created:             Thu Feb 13 19:45:03 -0600 (6 minutes ago)
Started:             Thu Feb 13 19:45:03 -0600 (6 minutes ago)
Duration:            6 minutes 6 seconds

STEP                            PODNAME                       DURATION  MESSAGE
 ● dag-diamond-wddzd (diamond)                                          
 └-◷ A (echo)                   dag-diamond-wddzd-1623379777  6m        CreateContainerConfigError: container has runAsNonRoot and image will run as root
```
- pod logs:
```
kubectl logs <failedpodname> -c wait
Error from server (BadRequest): container "wait" in pod "dag-diamond-wddzd-1623379777" is waiting to start: CreateContainerConfigError
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
