### ISSUE TITLE
Kubernetes Argo loop through JSON array

### ISSUE THREAD

**Issue by Montana** [argoproj/argo#2252]
I'm attempting to use Argo to loop through an array of JSON objects, however the workflow is returning:

```docker
failed to resolve {{item}}
```

The Argo workflow configuration is as follows:

```yaml
- name: output-parameter
   steps:
    - - name: generate-parameter
        template: getresult
    - - name: consume-parameter
         template: print-result
         arguments:
           parameters:          
           - name: result
           value: "{{item}}"
         withParam: "{{steps.generate-parameter.outputs.result}}"      

 - name: montanamendy
   script:
     image: python:alpine3.6
     command: [python]
     source: |        
       import json
       import sys

       json.dump([{"name":"Foo"},{"name":"Doe"}], sys.stdout)

 - name: print-result
   inputs:
     parameters:
     - name: result
   container:
     image: crweu.azurecr.io/ubuntu_run:v1.0.6
     command: [sh, -c]
     args: ["echo {{inputs.parameters.result}}"]
```

If I used the example Argo loop with:

```yaml
json.dump([i for i in range(20, 31)], sys.stdout)
```
It prints out the number range without any issues.

I assume the problem is due to the fact it's not a simple item its an object and the `{{item}}` needs to change but I am unable to find any documentation on it. Saw a similar post like this on StackOverflow, I understand that Argo is parsing the JSON output of the ```montanamendy``` step, and I have adjusted the arguments accordingly, but to no avail. 

-Montana
