### ISSUE TITLE
Reference outputs of nested steps

### ISSUE THREAD

**Issue by dfarr** [argoproj/argo#2302]
# Summary

Suppose we have the following workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: reference-nested-step-outputs-
spec:
  entrypoint: root
  templates:
  - name: root
    steps:
    - - name: step-1
        template: nested
    - - name: step-2
        template: echo
        arguments:
          parameters:
          - name: message
            value: "{{steps.step-1.steps.step-1c.outputs.result}}"

  - name: nested
    steps:
    - - name: step-1a
        template: echo
        arguments:
          parameters:
          - name: message
            value: "step-1a"
      - name: step-1b
        template: echo
        arguments:
          parameters:
          - name: message
            value: "step-1b"
    - - name: step-1c
        template: echo
        arguments:
          parameters:
          - name: message
            value: "{{steps.step-1a.outputs.result}} + {{steps.step-1b.outputs.result}}"

  - name: echo
    inputs:
      parameters:
      - name: message
    script:
      image: alpine
      command: ["ash"]
      source: |
        echo {{inputs.parameters.message}}
```

If we comment out `step-2` and execute the workflow, this will succeed. Specifically `step-1c` composes the results of `step-1a` and `step-1b` by referencing their outputs as follows:
```
{{steps.step-1a.outputs.result}} + {{steps.step-1b.outputs.result}}
```

However, if we uncomment `step-2`, our workflow will fail. Is it possible to enable referencing of nested step outputs in a workflow?

# Motivation

We have a workflow that creates EMR clusters on demand. We need to do a bunch of `aws` commands in parallel, followed by a single `aws create-cluster` command. Downstream steps need to know the `cluster-id` created in this step for further processing. It would be nice to encapsulate the "create EMR" steps within one template, and then be able to reference these outputs downstream in other steps/templates.

# Proposal

Perhaps nested steps could be referenced as follows:
```
{{steps.parent-step.steps.child-step.outputs.result}}
```

I think steps should have access to their own scope as well as their children's scope, but not their parents scope. Handling references to outputs of conditional steps would be tricky, it may have to be up to the workflow author to ensure conditional step outputs are not referenced in a scenario where the condition evaluates to false.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by changhc** [comment]
I'd like to take this issue.

**Comment by samath117** [comment]
Just noticed this. In this situation (and what you describe), can't you just export the result you want as an output parameter to the `nested` script?

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: reference-nested-step-outputs-
spec:
  entrypoint: root
  templates:
  - name: root
    steps:
    - - name: step-1
        template: nested
    - - name: step-2
        template: echo
        arguments:
          parameters:
          - name: message
            value: "{{steps.step-1.outputs.parameters.result}}"

  - name: nested
    steps:
    - - name: step-1a
        template: echo
        arguments:
          parameters:
          - name: message
            value: "step-1a"
      - name: step-1b
        template: echo
        arguments:
          parameters:
          - name: message
            value: "step-1b"
    - - name: step-1c
        template: echo
        arguments:
          parameters:
          - name: message
            value: "{{steps.step-1a.outputs.result}} + {{steps.step-1b.outputs.result}}"
    outputs:
      parameters:
      - name: result
        value: "{{steps.step-1c.outputs.result}}"

  - name: echo
    inputs:
      parameters:
      - name: message
    script:
      image: alpine
      command: ["ash"]
      source: |
        echo {{inputs.parameters.message}}
```

**Comment by dfarr** [comment]
This doesn't works as output parameters (unlike script results) must be bound to file with `valueFrom`. Here though the `echo` template is a here-script and the intention is not to write to a file.

**Comment by ktns** [comment]
JFYI, 
```
outputs:
  parameters:
    - name: result
      valueFrom:
        parameter: "{{steps.step-1c.outputs.result}}"
```
did the trick for me.
