### ISSUE TITLE
Default values for input parameters in WorkflowTemplate not working

### ISSUE THREAD

**Issue by tigerwings** [argoproj/argo#2305]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Previously (at least in v2.4.0-rc1), we can use default values for input parameters in a template in WorkflowTemplate. It works as expected. 
But now it's broken in v2.5.0. We also tried v2.6.0-rc2 and see the same issue. 

**What you expected to happen**:
We want to use default values for the input parameters in a template if the callers don't provide those. 

**How to reproduce it (as minimally and precisely as possible)**:
```
# workflow_template.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: example-workflow-template
spec:
  templates:
  - name: on-workflow-template
    inputs:
      parameters:
        - name: a
        - name: b
          value: "default"          # use default here
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["test a:{{inputs.parameters.a}}, b:{{inputs.parameters.b}}"]
```

```
# workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: directly-call-workflow-template-
spec:
  entrypoint: entrypoint
  arguments:
    parameters:
      - name: parameter-1
        value: "default-value-from-workflow"

  templates:
    - name: entrypoint
      templateRef:
        name: example-workflow-template
        template: on-workflow-template
      arguments:                       # use inputs instead of arguments in v2.5.0
        parameters:
          - name: a
            value: "{{workflow.parameters.parameter-1}}"
```
**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: vv2.5.2+4b25e2a.dirty
  BuildDate: 2020-02-24T22:49:11Z
  GitCommit: 4b25e2ac1d495991261e97c86d211d658423ab7f
  GitTreeState: dirty
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**Other debugging information (if applicable)**:
- workflow result:

```
argo get <workflowname>
```

**Logs**

```
argo get directly-call-workflow-template-xyz14
Name:                directly-call-workflow-template-xyz14
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             invalid spec: templates.entrypoint: failed to resolve {{inputs.parameters.b}}
Created:             Mon Feb 24 21:44:53 -0600 (10 seconds ago)
Started:             Mon Feb 24 21:44:53 -0600 (10 seconds ago)
Finished:            Mon Feb 24 21:44:53 -0600 (10 seconds ago)
Duration:            0 seconds
Parameters:
  parameter-1:       default-value-from-workflow

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
This seems related to #2267. It seems that you should actually be using `arguments` here and not `inputs`. @alexec What was your reasoning when removing `arguments` from the template spec?

**Comment by alexec** [comment]
I think this is because you are using `arguments` not `inputs`. Can you try inputs?

**Comment by simster7** [comment]
He mentions trying inputs in 2.5+

```
 arguments:                       # use inputs instead of arguments in v2.5.0
```

**Comment by alexec** [comment]
Check this out: https://github.com/argoproj/argo/issues/2046

**Comment by tigerwings** [comment]
@alexec , I don't #2046 solves this bug. I tried the workflow and workflowtemplate with v2.6.0-rc2 and got the same error.

**Comment by simster7** [comment]
I may be wrong, but it seems to me that `arguments` is actually correct here:

- `inputs` = definition of parameters that may be passed in to this template, could declare default values as well
- `arguments` = live arguments actively being passed in

It seems that when a user calls a WorkflowTemplate from a Tempalte, they are actually passing in the arguments they want to run instead of simply defining them. Hence the line: https://github.com/argoproj/argo/pull/2267/files#diff-a98e7d5b84013fc73846b376fae0f4fbL217

What do you think? It seems that there is actually large confusion on the distinction between the two (even I am not super confident on this), perhaps this would be a good time to settle this issue?

**Comment by tigerwings** [comment]
@simster7 , if I use `arguments` instead `inputs` in workflow.yaml, I will still get this error: 
```
invalid spec: templates.entrypoint inputs.parameters.a was not supplied
```

**Comment by simster7** [comment]
Hi @tigerwings. I have a workaround for you, when submitting your workflow just add your template under a `steps` or `dag` template:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: directly-call-workflow-template-
spec:
  entrypoint: steps
  arguments:
    parameters:
      - name: parameter-1
        value: "default-value-from-workflow"

  templates:
    - name: steps
      steps:
        - - name: run
            templateRef:
              name: example-workflow-template
              template: on-workflow-template
            arguments:                       # use inputs instead of arguments in v2.5.0
              parameters:
                - name: a
                  value: "{{workflow.parameters.parameter-1}}"
```

Currently calling `WorkflowTemplates` directly with an individual template is not supported.
