### ISSUE TITLE
Regression - argo cli doesn't prevent submission of workflow with missing arguments

### ISSUE THREAD

**Issue by cameronbraid** [argoproj/argo#2306]
**What happened**:

Argo used to prevent submission of a workflow if the parameters weren't provided

**What you expected to happen**:

the same as happened in argo 2.4.3

```
argo-2.4.3 submit ./params.yaml
2020/02/25 18:00:36 Failed to submit workflow: spec.arguments.message.value is required
```

However 2.5.2 does the following :

```
argo submit ./params.yaml
Name:                arguments-parameters-b5l6b
Namespace:           shared-builds
ServiceAccount:      default
Status:              Pending
Created:             Tue Feb 25 18:01:54 +1100 (now)
Parameters:          
```

Workflow (modified version of https://github.com/argoproj/argo/blob/master/examples/arguments-parameters.yaml with the parameter default removed)

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

```
