### ISSUE TITLE
Argo lint does not check the parameters/inputs validity of tasks in a dag

### ISSUE THREAD

**Issue by thundergolfer** [argoproj/argo#2313]
**Note:** [This was working in `2.2.1`](https://github.com/argoproj/argo/issues/2313#issuecomment-591259701)

----

Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

We had a Argo workflow spec that passed `lint`ing even though it had a step that did not specify a parameter required by the template it was referring to. On submission, the workflow failed with an error like: 

```
Name:                demonstrate-lint-bug-pmf45
Namespace:           argo
ServiceAccount:      default
Status:              Failed
Message:             invalid spec: templates.abc.tasks.a inputs.parameters.message was not supplied
Created:             Wed Feb 26 17:11:54 +1100 (now)
Started:             Wed Feb 26 17:11:54 +1100 (now)
Finished:            Wed Feb 26 17:11:54 +1100 (now)
Duration:            0 seconds
```

**What you expected to happen**:

`argo lint` should have failed with a message like: `FATA[0000] args-params.yaml: templates.whalesay inputs.parameters.message was not supplied`

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: abc
  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters: []
  templates:
  - dag:
      tasks:
        - name: a
          template: whalesay
          arguments:
             parameters:
        - name: b
          template: whalesay
          arguments:
             parameters:
               - name: message
                 value: "banana"
        - name: c
          template: whalesay
          arguments:
             parameters:
               - name: message
                 value: "apple"
    name: abc
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

**Anything else we need to know?**:

**Environment**:
- Argo version: We use Nix. Our Nix'd `argo` version is [2.4.3](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/argo/default.nix#L5)
- Kubernetes version : 
```
clientVersion:
  buildDate: "1970-01-01T00:00:01Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: archive
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.6
  major: "1"
  minor: 16+
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-12-22T23:14:11Z"
  compiler: gc
  gitCommit: c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2
  gitTreeState: clean
  gitVersion: v1.14.9-eks-c0eccc
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
