### ISSUE TITLE
git artifact fetch of reference fails due to missing credentials

### ISSUE THREAD

**Issue by Mohjive** [argoproj/argo#2343]
Checklist:

 * [ x] I've included the version.
 * [ x] I've included reproduction steps.
 * [ x] I've included the workflow YAML.
 * [ x] I've included the logs.
 
**What happened**:
I tried to checkout a gerrit change reference, using git artifacts. It failed due to the fetch didn't use authentication.

**What you expected to happen**:
The repo is cloned and the change is fetched and checked out.

**How to reproduce it (as minimally and precisely as possible)**:
1) Set up a git server with authentication enabled
2) Try to fetch and checkout a reference from that server

**Anything else we need to know?**:
To verify the setup I tried a clone and checkout a revision that exists, like a branch, and then it works, so it's the `fetch` that fails.
It can also be seen in artifacts/git.go that `Auth` is missing from `FetchOptions` (https://github.com/argoproj/argo/blob/master/workflow/artifacts/git/git.go#L106).
 
**Environment**:
- Argo version:
```
Argo 2.4.3
```
- Kubernetes version :
```
K8s v1.14.8
```

**Other debugging information (if applicable)**:
- workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: git-test-
spec:
  entrypoint: gerrit-change
  templates:
  - name: gerrit-change
    inputs:
      artifacts:
      - name: my-project
        path: /src
        git:
          repo: https://my-gerrit-server.com/projects/my-project.git
          fetch: ["refs/changes/12/12345/123:change"]
          revision: "change"
          usernameSecret:
            name: gerrit-credentials
            key: username
          passwordSecret:
            name: gerrit-credendtials
            key: password
          insecureIgnoreHostKey: true
    container:
      image: golang:1.10
      command: [sh, -c]
      args: ["git status && ls -la"]
      workingDir: /src
```
- executor logs:
```
Loading...
```
- workflow-controller logs:
```
time="2020-03-02T22:08:22Z" level=info msg="Processing workflow" namespace=argo workflow=git-test-knzvf
time="2020-03-02T22:08:23Z" level=info msg="Updating node git-test-knzvf (git-test-knzvf) status Pending -> Error"
time="2020-03-02T22:08:23Z" level=info msg="Updating node git-test-knzvf (git-test-knzvf) message: failed to load artifacts: authentication required"
time="2020-03-02T22:08:23Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=git-test-knzvf
time="2020-03-02T22:08:23Z" level=info msg="Updated message  -> failed to load artifacts: authentication required" namespace=argo workflow=git-test-knzvf
time="2020-03-02T22:08:23Z" level=info msg="Marking workflow completed" namespace=argo workflow=git-test-knzvf
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
