### ISSUE TITLE
Docs for aliyun OSS artifact.

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo#2358]
# Summary

We need the docs for OSS artifact, probably in https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@merlintang

**Comment by merlintang** [comment]
@whynowy I am so glad to write this document. Thanks

**Comment by yujingz** [comment]
@whynowy @merlintang 

we were trying out this feature wondering why it doesn't work and saw this issue. Any current workaround guys or is it something to be implemented?

**Comment by merlintang** [comment]
@yujingz can you illustrate your way to test it ? and post any log errors then we can look at it together.

**Comment by yujingz** [comment]
@merlintang Sure.

- k8s version: 1.14.8-aliyun.1
- argo version: 2.6.

We were testing this feature on Aliyun ACK following the configurations listed here 
https://github.com/argoproj/argo/blob/7c99c109e3dd726f6453c94a594d69bca709ccf6/docs/workflow-controller-configmap.yaml#L40

It works fine for our S3 buckets but once we change all the setup to OSS, it starts to timeout.  Below is a stripped out version of our OSS setup:
```yaml
  s3:
    accessKeySecret:
      key: accesskey
      name: argo-secrets
    secretKeySecret:
      key: secretkey
      name: argo-secrets
    bucket: argo-logs-dev
    endpoint: oss-cn-hangzhou-internal.aliyuncs.com
    region: oss-cn-hangzhou
    insecure: true
    keyFormat: "my-artifacts\
      /{{workflow.creationTimestamp.Y}}\
      /{{workflow.creationTimestamp.m}}\
      /{{workflow.creationTimestamp.d}}\
      /{{workflow.name}}\
      /{{pod.name}}"
```

The log look like 

```
failed to save outputs: timed out waiting for the condition
```

As I reading the code I actually found https://github.com/argoproj/argo/pull/1919/files, does this mean as of Argo 2.6 OSS is actually not supported yet?
 
Thanks for the help!
