### ISSUE TITLE
UI and CLI challenges running large (2000 node) workflows

### ISSUE THREAD

**Issue by tmbdev** [argoproj/argo#2367]
Checklist:

**What happened**:

I submitted a workflow with 2000 steps (two steps that loop over 1000 input files each)

- the Argo UI hangs and crashes
- "argo watch" tries to display 2000 lines on a single screen and scrolls wildly back and forth

- containers that are waiting to be scheduled are described as "Unschedulable"; that term suggests that the container is permanently impossible to schedule, instead of waiting
- the only distinction in the text output between running and completed containers is in the colorization; status information is available only with json or yaml output, making grep impossible

**What you expected to happen**:

Sensible output for "argo watch" and user interface..

Generally, I'd suggest:

- change "Unschedulable" to "Waiting to be scheduled"
- append "Waiting", "Running", "Succeeded", or "Failed" to the output of each line in "argo get" so that it's possible to grep for status
- do something about the web UI to deal more sensibly with thousands of pods (displaying graphs with thousands of nodes is easy for modern JS)
- provide summary views for the text and web UI for large numbers of jobs

**How to reproduce it (as minimally and precisely as possible)**:

Generate a workflow with a few thousand tasks.

**Anything else we need to know?**:

There are also issues with the workflow execution itself, with pods failing for various reasons. I'll submit a separate report.

**Environment**:
- Argo version:
```
$ argo version

argo: v2.6.0
  BuildDate: 2020-02-28T23:32:26Z
  GitCommit: 5d3bdd56607eea962183a9e45009e3d08fafdf9b
  GitTreeState: clean
  GitTag: v2.6.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
 

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-02-06T03:29:33Z"
  compiler: gc
  gitCommit: f5757a1dee5a89cc5e29cd7159076648bf21a02b
  gitTreeState: clean
  gitVersion: v1.14.10-dispatcher
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: linux/amd64
serverVersion:
  buildDate: "2020-01-17T23:10:13Z"
  compiler: gc
  gitCommit: bdceba0734835c6cb1acbd1c447caf17d8613b44
  gitTreeState: clean
  gitVersion: v1.14.10-gke.17
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
could you provide your YAML so I can investigate?

**Comment by tmbdev** [comment]
I'm not sure what difference the YAML makes; the problems I listed are general problems with large numbers of jobs executing in parallel. Anyway, here you go. The `generate-seg` stage generates a list with 1000 elements.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: segmentation-
spec:
  entrypoint: segmentation
  arguments:
    parameters:

  templates:

  - name: segmentation
    steps:

    - - name: generate-seg
        template: generate-seg

    - - name: extract-seg
        template: extract-seg
        arguments:
          parameters:
          - name: shard
            value: "{{item}}"
        withParam: "{{steps.generate-seg.outputs.result}}"

  - name: generate-seg
    script:
      image: tmbdev/ocr-prep
      command: [python3]
      source: |
        import os, re, simplejson
        inputs = [s.strip() for s in os.popen("gsutil ls gs://bucket-g1000-temp/g1000-ocr-*.tar").readlines()]
        ishards = [re.search(r"g1000-ocr-(....)", s).group(1) for s in inputs]
        outputs = [s.strip() for s in os.popen("gsutil ls gs://bucket-g1000-temp/g1000-seg-*.tar").readlines()]
        oshards = [re.search(r"g1000-seg-(....)", s).group(1) for s in outputs]
        missing = set(ishards)-set(oshards)
        missing = sorted(missing)
        # missing = missing[:10]
        print(simplejson.dumps(missing))
      resources:
        limits:
          cpu: 1
          memory: 2G

  - name: extract-seg
    inputs:
      parameters:
        - name: shard
    script:
      image: tmbdev/ocr-prep
      command: [bash]
      source: |
        set -x
        shard="{{inputs.parameters.shard}}"
        input="gs://bucket-g1000-temp/g1000-ocr-$shard.tar"
        output="gs://bucket-g1000-temp/g1000-seg-$shard.tar"
        source venv/bin/activate
        ocropus4 seg hocr2seg "pipe:gsutil cat $input" --output="pipe:gsutil cp - $output" --skip-missing=True --ignore-errors=skip || sleep 3600
      resources:
        limits:
          cpu: 2
          memory: 4G
```
