### ISSUE TITLE
Make aggregated output parameters available by name

### ISSUE THREAD

**Issue by mac9416** [argoproj/argo#2393]
# Summary

I'd like to be able to access aggregated output parameters filtered by name. Right now you [can get](https://github.com/argoproj/argo/issues/861) _all_ the output parameters as JSON using `{{steps.STEP-NAME.outputs.parameters}}`. I'd like to add `.PARAM-NAME` to get JSON for _just_ output params by that name.

# Motivation

Someone [asked on StackOverflow](https://stackoverflow.com/q/60569353/684776) how to access aggregated output parameters. They were attempting to access by name like `{{steps.STEP-NAME.outputs.parameters.PARAM-NAME}}`.

That seems intuitive/nice. It would be easy enough to filter using `jq`, but getting the results straight from Argo would be a better UX.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
It seems like this is already supported? From [Argo Variables](https://github.com/argoproj/argo/blob/master/docs/variables.md#steps-templates):

> ## Steps Templates:
> | Variable | Description|
> |----------|------------|
> ...
> | `steps.<STEPNAME>.outputs.parameters.<NAME>` | Output parameter of any previous step |
> ...
> 
> ## DAG Templates:
> | Variable | Description|
> |----------|------------|
> ...
> | `tasks.<TASKNAME>.outputs.parameters.<NAME>` | Output parameter of any previous task |
> ...

An example: https://github.com/argoproj/argo/blob/master/examples/nested-workflow.yaml

Am  I missing something here?

**Comment by mac9416** [comment]
That's true for retrieving output parameters for steps without parallelism. For a looped step, it seems like `steps.<TASKNAME>.outputs.parameters.<NAME>` isn't defined.

Example from the StackOverflow post:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate
        template: gen-number-list
    - - name: write
        template: output-number
        arguments:
          parameters:
          - name: number
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"
    - - name: fan-in
        template: fan-in
        arguments:
          parameters:
          - name: numbers
            value: "{{steps.write.outputs.parameters.number}}"

  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([i for i in range(20, 31)], sys.stdout)

  - name: output-number
    inputs:
      parameters:
      - name: number
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.number}} > /tmp/number.txt"]
    outputs:
      parameters:
        - name: number
          valueFrom:
            path: /tmp/number.txt

  - name: fan-in
    inputs:
      parameters:
        - name: numbers
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo received {{inputs.parameters.numbers}}"]
```
