### ISSUE TITLE
Argo UI workflow duration is counting down

### ISSUE THREAD

**Issue by theomessin** [argoproj/argo#2398]
**What happened**:
Workflow duration is counting down.

**What you expected to happen**:
Workflow duration should count up.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a workflow, navigate to workflow in UI and see duration.

**Anything else we need to know?**:
Nope

**Environment**:
- Argo version:
```
argo: v2.6.1
  BuildDate: 2020-03-04T21:25:34Z
  GitCommit: 842739d7831cc5b417c4f524ed85288408a32bbf
  GitTreeState: clean
  GitTag: v2.6.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-02-06T03:29:33Z"
  compiler: gc
  gitCommit: f5757a1dee5a89cc5e29cd7159076648bf21a02b
  gitTreeState: clean
  gitVersion: v1.14.10-dispatcher
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: linux/amd64
serverVersion:
  buildDate: "2020-01-17T23:10:13Z"
  compiler: gc
  gitCommit: bdceba0734835c6cb1acbd1c447caf17d8613b44
  gitTreeState: clean
  gitVersion: v1.14.10-gke.17
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
