### ISSUE TITLE
Intermittent RBAC permission problems in workflows using volumeClaimTemplates

### ISSUE THREAD

**Issue by thundergolfer** [argoproj/argo#2408]
Checklist:

 * [x] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

We're seeing that _sometimes_ our scheduled workflows are entering an `Error` state within a minute because of an error like: 

```
Status:              Error
Message:             persistentvolumeclaims "my-workflow-lnpwr-workdir" is forbidden: User "system:serviceaccount:argo:argo" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "argo"
```

For example, today this workflow was scheduled and entered the `Error` state after 13 seconds: 

```
Name:                editor-image-ltr-lnpwr
Namespace:           argo
ServiceAccount:      editor-image-ltr
Status:              Error
Message:             persistentvolumeclaims "editor-image-ltr-lnpwr-workdir" is forbidden: User "system:serviceaccount:argo:argo" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "argo"
Created:             Wed Mar 11 07:00:38 +1100 (4 hours ago)
Started:             Wed Mar 11 07:00:47 +1100 (4 hours ago)
Finished:            Wed Mar 11 07:01:00 +1100 (4 hours ago)
Duration:            13 seconds
Parameters:
```

After noticing this, I triggered this exact same workflow spec in the same way and _did not_ get an error: 

```
Name:                editor-image-ltr-7qd42
Namespace:           argo
ServiceAccount:      editor-image-ltr
Status:              Running
Created:             Wed Mar 11 11:06:32 +1100 (33 minutes ago)
Started:             Wed Mar 11 11:06:34 +1100 (33 minutes ago)
Duration:            33 minutes 54 seconds
Parameters:
```

Note the times. Run within hours but getting different results. Around `Wed Mar 11 11:06:32 +1100` I triggered it again and that worked fine. 

I cannot provide you with a minimal reproduction because I cannot reproduce this reliably myself, but this problem has happened multiple times for multiple workflows we have using `volumeClaimTemplates`. 

**What you expected to happen**:

I expect a valid, working workflow spec to _always_ succeed if submitted to Argo, not sometimes fail with a permission error related to PVCs.

**How to reproduce it (as minimally and precisely as possible)**:

Cannot reproduce this reliably within our system, so would be quite hard to put a minimal reproduction here. 

I'd just like some insight into what on earth could be going on here, and what I can do to fix it.

**Anything else we need to know?**:

* The PVC named in the errors is created, but. stays in `Pending` state on workflows that `Error`
* This has started happening around 2 weeks ago, but I cannot correlate this to any event/change in our system

**Environment**:
- Argo version: We use Nix. Our Nix'd `argo` version is [2.4.3](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/argo/default.nix#L5)
- Kubernetes version : 
```
clientVersion:
  buildDate: "1970-01-01T00:00:01Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: archive
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.6
  major: "1"
  minor: 16+
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-12-22T23:14:11Z"
  compiler: gc
  gitCommit: c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2
  gitTreeState: clean
  gitVersion: v1.14.9-eks-c0eccc
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
