### ISSUE TITLE
How to use the `spec.artifactRepositoryRef`, example

### ISSUE THREAD

**Issue by vilmosnagy** [argoproj/argo#2461]
# Summary
I'm interested in how to use artifactRepositoryRefs (`spec.artifactRepositoryRef`) in my workflow.

# Motivation

In our workflow, we use a few workflow templates and a huge amount of artifacts. We'd like to test this workflow in a test environment (let's call it `uat`), and use the same workflow files in the `prod` environment - but the Minio we use have different URLs, different bucket names, the one in the `uat` is insecure while the prod one is not, and there are a few other differences.

So it'd be nice to define the Minio's details in a separate file not in the `workflow.yml`s.

If I understand correctly, the [artifactRepositoryRef](https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md#configure-the-default-artifact-repository) should be the solution for it, but I'm not able to find any example, and I'm not able to get it working. The only example I found it in the chageset of MR #1350, but it's not helping me in any way.

So, currently, this is where I stuck:

 - I have a configMap, in the `argo-system` namespace (where argo is installed) with the following data:

```
[vilmosnagy@vnagy-dell argo]$ kubectl get configmaps cm-default-artifact-repository --namespace=argo-system -o yaml
apiVersion: v1
data:
  config: |
    artifactRepository:
      s3:
        accessKeySecret: {key: accesskey, name: init-s3-credentials}
        bucket: vilmos-test-bucket
        endpoint: <our minio endpoint>
        insecure: true
        secretKeySecret: {key: secretkey, name: init-s3-credentials}
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-17T12:16:57Z"
  name: cm-default-artifact-repository
  namespace: argo-system
  resourceVersion: "736035"
  selfLink: /api/v1/namespaces/argo-system/configmaps/cm-default-artifact-repository
  uid: 0f112476-9246-453f-94a0-4ee5af6f4771
```
(I tried to create this configmap in the default namespace, but then my second example failed as well, with something like _can't find artifactRepositoryRef, configmap `cm-...-...` does not exist_)

And a `workflow.yml`, where I try to download a `tar.gz` file from the minio, and list its content:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  artifactRepositoryRef:
    configMap: cm-default-artifact-repository
    key: config
  entrypoint: start
  templates:
    - name: start
      inputs:
        artifacts:
          - name: test
            path: /data
            s3:
              key: 'K9999.xyzt.tar.gz'
      script:
        image: ubuntu:latest
        command: ["sh", "-e"]
        source: |
          ls -laR /data
```

When I try to run it, it gives me the following error:

```
[vilmosnagy@vnagy-dell argo]$ argo submit test-workflow.yaml --watch 
2020/03/17 13:37:41 Failed to submit workflow: templates.start inputs.artifacts.test was not supplied
```

If I define all the necessary keys for the `s3` object, it runs fine, see below:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  artifactRepositoryRef:
    configMap: cm-default-artifact-repository
    key: config
  entrypoint: start
  templates:
    - name: start
      inputs:
        artifacts:
          - name: test
            path: /data
            s3:
              key: 'K9999.xyzt.tar.gz'
              accessKeySecret: {key: accesskey, name: init-s3-credentials}
              bucket: vilmos-test-bucket
              endpoint: <our minio endpoint>
              insecure: true
              secretKeySecret: {key: secretkey, name: init-s3-credentials}
      script:
        image: ubuntu:latest
        command: ["sh", "-e"]
        source: |
          ls -laR /data
```

But I'd like to define the S3 detail's in a less _environment dependent_ way (a k8s configmap just seems to be the perfect solution for it), not in our `workflow-definition.yml` file.

Is `artifactRepositoryRef` supposed to help me? Is there an example how to use it? Or any ideas how to achieve my goals?

Thanks,
Vilmos

**Comment by hadim** [comment]
I have the same issue:

`artifact-repositories-configmap.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
data:
  data-bucket: |
    gcs:
      bucket: my_cluster-dev-data
```

`wk.yaml`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-from-artifact-

spec:
  entrypoint: input-from-artifact
  serviceAccountName: workflow

  artifactRepositoryRef:
    key: data-bucket

  templates:
    - name: input-from-artifact
      script:
        image: garthk/unzip
        command: [sh]
        source: |
          mkdir -p /data/inputs
          unzip /inputs.zip -d /data/inputs/
          ls /data/inputs
          cat /data/inputs/data1.csv
          content=$(cat /data/inputs/data1.csv)
          if [ "$content" = "some data" ]; then
            exit 0
          else
            exit 1
          fi
      inputs:
        artifacts:
          - name: input-data
            path: /inputs.zip
            gcs:
              key: tests/inputs/data-test-inputs.zip


```

```
2020/06/12 16:08:14 Failed to submit workflow: templates.input-from-artifact inputs.artifacts.input-data was not supplied
```

Not if I add `bucket: my_cluster-dev-data` to my wk spec, it works.
