### ISSUE TITLE
Can't I use Argo Workflow for EKS on Fargate?

### ISSUE THREAD

**Issue by hayato1121** [argoproj/argo#2502]
# Summary

I am attempting to run pods on Argo Workflow with AWS Fargate.
And I got the same message below when I used [Fargate Profile](https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html), even if I use Volume Mount for ConfigMap or Secret or NOT. 

```
$ kubectl get pod -o yaml
...
spec:
...
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podmetadata
  - hostPath:
      path: /var/run/docker.sock
      type: Socket
    name: docker-sock
  - name: argo-token-nrjft
    secret:
      defaultMode: 420
      secretName: argo-token-nrjft
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-24T07:21:53Z"
    message: 'Pod not supported on Fargate: volumes not supported: docker-sock'
    reason: POD_UNSUPPORTED_ON_FARGATE
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
...
```

However I could successfully apply my manifest file and workflow was running, the `STATUS` of the pod was `Pending` and never started running. 

I'm guessing that Fargate automatically and always use `hostPath` when developers use Argo workflow with Fargate.

Is there anyone who had encountered and has solved it ?

FIY, this is my environment.
Kubernetes: 1.15
argo: v2.7.0-rc1

And this is my manifest file I tried to apply.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
  generateName: test-
  namespace: test
spec:
  serviceAccountName: argo
  entrypoint: test
  templates:
  - name: test
    container:
      image: nginx:alpine
      command: [sh,-c]
      args: ["echo test"]
```

# Motivation

Successfully run workflow by using Fargate.
