### ISSUE TITLE
Is it possible to loop on step name?

### ISSUE THREAD

**Issue by yananielsen** [argoproj/argo#2506]
Hi,
I am looking to dynamically set the steps that will be run from an outside parameter. Something like this, is it possible?
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-arg-
spec:
  entrypoint: loop-param-arg-example
  arguments:
    parameters:
    - name: os-list                                     # a list of items
      value: |
        [
          { "name": "first", "template": "first" },
          { "name": "second", "template": "second" }
        ]

  templates:
  - name: loop-param-arg-example
    inputs:
      parameters:
      - name: os-list
    steps:
    - - name: "{{item.name}}"
        template: "{{item.template}}"
        withParam: "{{inputs.parameters.os-list}}"      # parameter specifies the list to iterate over

  # This template is the same as in the previous example
  - name: first
     container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello"]
```
