### ISSUE TITLE
Getting authentication error while launching Argo server 

### ISSUE THREAD

**Issue by chittu11** [argoproj/argo#2509]
Hello all,
We have upgraded our Argo version from 2.4.3 to 2.6.2 and while I am launching argo server getting the below error on WebUI. Also including the role which I created for this.

```
argo: v2.6.2
  BuildDate: 2020-03-12T16:04:25Z
  GitCommit: be0a0bb46ba50ed4d48ab2fd74c81216d4558b56
  GitTreeState: clean
  GitTag: v2.6.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
Here is my role:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ce-default
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/logs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
  - create
```

Error while accessing the WebUI:

[](WARN[0008] finished unary call with code PermissionDenied  error="rpc error: code = PermissionDenied desc = workflows.argoproj.io is forbidden: User \"ce\" cannot list resource \"workflows\" in API group \"argoproj.io\" at the cluster scope" grpc.code=PermissionDenied grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-03-25T00:15:53Z" grpc.time_ms=0.764 span.kind=server system=grpc

 Forbidden
 Reload this page to try again.

Request
GET /api/v1/workflows/?
Response
HTTP 403
{
  "error": "workflows.argoproj.io is forbidden: User \"ce\" cannot list resource \"workflows\" in API group \"argoproj.io\" at the cluster scope",
  "code": 7,
  "message": "workflows.argoproj.io is forbidden: User \"ce\" cannot list resource \"workflows\" in API group \"argoproj.io\" at the cluster scope"
}
Stack Trace
Error: Forbidden
    at n.<anonymous> (http://ca-kubemaster-01:2746/main.0756a421fdcd74189f51.js:145:175076)
    at n.r.emit (http://ca-kubemaster-01:2746/main.0756a421fdcd74189f51.js:145:181349)
    at XMLHttpRequest.t.onreadystatechange (http://ca-kubemaster-01:2746/main.0756a421fdcd74189f51.js:145:178482)
Component Stack)

Thanks,
Chittu

error": "workflows.argoproj.io is forbidden: User
