### ISSUE TITLE
argo cron lint should run before argo cron create

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#2529]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.

This one is pretty simple, the title says it all. Just like with Argo Workflows and WorkflowTemplates, Argo CronWorkflows should be linted before they are created.

Here's a test example to demonstrate based on the hello world example:
```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: cron-lint-failure-
spec:
  schedule: "* * * * *"
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["{{workflow.parameters.hello}}"]
```

`argo cron lint` properly fails this, but `argo cron create` goes ahead and creates it anyways.

I'm using Argo v2.6.3.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
