### ISSUE TITLE
Ansible style lists and conditionals in YAML

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#253]
There is a common case for lists and conditionals when executing steps, to easily repeat a step with different arguments. 

Simple example:
```
steps:
   BUILD:
    template: mybuild
    arguments:
      parameters.BUILDOPT: "%%item%%"
    with_items:
    - gcc
    - g++
```

We can further borrow ansible's technique where the items can either be a string or even a map, to support combinations:
```
steps:
   BUILD:
    template: mybuild
    arguments:
      parameters.BUILDOPT: "%%item.option%%"
      parameters.TAG: "%%item.tag%%"
    with_items:
    - { option: gcc, tag: foo }
    - { option: g++, tag: bar }
```
