### ISSUE TITLE
Error when using PodSpecPatch to parameterize ActiveDeadlineSeconds

### ISSUE THREAD

**Issue by jananzhu** [argoproj/argo#2545]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
I would like to parameterize activeDeadlineSeconds for my workflows so that a timeout can be set at time of workflow submission, similar to the request in #703 . The PodSpecPatch functionality added in #1687 seems like it would suit this use case. However Argo returns an error message when I try to submit a workflow with a PodSpecPatch that modifies the activeDeadlineSeconds: `Error in Unmarshalling after merge the patch`
**What you expected to happen**:
A pod should be created from my workflow with activeDeadlineSeconds set to the value of the parameter.

**How to reproduce it (as minimally and precisely as possible)**:

Submit the following workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-patch
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: timeout
        value: 86400
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: timeout
    podSpecPatch: '{"activeDeadlineSeconds":"{{inputs.parameters.timeout}}"}'
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
2.6.2
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-10-15T19:16:51Z"
  compiler: gc
  gitCommit: 20c265fef0741dd71a66480e35bd69f18351daea
  gitTreeState: clean
  gitVersion: v1.15.5
  goVersion: go1.12.10
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-10-15T19:09:08Z"
  compiler: gc
  gitCommit: c97fe5036ef3df2967d086711e6c0c405941e14b
  gitTreeState: clean
  gitVersion: v1.16.2
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

**Logs**

```
Name:                pod-spec-patchgz7n6
Namespace:           tenant-redesign
ServiceAccount:      default
Status:              Error
Message:             Error in Unmarshalling after merge the patch
Created:             Mon Mar 30 15:47:14 -0400 (17 minutes ago)
Started:             Mon Mar 30 15:47:14 -0400 (17 minutes ago)
Finished:            Mon Mar 30 15:47:15 -0400 (17 minutes ago)
Duration:            1 second
Parameters:
  timeout:           86400

STEP                               PODNAME              DURATION  MESSAGE
 ⚠ pod-spec-patchgz7n6 (whalesay)  pod-spec-patchgz7n6  0s        Error in Unmarshalling after merge the patch
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by jananzhu** [comment]
I did some digging and the error is thrown here:
https://github.com/argoproj/argo/blob/8b92d33eb2f2de3b593459140576ea8eaff8fb4b/workflow/controller/workflowpod.go#L294

The underlying json error is `json: cannot unmarshal string into Go struct field PodSpec.activeDeadlineSeconds of type int64`. Seems like the cause might be due to parameter values being String types and so the numeric value for ActiveDeadlineSeconds is marshalled as a string but cannot be unmarshalled back into an int.

If this is the case though, I'm not sure why the call to `util.ValidateJsonStr` on the PodSpecPatch string isn't finding the same error.

**Comment by sarabala1979** [comment]
Thanks for your detailed debug information. We will take a look and work that.

**Comment by sarabala1979** [comment]
it is wrongly defined in podspec for number element should put ""s.
Try below config an let me know
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-patch
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: timeout
        value: 86400
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: timeout
    podSpecPatch: '{"activeDeadlineSeconds":{{inputs.parameters.timeout}}}'
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```
