### ISSUE TITLE
allow customization of securityContext for wait container in workflow-controller-configmap

### ISSUE THREAD

**Issue by heavytail** [argoproj/argo#2554]
# Summary

Currently there's no way to specify the securityContext just for the wait container. We could only set securityContext at the pod level. It would be useful if it's possible to set the securityContext in `workflow-controller-configmap`.

# Motivation

I have pod security policy of run as non root user. To use workflow, I have to change the securityContext of wait container because argoexec use root user by default. It would be helpful if we could configure the securityContext just for the wait container, instead of a securityContext impacting all containers.

# Proposal

Allow change `securityContext` for wait container in `workflow-controller-configmap`. For example:
```
   executor:
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      resources:
        requests:
          cpu: 0.1
          memory: 64Mi
        limits:
          cpu: 0.5
          memory: 512Mi
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
