### ISSUE TITLE
carriage returns are added to scripts with long lines, causing syntax errors

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo#2593]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

I submitted a workflow containing a bash script with a line with length greater than 83 characters. I got syntax errors. I checked YAML in the Argo UI and saw that the script had been rewritten, with carriage returns that broke it. I made a minimal case.

**What you expected to happen**:

I expected the script to run as written, or be at least be reformatted in a way that doesn't break it.

**How to reproduce it (as minimally and precisely as possible)**:

 Workflow as submitted:

```
metadata:
  name: awesome-tigeress
  namespace: default
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      script:
        name: main
        image: 'docker/whalesay:latest'
        command:
          - bash
        source: |
          if [[ -e /bin && -e /bin && -e /bin && -e /bin && -e /bin && -e /bin && -e /bin && -e /bin ]]
          then
              echo stuff
          fi
```

Workflow as displayed in UI YAML panel:

```
name: whalesay
arguments: {}
inputs: {}
outputs: {}
metadata: {}
script:
    name: main
    image: 'docker/whalesay:latest'
    command:
        - bash
    resources: {}
    source: >
        if [[ -e /bin && -e /bin && -e /bin && -e /bin && -e /bin && -e /bin && -e
        /bin && -e /bin ]]
        then
                echo stuff
        fi
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
(base) aacurtis@MT-206988:~$ argo version
argo: v2.7.0
  BuildDate: 2020-03-31T23:35:04Z
  GitCommit: 4d1175eb68f6578ed5d599f877be9b4855d33ce9
  GitTreeState: clean
  GitTag: v2.7.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
(base) aacurtis@MT-206988:~$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-11-13T11:23:11Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.12
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-10-15T19:07:57Z"
  compiler: gc
  gitCommit: 20c265fef0741dd71a66480e35bd69f18351daea
  gitTreeState: clean
  gitVersion: v1.15.5
  goVersion: go1.12.10
  major: "1"
  minor: "15"
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by foobarbecue** [comment]
Oops, that case I submitted actually doesn't cause a syntax error; it works ok. Trying to find a mincase that does now... thought I had one.

**Comment by foobarbecue** [comment]
I'm trying to get to a minimal case but not quite there yet. This yaml causes the problem:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nac-stereo-
spec:
  entrypoint: generate-DEM-and-orthoimages
  volumes:
    - name: nac-volume
      hostPath:
        path: /c/nacpldata4
        type: DirectoryOrCreate
  templates:
  - name: generate-DEM-and-orthoimages
    arguments: {}
    inputs:
      parameters:
        - name: right-prod-id
          value: M1142334242LE
        - name: left-prod-id
          value: M1096364254RE
    outputs: {}
    metadata: {}
    script:
      name: ''
      image: lmmp-local/lmmp-container
      command:
        - bash
      resources: {}
      volumeMounts:
        - name: nac-volume
          mountPath: /data/nac
      imagePullPolicy: IfNotPresent
      source: |
        if (! test -f /data/nac/{{inputs.parameters.left-prod-id}}xx{{inputs.parameters.right-prod-id}}*DEM.tif && \
            ! test -f /data/nac/{{inputs.parameters.left-prod-id}}xx{{inputs.parameters.right-prod-id}}*DRG.tif)
        then
          echo "Skipping step because output file already exists"
        fi
    retryStrategy:
      limit: 3
```

with output:
```
/argo/staging/script: line 1: test: /data/nac/M1096364254RExxM1142334242LE-median-DEM.tif: binary operator expected

/argo/staging/script: line 2: test: /data/nac/M1096364254RExxM1142334242LE-median-DRG.tif: binary operator expected

Skipping step because output file already exists
```

and YAML in the UI is:

```
name: generate-DEM-and-orthoimages
arguments: {}
inputs:
    parameters:
        - name: right-prod-id
            value: M1142334242LE
        - name: left-prod-id
            value: M1096364254RE
outputs: {}
metadata: {}
script:
    name: ''
    image: lmmp-local/lmmp-container
    command:
        - bash
    resources: {}
    volumeMounts:
        - name: nac-volume
            mountPath: /data/nac
    imagePullPolicy: IfNotPresent
    source: >
        if (! test -f
        /data/nac/{{inputs.parameters.left-prod-id}}xx{{inputs.parameters.right-prod-id}}*DEM.tif
        && \
                ! test -f /data/nac/{{inputs.parameters.left-prod-id}}xx{{inputs.parameters.right-prod-id}}*DRG.tif)
        then
            echo "Skipping step because output file already exists"
        fi
retryStrategy:
    limit: 3
```
