### ISSUE TITLE
failed to save outputs: read /argo/secret: is a directory

### ISSUE THREAD

**Issue by sylvainblot** [argoproj/argo#2600]
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [X] I've included the logs.
 
**What happened**:
Whem I'm trying to use artifact passing the output can't be saved (using https://raw.githubusercontent.com/argoproj/argo/master/examples/artifact-passing.yaml for instance)

My ConfigMap:
```
    artifactRepository:
      s3:
        bucket: XXXX
        endpoint: s3.eu-west-1.amazonaws.com
        accessKeySecret:
          name: argo-artifacts
          key: accesskey
          secretKeySecret:
          name: argo-artifacts
          key: secretkey
```

I've verified that my AWS credentials are valid, they appear in the dashboard, and was added that way:

```
kubectl create secret generic argo-artifacts --from-file=./accesskey --from-file=./secretkey
```

**What you expected to happen**:
The generated artifacts uploaded on the s3 bucket

**Environment**:
- Argo version:
```
argo: v2.5.1
  BuildDate: 2020-02-20T18:19:45Z
  GitCommit: fb496a244383822af5d4c71431062cebd6de0ee4
  GitTreeState: clean
  GitTag: v2.5.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-03-25T14:58:59Z"
  compiler: gc
  gitCommit: 9e991415386e4cf155a24b1da15becaa390438d8
  gitTreeState: clean
  gitVersion: v1.18.0
  goVersion: go1.13.8
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-03-25T14:50:46Z"
  compiler: gc
  gitCommit: 9e991415386e4cf155a24b1da15becaa390438d8
  gitTreeState: clean
  gitVersion: v1.18.0
  goVersion: go1.13.8
  major: "1"
  minor: "18"
  platform: linux/amd64
```

**Logs**

```
Name:                artifact-passing-98hkq
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             child 'artifact-passing-98hkq-1179724389' failed
Created:             Mon Apr 06 11:47:44 +0200 (1 minute ago)
Started:             Mon Apr 06 11:47:44 +0200 (1 minute ago)
Finished:            Mon Apr 06 11:47:48 +0200 (1 minute ago)
Duration:            4 seconds

STEP                                          PODNAME                            DURATION  MESSAGE
 ✖ artifact-passing-98hkq (artifact-example)                                               child 'artifact-passing-98hkq-1179724389' failed
 └---⚠ generate-artifact (whalesay)           artifact-passing-98hkq-1179724389  4s        failed to save outputs: read /argo/secret: is a directory
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
