### ISSUE TITLE
WorkflowTemplate needs to include `namespace: default` in the repo

### ISSUE THREAD

**Issue by ericmeadows** [argoproj/argo#2601]
**What happened**:
Tried to follow WorkflowTemplate examples.  It never applied.

**What you expected to happen**:
WorkflowTemplate examples would apply and create.
- Either use `namespace: default` by default, or give a more coherent message. 
- Update documentation to include `namespace: default` for all examples.

**How to reproduce it (as minimally and precisely as possible)**:
  - Take **any** example in the repo
  - Attempt to apply using the UI
  - See the error
    - `namespaces "undefined" not found`

**Anything else we need to know?**:
YAML
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

**Environment**:
```
argo: v2.7.0
  BuildDate: 2020-03-31T23:35:43Z
  GitCommit: 4d1175eb68f6578ed5d599f877be9b4855d33ce9
  GitTreeState: clean
  GitTag: v2.7.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-12-11T12:42:56Z"
  compiler: gc
  gitCommit: 6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4
  gitTreeState: clean
  gitVersion: v1.15.7
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-18T22:49:35Z"
  compiler: gc
  gitCommit: aa93664bafe74f3c051e021b27a64e28ac34ab40
  gitTreeState: clean
  gitVersion: v1.15.11-gke.1
  goVersion: go1.12.17b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
`namespaces "undefined" not found`
```
