### ISSUE TITLE
workflow.creationTimestamp.s doesn't expand to a Unix-formatted timestamp

### ISSUE THREAD

**Issue by qjcg** [argoproj/argo#2637]
**What happened**: Using `"{{workflow.creationTimestamp.s}}"` as the value of an environment variable for a container failed (the variable text was left as-is and was not expanded to a timestamp value).

**What you expected to happen**: `"{{workflow.creationTimestamp.s}}"` to return a unix-formatted timestamp.

**How to reproduce it (as minimally and precisely as possible)**: Use `"{{workflow.creationTimestamp.s}}"` in a Workflow, for example:

```yaml
container:
  ...
  env:
    - name: TIMESTAMP
      value: "{{workflow.creationTimestamp.s}}"
```

**Anything else we need to know?**:  In Python, you can use `%s` with `strftime()` to get a unix-formatted timestamp.

**Environment**:
- Argo version: 2.7.1

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
