### ISSUE TITLE
Workflow mutexes

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#2677]
# Summary

Spawned from https://github.com/argoproj/argo/issues/2550.

# Motivation

Similar to the semaphore proposal in #2550, a complimentary concept to semaphores could also be mutexes. 

# Proposal

Although mutexes are simply a binary semaphore, we would introduce it as a convenience so that deploying separate configmap object is not necessary for defining the value of the semaphore:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-mutex-
spec:
  mutex: foo
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-mutex-
spec:
  entrypoint: sleep
  templates:
  - name: sleep
    mutex: foo
    container:
      image: alpine:latest
      command: [sh, -c, sleep 10]
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
I would suggest implementing Semaphore and achieve the above function/usability using following design. if semaphore didn't configmap then it will act as binary Semaphore/mutex.

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).

**Comment by shmargum** [comment]
hi, love the work here, it would seem that I am not able to pass a paramater as the mutex name, this would be really useful, is there a way to achieve this?, example template:
```yaml
- name: postprocess
  synchronization:
    mutex:
      name: "postprocess-{{workflow.parameters.game}}"
```

i see this in the logs:
```
Waiting for argo-events/mutex/postprocess-{{workflow.parameters.game}} lock. Lock status: 0/1
```

i do see the annotation be correct on the pod:
```yaml
    workflows.argoproj.io/template: '{..."synchronization":{"mutex":{"name":"postprocess-g.1234"}}}'
```
