### ISSUE TITLE
Duplicate start when using CronWorkflow

### ISSUE THREAD

**Issue by clementlecorre** [argoproj/argo#2694]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

I use cronWorkflow, with the hello-word example I see a duplicate launch of the task. (per minute)

**What you expected to happen**:

A unique launch of the task. (per minute)

**How to reproduce it (as minimally and precisely as possible)**:

This is my yaml file.
```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
  labels:
    workflows.argoproj.io/controller-instanceid: dev-argo-ID
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["🕓 hello world"]
```

```
$ argo cron create cron-workflow.yaml
$ argo list --prefix hello
NAME                STATUS      AGE   DURATION   PRIORITY
hello-world-6jkhs   Succeeded   11s   4s         0
hello-world-rgmzj   Succeeded   11s   4s         0
hello-world-hpxqq   Succeeded   1m    4s         0
hello-world-lx895   Succeeded   1m    4s         0
```

I've got two workflows running per minute.

**Anything else we need to know?**: I use the ID instance label.

I don't really have a log that explains the duplicate launch.

**Environment**:
- Argo version:
```
$ argo: vv2.7.2+c52a65a.dirty
  BuildDate: 2020-04-10T19:26:18Z
  GitCommit: c52a65aa62426f5e874e1d3f1058af15c43eb35f
  GitTreeState: dirty
  GitTag: v2.7.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ clientVersion:
  buildDate: "2019-11-14T04:24:29Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.13
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-02-26T01:12:54Z"
  compiler: gc
  gitCommit: bac3690554985327ae4d13e42169e8b1c2f37226
  gitTreeState: clean
  gitVersion: v1.15.10-eks-bac369
  goVersion: go1.12.12
  major: "1"
  minor: 15+
  platform: linux/amd64
```
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
