### ISSUE TITLE
Child nodes of exit handlers don't execute on argo stop

### ISSUE THREAD

**Issue by mark9white** [argoproj/argo#2710]
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [X] I've included the logs.
 
**What happened**:

Children of onExit nodes are not marked as onExit, therefore they don't execute on 'argo stop'

**What you expected to happen**:

Children of onExit nodes to execute on 'argo stop'

**How to reproduce it (as minimally and precisely as possible)**:

- Submit this workflow
- Stop the workflow
- The exit handler pod will have the message 'workflow shutdown with strategy:  Stop'

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: exit-handler
spec:
  entrypoint: suspend
  onExit: exit-handler
  templates:
  - name: suspend
    suspend: {}

  - name: exit-handler
    steps:
      - - name: hello1
          template: exit-handler-2

  - name: exit-handler-2
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo send e-mail: {{workflow.name}} {{workflow.status}}. Failed steps {{workflow.failures}}"]
```

**Anything else we need to know?**:

**Environment**:
- Argo version: db6d1416

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                exit-handler
Namespace:           staging
ServiceAccount:      default
Status:              Failed (Terminated)
Message:             Stopped with strategy 'Stop'
Created:             Thu Apr 16 12:23:13 +0100 (1 minute ago)
Started:             Thu Apr 16 12:23:13 +0100 (1 minute ago)
Finished:            Thu Apr 16 12:23:28 +0100 (1 minute ago)
Duration:            15 seconds

STEP                    TEMPLATE        PODNAME                  DURATION  MESSAGE
 ✖ exit-handler         suspend                                            Stopped with strategy 'Stop'

 ✖ exit-handler.onExit  exit-handler                                       child 'exit-handler-1598429748' failed
 └---✖ hello1           exit-handler-2  exit-handler-1598429748  1s        workflow shutdown with strategy:  Stop
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
