### ISSUE TITLE
Loop waits until all members are scheduled before starting loop

### ISSUE THREAD

**Issue by amrragab8080** [argoproj/argo#2739]
Submitting a large scale 5000 member loop workload. It seems that argo waits before the entire loop is expanded before processing the loop. simple example with stress:
```
resources:
        limits:
          cpu: "1"
      command: ["stress"]
      args: ["--cpu","1","--timeout","40s"]
```
Expected container runtime is 40s but is in processing for well over 1 hour until all 5000 members are submitted and then processed and completed.
````
  argo: v2.6.3
  BuildDate: 2020-03-16T17:56:00Z
  GitCommit: 2e8ac609cba1ad3d69c765dea19bc58ea4b8a8c3
  GitTreeState: clean
  GitTag: v2.6.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
````
Is this expected behavior? Should the loop members start processing **during** loop expansion or **after** loop expansion? And is there any client side setting to improve argo pod loop expansion performance

**Comment by alexec** [comment]
Labeling with scalability.

**Comment by amrragab8080** [comment]
Here is a simple reproducible example
````
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate
        template: gen-number-list
    # Iterate over the list of numbers generated by the generate step above
    - - name: sleep
        template: sleep-n-sec
        arguments:
          parameters:
          - name: stress
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"

  # Generate a list of numbers in JSON format
  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([i for i in range(1, 1000)], sys.stdout)

  - name: sleep-n-sec
    retryStrategy:
      limit: 10
      retryPolicy: "Always"
    inputs:
      parameters:
      - name: stress
    container:
      image: polinux/stress
      resources:
        limits:
          cpu: "1"
      command: ["stress"]
      args: ["--cpu","1","--timeout","40s"]
````
