### ISSUE TITLE
Ability to specify volumes on a WorkflowTemplate

### ISSUE THREAD

**Issue by wreed4** [argoproj/argo#2777]
# Summary
There doesn't seem to be a way to share Volumes between two templates in a `WorkflowTemplate`.

# Motivation
When writing workflows that are meant to be kicked off by other workflows, the best way to accomplish this seems to be to use a WorkflowTemplate with a main template intended to be called by other Workflows.  In this case, the Template may get rather complex. In my case, I have a main `steps` template which calls three other templates, two of which need to share a `volume`.  When I do this in a `Workflow`, this works fine, but when I move that code over to a `WorkflowTemplate` and then try to call a particular ref, the workflow fails stating the volumes have not been declared.  If I move them to the `Workflow` it runs, but this is clearly bad code organization as the `Template` is supposed to hide the complexity. If every `Workflow` needs to know what volumes the `WorkflowTemplate` needs declared, that's terrible! :) 

# Proposal

A) all `volumes` declared on any `WorkflowTemplates` get added to the calling `Workflow` OR
B) There could be a clearer or more direct way (documented) to launch complex, multi-step workflows from other Workflows. This could use WorkflowTemplates and under the hood use the `submit --from` functionality.  But the complexity here is that when `--watch`ing or `get`ing the `Workflow`, you should see all the steps of the child workflow, not a single wrapper step.  

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dtaniwaki** [comment]
I like your idea A. If no one disagree, I will implement it.

**Comment by simster7** [comment]
@dtaniwaki Assigned

**Comment by simster7** [comment]
Before any works begins on this, @wreed4 did you know that you can currently specify volumes on a template level? Here is an example, I just tested it and it works.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: volumes-existing
  namespace: argo
spec:
  entrypoint: volumes-existing-example

  templates:
    - name: volumes-existing-example
      steps:
        - - name: generate
            template: append-to-accesslog
        - - name: print
            template: print-accesslog

    - name: append-to-accesslog
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: my-existing-volume
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo accessed at: $(date) | tee -a /mnt/vol/accesslog"]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol

    - name: print-accesslog
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: my-existing-volume
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo 'Volume access log:'; cat /mnt/vol/accesslog"]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-steps-
  namespace: argo
spec:
  entrypoint: call
  templates:
  - name: call
    steps:
    - - name: hello1
        templateRef:
          name: volumes-existing
          template: volumes-existing-example
```
