### ISSUE TITLE
Workflow Details are not Scrollable

### ISSUE THREAD

**Issue by ericmeadows** [argoproj/argo#2785]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Argo Workflows `fa fa-columns` page, when on an individual Workflow, is not scrollable.

**What you expected to happen**:

We can scroll, when there are large numbers of variables present.

**How to reproduce it (as minimally and precisely as possible)**:

Add more parameters than fit into view for a given Workflow

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: vv2.7.4+50b209c.dirty
  BuildDate: 2020-04-16T16:28:14Z
  GitCommit: 50b209ca14c056fb470ebb8329e255304dd5be90
  GitTreeState: dirty
  GitTag: v2.7.4
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-12-11T12:42:56Z"
  compiler: gc
  gitCommit: 6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4
  gitTreeState: clean
  gitVersion: v1.15.7
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-18T22:49:35Z"
  compiler: gc
  gitCommit: aa93664bafe74f3c051e021b27a64e28ac34ab40
  gitTreeState: clean
  gitVersion: v1.15.11-gke.1
  goVersion: go1.12.17b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

<img width="1792" alt="Screen Shot 2020-04-22 at 12 27 08 PM" src="https://user-images.githubusercontent.com/13244411/80008721-1cb7f480-8496-11ea-9883-24abe353b8a9.png">

**Logs**

```
N/A
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
