### ISSUE TITLE
Default values of empty string are ignored

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo#2799]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
We tried setting a default value of `""` for an output parameter. The workflow controller didn't register the default, and marked the workflow as failed when it couldn't resolve the output. Here's a reproducer:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-default-
spec:
  entrypoint: steps
  templates:
  - name: steps
    steps:
    - - name: dag
        template: dag
  - name: dag
    dag:
      tasks:
      - name: A
        when: "false == true"
        template: print-message
        arguments:
          parameters:
            - name: message
              value: "hello world"
    outputs:
      parameters:
        - name: output
          valueFrom:
            parameter: "{tasks.A.outputs.result}"
            default: ''

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.message}}"]
```
If I put any character into the default value, the default is registered.

**What you expected to happen**:
I expected empty strings to work as a default output.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.7.3
  BuildDate: 2020-04-15T22:52:59Z
  GitCommit: 66bd0425280c801c06f21cf9a4bed46ee6f1e660
  GitTreeState: clean
  GitTag: v2.7.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
```
clientVersion:
  buildDate: "2019-10-15T19:16:51Z"
  compiler: gc
  gitCommit: 20c265fef0741dd71a66480e35bd69f18351daea
  gitTreeState: clean
  gitVersion: v1.15.5
  goVersion: go1.12.10
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-02-29T01:24:35Z"
  compiler: gc
  gitCommit: 39e41a8d6b7221b901a95d3af358dea6994b4a40
  gitTreeState: clean
  gitVersion: v1.15.9-gke.24
  goVersion: go1.12.12b4
  major: "1"
  minor: 15+
  platform: linux/amd64

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
