### ISSUE TITLE
v2.7.1+ Regression: Global outputs cannot be defined by steps/DAGs templates

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#2823]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

In Argo v2.6.3, you could produce global output parameters as the outputs to steps/DAG templates as shown in the example below (based on [this example](https://github.com/argoproj/argo/blob/master/examples/global-outputs.yaml)). But in Argo v2.7.5, this is no longer working.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-outputs-
spec:
  entrypoint: generate-globals

  templates:
  - name: generate-globals
    steps:
    - - name: generate
        template: nested-global-output-generation
    - - name: consume
        template: global-output-consumption

  - name: output-generation
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["sleep 1; echo -n hello world > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello-param
        valueFrom:
          path: /tmp/hello_world.txt

  - name: nested-global-output-generation
    steps:
    - - name: generate-output
        template: output-generation
    outputs:
      parameters:
      - name: hello-param
        valueFrom:
          parameter: "{{steps.generate-output.outputs.parameters.hello-param}}"
        globalName: global-param

  - name: global-output-consumption
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo {{workflow.outputs.parameters.global-param}}"]
```

In this workflow, the `nested-global-output-generation` template takes the output of the `output-generation` template and packages its output parameter as a global variable. This is common in the templates I write; the lower-level template generates the parameters/artifacts, but I don't always want to export them; I add a wrapper akin to the nested template above if I do.

In Argo v2.7.0 (and earlier, at least v2.6.3), this works fine, as the logs show:
```
global-outputs-dblmm-1000914815: hello world
```
In `argo get`, we can also see that the output parameter is appropriately exported:
```
Output Parameters:
  global-param:      hello world
```

However, in Argo v2.7.1 through v2.7.5, this completely fails to happen. The workflow still executes, but the parameter is never saved as an output parameter, and the next step just prints:
```
global-outputs-4fqpq-1520819381: {{workflow.outputs.parameters.global-param}}
```
Its `argo get` is also missing the Output Parameters section entirely.

Note that we can still pass global outputs as in the original example from container/script templates, but can no longer do so from steps/DAG templates.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
