### ISSUE TITLE
UserContainer swagger definition not matching command line client

### ISSUE THREAD

**Issue by cburbridge** [argoproj/argo#2835]
**What happened**:

The API swagger file for release 2.7 (https://github.com/argoproj/argo/blob/release-2.7/api/openapi-spec/swagger.json) defines a UserContainer as a 

```
"io.argoproj.workflow.v1alpha1.UserContainer": {
      "description": "UserContainer is a container specified by a user.",
      "type": "object",
      "properties": {
        "container": {
          "$ref": "#/definitions/io.k8s.api.core.v1.Container"
        },
        "mirrorVolumeMounts": {
          "type": "boolean",
          "format": "boolean",
          "title": "MirrorVolumeMounts will mount the same volumes specified in the main container\nto the container (including artifacts), at the same mountPaths. This enables\ndind daemon to partially see the same filesystem as the main container in\norder to use features such as docker volume binding"
        }
      }
    },
```

and the `sidecars` property of a `Template` as an array of `UserContainers`. 

In the sidecar example at https://github.com/argoproj/argo/blob/master/examples/sidecar.yaml, the YAML for the sidecar property looks like:

```
    sidecars:
    - name: influxdb
      image: influxdb:1.2
```

whereas the swagger file suggests it should be generated as:

```
    sidecars:
    - container:
        name: influxdb
        image: influxdb:1.2
```

However, the argo command line client will not accept this format:

```
argo submit sidecars_wf.yaml --serviceaccount argo --instanceid "27"
2020/04/24 15:31:46 Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "container"
```

**What you expected to happen**:
The argo client (version 2.7.5) to accept the UserContainer in the form from the 2.7 swagger file.

It looks like the example and command line client still follow the swagger file from release 2.5.

**Environment**:
- Argo version:
```
argo: v2.7.5
  BuildDate: 2020-04-21T00:55:01Z
  GitCommit: ede163e1af83cfce29b519038be8127664421329
  GitTreeState: clean
  GitTag: v2.7.5
  GoVersion: go1.13
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-02-11T18:14:22Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.6
  major: "1"
  minor: "17"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-02-07T01:31:02Z"
  compiler: gc
  gitCommit: 502bfb383169b124d87848f89e17a04b9fc1f6f0
  gitTreeState: clean
  gitVersion: v1.14.9-eks-502bfb
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
