### ISSUE TITLE
Using submittable Workflowtemplate wit parameters

### ISSUE THREAD

**Issue by alex-lipkin-create** [argoproj/argo#2840]
Currently we would like start to use submittable workflow template.
The challenge is that workflow, which I would like to convert to workflowtemplates includes some run time parameter specified during submit.

In my understanding there is no possibility to convert workflow to workflowtemplate without
setting the parameter. Is that correct?

For sure I can set the parameter in yaml file and then create a template with that parameter value.
The challenge is: we are several developers which would use workflowtemplate with different value to the same timepoint.

Is there any good way to use workflowtemplate with parameter which might be different depending on the user, who is executing this workflowtemplate?

**Comment by sarabala1979** [comment]
yes, you can pass the parameter during workflow submission time using `-p`

Scenario 1: `Workflow` is  referring to `WorkflowTemplate` 

Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: "hello world"
  workflowTemplateRef:
    name: workflow-template-whalesay-template
```
Workflow Template:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

you can pass the `message` argument in runtime

```
argo submit hello-world.yaml -p message=welcome
```

Scenario 2: Directly submitting `WorkflowTemplate` as `Workflow` using --from option

Workflow Template : 

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  arguments:
    parameters:
      - name: message
        value: "hello world"
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```
argo template create <yaml>

```
argo submit --from workflowtemplate/workflow-template-whalesay-template -p message=welcome
