### ISSUE TITLE
Allow templates to be URLS, like Kubeflow

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2847]
# Summary

Allow resolution of templates by using URLs.

# Motivation

So we can have templates in a single place.

# Proposal

This is a feature that Kubeflow has and @Ark-kun mentions in #2793.

@mukulikak @jessesuen 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by Ark-kun** [comment]
Note that the Kubeflow Pipelines team does not require this feature to be present in Argo (KFP works fine as it is). But this might be a neat feature for people using raw Argo.

Here is an example of using this feature in KF Pipelines: https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.component.yaml 

Here is an example of graph (DAG) using task that references a component (template) using an HTTPS URL.
```
...
implementation:
  graph:
    tasks:
      Automl create dataset for tables:
        componentRef:
          url: https://raw.githubusercontent.com/kubeflow/pipelines/b3179d86b239a08bf4884b50dbf3a9151da96d66/components/gcp/automl/create_dataset_for_tables/component.yaml
        arguments:
          gcp_project_id:
            graphInput:
              inputName: gcp_project_id
          gcp_region:
            graphInput:
              inputName: gcp_region
          display_name:
            graphInput:
              inputName: dataset_display_name
...
```

Here is the schema of the [ComponentReference](https://github.com/kubeflow/pipelines/blob/f214a39420e7016baf9670189d1750d9ae7ebc82/sdk/python/kfp/components/structures/components.json_schema.json#L216) used by KFP components.
