### ISSUE TITLE
Exit code as output variable not resolving

### ISSUE THREAD

**Issue by seddonm1** [argoproj/argo#2849]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

I am testing Argo 2.8.0 RC1 and RC2 and have found that the `outputs.exitCode` variable created via PR #2111 does not appear to work: 

```
templates.exit-code-output-variable.steps failed to resolve {{steps.failing-container.outputs.exitCode}}
```

**What you expected to happen**:

Exit code should have been resolved as #2111 has been merged to Master and has been included in the list of PRs included in Argo 2.8.0 RC1.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
argo submit examples/exit-code-output-variable.yaml
```

**Environment**:
- Argo version:
```
argo: v2.8.0-rc2+4126d22.dirty
  BuildDate: 2020-04-23T22:28:41Z
  GitCommit: 4126d22b6f49e347ae1a75dd3ad6f484bee30f11
  GitTreeState: dirty
  GitTag: v2.8.0-rc2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-10-15T19:16:51Z"
  compiler: gc
  gitCommit: 20c265fef0741dd71a66480e35bd69f18351daea
  gitTreeState: clean
  gitVersion: v1.15.5
  goVersion: go1.12.10
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-01-14T00:09:19Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.4
  major: "1"
  minor: "17"
  platform: linux/amd64
```
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
