### ISSUE TITLE
Manual intervention in workflow process

### ISSUE THREAD

**Issue by kabilan6** [argoproj/argo#2852]
# Summary

I have scenario in workflow where manual approval step is required in the flow and it needs to hold till the approval and move forward once it is approved .

is it possible to achieve this in Argo workflow ? can you please provide eg for this ?

The workflow will have 6-7 steps with dependency and it will run in loop for about 100 times. so may go for Approval and some mayn't go for approval. The loop shouldn't be impacted if one flow is waiting on the approval when the other one's aren't waiting on the approval. I can set the parallelism of 8.

**Comment by simster7** [comment]
Take a look at: https://github.com/argoproj/argo/blob/master/examples/suspend-template.yaml

**Comment by kabilan6** [comment]
my scenario- i dunno know exactly how long it will take for approval step. i want that next step to after approval. 

Also my workflow could 6-10 steps and it will run in loops/iteration for each input. In that flow, one step could be approval (based on case condition, approval not req for each input iteration )

**Comment by simster7** [comment]
> my scenario- i dunno know exactly how long it will take for approval step. i want that next step to after approval.

Per the example, an empty suspend template will stop execution until manual intervention is made:

```yaml
  - name: approve
    suspend: {}
```

> Also my workflow could be 6-10 steps and it will run in loops/iteration for each input. In that flow, one step could be approval (based on case condition, approval not req for each input iteration ). I don;t want the entire workflow to be on suspend mode only when some of the input in a loop is waiting for approval

You should be able to add suspend templates to each of the items in your loop:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: suspend-template-
  namespace: argo
spec:
  entrypoint: disptach
  templates:
    - name: disptach
      steps:
        - - name: steps
            template: step
            arguments:
              parameters:
                - name: wait-period
                  value: "{{item}}"
            withParam: '["15", "10", "5"]'

    - name: step
      inputs:
        parameters:
          - name: wait-period
      steps:
        - - name: build
            arguments:
              parameters:
                - name: wait-period
                  value: "{{inputs.parameters.wait-period}}"
            template: whalesay
        - - name: approve
            template: approve

    - name: approve
      suspend: {}

    - name: whalesay
      inputs:
        parameters:
          - name: wait-period
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["sleep {{inputs.parameters.wait-period}}"]
```

This can result in some steps finishing before others and therefore suspending before others:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/614838/80407667-d6d6a400-887a-11ea-9366-1db7df4a2768.png">

To resume you would need to use the `--node-field-selector` feature of `argo resume`.

```
$ argo resume suspend-template-mdzl9 --node-field-selector="displayName=approve"
```

There are some issues with this:

1. Currently the only applicable "field" that you can use for this is `displayName=approve`. However, as you can see here, the display names of all of the nodes are the same ("approve") making it impossible to distinguish which exact approve step you want to resume.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/614838/80407804-0b4a6000-887b-11ea-878a-b77f12f4e0c4.png">

2. There is no documentation for this at the moment. Opened #2860 for this.
