### ISSUE TITLE
Add descriptions for steps that can show up in ui

### ISSUE THREAD

**Issue by HumairAK** [argoproj/argo#2871]
# Summary

Add step description field that can add human readable descriptions about the step. 

# Motivation

We make the ui available for others on our teams to view, but they do not necessarily have the full technical understanding of what the workflow is doing. It would be great if instead we could offer them a description of a step when they click on it to get a summary of what the step is doing. 

# Proposal
Not sure, but I'd imagine the end result would be an additional field within templates.steps when designing a workflow.

**Comment by alexec** [comment]
This sounds useful, and there is "display name" for a step. Have you set that?

**Comment by HumairAK** [comment]
Is that separate from the `name` field within a step? I.e. the name you see in the ui on workflow square icon? Those get truncated after exceeding a certain number of characters. I was thinking more along the lines of a way to click the specific step then be able to see a more detailed description in a form of a paragraph - if that makes sense.

**Comment by alexec** [comment]
Sounds good too. Would you like to raise a PR?

**Comment by alexec** [comment]
I would recommend you make your workflows and template compatibly with the **[template catalog](https://argoproj-labs.github.io/argo-workflows-catalog/)** by using the annotations:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: This is a basic catalog example that simply
      prints "hello argo!".
    workflows.argoproj.io/maintainer: '@alexec'
    workflows.argoproj.io/tags: example
    workflows.argoproj.io/version: '>= 2.9.0'
  name: hello-world
```
