### ISSUE TITLE
workflow-controller should throw an error when config has 'config' and any other key

### ISSUE THREAD

**Issue by mac9416** [argoproj/argo#2885]
**What happened**:

Copy/pasting the following workflow-controller config from getting-started (before it was [fixed](https://github.com/argoproj/argo/pull/2872)), would cause workflow-controller to silently ignore the section after `config`. (I think the `|` causes the structure to be flattened).

```
data:
  config: |
    artifactRepository: |
      s3:
        bucket: my-bucket
        endpoint: argo-artifacts.default:9000
        insecure: true
        # accessKeySecret and secretKeySecret are secret selectors.
        # It references the k8s secret named 'argo-artifacts'
        # which was created during the minio helm install. The keys,
        # 'accesskey' and 'secretkey', inside that secret are where the
        # actual minio credentials are stored.
        accessKeySecret:
          name: argo-artifacts
          key: accesskey
        secretKeySecret:
          name: argo-artifacts
          key: secretkey
```

**What you expected to happen**:

I would have expected workflow-controller to throw an exception.

**How to reproduce it (as minimally and precisely as possible)**:

Install the minio manifest and copy/paste the above config to the workflow-controller configmap.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
