### ISSUE TITLE
SSL enforced Mysql database connections for Workflow repository

### ISSUE THREAD

**Issue by murali198** [argoproj/argo#2902]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
The workflow repository backed by mysql databases does not seem to support SSL.

**What you expected to happen**:
SSL enforced mysql databases can be used to as workflow repository

**How to reproduce it (as minimally and precisely as possible)**:
Create an SSL enforced Mysql instance (Azure Mysql server for instance). Setup Argo to use the database as workflow repository. See errors in workflow controller as it is unable to establish database connection.

Deploy argo with Helm chart and set values as follows:
```yaml
controller:
  persistence:
    nodeStatusOffLoad: true
    archive: true
    archiveTTL: 180d
    mysql:
      host: test.mysql.database.azure.com
      port: 3306
      database: argo
      tableName: argo_workflows
      options:
        useSSL: true
        requireSSL: false
      userNameSecret:
        name: argo-mysql-secret
        key: username
      passwordSecret:
        name: argo-mysql-secret
        key: password  
```
**Environment**:

- Argo version:
```
$ argo version
argo: v2.7.2
  BuildDate: 2020-04-10T19:25:22Z
  GitCommit: c52a65aa62426f5e874e1d3f1058af15c43eb35f
  GitTreeState: clean
  GitTag: v2.7.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-09-18T14:47:22Z"
  compiler: gc
  gitCommit: 8fca2ec50a6133511b771a11559e24191b1aa2b4
  gitTreeState: clean
  gitVersion: v1.14.7
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-09-18T14:39:02Z"
  compiler: gc
  gitCommit: 8fca2ec50a6133511b771a11559e24191b1aa2b4
  gitTreeState: clean
  gitVersion: v1.14.7
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Logs**

```
time="2020-04-29T14:21:06Z" level=info msg="Persistence configuration enabled"
time="2020-04-29T14:21:06Z" level=info msg="Creating DB session"
time="2020-04-29T14:21:06Z" level=fatal msg="Failed to update config: Error 9002: SSL connection is required. Please specify SSL options and retry.\x00"
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Would you like to sbumit a PR to fix this?

**Comment by Sharathmk99** [comment]
Facing same problem.

**Comment by Sharathmk99** [comment]
@alexec can you help to fix this?

**Comment by mcwienczek** [comment]
having the same issue with postgres connections

**Comment by alexec** [comment]
Would you like to submit a PR to fix?

**Comment by mcwienczek** [comment]
PS. postgres actually works but there was undocumented SSL flag needed. Here is my PR that fixes it. Unfortunately I dont know what's the status with MySQL. 

https://github.com/argoproj/argo/pull/3924

**Comment by ttjohn** [comment]
Is there a specific issue that MySQL is not supported?  Any issues with underlying drivers?

**Comment by kmorkans** [comment]
Facing the same problem. Cannot connect to TLS enforced server.
github.com/go-sql-driver/mysql has params tls=true and I would suggest also adding skip-verify.
If time permits will try to submit a PR soon

**Comment by thetimpanist** [comment]
If anyone stumbles across this and is looking for a way to connect to mysql with TLS, I was able to get it working by adding the following to helm values:
```
controller:
  persistence:
    mysql:
      options:
        tls: skip-verify
```
