### ISSUE TITLE
Unable to understand error messgae "fatal: Not a valid object name /argo/staging/script"

### ISSUE THREAD

**Issue by rjdp** [argoproj/argo#2903]
Here is my Workflow definition:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-try-
spec:
  entrypoint: ci-pipeline
  arguments:
    artifacts:
    - name: argoflowtest
      git:
        repo: https://github.com/rjdp/argoflowtest
        revision: release
        depth: 1
  templates:
    - name: ci-pipeline
      inputs:
        artifacts:
        - name: argoflowtest
      steps:
      - - name: fetchTag
          template: tagGet
          arguments:
            artifacts:
              - name: source
                from: "{{inputs.artifacts.argoflowtest}}"
    - name: tagGet
      inputs:
        artifacts:
        - name: source
          path: /src/argo-try
      script:
        image: alpine/git
        args:
          ["describe", "--exact-match", "--tags", "--abbrev=0"]
        workingDir: /src/argo-try
```

Here is the message from argo UI, Thanks

![Screenshot from 2020-04-30 11-22-58](https://user-images.githubusercontent.com/7734938/80678364-64fb9600-8ad8-11ea-90d4-5e596ef6cbb7.png)
