### ISSUE TITLE
Failed to submit workflow when a nested template is chosen via input parameter.

### ISSUE THREAD

**Issue by shadiramadan** [argoproj/argo#2905]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
```
argo submit test.yaml
2020/04/30 04:24:17 Failed to submit workflow: templates.test-param.tasks.test-param templates.nested-dag.tasks.test-nested-task template name 'placeholder-3' undefined
```

**What you expected to happen**:
I expected the workflow to submit and for the the template `echo-hello` to run.
It does not seem to be resolving the input parameter.

**How to reproduce it (as minimally and precisely as possible)**:
`test.yaml`:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-param-
spec:
  entrypoint: test-param

  # arguments:
  #   parameters:
  #     - name: template-name

  templates:
    - name: echo-hello
      container:
        image: alpine:latest
        command: [echo]
        args: ["Called template echo-hello"]

    - name: test-param
      dag:
        tasks:
          - name: test-param
            template: nested-dag
            arguments:
              parameters:
                - name: template-name
                  value: echo-hello

    - name: nested-dag
      inputs:
        parameters:
        - name: template-name
      dag:
        tasks:
          - name: test-nested-task
            template: "{{inputs.parameters.template-name}}"
```
```
argo submit test.yaml
```

**Anything else we need to know?**:
Replacing the input parameter with a workflow parameter in the given example _does_ succeed.  I would expect these to be interchangeable.

The reason I would like to do this is because it would cut down one of my workflows _significantly_ (400+ lines saved).

**Environment**:

- Argo version:
```
$ argo version
argo: v2.7.6+70facdb.dirty
  BuildDate: 2020-04-28T17:09:06Z
  GitCommit: 70facdb67207dbe115a9029e365f8e974e6156bc
  GitTreeState: dirty
  GitTag: v2.7.6
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```

- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-02-13T18:08:14Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.8
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-10-15T12:02:12Z"
  compiler: gc
  gitCommit: 211047e9a1922595eaa3a1127ed365e9299a6c23
  gitTreeState: clean
  gitVersion: v1.14.8
  goVersion: go1.12.10
  major: "1"
  minor: "14"
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Hmm, I don't think we officially support parametrizing template names... although I don't see why we wouldn't. Let me explore this

**Comment by leoluz** [comment]
We are having a similar issue.

A brief explanation of our use-case:

We want to run validation steps in parallel and after each validation we need to run a generic post processing step. Validations will be provided by different teams, so it should be easy to add new validations in future. Ideally, to provide a new validation a team would have to add a new container template in the workflow and add its name in the validation list argument.

This is a minimalist example of what Im trying to do:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: validation-
  namespace: workflow
spec:
  entrypoint: validations
  arguments:
    parameters:
      - name: validation
        value: opa-validation
      - name: validations
        value: |
          [
            "opa-validation",
            "config-validation"
          ]

  templates:
  - name: validations
    steps:
      - - name: validate
          template: invoke-validation
          arguments:
            parameters:
            - name: validation-name
              value: "{{item}}"
          withParam: "{{workflow.parameters.validations}}"

  - name: invoke-validation
    inputs:
      parameters:
        - name: validation-name
    steps:
      - - name: invoke-validate
          template: "{{inputs.parameters.validation-name}}"
      - - name: post-step
          template: do-post-step

  - name: opa-validation
    script:
      image: alpine
      command: [sh]
      source: |
        echo "opa validation"

  - name: config-validation
    script:
      image: alpine
      command: [sh]
      source: |
        echo "config validation"

  - name: do-post-step
    script:
      image: alpine
      command: [sh]
      source: |
        echo "post step"
```

if I try to submit this workflow I get:

```
Failed to submit workflow: templates.validations.steps[0].validate templates.invoke-validation.steps[0].invoke-validate template name 'placeholder' undefined
```

However parametrizing the template name doesn't seem to be an issue because if I replace the line:

`template: "{{inputs.parameters.validation-name}}"`

with:

`template: "{{workflow.parameters.validation}}"`

it works.

Having the ability to provide the step names as input parameters would not only reduce the size of the workflow but it also makes it much simpler for different teams to extend it.
