### ISSUE TITLE
Large workflow won't start, even with persistence enabled

### ISSUE THREAD

**Issue by bolthar** [argoproj/argo#2936]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
This is what I get when trying to ```argo submit``` the workflow which I put in [this gist](https://gist.github.com/bolthar/dac4d699cdc25a1fc9d8d2eb2ea934bf)

```
ERRO[0028] Create request is failed. Error: etcdserver: request is too large 
2020/05/03 20:30:57 Failed to submit workflow: etcdserver: request is too large
```

After digging for a bit, I figured out that the above is a hard limit on etcd and that it is possible to persist workflow status using postgresql/mysql, which I have enabled applying the [linked configmap/controller .yaml config](https://gist.github.com/bolthar/d1dfd42d1eb3c23fa10cd7890bc20f7d) (redacted the host out, except for that it's identical to what I have applied on my cluster)

It seems that what's persisted is the workflow status, and not the workflow definition itself: that is still on etcd and if it is larger that 1Mb compressed (and mine is) it still fails.

**What you expected to happen**:

I would expect argo not to use etcd at all when persistence is enabled 

**How to reproduce it (as minimally and precisely as possible)**:

You can try and start the linked workflow definition against a persistence enabled controller

--

I would be very happy to delve in and implement this myself, if this is really not implemented and I'm just not missing something - please let me know, and thanks in the meantime for the great tool you provide :)

- Argo version:
```
argo: v2.7.5
  BuildDate: 2020-04-21T00:55:01Z
  GitCommit: ede163e1af83cfce29b519038be8127664421329
  GitTreeState: clean
  GitTag: v2.7.5
  GoVersion: go1.13
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-04-08T17:11:31Z"
  compiler: gc
  gitCommit: b7394102d6ef778017f2ca4046abbaa23b88c290
  gitTreeState: clean
  gitVersion: v1.14.1
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-02-21T18:09:01Z"
  compiler: gc
  gitCommit: 879c3621692a32b5d77a951ca0e61ee55aefc80f
  gitTreeState: clean
  gitVersion: v1.13.12-eks-879c36
  goVersion: go1.11.13
  major: "1"
  minor: 13+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
