### ISSUE TITLE
Argo server issue, breaking intermittently

### ISSUE THREAD

**Issue by chittu11** [argoproj/argo#2945]
Hi,
We deployed argo 2.6.2 and its working fine. But we have to run "argo server" command in the background in order to see the argo server UI. sometimes the background process is breaking and its causing issues with argo servers and we are unable to access the UI as well as our job submission is getting crippled. I  deployed argo server using the following instruction from official argo github:

https://github.com/argoproj/argo/tree/master/manifests/base/argo-server

Is there anyway I can have "argo server" service running continuously without initiating it manually through command line "argo server"?

  **argo: v2.6.2
  BuildDate: 2020-03-12T16:04:25Z
  GitCommit: be0a0bb46ba50ed4d48ab2fd74c81216d
  GitTreeState: clean
  GitTag: v2.6.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64**

Thank you and appreciate any help or inputs with this issue?

Regards,
CS

**Comment by simster7** [comment]
This would be hard to diagnose without any logs. Can you get logs for the Argo Server that cover when the server restarts? `kubectl logs deploy/argo-server`

**Comment by chittu11** [comment]
> This would be hard to diagnose without any logs. Can you get logs for the Argo Server that cover when the server restarts? `kubectl logs deploy/argo-server`

Thank you for the reply. I am looking something with in Argo to run the argo server service continuously instead of firing "argo server" command line? do we have any option from Argo side?

**Comment by simster7** [comment]
You're looking to host the server in [hosted mode](https://github.com/argoproj/argo/blob/master/docs/argo-server.md#hosted-mode).

In short, you need a deployment that essentially runs the `argo server` command in the cluster:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      serviceAccountName: argo-server
      containers:
        - name: argo-server
          image: argoproj/argocli:latest
          args: [server]
          ports:
            - name: web
              containerPort: 2746
          readinessProbe:
            httpGet:
              port: 2746
              scheme: HTTP
              path: /
            initialDelaySeconds: 10
            periodSeconds: 20
      nodeSelector:
        kubernetes.io/os: linux
```
