### ISSUE TITLE
Passing non-scalar workflow parameter value into a container

### ISSUE THREAD

**Issue by erhhung** [argoproj/argo#2989]
# Summary

I would like to pass an object, embedded directly in the workflow YAML, as a workflow parameter into my container as a JSON file using the artifact driver:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: param-test-
spec:
  entrypoint: param-test
  arguments:
    parameters:
    - name: object
      value:
        const: 42
        files:
        - hello.js
        - src: /src.txt
          dest: /dest.txt
  templates:
  - name: param-test
    inputs:
      artifacts:
      - name: param
        path: /param.json
        archive:
          none: {}
        raw:
          data: '{{workflow.parameters.object}}'
    container:
      image: alpine
      command:
      - sh
      - -c
      args:
      - |-
        echo -e "PARAM\n-----"
        cat /param.json
```

However, I don't see a way to **specify the serialization format of the artifact** that gets created.
In fact, here's the output of the workflow:

```
PARAM
-----
map[const:42 files:[hello.js map[dest:/dest.txt src:/src.txt]]]
```

The good news is that my parameter content does get written into a file in the container, but what serialization format is it by default? I don't recognize the `map[key:value]` construct.

# Motivation

I'm actually **using the REST API** to submit this workflow (as JSON request body) after **manually injecting the non-scalar workflow parameter** from another source. My use case complexity lies between passing simple strings or numbers (the only examples I can see) and passing file-based content via URL.
