### ISSUE TITLE
How to use YAML inputs with ARGO

### ISSUE THREAD

**Issue by engineerakki** [argoproj/argo#3005]
# Summary
I am just getting started with Argo and want to pass parameters to my workflow from a YAML file.(i.e inputs.yaml)

Here is my inputs.yaml:
```
- name: message
  value: HelloWorld
  required: True
```
What do you want to know about this project?

Here is my ArgoWorkFlow hello.yaml:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: whalesay

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

I am running following command to run my workflow 
`argo submit hello.yaml -f inputs.yaml`

But I am getting following error:
`
FATA[0000] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type map[string]json.RawMessage 
`

If I pass parameters in JSON format then it works as expected.
Does ARGO support YAML parameters?
If yes Am I doing something wrong ?
