### ISSUE TITLE
Running argo server with "namespaced"

### ISSUE THREAD

**Issue by chittu11** [argoproj/argo#3031]
HI Team,
We deployed argo server and it is working fine. Now we created custom kube config with defined roles and rolebinding rules. We have to fire argo server with "argo server --namespaced" to load the kubeconfig and to reflect the roles we enforced for kube config on argo server. I also deployed argo server service using the below instructions. it is also working fine for normal "argo server" when I launched "argo server" as root but how should I pass "argo server --namespaced" to load the custom configured kube configuration which essentially runs from user account as "argo server --namespace" currently we are running it through manual command. I like to run this as a service for all users who use the custom kube config, so how should I define "argo server --namespaced" in the below deployment yaml?

https://github.com/argoproj/argo/tree/master/manifests/base/argo-server

```
serviceAccountName: argo-server
      containers:
        - name: argo-server
          image: argoproj/argocli:latest
          args: [server]
```
```
argo: v2.6.2
BuildDate: 2020-03-12T16:04:25Z
GitCommit: be0a0bb
GitTreeState: clean
GitTag: v2.6.2
GoVersion: go1.13.4
Compiler: gc
Platform: linux/amd64
```
Kubernetes version:

```
Client Version: v1.18.2
Server Version: v1.17.1
```

Thanks,
Chittu
