### ISSUE TITLE
Collect dynamic number of metrics from artifact/output parameter

### ISSUE THREAD

**Issue by vanpeltj** [argoproj/argo#3042]
I use Argo Workflows to run batch jobs. Most of these batch jobs share a common docker image but each job has a different set of custom metrics. At first, I tested the custom metrics by writing an individual text file for each metric and then have a static definition of that metric in my template. And to be clear, this works as it should. However, it would be a lot easier if I could define it dynamically in a way that e.g. one file with a JSON array of metrics (name, labels, value) is transformed in a set of Prometheus metrics.

Cases I was (partially) able to implement:

1.  Define metrics one by and use an output parameter as the value for the metric as properly describe in the documentation (lots of work and maintenance for creating new metrics or updating old ones)
 ``` yaml
...
    templates:
    - name: clean-up-clean-layer-job
      metrics:
        prometheus:
          - name: testing_gauge       # Metric name (will be prepended with "argo_workflows_")
            help: "test metric"
            labels:                           # Labels are optional. Avoid cardinality explosion.
              - key: name
                value: model_a
            gauge:                            # The metric type. Available are "gauge", "histogram", and "counter".
              value: "{{outputs.parameters.first_test}}"
      inputs:
        parameters: [{name: job, value: cleanup-clean-layer}]
      outputs:
        parameters:
        - name: first_test
          valueFrom:
            default: "3"
            path: /home/output/metrics/test.txt
...
```
2.  Generate metric values with a script and populate the prometheus metrics dynamically in a individual step

``` yaml
...
 templates:
  - name: metric-collection-workflow
    steps:
    - - name: generate-values
        template: generate
    - - name: collect-metrics
        template: collect-metrics-template
        arguments:
          parameters:
          - name: metric
            value: "{{item}}"
        withParam: "{{steps.generate-artifact.outputs.result}}"
  - name: generate
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([{'name':i } for i in range(20, 22)], sys.stdout)
  - name: collect-metrics-template
    metrics:
      prometheus:
        - name: "sample_metric"    # Metric name (will be prepended with "argo_workflows_")
          help: "test metric"
          gauge:                            # The metric type. Available are "gauge", "histogram", and "counter".
            value: "{{inputs.parameters.metric}}"
    inputs:
      parameters:
      - name: metric
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo metric value is {{inputs.parameters.metric}} seconds; echo done"]
...
```
The problem with this approach, is first of all that it creates a sepearte step and thus needs resources. More importantly, the input parameter is a single value and not a list of parameters like 'metric_name', 'metric_value', 'metric_type', 'metric_labels'... and on top of that it seems that dynamic metric names are also not allowed: _
> "Metric names must contain alphanumeric characters, '_', or ':'"
_
So this means, that all the steps update the same metric which is of course not what I try to achieve.

I am still quite new to Argo so I am not always aware of the possibilities so the main question is whether this dynamic declaration of custom metrics is possible and if yes, how?

Thanks in advance for your help
