### ISSUE TITLE
argo executor doesn't untar artifacts before mounting volumes

### ISSUE THREAD

**Issue by julienvey** [argoproj/argo#3043]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

We are using argo v2.7.3. Since this morning, all our workflows that use artifacts started to fail. 
Our symptom was this error 
```
OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/c64c85b8-9681-11ea-be06-0ec02ce6625e/volume-subpaths/input-artifacts/main/2\\\" to rootfs \\\"/var/lib/docker/overlay2/83403941a672bd1fb62f9947224891d26cd136e477a21594e0943752cc1c8082/merged\\\" at \\\"/var/lib/docker/overlay2/83403941a672bd1fb62f9947224891d26cd136e477a21594e0943752cc1c8082/merged/workdir\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
After some investigation, we discovered that our artifact (initially a folder, which was tar and sent to S3) was not untar before being mounted in our container.

We also discovered that we were using `argoproj/argoexec:latest` instead of a fixed version, this is why it suddenly started to fail without any explanation.

Problem seems related to this commit https://github.com/argoproj/argo/commit/a1ac8bcf548c4f8fcff6b7df25aa61ad9e4c15ed

**What you expected to happen**:

artifact should be correctly untar before being mounted on the pod

**How to reproduce it (as minimally and precisely as possible)**:

We were able so simply reproduce with this workflow

```yaml
# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  serviceAccountName: argo-workflow
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["ls -alh /tmp; cd /tmp; tar -xvf message; ls -alh; cat hello_world.txt;"]
```
the `tar -xvf message;` at the end should not be necessary

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
workflow-controller: 2.7.3
argo-server: 2.7.3
argoexec: latest
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-12-16T04:39:52Z
  compiler: gc
  gitCommit: b1d75deca493a24a2f87eb1efde1a569e52fc8d9
  gitTreeState: clean
  gitVersion: v1.11.6
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2019-02-28T18:40:05Z
  compiler: gc
  gitCommit: 4e209c9383fa00631d124c8adcc011d617339b3c
  gitTreeState: clean
  gitVersion: v1.11.8
  goVersion: go1.10.8
  major: "1"
  minor: "11"
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
