### ISSUE TITLE
Annotations assigned to a template are not applied to a pod

### ISSUE THREAD

**Issue by samirmajen** [argoproj/argo#3044]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Defining annotations in a workflowTemplate are not applied to a pod, however applying them to a workflow which inherits the template works fine.

**What you expected to happen**:

Annotation applied at a workflowtemplate level should be applied when using a template

**How to reproduce it (as minimally and precisely as possible)**:
Doesnt work:

`apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-template
spec:
  entrypoint: my-template
  templates:
  - name: my-template
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"`

`metadata:
  generateName: my-template-
spec:
  entrypoint: use-template
  templates:
    - name: use-template
      templateRef:
        name: my-template
        template: my-template`

Works:

metadata:
  generateName: my-template-
spec:
  entrypoint: use-template
  templates:
    - name: use-template
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      templateRef:
        name: my-template
        template: my-template

**Anything else we need to know?**:

**Environment**:

- Argo version: v2.7.4
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:

- workflow result:

```
argo --loglevel DEBUG get <workflowname>
```

- executor logs:

```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```

- workflow-controller logs:

```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
I couldn't reproduce this issue on my env with the below example.  can you try it with the latest release?

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
      - - name: call-whalesay-template
          templateRef:
            name: workflow-template-whalesay-template
            template: whalesay-template
          arguments:
            parameters:
            - name: message
              value: "hello world"
```

**Comment by samirmajen** [comment]
Hi sarabala1979, the issue is when you have a template that has an annotation which is then used by another workflow that references the template. If I use the template directly the annotation is applied, if i reference the template from another workflow, the annotation is not applied

**Comment by alexec** [comment]
@samirmajen sorry this has been dropped - we're pretty busy at the moment - could I please ask you to attach manifests which exhibit this behaivour?

**Comment by ozooxo** [comment]
@samirmajen If you put the label in `metadata` in `WorkflowTemplate`, but if you put it in `spec.template.metadata` then it will.

```
metadata:
  name: foobar
  labels:
    abc: def
spec:
  templates:
      metadata:
        labels:
          hij: klm
```

Then 

```
$ kubectl -describe pod foo-bar-xxxxx
Name:               foo-bar-xxxxx
...
Labels:             hij=klm
                    workflows.argoproj.io/completed=true
                    workflows.argoproj.io/workflow=foo-bar-xxxxx
Annotations:        kubernetes.io/psp: eks.privileged
                    workflows.argoproj.io/node-name: foo-bar-xxxxx
                    workflows.argoproj.io/outputs: {"exitCode":"0"}
                    workflows.argoproj.io/template:
                      {"name":"foo-bar","arguments":{},"inputs":{},"outputs":{},"metadata":{"labels":{"hij":"klm"}},"container":{"name":"","image":"busybox:...
```
