### ISSUE TITLE
Reduce node status bloat

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3051]
# Summary

We can create massive nodes:

```
    archive-strategies-157438702:
      id: archive-strategies-157438702
      name: archive-strategies.generate-default
      displayName: generate-default
      type: Pod
      templateName: generate-default
      templateScope: local/archive-strategies
      phase: Succeeded
      boundaryID: archive-strategies
      startedAt: '2020-05-18T17:19:46Z'
      finishedAt: '2020-05-18T17:19:49Z'
      resourcesDuration:
        cpu: 2
        memory: 1
      outputs:
        artifacts:
          - name: file
            path: /tmp/file
            s3:
              endpoint: 'minio:9000'
              bucket: my-bucket
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: archive-strategies/archive-strategies-157438702/file.tgz
          - name: main-logs
            archiveLogs: true
            s3:
              endpoint: 'minio:9000'
              bucket: my-bucket
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
              key: archive-strategies/archive-strategies-157438702/main.log
```

# Motivation

Run workflows faster.

# Proposal

TBD

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
