### ISSUE TITLE
CPU and memory request values from workflow parameters

### ISSUE THREAD

**Issue by theStrayPointer** [argoproj/argo#3058]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Unable to set CPU and memory request values from workflow parameters. Error on submit:
```
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

**What you expected to happen**:

Successful submit

**How to reproduce it (as minimally and precisely as possible)**:

Run
```bash
argo submit
```

With this workflow:
```yaml
metadata:
  name: lovely-tiger
  namespace: default
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: memory
        value: 1Gi
      - name: cpu
        value: 2
  templates:
    - name: whalesay
      container:
        name: main
        image: 'docker/whalesay:latest'
        command:
          - cowsay
        args:
          - hello world
        resources:
          requests:
            memory: "{{workflow.parameters.memory}}"
            cpu: "{{workflow.parameters.cpus}}"
```

**Anything else we need to know?**:

I unsuccessfully tried this too:
```yaml
 memory: "'{{workflow.parameters.memory}}'"
 cpu: "'{{workflow.parameters.cpus}}'"
```
Edit: I'd like to add that we're using the Go client to submit the workflows, so the parameter values are being set programmatically.

**Environment**:

- Argo version:
```
v2.8.0-rc2+4126d22.dirty
```
- Kubernetes version :
```
v1.18.1
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by salanki** [comment]
All argo parameters are strings, while CPU and GPUs are expected to be Numbers.

Passing the resources as parameters can be achieved with a `podSpecPatch`
```
  - name: tf14-resnet50-bench
    inputs:
      parameters:
        - name: value
    retryStrategy:
      limit: 1
    script:
      image: cemizm/tf-benchmark-gpu
      command: [bash]
      source: |
        ./benchmark.sh --model resnet50 --num_gpus={{inputs.parameters.gpus}}

      tty: true
      resources:
        requests:
          memory: 8Gi
          cpu: 2 # 2 Cores

    podSpecPatch: '{"containers":[{"name":"main", "resources":{"limits":{"nvidia.com/gpu": "{{inputs.parameters.gpus}}" }}}]}'
```

**Comment by sarabala1979** [comment]
https://github.com/argoproj/argo/blob/master/examples/pod-spec-from-previous-step.yaml
https://github.com/argoproj/argo/blob/master/examples/pod-spec-patch.yaml
https://github.com/argoproj/argo/blob/master/examples/pod-spec-yaml-patch.yaml

**Comment by theStrayPointer** [comment]
Using `podSpecPatch` worked flawlessly. Thank you.
Quick note: I think for workflows with `dag`, you have to define the `podSpecPatch` in the template implementation (along with `script` and `image` ...).

**Comment by paravatha** [comment]
@sarabala1979 @alexec 
is this fixed in argo 9.2.x versions? or we should use as below?
`    podSpecPatch: '{"containers":[{"name":"main", "resources":{"limits":{"cpu": "{{workflow.parameters.cpu-limit}}" }}}]}'
`

**Comment by sarabala1979** [comment]
@paravatha  This feature is available from 2.4.x +.

**Comment by paravatha** [comment]
@sarabala1979 , I mean like this? without using podSpec
```
container:
  - name: app
    image: images.my-company.example/app:v4
    env:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```
