### ISSUE TITLE
Question: how do we setup argo server using "hybrid" mode?

### ISSUE THREAD

**Issue by cy-zheng** [argoproj/argo#3062]
# Summary

How do we setup argo server using "hybrid" mode?
I find some guide below in one of README:
`"hybrid" - use the client token if provided, fallback to the server token if note.`
So how do we setup server token here? I can not find any guide about that.

# Motivation

I want to set up argo server with basic authentication and authorization:

- If user don't set token in his request, argo server will use read only token. 
- If user send request with authorization header, then argo server should use token they provided.

**Comment by cy-zheng** [comment]
Should argo service fallback to use k8s service account? I've set service account in argo server deployment, but it seems that argo server doesn't use the service account.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server-readonly
  namespace: argo
spec:
  selector:
    matchLabels:
      app: argo-server-readonly
  template:
    metadata:
      labels:
        app: argo-server-readonly
    spec:
      containers:
        - args:
            - server
            - --auth-mode=hybrid
          image: argoproj/argocli:v2.8.0
          name: argo-server-readonly
          ports:
            - containerPort: 2746
              name: web
          readinessProbe:
            httpGet:
              path: /
              port: 2746
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
      serviceAccountName: argo-server-readonly
```
