### ISSUE TITLE
Handle CSV rows in WithParam

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo#3072]
# Summary

The `WithParam` field currently supports only JSON and YAML. However, there're several needs in my team that they want to run a step for each rows in a CSV file.

# Motivation

We have CSV files which need to be parsed and run a step for each row.

# Proposal

Either of the following items are possible.

- `WithParam` automatically identify CSV format and parse it.
- Create another field like `WithCSV`.
- Add another field in `outputs` like `converter: csv` and pass converted json to `WithParam`

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dtaniwaki** [comment]
> - Add another field in outputs like converter: csv and pass converted json to WithParam

I think something like this idea can be useful because the same mechanism can be used for `inputs` as well. For example, consider the following template.

```
templates:
- name: foo
  inputs:
    artifacts:
    - name: params-json
       path: /tmp/params.json
       raw:
         data: "{{workflow.parameters}}"
```

The `params.json` file is written as json, but we can get it as YAML if we have `converter` as below.

```
templates:
- name: foo
  inputs:
    artifacts:
    - name: params-json
       path: /tmp/params.json
       raw:
         data: "{{workflow.parameters}}"
      converter:
        from: json
        to: yaml
```
