### ISSUE TITLE
running onExit handler in dag task even if condition isn't match

### ISSUE THREAD

**Issue by sh-tatsuno** [argoproj/argo#3081]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

If you set both "onExit" and "when" in dag task and a workflow does not satisfy the condition during running, dag task does not start but onExit handler starts runnig.

**What you expected to happen**:

The workflow should not run the onExit handler because main dag task has skipped.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-primay-branch-
spec:
  entrypoint: statis
  templates:
  - name: a
    container:
      image:  docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
    serviceAccountName: argo
  - name: exit
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["exit!"]
    serviceAccountName: argo
  - name: statis
    dag:
      failFast: false
      tasks:
      - name: A
        template: a
      - name: B
        onExit: exit
        dependencies: [A]
        template: a
        when: '{{tasks.A.status}} != Succeeded'
      - name: C
        dependencies: [A]
        template: a
```

**Anything else we need to know?**:

I expected that B.onExit should not run.

**Environment**:

- Argo version:

```
argo: v2.8.0
  BuildDate: 2020-05-11T22:55:43Z
  GitCommit: 8f696174746ed01b9bf1941ad03da62d312df641
  GitTreeState: clean
  GitTag: v2.8.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```

- Kubernetes version :

```
❯ kubectl version -o yaml
clientVersion:
  buildDate: "2019-12-07T21:20:10Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.4
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-04-06T16:33:17Z"
  compiler: gc
  gitCommit: 34a615f32e9a0c9e97cdb9f749adb392758349a6
  gitTreeState: clean
  gitVersion: v1.14.10-gke.36
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

The workflow result is below.

```
STEP                        TEMPLATE  PODNAME                             DURATION  MESSAGE
 ✔ dag-primay-branch-wvwj7  statis                                                                                                 
 ├-✔ A                      a         dag-primay-branch-wvwj7-142456446   3s                                                       
 ├-○ B                      a                                                       when 'Succeeded != Succeeded' evaluated false  
 ├-✔ C                      a         dag-primay-branch-wvwj7-108901208   4s                                                       
 └-✔ B.onExit               exit      dag-primay-branch-wvwj7-1879783180  3s    
```
