### ISSUE TITLE
archivedlog doesn't appear as output artifacts for failure node

### ISSUE THREAD

**Issue by lilida** [argoproj/argo#3105]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
When archiveLog enabled, if one node execution failed (for ex, app bug), its log was uploaded. However, the main-log was not listed as outputs artifacts in the status of the node.
Belo is an example of the node status
```
    downloadandprocess-kz2z6-2237584549:
      boundaryID: downloadandprocess-kz2z6
      displayName: preprocess
      finishedAt: "2020-05-25T18:24:31Z"
      id: downloadandprocess-kz2z6-2237584549
      inputs:
        artifacts:
        - gcs:
            bucket: testbucket
            key: pipeline-artifacts/downloadandprocess-kz2z6/downloadandprocess-kz2z6-4211634475/data.tgz
            serviceAccountKeySecret:
              key: ""
          name: preprocess_output_path
          path: /tmp/inputs/input_path/data
      message: failed with exit code 1
      name: downloadandprocess-kz2z6.preprocess
      phase: Failed
      startedAt: "2020-05-25T18:24:14Z"
      templateName: preprocess-template-preprocess
      type: Pod
```
**What you expected to happen**:
The main-log should be listed as output artifacts in the status of the node
```
outputs:
artifacts:  
  - archiveLogs: true
          gcs:
            bucket: kaistack-hypertensor
            key: pipeline-artifacts/downloadandprocess-kz2z6/downloadandprocess-kz2z6-2237584549/main.log
```
**How to reproduce it (as minimally and precisely as possible)**:
Enable log archive, execute a failure pod.

**Anything else we need to know?**:

**Environment**:

- Argo version: 2.7.1

- Kubernetes version : 1.14.7

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
