### ISSUE TITLE
argo get/watch should list parallel entries in order, not alphabetize

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#3145]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

When running any parallel workflow (`withParam`, `withSequence`, or `withItems`), the fanned out entries are displayed in alphabetical order of the step names. If there are 10 or fewer, this order matches the standard order, since the names are all prepended with digits. But if you go past 10, the alphabetical order and numerical order no longer agree: 10-19 come before 1, 20-29 come before 2, and so on.

**What you expected to happen**:

They should instead be ordered by the numbers in those step names. In addition to the aesthetic benefits, this would also make it a lot easier to see exactly how many parallel entries there are -- just look at the number of the last one (and add one).

**How to reproduce it (as minimally and precisely as possible)**:

Run any parallel workflow with fan out greater than 10. Here's an example:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: many-items-
spec:
  entrypoint: parallel-sleep
  templates:
  - name: parallel-sleep
    steps:
    - - name: sleep
        template: sleep
        withItems:
        - zero
        - one
        - two
        - three
        - four
        - five
        - six
        - seven
        - eight
        - nine
        - ten
        - eleven
        - twelve

  - name: sleep
    container:
      image: alpine:latest
      command: [sh, -c, sleep 10]
```

In `argo watch` or `argo get`, this is represented as follows:
```
STEP                     TEMPLATE        PODNAME                      DURATION  MESSAGE
 ✔ many-items-bp774      parallel-sleep
 └-·-✔ sleep(0:zero)     sleep           many-items-bp774-1191717986  18s
   ├-✔ sleep(10:ten)     sleep           many-items-bp774-1715531170  25s
   ├-✔ sleep(11:eleven)  sleep           many-items-bp774-2634080843  23s
   ├-✔ sleep(12:twelve)  sleep           many-items-bp774-153115818   24s
   ├-✔ sleep(1:one)      sleep           many-items-bp774-3071867483  20s
   ├-✔ sleep(2:two)      sleep           many-items-bp774-2507206310  18s
   ├-✔ sleep(3:three)    sleep           many-items-bp774-4054797277  25s
   ├-✔ sleep(4:four)     sleep           many-items-bp774-383720484   20s
   ├-✔ sleep(5:five)     sleep           many-items-bp774-3297451019  20s
   ├-✔ sleep(6:six)      sleep           many-items-bp774-1930420580  25s
   ├-✔ sleep(7:seven)    sleep           many-items-bp774-3209167226  20s
   ├-✔ sleep(8:eight)    sleep           many-items-bp774-1893091255  21s
   └-✔ sleep(9:nine)     sleep           many-items-bp774-243241999   25s
```
Just glancing at the bottom, you'd think that only 10 entries ran, but the last three are misordered.

This is on Argo v2.8.1.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
