### ISSUE TITLE
Realtime/live logs

### ISSUE THREAD

**Issue by hadim** [argoproj/argo#3169]
Is that possible to get live logs of a running pod? Consider the below workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: long-workflow-
spec:
  serviceAccountName: argo
  entrypoint: long-workflow

  templates:
  - name: long-workflow
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: flip-coin2
        template: flip-coin
      - name: flip-coin3
        template: flip-coin

  - name: flip-coin
    script:
      image: python:alpine3.7
      command: [python]
      source: |
        import time
        print("Start")
        for i in range(5):
          print(f"{i}: Flipping a coin !")
          time.sleep(2)
        print("Done")

```

When logging with `argo logs -f long-workflow-5rnj`, I see the logs of one pod when its execution end and not in real-time. I am wondering if this is a limitation of Argo/k8s or if I am missing something.

If this is a limitation what strategy would you suggest to get logs in real-time (without using an external service)?

I also tried logging using `kubectl` without success.

**Comment by hadim** [comment]
Using `sh` instead of python is working correctly:

```yaml
  - name: flip-coin-bash
    script:
      image: alpine:3.7
      command: [sh]
      source: |
        for i in $(seq 5);
        do
          echo Hello $i
          sleep 5s
        done
```

Why such a limitation using python + the print function?
