### ISSUE TITLE
Allow workflow to overwrite its template command and args

### ISSUE THREAD

**Issue by iMoses** [argoproj/argo#3191]
# Summary

AFAIK there's no way to use a WorkflowTemplate and have the Workflow override the `command` and/or `args` provided by the template. If I'm wrong then let's shit this discussion to providing docs :)

Seeing as templates using templates is deprecated I can think of no way to achieve this simple task of having the template provide only the defaults while the workflow is still allowed to provide container specs.

# Motivation

In order to simplify lots of workflows we developed a CLI to run each task.

Lets say I have a CLI app like this:
```
my-cli plugins my-plugin start --name --from=X --to=X --force
my-cli plugins my-plugin stop --name
my-cli plugins my-plugin status --all --none --any --some
my-cli plugins my-plugin version --minor --major --patch --up --down --set=X
```

and this template:

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cluster-workflow-cli-templates
spec:
  arguments:
    parameters:
      - name: command
        value: --help
  templates:
    - name: plugin-cli-template
      inputs:
        parameters:
          - name: commands
      container:
        image: plugin:latest
        args: [{{`"{{inputs.parameters.command}}"`}}]
        command: [my-cli plugins my-plugin]
```

This is nice if I didn't have a nested API or too many CLI args, but when it gets bloated I'm forced to create a different unique template for every command i have in my CLI and set the arguments accordingly, repeating the volumes and image data over and over which defeats the purpose of a tempalte.

Won't it be nice if a workflow could inherit from a template and override the `args` or even the `command` so that workflow will have more control over what's executed while still inheriting volumes, mounts, image and all the repeating data i'm glad i have a template for?

# Proposal

Allow using `templateRef` with `command` and/or `args` as overrides.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@dtaniwaki or @sarabala1979 do you want to own this please?

**Comment by sarabala1979** [comment]
yes, I will update the comments

**Comment by sarabala1979** [comment]
In v2.8
you can use step template to refer to the `Workflowtemplate` and pass the parameters
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
      - - name: call-whalesay-template
          templateRef:
            name: workflow-template-whalesay-template
            template: whalesay-template
          arguments:
            parameters:
            - name: message
              value: "hello world client"
```
WorkflowTemplate:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

Master : (It will be released in v2.9)
you can refer the `Workflow-template1` in as workflow spec using `WorkflowTemplateRef`. you pass the glopal parameters to `WorkflowTemplate`
Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: "hello world32"
  workflowTemplateRef:
    name: workflow-template-whalesay-template
```
WorkflowTemplate:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{workflow.parameters.message}}"]
```

**Comment by iMoses** [comment]
assuming i want to be able to pass multiple unknown cli args to the container's command from a workflow that uses a workflow-template, is that possible?

WorkflowTemplate:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-awscli-template
spec:
  entrypoint: awscli-template
  templates:
  - name: awscli-template
    inputs:
      parameters:
      - name: message
    container:
      image: awscli:latest
      command: [aws]
      args: ["{{workflow.parameters.message}}"]
```
and i want to use this single template to execute any workflow that has `aws` as the base command but with different args each time depending on the workflow itself (not the template). The above example will not work because args will only have a single `message` argument, i don't know of a way to dynamically add more when using a template.

**Comment by sarabala1979** [comment]
I tried below example with `awscli` somewhat it didn't work might `aws cli` parsing args might be different. But I tried with `Linux` it works.  try with your container and let me know

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-awscli-template
spec:
  entrypoint: awscli-template
  templates:
  - name: awscli-template
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ['{{workflow.parameters.cmd}}']
```

workflow
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-awscli-
spec:
  entrypoint: awscli-template
  arguments:
    parameters:
      - name: cmd
        value: "ls -lrth a*"
  workflowTemplateRef:
    name: workflow-template-awscli-template
```

you can pass dynamically args from cli also

```
argo submit wf.yaml -p cmd="ls -l b* "
```

**Comment by iMoses** [comment]
it can only work if your cli is accepting a single string arg which contains multiple instructions in it, such as `sh -c`. that's exactly my problem, it doesn't seem possible to get to pass multiple (a list of) args and this feature will help us greatly to organize our workflows.

**Comment by sarabala1979** [comment]
Thanks for your clarification. Here solution which will work for your scenario. 
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-awscli-template
spec:
  entrypoint: awscli-template
  templates:
  - name: awscli-template
    podSpecPatch: '{"containers":[{"name":"main", "args":[{{workflow.parameters.cmd}}]}]}'
    container:
      image: amazon/aws-cli:latest
      command: [aws]
      args: ["{{workflow.parameters.cmd}}"]
```

Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  arguments:
    parameters:
      - name: cmd
        value: '"s3", "ls", "help"'
  workflowTemplateRef:
    name: workflow-template-awscli-template
```
