### ISSUE TITLE
Operation cannot be fulfilled on resourcequotas "gke-resource-quotas": the object has been modified; please apply your changes to the latest version and try again

### ISSUE THREAD

**Issue by bryanlarsen** [argoproj/argo#3217]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Argo workflows failed with the error "Operation cannot be fulfilled on resourcequotas \"gke-resource-quotas\": the object has been modified; please apply your changes to the latest version and try again"

**What you expected to happen**:

Workflows complete.

**How to reproduce it (as minimally and precisely as possible)**:

Try and run two workflows simultaneously, each with a parallelism of > 300 or so.

Sample workflows attached.

**Anything else we need to know?**:

This seems to be a Kubernetes bug, but a workaround in Argo would be much more under our control as we're running in GKE.

https://github.com/kubernetes/kubernetes/issues/67761

**Environment**:

- Argo version: 2.8.1
- Kubernetes version: v1.14.10-gke.36

**Other debugging information (if applicable)**:

- workflow-controller logs:

`time="2020-06-11T18:14:20Z" level=info msg="node &NodeStatus{ID:loops-param-result-b-1634545795,Name:loops-param-result-b[1].sleep(322:2),DisplayName:sleep(322:2),Type:Pod,TemplateName:sleep-n-sec,TemplateRef:nil,Phase:Error,BoundaryID:loops-param-result-b,Message:,StartedAt:2020-06-11 18:14:20.364568768 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:&Inputs{Parameters:[]Parameter{Parameter{Name:seconds,Default:nil,Value:*2,ValueFrom:nil,GlobalName:,},},Artifacts:[]Artifact{},},Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:local/loops-param-result-b,ResourcesDuration:ResourcesDuration{},HostNodeName:,} message: Operation cannot be fulfilled on resourcequotas \"gke-resource-quotas\": the object has been modified; please apply your changes to the latest version and try again" namespace=argo workflow=loops-param-result-b`

- sample workflows that reproduce issue:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: loops-param-result-a
spec:
  entrypoint: loop-param-result-example
  serviceAccountName: argo
  templates:
  - name: loop-param-result-example
    parallelism: 300
    steps:
    - - name: generate
        template: gen-number-list
    # Iterate over the list of numbers generated by the generate step above
    - - name: sleep
        template: sleep-n-sec
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"

  # Generate a list of numbers in JSON format
  - name: gen-number-list
    script:
      image: alpine:latest
      command: [sh, -c]
      args:
        - echo "[$(for i in $(seq 100) ; do seq 0 9 | tr '\n' ','; done )10]"

  - name: sleep-n-sec
    inputs:
      parameters:
      - name: seconds
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo sleeping for {{inputs.parameters.seconds}} seconds; sleep {{inputs.parameters.seconds}}; echo done"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: loops-param-result-b
spec:
  entrypoint: loop-param-result-example
  serviceAccountName: argo
  templates:
  - name: loop-param-result-example
    parallelism: 300
    steps:
    - - name: generate
        template: gen-number-list
    # Iterate over the list of numbers generated by the generate step above
    - - name: sleep
        template: sleep-n-sec
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"

  # Generate a list of numbers in JSON format
  - name: gen-number-list
    script:
      image: alpine:latest
      command: [sh, -c]
      args:
        - echo "[$(for i in $(seq 100) ; do seq 0 9 | tr '\n' ','; done )10]"

  - name: sleep-n-sec
    inputs:
      parameters:
      - name: seconds
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo sleeping for {{inputs.parameters.seconds}} seconds; sleep {{inputs.parameters.seconds}}; echo done"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: loops-param-result-c
spec:
  entrypoint: loop-param-result-example
  serviceAccountName: argo
  templates:
  - name: loop-param-result-example
    parallelism: 300
    steps:
    - - name: generate
        template: gen-number-list
    # Iterate over the list of numbers generated by the generate step above
    - - name: sleep
        template: sleep-n-sec
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"

  # Generate a list of numbers in JSON format
  - name: gen-number-list
    script:
      image: alpine:latest
      command: [sh, -c]
      args:
        - echo "[$(for i in $(seq 100) ; do seq 0 9 | tr '\n' ','; done )10]"

  - name: sleep-n-sec
    inputs:
      parameters:
      - name: seconds
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo sleeping for {{inputs.parameters.seconds}} seconds; sleep {{inputs.parameters.seconds}}; echo done"]
```

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
