### ISSUE TITLE
Unable to use artifact passing using k8sapi or pns executor in OpenShift 3.11

### ISSUE THREAD

**Issue by soumochak83** [argoproj/argo#3252]
Platform details - OpenShift version: 3.11, Kubernetes version: v1.11.0 - running on IBM Cloud
Issue: Tried to run the artifact passing experiments from Argo using k8sapi or pns executor, it fails giving different error. We configured minio as S3 repository and trying to use that for artifact passing.

**Error when using k8sapi** - _"failed to save outputs: CopyFile() is not implemented in the k8sapi executor"_
**Error when using pns** - _"failed to save outputs: process namespace sharing is not enabled on pod"_

Minio S3 config in argo workflow controller configmap:
```
s3:
  bucket: my-bucket
  endpoint: argo-artifacts:9000
  insecure: true
  # accessKeySecret and secretKeySecret are secret selectors.
  # It references the k8s secret named 'argo-artifacts'
  # which was created during the minio helm install. The keys,
  # 'accesskey' and 'secretkey', inside that secret are where the
  # actual minio credentials are stored.
  accessKeySecret:
    name: argo-artifacts
    key: accesskey
  secretKeySecret:
    name: argo-artifacts
    key: secretkey
```
This is the artifact passing experiment being used:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
  namespace: argo
spec:
  entrypoint: artifact-example
  serviceAccountName: argo
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```
Please help to run this experiment on OpenShift with the mentioned configs.
