### ISSUE TITLE
Namespace-specific configurations

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#3255]
# Summary

Allow a way to set certain controller configurations to only act in certain namespaces.

# Motivation

A user may be running Argo on different namespaces with different requirements. The ability to specify different options per namespace would be helpful.

# Proposal

On the config map:

```yaml
data:
  namespaceConfig:
    - namespace: "argo"
      configMapRef: ...
```

The config maps would be then strategically merged.
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
