### ISSUE TITLE
1 min delay in showing steps in UI (exposed via Ingress)

### ISSUE THREAD

**Issue by psschwei** [argoproj/argo#3257]
Checklist:

 * [ ] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Ran a sample workflow (`whalesay`) through the UI, which has been exposed through an ingress. Initially, the UI shows this:

![image](https://user-images.githubusercontent.com/44698588/85088828-00db8100-b1af-11ea-89b9-efca6425b982.png)

Then, almost exactly 1 minute later (on the 5 runs I have timed, it has always been at 59.x seconds), the step details show up:

![image](https://user-images.githubusercontent.com/44698588/85088943-3da77800-b1af-11ea-8ffd-96ad1daa1295.png)

If the UI is accessed through via port-forwarding (i.e. `kubectl -n argo port-forward deployment/argo-server 2746:2746`), then there is no delay in the step details showing in the UI.

**What you expected to happen**:

The UI to behave consistently, whether exposed via ingress or port-forwarding.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a 1.15.12 Kubernetes cluster
2. Create `argo` namespace
3. Install argo into `argo` namespace and patch rolebindings:
```bash
NAMESPACE=argo
kubectl apply -n $NAMESPACE -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/namespace-install.yaml
kubectl patch configmap -n $NAMESPACE workflow-controller-configmap -p '{"data": {"containerRuntimeExecutor": "pns"}}'
kubectl patch rolebindings -n $NAMESPACE argo-binding -p '{"subjects": [{"name": "default", "kind": "ServiceAccount", "namespace": "'$NAMESPACE'"}, {"name": "argo", "kind": "ServiceAccount", "namespace": "'$NAMESPACE'"}]}' 
kubectl patch rolebindings -n $NAMESPACE argo-server-binding -p '{"subjects": [{"name": "default", "kind": "ServiceAccount", "namespace": "'$NAMESPACE'"}, {"name": "argo-server", "kind": "ServiceAccount", "namespace": "'$NAMESPACE'"}]}' 
```
4. Create an ingress:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argo
spec:
  rules:
  - host: <HOST>
    http:
      paths:
      - backend:
          serviceName: argo-server
          servicePort: 2746
        path: /
  tls:
  - hosts:
    - <HOST>
    secretName: <SECRET>
```
5. Access `<HOST>`, click "Submit New Workflow" button, and click "Submit" to run `whalesay` job
6. Wait for steps to show.

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
argo: v2.8.1
  BuildDate: 2020-05-28T23:39:46Z
  GitCommit: 0fff4b21c21c5ff5adbb5ff62c68e67edd95d6b8
  GitTreeState: clean
  GitTag: v2.8.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-05-06T05:17:59Z"
  compiler: gc
  gitCommit: e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725
  gitTreeState: clean
  gitVersion: v1.15.12
  goVersion: go1.12.17
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-05-08T15:08:35Z"
  compiler: gc
  gitCommit: ab8a13f032bccd858fa0232d64fcdd05671f57e6
  gitTreeState: clean
  gitVersion: v1.15.12+IKS
  goVersion: go1.12.17
  major: "1"
  minor: "15"
  platform: linux/amd64

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
