### ISSUE TITLE
WorklowTemplate OnExit didn't work on WorkflowTemplateRef 

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#3259]
**What happened**:
OnExit template is not found in `WorkflowTemplateRef`
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  onExit: exit-handler
  templates:
  - name: whalesay-template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["test"]
  - name: exit-handler
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["Welcome to Exit-handler"]
```

**What you expected to happen**:
OnExit template should be executed
