### ISSUE TITLE
Edit a failed WF, then retry, when WF succeed the status is ERROR

### ISSUE THREAD

**Issue by wpeng102** [argoproj/argo#3264]
1) I modify the `https://github.com/argoproj/argo/blob/master/examples/hello-world.yaml` example change the command to a nonexistent command  
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: false
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay_test]
      args: ["hello world"]
```

2) submit the above wf, it failed
```
# argo list
NAME                 STATUS   AGE   DURATION   PRIORITY
hello-world1-k77qh   Failed   9m    9m         0
```
3) I use `kubectl edit wf hello-world1-k77qh` to correct the command, then `argo retry hello-world1-k77qh ` to retry this wf
4) Finally, this wf retry finished, but got a Error final status
```
# argo logs hello-world1-k77qh 
hello-world1-k77qh:  _____________ 
hello-world1-k77qh: < hello world >
hello-world1-k77qh:  ------------- 
hello-world1-k77qh:     \
hello-world1-k77qh:      \
hello-world1-k77qh:       \     
hello-world1-k77qh:                     ##        .            
hello-world1-k77qh:               ## ## ##       ==            
hello-world1-k77qh:            ## ## ## ##      ===            
hello-world1-k77qh:        /""""""""""""""""___/ ===        
hello-world1-k77qh:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
hello-world1-k77qh:        \______ o          __/            
hello-world1-k77qh:         \    \        __/             
hello-world1-k77qh:           \____\______/   


# argo list
NAME                 STATUS   AGE   DURATION   PRIORITY
hello-world1-k77qh   Error    20m   20m        0
```

Why wf retry finished successfully but it shows  in Error status?
