### ISSUE TITLE
Workflow artifact minio access denied

### ISSUE THREAD

**Issue by DrissiReda** [argoproj/argo#3300]
Hello I'm trying to use an s3 artifact in my workflow, I'm using minio and I have "Failed to put file: Access Denied."

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sql-to-s3-
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: sql-to-s3
  templates:
  - name: sql-to-s3
    outputs:
      artifacts:
      - name: output-dump
        path: /pg_dump.txt
        s3:
          endpoint: s3.default:9000
          bucket: ch-backup
          insecure: true
          key: pg_dump_latest.txt
          accessKeySecret:
            name: minio-secret
            key: accessKey
          secretKeySecret:
            name: minio-secret
            key: secretKey
    container:
      image: postgres:11.7
      command: [ "/bin/sh", "-c", "export PGPASSWORD=$(DB_PWD); pg_dump -h sql.default -p 5432 -U $(DB_USERNAME) --column-inserts > /pg_dump.txt"]
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: sql-to-s3-db-secret
              key: username
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: sql-to-s3-db-secret
              key: password
```
Minio was deployed by itself, it's been working, I use the same secret elsewhere and it works.
Should I add some kind of special permissions for the minio stateful set? or to the argo service account?  

<details>
<summary>logs</summary>

```bash

time="2020-06-25T11:32:06Z" level=info msg="Waiting on main container"
time="2020-06-25T11:32:07Z" level=info msg="main container started with container ID: ef70f06d309e46440f4a2d06b7a3b9c0e5212905aa6a39662fc09266495c4d99"
time="2020-06-25T11:32:07Z" level=info msg="Starting annotations monitor"
time="2020-06-25T11:32:07Z" level=info msg="docker wait ef70f06d309e46440f4a2d06b7a3b9c0e5212905aa6a39662fc09266495c4d99"
time="2020-06-25T11:32:07Z" level=info msg="Starting deadline monitor"
time="2020-06-25T11:32:07Z" level=info msg="Main container completed"
time="2020-06-25T11:32:07Z" level=info msg="No output parameters"
time="2020-06-25T11:32:07Z" level=info msg="Saving output artifacts"
time="2020-06-25T11:32:07Z" level=info msg="Staging artifact: output-dump"
time="2020-06-25T11:32:07Z" level=info msg="Copying /pg_dump.txt from container base image layer to /tmp/argo/outputs/artifacts/output-dump.tgz"
time="2020-06-25T11:32:07Z" level=info msg="Annotations monitor stopped"
time="2020-06-25T11:32:07Z" level=info msg="Archiving ef70f06d309e46440f4a2d06b7a3b9c0e5212905aa6a39662fc09266495c4d99:/pg_dump.txt to /tmp/argo/outputs/artifacts/output-dump.tgz"
time="2020-06-25T11:32:07Z" level=info msg="sh -c docker cp -a ef70f06d309e46440f4a2d06b7a3b9c0e5212905aa6a39662fc09266495c4d99:/pg_dump.txt - | gzip > /tmp/argo/outputs/artifacts/output-dump.tgz"
time="2020-06-25T11:32:07Z" level=info msg="Archiving completed"
time="2020-06-25T11:32:07Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/output-dump.tgz, key: pg_dump_latest.txt"
time="2020-06-25T11:32:07Z" level=info msg="Creating minio client s3.default:9000 using static credentials"
time="2020-06-25T11:32:07Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/output-dump.tgz to s3 (endpoint: s3.default:9000, bucket: ch-backup, key: pg_dump_latest.txt)"
time="2020-06-25T11:32:08Z" level=warning msg="Failed to put file: Access Denied."
time="2020-06-25T11:32:08Z" level=info msg="Deadline monitor stopped"
time="2020-06-25T11:32:10Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/output-dump.tgz, key: pg_dump_latest.txt"
time="2020-06-25T11:32:10Z" level=info msg="Creating minio client s3.default:9000 using static credentials"
time="2020-06-25T11:32:10Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/output-dump.tgz to s3 (endpoint: s3.default:9000, bucket: ch-backup, key: pg_dump_latest.txt)"
time="2020-06-25T11:32:10Z" level=warning msg="Failed to put file: Access Denied."
```

</details>
