### ISSUE TITLE
How can I access workflow parameters inside Go template block

### ISSUE THREAD

**Issue by ramanNarasimhan77** [argoproj/argo#3319]
# Summary

How can I use workflow parameters inside a go template block

# Motivation
Recently I worked on integrating Hashicorp vault with my workflow.  
Vault allows me to write Go Templates for doing some transformations before writing the secret to file.

So, consider below snippet, here I am trying to use vault-gitcreds-secret inside a go template. This does not work and “{{workflow.parameters.vault-gitcreds-secret}}” is not getting replaced.

Everything works fine when I hardcode values in the workflow 

How can I write the snippet such that argo understands that “{{workflow.parameters.vault-gitcreds-secret}}” should be replaced?

```
metadata:
      annotations:
            vault.hashicorp.com/agent-inject-template-.git-credentials: |
               {{- with secret “{{workflow.parameters.vault-gitcreds-secret}}” -}}
                    {{ .Data.data.gitcreds }}
              {{- end }}
```

P.S - Posted the same question on slack : https://argoproj.slack.com/archives/C8J6SGN12/p1593174809419900

**Comment by simster7** [comment]
Argo does not do parameter replacement in annotations. Would this be the issue? Not too familiar with this use case.

**Comment by ramanNarasimhan77** [comment]
> Argo does not do parameter replacement in annotations. Would this be the issue? Not too familiar with this use case.

@simster7 
In below annotations snippet, vault.hashicorp.com/agent-inject-secret-.git-credentials gets replaced correctly. The issue is only with the vault.hashicorp.com/agent-inject-template-.git-credentials section

```
- name: get-source-code-https
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-.git-credentials: "{{workflow.parameters.vault-gitcreds-secret}}"
        vault.hashicorp.com/agent-inject-template-.git-credentials: |
          {{- with secret "{{workflow.parameters.vault-gitcreds-secret}}" -}}
            {{ .Data.data.gitcreds }}
          {{- end }}
```

**Comment by simster7** [comment]
I see. What is the Kind of `get-source-code-https` is it a Workflow? It's not clear where this snippet is from relative to the workflow as a whole

**Comment by ramanNarasimhan77** [comment]
> I see. What is the Kind of `get-source-code-https` is it a Workflow? It's not clear where this snippet is from relative to the workflow as a whole

@simster7 
I have a workflow with 3 steps - clone the git repo, set some output parameters and then do a kaniko build
get-source-code-https is a template

```
  - name: workflow
    steps:
    - - name: get-source
        template: get-source-code-https
    - - name: get-params-for-build
        template: get-build-params
    - - name: build-push-image
        template: build-and-push
        arguments:
          parameters:
          - name: model_id
            value: "{{steps.get-params-for-build.outputs.parameters.model_id}}"
          - name: model_version
            value: "{{steps.get-params-for-build.outputs.parameters.model_version}}"
          - name: project_name
            value: "{{steps.get-params-for-build.outputs.parameters.project_name}}"
          - name: current_time
            value: "{{steps.get-params-for-build.outputs.parameters.current_time}}"
```


Pasted the definition of `get-source-code-https` template below
Since I want to get git-credentials from vault, I am using this approach where I mount the git-credentials file into the Pod and enable git credential store so that git clone gets the credentials from the credentials file (as opposed to the git input artifact approach from the examples) 

```
  - name: get-source-code-https
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-.git-credentials: "{{workflow.parameters.vault-gitcreds-secret}}"
        vault.hashicorp.com/secret-volume-path: "/home/appuser"
        vault.hashicorp.com/role: "{{workflow.parameters.vault-auth-role}}"
        vault.hashicorp.com/agent-inject-template-.git-credentials: |
          {{- with secret "{{workflow.parameters.vault-gitcreds-secret}}" -}}
            {{ .Data.data.gitcreds }}
          {{- end }}
    securityContext:
      runAsUser : 1000
      fsGroup: 1000
    container:
      image: my-custom-alpine:latest
      command: [sh, -c]
      args:
        - ls -ld /workspace;
          whoami;
          mkdir -p /workspace/modelcode && cd /workspace;
          git config --global credential.helper store;
          git clone "{{workflow.parameters.git-repo-url}}" modelcode;
          cd modelcode;
          git checkout "{{workflow.parameters.git-revision}}";
          echo '\n\nlisting workspace\n';
          ls /workspace/modelcode
      volumeMounts:
      - name: workspace
        mountPath: /workspace
```
