### ISSUE TITLE
Labels for [cluster] workflows templates

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3325]
# Summary

The only way to label a workflow created from a template is at the point of submission.

# Motivation

Make it easier to search for workflows created from templates.

# Proposal

Same as cron workflows:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-tmpl
spec:
  workflowMetadata:
    labels:
      foo: bar
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
