### ISSUE TITLE
How does Argo support long running workload

### ISSUE THREAD

**Issue by wpeng102** [argoproj/argo#3334]
Something like I define first step start a nginx pod. The following workflow will stuck in the first step. I want to know if Argo has some way to support long running workload?
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: nginx
    - - name: hello2a
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello2a"}]
      - name: hello2b
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello2b"}]

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

  - name: nginx
    container:
      image: nginx:1.7.9
      ports:
        - containerPort: 80
```
