### ISSUE TITLE
volumes in WorkflowTemplates are not carried over to Workflows

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo#3341]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

This Workflow suceeds, and writes a file test.txt to the host:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: voltest-
  namespace: default
spec:
  entrypoint: test-vols
  volumes:
    - name: nac-volume
      hostPath:
        path: /c/testdir
        type: DirectoryOrCreate

  templates:
    - name: test-vols
      container:
        image: ubuntu
        volumeMounts:
          - name: nac-volume
            mountPath: /data
        command: [sh, -c]
        args: ["echo test > /data/test.txt"]
```

However, if you convert it to a WorkflowTemplate and submit a Workflow based on it, then it fails with 
`volume 'nac-volume' not found in workflow spec`

Here's the WorkflowTemplate version:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: voltesttmpl
  generateName: voltest-
  namespace: default
spec:
  entrypoint: test-vols
  volumes:
    - name: nac-volume
      hostPath:
        path: /c/testdir
        type: DirectoryOrCreate

  templates:
    - name: test-vols
      container:
        image: ubuntu
        volumeMounts:
          - name: nac-volume
            mountPath: /data
        command: [sh, -c]
        args: ["echo test > /data/test.txt"]
```

**What you expected to happen**:

I expected the `volumes` to be carried over to the Template from the WorkflowTemplate.

**How to reproduce it (as minimally and precisely as possible)**:

See "what happened" above.

**Environment**:

- Argo version:
```
$ argo version
argo: v2.9.0-rc4
  BuildDate: 2020-06-26T21:54:40Z
  GitCommit: 5b109bcb9257653ecbae46e6315c8d65842de58a
  GitTreeState: clean
  GitTag: v2.9.0-rc4
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-11-13T11:23:11Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.12
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-01-15T08:18:29Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: clean
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.5
  major: "1"
  minor: 16+
  platform: linux/amd64
```

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
