### ISSUE TITLE
Unable to use workflowTemplateRef with defaults workflow serviceAccountName

### ISSUE THREAD

**Issue by stefansedich** [argoproj/argo#3355]
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Ever since the validation changes were introduced in https://github.com/argoproj/argo/pull/2912 we are unable to submit a workflow using a `workflowTemplateRef` when there is an `serviceAccountName` defined in workflow defaults, given the following defaults:

```
workflowDefaults:
  serviceAccountName: argo-workflow
```

When submitting the following workflow:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: foo-fw4vp
  namespace: models
spec:
  arguments:
    parameters:
  serviceAccountName: argo-workflow
  workflowTemplateRef:
    name: foo
```

 it raises the following error:

```ServiceAccountName is invalid field in spec if workflow referred WorkflowTemplate reference```

**What you expected to happen**:

That this will work as it did prior to these changes.

**How to reproduce it (as minimally and precisely as possible)**:

Configure argo with the workflow defaults configmap defining a default `serviceAccountName` and submit a workflow using a `workflowTemplateRef`.

**Environment**:

- Argo version: `2.9.0-RC4`
- Kubernetes version : `1.15`

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
