### ISSUE TITLE
Getting "does not exist in archive" error when tying to store file in S3 output archive

### ISSUE THREAD

**Issue by afritzler** [argoproj/argo#3388]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Not sure if this a bug or my stupidity :-)

I am trying to run this sample workflow which should zip up and write a file into my minio setup within the same cluster

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: minio-test
  namespace: argo
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
        s3:
          endpoint: minio-1593869186.default:9000
          bucket: my-bucket
          insecure: true
          key: /my-output-artifact.tgz
          accessKeySecret:
            name: minio-creds
            key: accessKey
          secretKeySecret:
            name: minio-creds
            key: secretKey

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
        s3:
          endpoint: minio-1593869186.default:9000 
          bucket: my-bucket
          insecure: true
          accessKeySecret:
            name: minio-creds
            key: accessKey
          secretKeySecret:
            name: minio-creds
            key: secretKey
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```

Unfortunatelly the workflow fails with this error in the `wait` container:

```
time="2020-07-05T14:43:30.801Z" level=fatal msg="path /tmp/hello_world.txt does not exist in archive /tmp/argo/outputs/artifacts/hello-art.tgz\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/errors.Errorf\n\t/go/src/github.com/argoproj/argo/errors/errors.go:55\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).CopyFile\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:82\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).stageArchiveFile\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:380\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).saveArtifact\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:265\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveArtifacts\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:251\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:71\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"
```

Not sure if am missing something. I tried to alter the file name, key name etc. without any luck.

**What you expected to happen**:

The file `/tmp/hello_world.txt` is tarballed and stored inside my bucket.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup minio in your cluster
2. `kubectl apply -f ABOVE_WORKFLOW

**Anything else we need to know?**:

Not really.

**Environment**:

The setup is based on Minikube (1.18.3), with Argo 2.9.1 and minio deployed inside minikube.

- Argo version:
```
argo: v2.8.0
  BuildDate: 2020-05-11T22:55:16Z
  GitCommit: 8f696174746ed01b9bf1941ad03da62d312df641
  GitTreeState: clean
  GitTag: v2.8.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-06-26T03:47:41Z"
  compiler: gc
  gitCommit: e6503f8d8f769ace2f338794c914a96fc335df0f
  gitTreeState: clean
  gitVersion: v1.18.5
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-05-20T12:43:34Z"
  compiler: gc
  gitCommit: 2e7996e3e2712684bc73f0dec0200d64eec7fe40
  gitTreeState: clean
  gitVersion: v1.18.3
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow result:

```
DEBU[0000] CLI version                                   version="{v2.8.0 2020-05-11T22:55:16Z 8f696174746ed01b9bf1941ad03da62d312df641 v2.8.0 clean go1.13.4 gc linux/amd64}"
DEBU[0000] Client options                                opts="{{ false false} 0x15746d0 0xc0004899f0}"
Name:                minio-test
Namespace:           argo
ServiceAccount:      default
Status:              Failed
Message:             child 'minio-test-3293111538' failed
Conditions:          
 Completed           True
Created:             Sun Jul 05 16:43:28 +0200 (10 minutes ago)
Started:             Sun Jul 05 16:43:28 +0200 (10 minutes ago)
Finished:            Sun Jul 05 16:43:34 +0200 (10 minutes ago)
Duration:            6 seconds
ResourcesDuration:   0s*cpu,0s*memory

STEP                      TEMPLATE          PODNAME                DURATION  MESSAGE
 ✖ minio-test             artifact-example                                   child 'minio-test-3293111538' failed                                       
 └---⚠ generate-artifact  whalesay          minio-test-3293111538  4s        failed to save outputs: Failed to establish pod watch: unknown (get pods)  

```

- executor logs:

```
time="2020-07-05T14:43:30.693Z" level=info msg="Starting Workflow Executor" version=v2.9.1
time="2020-07-05T14:43:30.699Z" level=info msg="Creating a docker executor"
time="2020-07-05T14:43:30.699Z" level=info msg="Executor (version: v2.9.1, build_date: 2020-07-03T15:18:16Z) initialized (pod: argo/minio-test-3293111538) with template:\n{\"name\":\"whalesay\",\"arguments\":{},\"inputs\":{},\"outputs\":{\"artifacts\":[{\"name\":\"hello-art\",\"path\":\"/tmp/hello_world.txt\",\"s3\":{\"endpoint\":\"minio-1593869186.default:9000\",\"bucket\":\"my-bucket\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"minio-creds\",\"key\":\"accessKey\"},\"secretKeySecret\":{\"name\":\"minio-creds\",\"key\":\"secretKey\"},\"key\":\"/my-output-artifact.tgz\"}}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"docker/whalesay:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"cowsay hello world | tee /tmp/hello_world.txt\"],\"resources\":{}}}"
time="2020-07-05T14:43:30.699Z" level=info msg="Waiting on main container"
time="2020-07-05T14:43:30.705Z" level=error msg="executor error: Failed to establish pod watch: unknown (get pods)\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapErrorf\n\t/go/src/github.com/argoproj/argo/errors/errors.go:78\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).waitMainContainerStart\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:937\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).Wait\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:901\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:40\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"
time="2020-07-05T14:43:30.705Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2020-07-05T14:43:30.705Z" level=info msg="Capturing script exit code"
time="2020-07-05T14:43:30.754Z" level=warning msg="Was not able to parse exit code output '' as int: strconv.Atoi: parsing \"\": invalid syntax"
time="2020-07-05T14:43:30.754Z" level=info msg="No output parameters"
time="2020-07-05T14:43:30.754Z" level=info msg="Saving output artifacts"
time="2020-07-05T14:43:30.756Z" level=info msg="Staging artifact: hello-art"
time="2020-07-05T14:43:30.756Z" level=info msg="Copying /tmp/hello_world.txt from container base image layer to /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2020-07-05T14:43:30.756Z" level=info msg="Archiving :/tmp/hello_world.txt to /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2020-07-05T14:43:30.756Z" level=info msg="sh -c docker cp -a :/tmp/hello_world.txt - | gzip  > /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2020-07-05T14:43:30.795Z" level=warning msg="path /tmp/hello_world.txt does not exist in archive /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2020-07-05T14:43:30.796Z" level=error msg="executor error: path /tmp/hello_world.txt does not exist in archive /tmp/argo/outputs/artifacts/hello-art.tgz\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/errors.Errorf\n\t/go/src/github.com/argoproj/argo/errors/errors.go:55\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).CopyFile\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:82\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).stageArchiveFile\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:380\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).saveArtifact\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:265\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveArtifacts\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:251\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:71\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"
time="2020-07-05T14:43:30.796Z" level=info msg="Killing sidecars"
time="2020-07-05T14:43:30.799Z" level=info msg="Alloc=6316 TotalAlloc=15207 Sys=70336 NumGC=4 Goroutines=6"
time="2020-07-05T14:43:30.801Z" level=fatal msg="path /tmp/hello_world.txt does not exist in archive /tmp/argo/outputs/artifacts/hello-art.tgz\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/errors.Errorf\n\t/go/src/github.com/argoproj/argo/errors/errors.go:55\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).CopyFile\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:82\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).stageArchiveFile\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:380\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).saveArtifact\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:265\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveArtifacts\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:251\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:71\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"

```

- workflow-controller logs:

```
time="2020-07-05T14:43:28Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Steps node minio-test initialized Running" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="StepGroup node minio-test-1935382032 initialized Running" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Pod node minio-test-3293111538 initialized Pending" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Created pod: minio-test[0].generate-artifact (minio-test-3293111538)" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Workflow step group node minio-test-1935382032 not yet completed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=23169 workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Processing workflow" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Workflow step group node minio-test-1935382032 not yet completed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=23172 workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Processing workflow" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Updating node minio-test-3293111538 message: ContainerCreating"
time="2020-07-05T14:43:28Z" level=info msg="Workflow step group node minio-test-1935382032 not yet completed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=23173 workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Processing workflow" namespace=argo workflow=minio-test
time="2020-07-05T14:43:28Z" level=info msg="Workflow step group node minio-test-1935382032 not yet completed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:29Z" level=info msg="Processing workflow" namespace=argo workflow=minio-test
time="2020-07-05T14:43:29Z" level=info msg="Workflow step group node minio-test-1935382032 not yet completed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:33Z" level=info msg="Processing workflow" namespace=argo workflow=minio-test
time="2020-07-05T14:43:33Z" level=info msg="Updating node minio-test-3293111538 status Pending -> Running"
time="2020-07-05T14:43:33Z" level=info msg="Workflow step group node minio-test-1935382032 not yet completed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:33Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=23196 workflow=minio-test
time="2020-07-05T14:43:33Z" level=info msg="Processing workflow" namespace=argo workflow=minio-test
time="2020-07-05T14:43:33Z" level=info msg="Workflow step group node minio-test-1935382032 not yet completed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Processing workflow" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Updating node minio-test-3293111538 status Running -> Error"
time="2020-07-05T14:43:34Z" level=info msg="Updating node minio-test-3293111538 message: failed to save outputs: Failed to establish pod watch: unknown (get pods)"
time="2020-07-05T14:43:34Z" level=info msg="Step group node minio-test-1935382032 deemed failed: child 'minio-test-3293111538' failed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="node minio-test-1935382032 phase Running -> Failed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="node minio-test-1935382032 message: child 'minio-test-3293111538' failed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="node minio-test-1935382032 finished: 2020-07-05 14:43:34.778087594 +0000 UTC" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="step group minio-test-1935382032 was unsuccessful: child 'minio-test-3293111538' failed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Outbound nodes of minio-test-3293111538 is [minio-test-3293111538]" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Outbound nodes of minio-test is [minio-test-3293111538]" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="node minio-test phase Running -> Failed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="node minio-test message: child 'minio-test-3293111538' failed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="node minio-test finished: 2020-07-05 14:43:34.77830792 +0000 UTC" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Checking daemoned children of minio-test" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Updated message  -> child 'minio-test-3293111538' failed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Marking workflow completed" namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Checking daemoned children of " namespace=argo workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=23199 workflow=minio-test
time="2020-07-05T14:43:34Z" level=info msg="Labeled pod argo/minio-test-3293111538 completed"
time="2020-07-05T14:44:50Z" level=info msg="Alloc=6288 TotalAlloc=111553 Sys=70592 NumGC=83 Goroutines=162"
time="2020-07-05T14:49:50Z" level=info msg="Alloc=5986 TotalAlloc=111748 Sys=70592 NumGC=85 Goroutines=162"
time="2020-07-05T14:54:50Z" level=info msg="Alloc=5971 TotalAlloc=111942 Sys=70592 NumGC=88 Goroutines=162"

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
```
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'hi' > /tmp/message"]
```
