### ISSUE TITLE
Accessing artifacts of an entrypoint dag step from an exit handler step

### ISSUE THREAD

**Issue by ashrafgt** [argoproj/argo#3393]
# Summary

I'd like to know if it's possible to access artifacts from a step in the main (entrypoint) DAG from a step in an exit handler DAG.

# Motivation

The purpose is to recover some checkpoint files in case a step fails, then report them to another service via the exit handler.

# Attempt

This snippet below demonstrates what I'm trying to achieve:
The entrypoint is a single-step DAG, which writes to a file (that's exported as an output artifact) then fails. I attempt to read that artifact from the exit handler with the reference `{{main.tasks.main-step.outputs.artifacts.checkpoint}}` which Argo fails to resolve (I also tried `{{main.main-step.outputs.artifacts.checkpoint}}` and `{{main.outputs.artifacts.checkpoint}}` unsuccessfully).

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
  namespace: default
spec:
  entrypoint: main
  onExit: exit
  templates:
    
    - name: main
      dag: 
        tasks:
          - name: main-step
            template: do-main-step

    - name: exit
      dag: 
        tasks:
          - name: exit-step
            template: do-exit-step
            arguments:
              artifacts:
                - name: checkpoint
                  from: "{{main.tasks.main-step.outputs.artifacts.checkpoint}}"

    - name: do-main-step
      outputs:
        artifacts:
          - name: checkpoint
            path: /mnt/checkpoint.txt
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo test > /mnt/checkpoint.txt
          exit 1

    - name: do-exit-step
      inputs:
        artifacts:
          - name: checkpoint
            path: /mnt/saved_checkpoint.txt
      script:
        image: alpine:latest
        command: [sh]
        source: |
            cat /mnt/saved_checkpoint.txt
```

**Comment by arbielsk** [comment]
I think you should be able to do this by declaring the output artifact of the main step with a globalName.
Reference: https://argoproj.github.io/argo/fields/#outputs (search for globalName)

**Comment by ashrafgt** [comment]
@arbielsk Thank you for your reply. 

I unsuccessfully tried adding the `globalName` field to the template that exports the artifact, then I used the syntax from the documentation to access it as `{{io.argoproj.workflow.v1alpha1.outputs.artifacts.checkpoint}}` from the exit handler.

Could you please review the revision of my demo workflow? (changes in lines 25 and 31)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
  namespace: deep-chain
spec:
  entrypoint: main
  onExit: exit
  templates:

    - name: main
      dag: 
        tasks:
          - name: main-step
            template: do-main-step

    - name: exit
      dag: 
        tasks:
          - name: exit-step
            template: do-exit-step
            arguments:
              artifacts:
                - name: checkpoint
                  from: "{{io.argoproj.workflow.v1alpha1.outputs.artifacts.checkpoint}}"

    - name: do-main-step
      outputs:
        artifacts:
          - name: checkpoint
            globalName: checkpoint
            path: /mnt/checkpoint.txt
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo test > /mnt/checkpoint.txt
          exit 1

    - name: do-exit-step
      inputs:
        artifacts:
          - name: checkpoint
            path: /mnt/saved_checkpoint.txt
      script:
        image: alpine:latest
        command: [sh]
        source: |
            cat /mnt/saved_checkpoint.txt
```
