### ISSUE TITLE
Custom Metrics w/ retryStrategy does not work

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo#3404]
**What happened**:

When attempting to emit custom metrics from a template that also defines a `retryStrategy`, no custom metrics are emitted.

**What you expected to happen**:

Custom metrics should be emitted (and in the case of duration, should likely be the sum of all child nodes).

**How to reproduce it (as minimally and precisely as possible)**:

Create an environment running the latest release of argo (I used v2.9.1), enable metrics config if needed, then run the following workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-whalesay-
  namespace: argo
spec:
  entrypoint: whalesay
  serviceAccountName: argo
  templates:
  - name: whalesay
    metrics:
      prometheus:
        - name: workflow_counter
          help: "number of times the outer workflow was invoked"
          counter:
            value: "1"
    steps:
      - - name: call-whalesay-template
          template: whalesay-template
          arguments:
            parameters:
            - name: message
              value: "hello world"
  - name: whalesay-template
    retryStrategy:
      limit: 3
    metrics:
      prometheus:
        - name: template_counter
          help: "number of times the template was executed"
          counter:
            value: "1"
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

Observe that on the metrics page, neither of the custom metrics are emitted.  (Side note: Not sure whether or not metrics are supported on templates that just define steps; that may be a separate bug).

If you remove the `retryStrategy` and re-run the workflow, metrics are emitted as expected.

**Anything else we need to know?**:

Nope

**Environment**:

- Argo version:
```
v2.9.1
```
- Kubernetes version :
```
v1.18.2
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
