### ISSUE TITLE
lifecycle hooks not running

### ISSUE THREAD

**Issue by Jacky2Wong** [argoproj/argo#3410]
Lifecycle hooks do not appear to be running with Argo. 

Reproducible example: 

```
apiVersion: argoproj.io/v1alpha1
 kind: Workflow
 metadata:
   generateName: hello-world-
   labels:
     workflows.argoproj.io/archive-strategy: false
 spec:
   entrypoint: whalesay
   templates:
   - name: whalesay
     container:
       image: docker/whalesay:latest
       imagePullPolicy: Always
       command: [cowsay]
       lifecycle:
         postStart:
           exec:
             command: ["/bin/sh", "-c", "echo HI HI HI HI HI HI HI HI HI"]
      args: ["hello world"]

```
I tried to find them using `argo logs` and `kubectl logs` in the wait and main containers but I still wasn't able to find any output of "HI HI HI HI HI" .

I also tried it using webhooks in slack in case the logging was strange but wasn't able to get it working.
```
apiVersion: argoproj.io/v1alpha1
 kind: Workflow
 metadata:
   generateName: hello-world-
   labels:
     workflows.argoproj.io/archive-strategy: false
 spec:
   entrypoint: whalesay
   templates:
   - name: whalesay
     container:
       image: docker/whalesay:latest
       imagePullPolicy: Always
       command: [cowsay]
       lifecycle:
         postStart:
           exec:
             command: ['/bin/bash', 'text=testifargolifecycleworks; json="{\"text\": \"$text\"}"; curl -X      POST -H "Content-type: application/json" --data $json https://hooks.slack.com/services/XXX/XXX/XXX;']
       args: ["hello world"]
```
