### ISSUE TITLE
Unable to run step when k8s cluster's podsecuritypolicy has  rule: 'MustRunAsNonRoot'

### ISSUE THREAD

**Issue by maryoush** [argoproj/argo#3415]
Hi 

we have issue running out step templates.

The setup looks following  :

* Argoworklow 2.8
```
argo: v2.8.0
  BuildDate: 2020-05-11T22:55:43Z
  GitCommit: 8f696174746ed01b9bf1941ad03da62d312df641
  GitTreeState: clean
  GitTag: v2.8.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```

* runs on k8s cluster version 1.17x

```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

with istio installed 

we have step template

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: full-model-training-flow
  generateName: full-model-training-flow-
  namespace: argo
spec:
  serviceAccountName: argo
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  templates:
    - name: full-model-training-flow
      podSpecPatch: '{"containers":[{"name":"wait", "command": ["/bin/bash", "-c"], "args": ["sleep 10; argoexec wait"]}]}'
      outputs:
        parameters:
          - name: output-json
            value: "some input"
          - name: status
            valueFrom:
              default: NO_CATAGLOG_DATA #OK for continue execution
              path: /usr/local/status.txt
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
          logging.idefix/enabled: "true"
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          status = "OK"
          file = open("/usr/local/status.txt", "w")
          file.write(status)
          file.close()
          print("Catalog exported")
          print(status)


```

which  fails to start when given PodSecurityPolicy is applied 

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    garden.cloud/description: |
      argoworkflow.privileged allows full unrestricted access to Pod features, as if the PodSecurityPolicy controller was not enabled.
    garden.sapcloud.io/description: |
      argoworkflow.privileged allows full unrestricted access to Pod features, as if the PodSecurityPolicy controller was not enabled.
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: argoworkflow.privileged
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  volumes:
    - '*'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false

```
The PSP is bound to serviceAccount argo via clusterrole

```

- apiVersion: rbac.authorization.k8s.io/v1
--
  | kind: ClusterRole
  | metadata:
  | name: argo-cluster-role
  | rules:
  | # added podsecuritypolicy referenced from  cds-otterbots-helm-charts project cds-psps/templates/argo-workflow.yaml
  | - apiGroups:
  | - extensions
  | resourceNames:
  | - argoworkflow.privileged
  | resources:
  | - podsecuritypolicies
  | verbs:
  | - use
  | - apiGroups:
  | - ""


```

There was a ticket solving the security context injection to wait container https://github.com/kubernetes/kubernetes/issues/65314 

However this seems to be related to init container 

```
 $ k describe pod full-model-training-flow-bqtkk-445279901 -n argo
Name:         full-model-training-flow-bqtkk-445279901
Namespace:    argo
Priority:     0
Node:         ip-10-80-9-150.ec2.internal/10.80.9.150
Start Time:   Tue, 07 Jul 2020 16:22:08 +0200
Labels:       security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=full-model-training-flow-bqtkk-445279901
              service.istio.io/canonical-revision=latest
              workflows.argoproj.io/completed=false
              workflows.argoproj.io/workflow=full-model-training-flow-bqtkk
Annotations:  cni.projectcalico.org/podIP: 100.96.12.205/32
              cni.projectcalico.org/podIPs: 100.96.12.205/32
              kubernetes.io/psp: argoworkflow.privileged
              logging.idefix/enabled: true
              sidecar.istio.io/inject: true
              sidecar.istio.io/status:
                {"version":"e08631b4e66c43820d5cd81e1dda38bc2358f700e66513986917e8bab7d82747","initContainers":["istio-validation"],"containers":["istio-p...
              workflows.argoproj.io/node-name: full-model-training-flow-bqtkk[0].execute[0].export[0].catalog-export
              workflows.argoproj.io/template:
                {"name":"catalog-export","arguments":{},"inputs":{},"outputs":{"parameters":[{"name":"output-json","value":"{ \"catalogExportId\": \"7b6da...
Status:       Pending
IP:           100.96.12.205
IPs:
  IP:           100.96.12.205
Controlled By:  Workflow/full-model-training-flow-bqtkk
Init Containers:
  init:
    Container ID:  
    Image:         argoproj/argoexec:v2.8.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      init
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:  full-model-training-flow-bqtkk-445279901 (v1:metadata.name)
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /argo/staging from argo-staging (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from argo-token-q5nkz (ro)
```

These are step's pod describe result

``` 
Normal   Scheduled       <unknown>         default-scheduler                     Successfully assigned argo/full-model-training-flow-bqtkk-445279901 to ip-10-80-9-150.ec2.internal
  Normal   SandboxChanged  19s               kubelet, ip-10-80-9-150.ec2.internal  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          5s (x5 over 20s)  kubelet, ip-10-80-9-150.ec2.internal  Container image "argoproj/argoexec:v2.8.0" already present on machine
  Warning  Failed          5s (x5 over 20s)  kubelet, ip-10-80-9-150.ec2.internal  Error: container has runAsNonRoot and image will run as root
```
As the solution PSP had to be relaxed to 

```

runAsUser:
--
  | # Require the container to run without root privileges.
  | rule: 'RunAsAny'


```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
