### ISSUE TITLE
spec.entrypoint is required on a wftmpl if we want to submit it 

### ISSUE THREAD

**Issue by cscetbon** [argoproj/argo#3452]
**What happened**:
When I try to submit a workflow template that does not define spec.entrypoint `argo submit` fails. It's not mandatory and the command should support it as workflows do when they call a workflow template that does not define it.
```
$ argo submit --from wftmpl/wt-run-get-reports-job -p p1=v1 -p p2=v2 -p p3=v3
2020/07/10 18:06:28 Failed to submit workflow: spec.entrypoint is required
```
**What you expected to happen**:
I expect the definition of entrypoint to not be mandatory if we want to submit a workflow template.

**How to reproduce it (as minimally and precisely as possible)**:
Create https://github.com/lippertmarkus/argo/blob/a7ca46e1185145d7d7b27a802506f35d5bd8a524/examples/workflow-template/templates.yaml#L1-L15 after having removed the entrypoint and try to submit it
```
argo submit --from wftmpl/workflow-template-whalesay-template -p message=test
2020/07/10 18:34:08 Failed to submit workflow: spec.entrypoint is required
```

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
argo version                                                                                                                                      100%    18:36:10 
argo: 2.8.2+8a151ae.dirty
  BuildDate: 2020-06-18T23:53:01Z
  GitCommit: 8a151aec6538c9442cf2380c2544ba3efb60ff60
  GitTreeState: dirty
  GitTag: 2.8.2
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-06-18T02:59:13Z"
  compiler: gc
  gitCommit: c96aede7b5205121079932896c4ad89bb93260af
  gitTreeState: clean
  gitVersion: v1.18.4
  goVersion: go1.14.3
  major: "1"
  minor: "18"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-27T21:51:36Z"
  compiler: gc
  gitCommit: af3caf6136cd355f467083651cc1010a499f59b1
  gitTreeState: clean
  gitVersion: v1.15.11-eks-af3caf
  goVersion: go1.12.17
  major: "1"
  minor: 15+
  platform: linux/amd64
```

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
