### ISSUE TITLE
Capture python exception messages into the Argo step messages

### ISSUE THREAD

**Issue by ashrafgt** [argoproj/argo#3458]
# Summary

I'd like to know if it's possible to capture python exception messages (or whatever other `stderr` content) into the step exit message.

# Motivation

Being able to access and report a summary of the errors and their descriptions (coming from the exception messages) directly from `{{workflow.failures}}`.

I do realize that it's possible to implement a custom mechanism based on text files, but if there's a way to do things with Argo syntax, I prefer to learn about it.

# Example Case

For example, is it possible to show the `ValueError` message `Error description here ...` as a part of the step message (which is `failed with exit code 1` in this case):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
  namespace: default
spec:
  entrypoint: main
  templates:
    - name: main
      dag: 
        tasks:
          - name: main-step
            template: do-main-step
            arguments:
              artifacts:
                - name: test
                  raw:
                    data: |
                      raise ValueError("Error description here ...")
 
    - name: do-main-step
      inputs:
        artifacts:
          - name: test
            path: /tmp/test.py
      script:
        image: python:rc-alpine3.11
        command: [sh]
        source: |
          python /tmp/test.py
```

Thank you.

**Comment by alexec** [comment]
I'm afraid that there is not 1st class way to do this today. I've marked this issue as `workaround` as you've stated you have one already.

**Comment by ashrafgt** [comment]
@alexec

Regarding the workaround, for situations where we'd like to avoid using persistent-volume to access files across steps, I've been trying to implement something based on global/optional artifacts. 

Unfortunately, I'm unable to get a demo to work (the `report-failed-steps` step fails to resolve the supposedly optional artifact `step-b-error`). If you could please review it and see if it's possible to get a solution like this to work:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
  namespace: default
spec:
  entrypoint: main
  onExit: exit
  templates:
    - name: main
      dag: 
        tasks:
          - name: run-a
            template: step-a
          - name: run-b
            dependencies: [run-a]
            template: step-b

    - name: exit
      dag: 
        tasks:
          - name: report-failed-steps
            template: failure-reporter
            arguments:
              artifacts:
                - name: step-a-error
                  optional: true
                  from: "{{workflow.outputs.artifacts.step-a-error}}"
                - name: step-b-error
                  optional: true
                  from: "{{workflow.outputs.artifacts.step-b-error}}"

    - name: step-a
      artifacts:
        - name: error
          globalName: step-a-error
          path: /mnt/step_a_error.txt  
      script:
        image: "alpine:latest"
        command: [sh]
        source: |
          echo test > /mnt/step_a_error.txt
          exit 1

    - name: step-b
      artifacts:
        - name: error
          globalName: step-b-error
          path: /mnt/step_b_error.txt  
      script:
        image: "alpine:latest"
        command: [sh]
        source: |
          echo test > /mnt/step_b_error.txt
          exit 1

    - name: failure-reporter
      inputs:
        artifacts:
          - name: step-a-error
            path: /mnt/step_a_error.txt
          - name: step-b-error
            path: /mnt/step_b_error.txt
      script:
        image: dwdraju/alpine-curl-jq
        imagePullPolicy: IfNotPresent
        command: [sh]
        source: |
          echo Step A:
          cat /mnt/step_a_error.txt
          echo Step B:
          cat /mnt/step_b_error.txt
```
