### ISSUE TITLE
Unclear error when using an output parameter with `valueFrom.path` in a template that inherits from another template, has steps, and is used as a template for steps

### ISSUE THREAD

**Issue by gmahomarf** [argoproj/argo#3459]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
_See [this workflow spec][gist] for a minimal example and reference._ 

We have a template that receives a shell script as an argument (**BASE_TEMPLATE**), which it executes after some common setup. One of our steps uses a template (**OUTPUT_PARAM_TEMPLATE**) that has steps that inherit from said template and produces an output parameter from the contents of a file. When submitting or linting the workflow, we get an error that we don't understand how to fix (see **Logs** section). As far as we can tell, according to the docs (field reference and examples), our Workflow specs are correct.

**What you expected to happen**:
We expect the workflow to be submitted successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Try to submit or lint [this workflow][gist]

**Anything else we need to know?**:
This error only seems to happen when creating the output parameter with `valueFrom.path`. Using `value` or `valueFrom.parameter` works fine. Also, if we copy the setup from **BASE_TEMPLATE** to **OUTPUT_PARAM_TEMPLATE**, and replace the steps with a script, it works (see [this other example][gist2]). However, this results in unnecessary duplication of code.

**Environment**:

- Argo version:
```
argo: v2.9.2
  BuildDate: 2020-07-08T23:55:01Z
  GitCommit: 65c2bd44e45c11e0a0b03adeef8d6800b72cd551
  GitTreeState: clean
  GitTag: v2.9.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-07-04T14:53:16Z"
  compiler: gc
  gitCommit: e6503f8d8f769ace2f338794c914a96fc335df0f
  gitTreeState: clean
  gitVersion: v1.18.5
  goVersion: go1.14.4
  major: "1"
  minor: "18"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-06-24T14:35:11Z"
  compiler: gc
  gitCommit: eb3f4bec359a47739117117f61c1a1f35dd1ae10
  gitTreeState: clean
  gitVersion: v1.16.11
  goVersion: go1.14.4
  major: "1"
  minor: 16+
  platform: linux/amd64
```

**Logs**

```
$ argo lint test.yaml
ERRO[0000] Error in file test.yaml: templates.entry-steps.steps[1].get-name templates.get-name.outputs.parameters.name-o.parameter must be specified for Steps templates
FATA[0000] Errors encountered in validation

$ argo submit test.yaml
2020/07/13 10:19:23 Failed to submit workflow: templates.entry-steps.steps[1].get-name templates.get-name.outputs.parameters.name-o.parameter must be specified for Steps templates
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

[gist]: https://gist.github.com/gmahomarf/08d19749a00fcbe79cb9bce854b006f6
[gist2]: https://gist.github.com/gmahomarf/026b2f6363d31e513e10aa043a1e8613
