### ISSUE TITLE
TTLStrategy.secondsAfterCompletion does not work with value > 22 seconds

### ISSUE THREAD

**Issue by arbielsk** [argoproj/argo#3460]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
I specified TTLStrategy.secondsAfterCompletion to a value of 30 seconds (also tried 60, 22, 25, 120 and 20). However if a value of 22+ seconds was specified, the workflow was not garbage collected as expected. 

**What you expected to happen**:
I expect completed workflows to be garbage collected if a TTLStrategy.secondsAfterCompletion is defined, no matter how high the value of secondsAfterCompletion is. I believe, it should be possible to garbage collect a workflow a day after it has completed, not only within the first 20 seconds after completion.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example
spec:
  TTLStrategy:
    secondsAfterCompletion: 30 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
  entrypoint: sleep-5
  templates:
    - name: sleep-5
      container:
        image: alpine:latest
        command:
          - sh
          - -c
        args:
          - "echo running sleep-5 template && sleep 5 && echo done"
```
**Anything else we need to know?**:
There was also 1 instance I observed where a value of 20 seconds did not lead to garbage collection of the workflow.

**Environment**:

- Argo version:
```
$ argo version
argo: v2.9.2
  BuildDate: 2020-07-08T23:55:01Z
  GitCommit: 65c2bd44e45c11e0a0b03adeef8d6800b72cd551
  GitTreeState: clean
  GitTag: v2.9.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```

- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-01-15T08:26:26Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: clean
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.5
  major: "1"
  minor: 16+
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-01-15T08:18:29Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: clean
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.5
  major: "1"
  minor: 16+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow result:
in this example secondsAfterCompletion was set to 22 seconds
```
argo --loglevel DEBUG get <workflowname>
DEBU[0000] CLI version                                   version="{v2.9.2 2020-07-08T23:55:01Z 65c2bd44e45c11e0a0b03adeef8d6800b72cd551 v2.9.2 clean go1.13.4 gc darwin/amd64}"
DEBU[0000] Client options                                opts="{{ false false}  0x2277640 0xc00004d0e0}"
Name:                example
Namespace:           argo
ServiceAccount:      default
Status:              Succeeded
Conditions:          
 Completed           True
Created:             Mon Jul 13 11:43:35 +0200 (3 minutes ago)
Started:             Mon Jul 13 11:43:35 +0200 (3 minutes ago)
Finished:            Mon Jul 13 11:43:45 +0200 (2 minutes ago)
Duration:            10 seconds
ResourcesDuration:   12s*(1 cpu),12s*(100Mi memory)

STEP        TEMPLATE  PODNAME  DURATION  MESSAGE
 ✔ example  sleep-5   example  8s 
```

- executor logs:
Not applicable.
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```

- workflow-controller logs:

```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
time="2020-07-13T09:43:22Z" level=info msg="Deleting TTL expired workflow argo/example"
time="2020-07-13T09:43:22Z" level=info msg="Successfully deleted 'argo/example'"
time="2020-07-13T09:43:35Z" level=info msg="Processing workflow" namespace=argo workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Pod node example initialized Pending" namespace=argo workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Created pod: example (example)" namespace=argo workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1560798 workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Processing workflow" namespace=argo workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1560802 workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Processing workflow" namespace=argo workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Updating node example message: ContainerCreating"
time="2020-07-13T09:43:35Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1560803 workflow=example
time="2020-07-13T09:43:35Z" level=info msg="Processing workflow" namespace=argo workflow=example
time="2020-07-13T09:43:36Z" level=info msg="Processing workflow" namespace=argo workflow=example
time="2020-07-13T09:43:41Z" level=info msg="Processing workflow" namespace=argo workflow=example
time="2020-07-13T09:43:41Z" level=info msg="Updating node example status Pending -> Running"
time="2020-07-13T09:43:41Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=1560820 workflow=example
time="2020-07-13T09:43:41Z" level=info msg="Processing workflow" namespace=argo workflow=example
time="2020-07-13T09:43:45Z" level=info msg="Processing workflow" namespace=argo workflow=example
time="2020-07-13T09:43:45Z" level=info msg="Setting node example outputs"
time="2020-07-13T09:43:45Z" level=info msg="Updating node example status Running -> Succeeded"
time="2020-07-13T09:43:45Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=example
time="2020-07-13T09:43:45Z" level=info msg="Marking workflow completed" namespace=argo workflow=example
time="2020-07-13T09:43:45Z" level=info msg="Checking daemoned children of " namespace=argo workflow=example
time="2020-07-13T09:43:45Z" level=info msg="Found Workflow argo/example set expire at 2020-07-13 09:44:07 +0000 UTC (21.240159s from now)"
time="2020-07-13T09:43:45Z" level=info msg="Queueing workflow argo/example for delete in 21.240159s"
time="2020-07-13T09:43:45Z" level=info msg="Found Workflow argo/example set expire at 2020-07-13 09:44:07 +0000 UTC (21.239524s from now)"
time="2020-07-13T09:43:45Z" level=info msg="Queueing workflow argo/example for delete in 21.239524s"
time="2020-07-13T09:43:45Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=1560833 workflow=example
time="2020-07-13T09:43:45Z" level=info msg="Labeled pod argo/example completed"
time="2020-07-13T09:44:00Z" level=info msg="Running xxxxxxxxxxx-xxxxxxxxxxxxxxxx" namespace=argo workflow=xxxxxxxxxxx-xxxxxxxxxxxxxxxx
time="2020-07-13T09:44:03Z" level=info msg="xxxxxxxxxxx-xxxxxxxxxxxxxxxx is suspended, skipping execution" namespace=argo workflow=xxxxxxxxxxx-xxxxxxxxxxxxxxxx
time="2020-07-13T09:44:08Z" level=info msg="Alloc=20030 TotalAlloc=228395 Sys=71040 NumGC=23 Goroutines=162"
```

**Logs**
see above
```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Hi @arbielsk - your YAML is invalid. It should be:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example
spec:
  ttlStrategy:
    secondsAfterCompletion: 30
  entrypoint: sleep-5
  templates:
    - name: sleep-5
      container:
        image: 'alpine:latest'
        command:
          - sh
          - '-c'
        args:
          - echo running sleep-5 template && sleep 5 && echo done
```
