### ISSUE TITLE
How to use global variables in workflow templates?

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo#3468]
# Summary

Is it possible to use global variables inside workflow templates? I tried to do it but I get an error of failed to resolve <GLOBAL_VARIABLE>

# Motivation

I have like 5 workflows that shares the same templates, I'd like to put those templates on a separate workflow template so that I could just reference them. But they have global variables like {{workflow.failures}} and {{workflow.status}}. I think these global variables should just be inherited from the current workflow they are referenced.

**Comment by sarabala1979** [comment]
Are you using this variable in the exit handler and the exit handler template is referring workflowtemplate? These global variables are only available in exit handler.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  onExit: exit
  templates:
  - name: whalesay
    steps:
      - - name: call-whalesay-template
          templateRef:
            name: workflow-template-whalesay-template
            template: whalesay-template
          arguments:
            parameters:
            - name: message
              value: "hello world"
  - name: exit
    steps:
      - - name: exit-tmpl
          templateRef:
            name: workflow-template-exit
            template: whalesay-template
```


```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-exit
spec:
  entrypoint: whalesay-template
  templates:
    - name: whalesay-template
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{workflow.status}} {{workflow.failures}}"]
```
