### ISSUE TITLE
Is it possible to create and mount a volume on the wait container? 

### ISSUE THREAD

**Issue by kimberly-lee** [argoproj/argo#3479]
# Summary

Is it possible to create and mount a volume on the wait container? The executor in the docs looks like we can only set container specs: https://github.com/argoproj/argo/blob/master/docs/workflow-controller-configmap.yaml#L107

If we need to do a combination of both container and pod specs on the workflow-controller-configmap under `executor`, what would that look like?

# Motivation

This is for setting the credentials to push the output artifacts to S3. Our k8 secrets only contains a filepath to a credentials file instead of the accessKey and the secretKeySecret. The team that was responsible for creating our IAM role told us if we mount the volume to our container on our pod and set the `AWS_SHARED_CREDENTIALS_FILE`, we should be able to access our s3 bucket.

We are unsure how to set in the configMap for  workflow-controller-configmap.yaml to create this volume and mount it on the wait container. This was what we tried but the volume didn't get created or mounted. 

```
    executor:
      volumes:
      - name: creds
        secret:
          secretName: 'secrets'
      env:
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /path/to/credentials.process
      volumeMounts:
      - name: creds
        mountPath: /meta/aws-iam
```

Any advice would be great. Thank you!

**Comment by kimberly-lee** [comment]
I ended finding a very roundabout way to do this. I mounted the volumes in my Workflow template. The `wait` container got those same volumes that are in the `main` container under the `/mainctrfs` directory. Then I set the env variable to that location and then pushing to S3 worked.

We would prefer though to be able to specify in the workflow_controller_configmap.yaml to mount the volume on the wait container. Is this possibly a feature gap or can someone point me to an example on how we would be able to specify pod level specs in the workflow_controller_configmap.yaml?

**Comment by alexec** [comment]
Try Workflow Defaults?

**Comment by kimberly-lee** [comment]
Thanks @alexec for the suggestion. I just gave this a try and the volume didn't get created:
This is what my config file looks like: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    artifactRepository:
      s3:
        bucket: my-bucket
        endpoint: s3.amazonaws.com
        useSDKCreds: true
        region: us-west-2
    containerRuntimeExecutor: k8sapi
    executor:
      env:
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /meta/aws-iam/credentials
      volumeMounts:
      - name: creds
        mountPath: /meta/aws-iam
    workflowDefaults:
      spec:
        volumes:
        - name: creds
          secret:
            secretName: 'secretName'
```

I followed the format from [here](https://github.com/argoproj/argo/blob/master/docs/workflow-controller-configmap.yaml#L204).

**Comment by omerfsen** [comment]
I also have this requirement too. So my purpose is to change CA so internal CA cert can be used and minio does not get

```bash
x509: certificate signed by unknown authority
```

error

I have tried: (after every change i have restarted all pods via kubectl rollout restart deployment -n argo  so ALL pods restarted)

```yaml
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: docker
    executor:
      volumeMounts:
        - mountPath: /etc/ssl/certs/
          name: ssl-certs
          readOnly: true
      volumes:
        - name: ssl-certs
          secret:
            items:
            - key: tls.crt
              path: ca-certificates.crt
            secretName: ingress-tls
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-minio
        secretKeySecret:
          key: secretkey
          name: argo-minio
        bucket: argo-artifacts
        endpoint: services.domain.com:9000
        insecure: false
kind: ConfigMap
```

or

```yaml
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: docker
    executor:
      volumeMounts:
      - name: ssl-certs
        mountPath: /etc/ssl/certs/
        readOnly: true
    workflowDefaults:
      spec:
        volumes:
        - name: ssl-certs
          secret:
            items:
            - key: tls.crt
              path: ca-certificates.crt
            secretName: ingress-tls
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-minio
        secretKeySecret:
          key: secretkey
          name: argo-minio
        bucket: argo-artifacts
        endpoint: services.domain.com:9000
        insecure: false
kind: ConfigMap

```

or

```yaml
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: docker
    executor:
    workflowDefaults:
      spec:
        volumes:
        - name: ssl-certs
          secret:
            items:
            - key: tls.crt
              path: ca-certificates.crt
            secretName: ingress-tls
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs/
          readOnly: true
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-minio
        secretKeySecret:
          key: secretkey
          name: argo-minio
        bucket: argo-artifacts
        endpoint: services.domain.com:9000
        insecure: false
kind: ConfigMap
```
