### ISSUE TITLE
Access denied for mysql user when persistence is enabled

### ISSUE THREAD

**Issue by viperKiran** [argoproj/argo#3507]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
When I enabled persistence and added mysql configuration, I am seeing the following error
`time="2020-07-17T16:38:26Z" level=fatal msg="Failed to update config: Error 1045: Access denied for user 'argo_user\n'@'10.175.106.192' (using password: YES)"`

I suspect argo is suffixing "\n" to the user.

**What you expected to happen**:
DB session should be successful

**How to reproduce it (as minimally and precisely as possible)**:
1. configmap:
```
apiVersion: v1
data:
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
    nodeStatusOffLoad: true
    archive: true
    archiveTTL: 7d
    mysql:
      host: argoflow-db.argoflow.svc.cluster.local
      port: 3306
      database: argo_db
      tableName: argo_workflows
      userNameSecret:
        name: argo-mysql-config
        key: username
      passwordSecret:
        name: argo-mysql-config
        key: password
kind: ConfigMap
name: workflow-controller-configmap
namespace: argoflow
```
2. Secret
```
kubectl get secrets argo-mysql-config -n argoflow -o yaml
apiVersion: v1
data:
  password: <secret|base64>
  username: YXJnb191c2VyCg==
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
  creationTimestamp: "2020-07-17T04:00:36Z"
  labels:
    app: mysql
  name: argo-mysql-config
  namespace: argoflow
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: argo-mysql-config
    uid: 11f87192-c7e2-11ea-a6eb-024ce1626f16
  resourceVersion: "11747679"
  selfLink: /api/v1/namespaces/argoflow/secrets/argo-mysql-config
  uid: 1213d276-c7e2-11ea-9d8e-06829451feb8
type: Opaque
```
3. Restart the controller pod.

**Anything else we need to know?**:
I did some troubleshooting to confirm the behavior.

```
kubectl run "mysql-${USER}" -it --rm --image=mysql:8 --restart=Never -n argoflow -- mysql -h argoflow-db.argoflow.svc.cluster.local -P 3306 -u "argo_user\n" -p<SECRET>

If you don't see a command prompt, try pressing enter.
ERROR 1045 (28000): Access denied for user 'argo_user\n'@'10.175.107.168' (using password: YES)
pod "mysql-kiransundaravarathan" deleted
pod argoflow/mysql-kiransundaravarathan terminated (Error)
```
The above error is as same as argo controller/server log.

I am also able to access db from kubectl:
```
kubectl run "mysql-${USER}" -it --rm --image=mysql:8 --restart=Never -n argoflow -- mysql -h argoflow-db.argoflow.svc.cluster.local -P 3306 -u "argo_user" -p<Secret>

If you don't see a command prompt, try pressing enter.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 539
Server version: 5.7.25-log Source distribution

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

**Environment**:

- Argo version:
```
$ argo version
2.9.3
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-06-19T16:40:16Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-18T04:24:17Z"
  compiler: gc
  gitCommit: f459c0672169dd35e77af56c24556530a05e9ab1
  gitTreeState: clean
  gitVersion: v1.14.9-eks-f459c0
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow-controller logs:

```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
time="2020-07-17T16:48:27Z" level=info msg="config map" name=workflow-controller-configmap
time="2020-07-17T16:48:27Z" level=info msg="Configuration:\nartifactRepository: {}\nmetricsConfig: {}\nnodeEvents: {}\npersistence:\n  archive: true\n  archiveTTL: 168h0m0s\n  connectionPool:\n    maxIdleConns: 100\n  mysql:\n    database: argo_db\n    host: argoflow-db.argoflow.svc.cluster.local\n    passwordSecret:\n      key: password\n      name: argo-mysql-config\n    port: \"3306\"\n    tableName: argo_workflows\n    userNameSecret:\n      key: username\n      name: argo-mysql-config\n  nodeStatusOffLoad: true\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\ntelemetryConfig: {}\n"
time="2020-07-17T16:48:27Z" level=info msg="Persistence configuration enabled"
time="2020-07-17T16:48:27Z" level=info msg="Creating DB session"
time="2020-07-17T16:48:28Z" level=fatal msg="Failed to update config: Error 1045: Access denied for user 'argo_user\n'@'10.175.106.192' (using password: YES)"
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
