### ISSUE TITLE
Can I create pod in another cluster?

### ISSUE THREAD

**Issue by luozhaoyu** [argoproj/argo#3516]
# Summary

Our k8s has several clusters, it would be best if we can only install Argo Workflow into only one cluster, but allow Workflow to create `Workflow/Pod` in the other clusters. Is it possible to achieve that?

The closest field I find is `clusterName`: https://argoproj.github.io/argo/fields/#fields_57
> The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request.

So seems this field will be ignored if I want to create a new `Workflow`, am I right?

# Motivation

Why do you need to know this, any examples or use cases you could include?

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: false
  namespace: argo
  clusterName: another-cluster-i-want-to-run-this-workflow
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    serviceAccountName: argo
    container:
      image: docker/whalesay
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
      command: [cowsay]
      args: ["hello world"]
```

^^ this is an example I want to run Workflow in another cluster
