### ISSUE TITLE
Provide a link template for external logs in Argo UI

### ISSUE THREAD

**Issue by brabster** [argoproj/argo#3521]
# Summary

A way of providing a templated link for externally-hosted logs, visible in the Argo UI for task and workflow logs

# Motivation

Logs for GKE containers exported to Stackdriver, accessible via a link. Example:
`https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22argo-workflow-5hjbp%22?project=myproject&query=%0A`

Template might be

`https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22{{pod_name}}%22?project=myproject&query=%0A` - Argo doesn't know what `myproject` is, so it would likely need to provided as part of deployment automation effectively hardcoded into the template

# Proposal

How do you think this should be implemented?

- Configuration option for a templated external log link that is interpolated and displayed as a clickable link in the Argo UI.
- Probably best a key and value, key is what is display as the link text - might want to say explicitly "View in Stackdriver" or "View in Elasticsearch" or provide a non-English text
- Also good to be visible in kubectl get pod output?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
This feature is already supported:

https://argoproj.github.io/argo/links/

```
   links:
      - name: Example Workflow Link
        scope: workflow
        url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}
      - name: Example Pod Link
        scope: pod
        url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}
```
