### ISSUE TITLE
Does `emptyDir` storage can be reused across multiple steps?

### ISSUE THREAD

**Issue by bappr** [argoproj/argo#3533]
Hey guys,

Can I share an empty_dir volumes across multiple steps ? -> https://github.com/argoproj/argo/blob/master/examples/volumes-emptydir.yaml

Idea is to avoid using PVC cuz they takes too much time to be created and mounted during my CICD workflow

Does argo make sure that the pods using the volumes are being mounted on the same node?

Example that fails:

```
# This example demonstrates the ability for a workflow to use an
# emptyDir volume.
#
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: volumes-emptydir-
spec:
  entrypoint: main
  volumes:
  - name: workdir
    emptyDir: {}

  templates:
  - name: main
    steps:
    - - name: volumes-emptydir-example
        template: volumes-emptydir-example
    - - name: volumes-emptydir-example-2
        template: volumes-emptydir-example-2
  - name: volumes-emptydir-example
    container:
      image: debian:latest
      command: ["/bin/bash", "-c"]
      args: ["echo 'toto' > /mnt/vol/toto.txt"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
  - name: volumes-emptydir-example-2
    container:
      image: debian:latest
      command: ["/bin/bash", "-c"]
      args: ["cat /mnt/vol/toto.txt"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
```

getting `volumes-emptydir-2vhxz-2751420709: cat: /mnt/vol/toto.txt: No such file or directory`
