### ISSUE TITLE
Support DAG outputs

### ISSUE THREAD

**Issue by arbielsk** [argoproj/argo#3545]
I did ask in the slack channel, but unfortunately I was not able to get a response.

# Summary

What do you want to know about this project?

Currently it is not possible to have dag-level outputs (referencing a step output) with the k8s api executor, as the validation doesn't allow outputs that don't reference a volumePath. Is this intended or is the validation just too strict for this particular use-case?

# Motivation

I am currently evaluating how we can run argo on OpenShift 3.11 and therefore I am having a look at the k8s api executor.
I am currently using a workflow template which consists of a DAG that outputs an artifact from one of its subtasks (similar to the example below).

```
  templates:
    - name: dag
      outputs:
        artifacts:
          - name: artifact
            from: "{{ tasks.task-2.outputs.artifacts.artifact }}"
      dag:
        tasks:
          - name: task-1
            template: sleep-5-param-output
          - name: task-2
            template: sleep-5-artifact-output
```

I am using an emptyDir within the 'task-2' so the artifact can correctly be outputted by the step (I have verified this also).

However my 'dag' template is rejected by the validation with the message: invalid spec: templates.dag.outputs.artifacts.artifact: k8sapi executor does not support outputs from base image layer. must use emptyDir

I'm not sure if this kind of output-artifact from a dag is simply not supported by the k8s-api executor, or if the validation is too restrictive (a quick look at the code showed that this might be the case as the validation does not seem to consider this use-case).

Thank you for considering my problem! If this is indeed a bug and not intended behavior I would be more than glad to file a bug-report including all necessary information.

**Comment by alexec** [comment]
The K8S executor needs some attention.

**Comment by sarabala1979** [comment]
Argo won't support the DAG level output artifacts/parameters. Can you provide us your usecase for this?

**Comment by jessesuen** [comment]
> invalid spec: templates.dag.outputs.artifacts.artifact: k8sapi executor does not support outputs from base image layer. must use emptyDir

 This is a fundamental limitation of the k8s executor, unrelated to the use of a DAG template. the K8s executor cannot retrieve artifacts of a completed container, unlike docker/pns. The error you are seeing is the validation detecting this.

**Comment by arbielsk** [comment]
> Argo won't support the DAG level output artifacts/parameters. Can you provide us your usecase for this?

@sarabala1979 At least with the docker container this already works (maybe it's not intended and just a nice side-effect). I just came upon issues with this when I was using the k8s api executor, as it has validation that disallows this (maybe it would even work, if the validation was not applied to DAG-level outputs)

My use case is as follows:
We are generating YAML code for complex workflows. In order to make these more readable and especially more maintainable, we have several WorkflowTemplates which usually have DAGs or steps as their main template. In some cases we want to pass on an artifact from the WorkflowTemplate up to the main workflow. We are currently using DAG/step-level outputs for these.

One of these DAGs is used to (task-1) retrieve artifacts from an unsupported source (SVN), followed by another task (task-2) which publishes an AMQP message to let our system know some info about the artifact that has been retrieved. The artifact  then needs to be provided to the main workflow that uses this WorkflowTemplate. We are currently doing this with DAG/steps-level outputs.

I really do think this is an essential feature for utilizing the power of WorkflowTemplates.

Example:
**WorkflowTemplate**
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: artifact-svn-template
spec:
  templates:
    - name: artifact-svn
      inputs:
        parameters:
          - name: remote-path
          - name: filename
      outputs:
        artifacts:
          - name: artifact
            from: "{{tasks.artifact-svn-retrieve.outputs.artifacts.artifact}}"
      dag:
        tasks:
        - name: artifact-svn-retrieve
          template: artifact-svn-retrieve
          arguments:
            parameters:
              - name: remote-path
                value: "{{inputs.parameters.remote-path}}"
              - name: filename
                value: "{{inputs.parameters.filename}}"
        - name: mq-publish-download-status
          dependencies:
            - artifact-svn-retrieve
          templateRef:
            name: mq-publish-download-status
            template: mq-publish-download-status
          arguments:
            artifacts:
              - name: artifact
                value: "{{tasks.artifact-svn-retrieve.outputs.artifacts.artifact}}"
    - name: artifact-svn-retrieve
      inputs:
        parameters:
          - name: remote-path
          - name: filename
      outputs:
        artifacts:
          - name: artifact
            path: "/vol/{{inputs.parameters.filename}}"
      container:
        image: jgsqware/svn-client
        command:
          - sh
          - -c
        args:
          - "cd /vol && svn export --username=$SVN_USERNAME --password=$SVN_PASSWORD {{inputs.parameters.remote-path}} /vol --force && ls /vol"
        volumeMounts:
          - name: vol
            mountPath: "/vol"
      volumes:
        - name: vol
          emptyDir: {}
```

**Main Workflow**
```
apiVersion: "argoproj.io/v1alpha1"
kind: "Workflow"
metadata:
  generateName: "main-"
spec:
  entrypoint: "main"
  templates:
    - name: "main"
      dag:
        tasks:
          - name: "artifact-task"
            templateRef:
              name: "artifact-svn-template"
              template: "artifact-svn"
            arguments:
              parameters:
                - name: "remote-path"
                  value: "https://some-svn-url.com"
                - name: "filename"
                  value: "svn-file.xml"
          - name: "dependent-task"
            template: "some-template"
            dependencies:
              - "artifact-task"
            arguments:
              artifacts:
                - name: "50b9c723-4dda-4483-9f99-8a4c237db242"
                  from: "{{tasks.artifact-task.outputs.artifacts.artifact}}"
```

> This is a fundamental limitation of the k8s executor, unrelated to the use of a DAG template. the K8s executor cannot retrieve artifacts of a completed container, unlike docker/pns. The error you are seeing is the validation detecting this.

@jessesuen Please excuse me for adding another question to this, because I'm not sure whether it applies in this case. In this case the artifact can be retrieved successfully from the template that outputs it and is stored in my configured artifactory. And it can also be passed on to another step successfully (with "{{tasks.artifact-task.outputs.artifacts.artifact}}"). My hypothesis would therefore be that "{{tasks.artifact-task.outputs.artifacts.artifact}}" is referencing to the output in the artifactory. Is this assumption correct? Because if it is, I don't believe that the k8s api executor is actually not able to do this. I'd expect that this is simply an issue with the validation being too restrictive (probably because DAG/steps-level outputs are not intended to be supported, if I underst @sarabala1979 correctly).

Thank you for considering my issue!
