### ISSUE TITLE
withItems incorrect type in full CRD

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3578]
Is

```yaml
                            withItems:
                              items:
                                properties:
                                  value:
                                    format: byte
                                    type: string
                                required:
                                - value
                                type: object
                              type: array
```

Should be:

```yaml
                            withItems:
                              items:
                                type: object
                              type: array
```
