### ISSUE TITLE
Upload artifact output as a folder without archiving

### ISSUE THREAD

**Issue by hadim** [argoproj/argo#3599]
# Summary

It would be nice to be able to upload an output artifact folder to S3/GCS without archiving it.

# Motivation

In certain cases, it's easier to have the data ready to be processed on S3/GCS. For example, you can retrieve a specific file from the output without having to download + unpack the archive.

# Proposal

The backward compat should be kept. We could add an option to the artifact spec.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by hadim** [comment]
Probably also of interest:

- https://github.com/argoproj/argo/issues/3402

**Comment by alexec** [comment]
Could you please add some example of the YAML you'd expect?

**Comment by hadim** [comment]
Something like thise:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-outputs-from-bucket-
spec:
  entrypoint: input-step-template

  templates:
    - name: input-step-template
      script:
        image: alpine
        command: [sh]
        source: |
          ls /data/inputs
          cat /data/inputs/data1.csv
          content=$(cat /data/inputs/data1.csv)
          if [ "$content" = "some data" ]; then
            exit 0
          else
            exit 1
          fi
      inputs:
        artifacts:
          - name: input-data
            path: /data/inputs
            gcs:
              key: tests/workflow_5ef698/inputs
              bucket: my-gcs-bucket
      outputs:
        artifacts:
          - name: output-data
            path: /data/outputs
            gcs:
              # HERE: instead of `tests/workflow_5ef698/outputs.tar.gz`, upload to `tests/workflow_5ef698/`
              key: tests/workflow_5ef698/
              bucket: my-gcs-bucket
```

**Comment by alexec** [comment]
I think there is an archive strategy option. I'm not sure if it is implemented. Could you try that?

**Comment by hadim** [comment]
But the archive option will still create a single output file `output.tar` (with no compression). It's a good point but my initial thought was to have the folder itself being uploaded (instead of a single archive file).

**Comment by hadim** [comment]
Oh but it actually already works!

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-as-folder-
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      script:
        image: alpine
        command: [sh]
        source: |
          mkdir -p /data/outputs
          mkdir -p /data/outputs/figures
          echo "result1" > /data/outputs/results1.csv
          echo "result2" > /data/outputs/results2.csv
          echo "a figure" > /data/outputs/figures/plot.png
      outputs:
        artifacts:
          - name: output-data
            path: /data/outputs
            gcs:
              key: tests/outputs-as-folder
              bucket: gargantua-test-data
            archive:
              none: {}
```

Sorry for the noise @alexec . I close here.
