### ISSUE TITLE
Workflow fails when a dash ('-') is in the conditional "when" statement

### ISSUE THREAD

**Issue by Syps** [argoproj/argo#3611]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.

Argo version: v2.9.2

 
**What happened**:
In a conditional workflow step (one using the "when" attribute), if there is a "-" character in the string value for `when:`, the workflow will fail.

**What you expected to happen**:
Strings containing `-` should be considered valid.

**How to reproduce it (as minimally and precisely as possible)**:

Submit the following workflow:

```
# Conditionals provide a way to affect the control flow of a
# workflow at runtime, depending on parameters. In this example
# the 'print-hello' template may or may not be executed depending
# on the input parameter, 'should-print'. When submitted with:
#   argo submit examples/conditionals.yaml
# the step will be skipped since 'should-print' will evaluate false.
# When submitted with:
#   argo submit examples/conditionals.yaml -p should-print=true
# the step will be executed since 'should-print' will evaluate true.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-
spec:
  entrypoint: conditional-example
  arguments:
    parameters:
    - name: should-print
      value: "false"

  templates:
  - name: conditional-example
    inputs:
      parameters:
      - name: should-print
    steps:
    - - name: print-hello
        template: whalesay
        when: "{{inputs.parameters.should-print}} == true-dash-true"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello"]
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
```

Workflow fails with the following output (`--watch` flag passed to `argo submit`):

```
Name:                conditional-9bnkg
Namespace:           my-namespace
ServiceAccount:      argo-runner-sa
Status:              Failed
Message:             Failed to evaluate 'when' expresion 'false == true-dash-true': Value 'true' cannot be used with the modifier '-', it is not a number
Created:             Mon Jul 27 15:07:33 -0400 (now)
Started:             Mon Jul 27 15:07:33 -0400 (now)
Finished:            Mon Jul 27 15:07:33 -0400 (now)
Duration:            0 seconds
Parameters:
  should-print:      false

STEP                  TEMPLATE             PODNAME  DURATION  MESSAGE
 ✖ conditional-9bnkg  conditional-example                     Failed to evaluate 'when' expresion 'false == true-dash-true': Value 'true' cannot be used with the modifier '-', it is not a number
```

Thanks!

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
