### ISSUE TITLE
Pvc created using a resource template not deleted automatically after workflow completion

### ISSUE THREAD

**Issue by cdlcs** [argoproj/argo#3657]
Hello,

I have an Argo workflow where I create PersistentVolumeClaims at the template level, using a resource template as described on the documentation https://argoproj.github.io/argo/examples/#volumes

I'm setting the setOwnerReference field to "true" but the PVCs are not being deleted after the workflow finishes. It is my understanding that if 'setOwnerReference: true' the PVCs would be deleted after completion, is this not the case?.

Example template:

```
- name: generate-pvc
  inputs:
    parameters:
      - name: pvc-prefix
  resource:
    action: create
    setOwnerReference: true
    manifest: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        generateName: '{{inputs.parameters.pvc-prefix}}'-
        namespace: namespace-test
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: '1.5Ti'
  outputs:
    parameters:
    - name: pvc-name
      valueFrom:
        jsonPath: '{.metadata.name}'

```

Thanks

**Comment by cdlcs** [comment]
```
10:05 $ argo version
argo: v2.6.0
  BuildDate: 2020-02-28T23:32:45Z
  GitCommit: 5d3bdd56607eea962183a9e45009e3d08fafdf9b
  GitTreeState: clean
  GitTag: v2.6.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
 
```

```
10:05 $ kubectl version -o yaml
clientVersion:
  buildDate: "2019-11-14T04:24:34Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.13
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-27T21:51:36Z"
  compiler: gc
  gitCommit: af3caf6136cd355f467083651cc1010a499f59b1
  gitTreeState: clean
  gitVersion: v1.15.11-eks-af3caf
  goVersion: go1.12.17
  major: "1"
  minor: 15+
  platform: linux/amd64
```

**Comment by sarabala1979** [comment]
I think Argo is not setting `controller=true` for cascading deletion.  Can you try the PVC support on argo instead of using a resource template? Argo will create PVC when the workflow starts.  It will get deleted if the workflow completes with success.

https://github.com/argoproj/argo/blob/master/examples/volumes-pvc.yaml

**Comment by jessesuen** [comment]
> I'm setting the setOwnerReference field to "true" but the PVCs are not being deleted after the workflow finishes. It is my understanding that if 'setOwnerReference: true' the PVCs would be deleted after completion, is this not the case?.

No this is not the case. `setOwnerReference` only deletes workflows when the workflow is deleted, using normal k8s cascaded deletion. It will not delete it when the workflow completes.

**Comment by cdlcs** [comment]
Is it possible to make this work declaring the PVCs at the template level, mimicking the functionality offered by the volumeClaimTemplates at the workflow level?. The only part that is missing is to clean-up the PVCs after the workflow completes. We have a use case where we only want to create these PVCs for tasks associated with specific template. Using volumeClaimTemplates the PVCs are created for all templates which creates a lot of unnecessary PVCs.

**Comment by plopezgarcia** [comment]
> Found a way to do it by creating a new resource template to delete the PVCs. I had to enable the podGC feature to delete the pods after the workflow completion (because the PVC can't be deleted if the pod is on COMPLETE status) and the Argo archive feature to store the logs that are lost after deleting the pod.

Hi, I'm having the exact same trouble as you but I can't figure out how to properly delete the PVCs.

I create the volume like this:

```
    - name: generate-volume
      inputs:
        parameters:
          - name: pvc-name
          - name: pvc-size
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            generateName: '{{inputs.parameters.pvc-name}}'
          spec:
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: '{{inputs.parameters.pvc-size}}'
      outputs:
        parameters:
          - name: pvc-name
            valueFrom:
              jsonPath: '{.metadata.name}'
```

And I created another template to delete it, like you suggested.

```
   - name: delete-volume
      inputs:
        parameters:
          - name: pvc-name
      resource:
        action: delete
        setOwnerReference: true
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            namespace: "argo"
            name: "'{{inputs.parameters.pvc-name}}'"`
```
And ran it like this after generating the volume at a previous step:
```
        - - name: delete-volume
            template: delete-volume
            arguments:
              parameters:
              - name: pvc-name
                value: "{{steps.generate-volume.outputs.parameters.pvc-name}}"   
```
I runs fine but it does nothing. Running `kubectl delete pvc pvc-name` works, though.

What am I doing wrong? Could you @cdlcs  please share your solution? Thanks in advance!
