### ISSUE TITLE
Make start: error: no objects passed to apply

### ISSUE THREAD

**Issue by seperman** [argoproj/argo#3663]
**What happened**:
Running `make start` I get:

```
kubectl -n argo apply -l app.kubernetes.io/part-of=argo --prune --force -f dist/minimal.yaml
error: no objects passed to apply
make: *** [install] Error 1
```

**What you expected to happen**:
`make start` to work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to `~/Go/src/github.com/argoproj/argo`
2. Run `make start`
3. Get the error

**Environment**: 

- Argo version:
Argo is at the current master branch at dbb39368295cbc0ef886e78236338572c37607a1

Note: The `argo version` command reports a different git commit than the commit I'm actually running. It also reports a wrong version of Go. My go version is  `go1.14.5 darwin/amd64`

```
argo: v2.9.2
  BuildDate: 2020-07-08T23:55:01Z
  GitCommit: 65c2bd44e45c11e0a0b03adeef8d6800b72cd551
  GitTreeState: clean
  GitTag: v2.9.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```

- Kubernetes version :

```
clientVersion:
  buildDate: "2020-07-16T00:04:31Z"
  compiler: gc
  gitCommit: dff82dc0de47299ab66c83c626e08b245ab19037
  gitTreeState: clean
  gitVersion: v1.18.6
  goVersion: go1.14.4
  major: "1"
  minor: "18"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-05-20T12:43:34Z"
  compiler: gc
  gitCommit: 2e7996e3e2712684bc73f0dec0200d64eec7fe40
  gitTreeState: clean
  gitVersion: v1.18.3
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
