### ISSUE TITLE
Argo WorkflowTemplate linting should raise an error when no main keys are present

### ISSUE THREAD

**Issue by ericandrewmeadows** [argoproj/argo#3664]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
Warning was raised

**What you expected to happen**:
Error is raised because none of `script`, `container`, or `steps` appeared.

**How to reproduce it (as minimally and precisely as possible)**:
Output the JSON below to a file and run `argo lint <fileLocation>`

**Anything else we need to know?**:

**Environment**:

- Argo version:  **2.8.0**
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-12-11T12:42:56Z"
  compiler: gc
  gitCommit: 6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4
  gitTreeState: clean
  gitVersion: v1.15.7
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-06-01T22:20:10Z"
  compiler: gc
  gitCommit: fb7add51f767aae42655d39972210dc1c5dbd4b3
  gitTreeState: clean
  gitVersion: v1.15.12-gke.2
  goVersion: go1.12.17b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

```yaml
{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "WorkflowTemplate",
  "metadata": {
    "labels": {
      "git-hash": "hashhashhash",
      "workflows.argoproj.io/controller-instanceid": "build-controller"
    },
    "name": "prefix--a",
    "namespace": "eric-meadows"
  },
  "spec": {
    "templates": [
      {
        "inputs": {
          "artifacts": [

          ],
          "parameters": [

          ]
        },
        "name": "run",
        "outputs": {
          "artifacts": [

          ],
          "parameters": [

          ]
        },
        "script:": {
          "command": [
            "bash"
          ],
          "env": [
            {
              "name": "ENVIRONMENT",
              "value": "dev"
            },
            {
              "name": "PROJECT",
              "value": "OUR_PROJECT"
            },
            {
              "name": "NAMESPACE",
              "value": "eric-meadows"
            },
            {
              "name": "COMMIT_HASH",
              "value": "hashhashhash"
            }
          ],
          "image": "thisIsAnImageUri",
          "imagePullPolicy": "Always",
          "resources": {
            "limits": {
              "cpu": "0.1",
              "memory": "1Gi"
            },
            "requests": {
              "cpu": "0.1",
              "memory": "1Gi"
            }
          },
          "source": [
            "python3 /app/main.py"
          ],
          "volumeMounts": [

          ]
        },
        "sidecars": [

        ]
      }
    ],
    "volumes": [

    ]
  }
}
```

```
time="2020-08-04T13:55:08Z" level=error msg="./json-to-validate.json failed to parse: json: unknown field \"script:\""
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
