### ISSUE TITLE
Race conditions when persisting Workflows causing undefined behavior

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3665]
Users are reporting

Fabio Rigato: "stuck with deleted pods"

* v2.9.2 workflows can get stuck with deleted pods: `Error from server (NotFound): pods "..." not found"`. There are #3097 and #3469 in v2.9.3 that could fix this.

Prateek Khera:  "deadline exceeded"

* v2.9.3 workflows stuck in progressing `level=warning msg="Deadline exceeded" namespace=XXXX workflow=XXX level=error msg="error in entry template execution" error="Deadline exceeded" namespace=ci workflow=XXX

Jonathan Steele: "stuck workflow parent task"

> I upgraded to 2.9.4  and am now experiencing "stuck" workflows where all of the tasks are complete, but the parent task is still running

**Comment by alexec** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-
  namespace: ci
spec:
  entrypoint: ci
  onExit: final-steps
  arguments:
    parameters:
      - name: branch
        value: "ci"       #default value
      - name: build_develop
        value: "false"    #default value
      - name: build_release
        value: "false"    #default value
      - name: image_tag
        value: "na"       #default value
      - name: refid
        value: "na"       #default value
      - name: latest-commit
        value: "na"       #default value
      - name: change_type
        value: "na"       #default value
      - name: user_slug
        value: "na"       #default value
  imagePullSecrets:
    - name: XXX
  templates:
    - name: ci
      dag:
        tasks:
          - name: ci-inprogress
            template:  build-status
            arguments:
              parameters:
                - name: status
                  value: INPROGRESS
          - name: ci-make-lint
            template: ci-make-lint-template
            dependencies: [ci-inprogress]
          - name: ci-make-unit-test
            template: ci-make-unit-test-template
            dependencies: [ci-make-lint]
          - name: ci-make-integration-test
            template: ci-make-integration-test-template
            dependencies: [ci-make-lint]
          - name: ci-build-image
            template: docker-build-template
            when: "{{workflow.parameters.build_develop}} == true || {{workflow.parameters.build_release}} == true"
            dependencies: [ci-make-integration-test,ci-make-unit-test]   
    - name:  build-status
      inputs:
        parameters:
          - name: status
      metadata:
        labels:
          app: ci
          commit: '{{workflow.parameters.latest-commit}}'
          stage: '{{workflow.name}}-notification-{{inputs.parameters.status}}'
          workflow: '{{workflow.name}}'   
      container:
        name: build-status
        image: XXX
        imagePullPolicy: Always
        command: ["python3"]
        args: ["ops/k8s/dev/ci/status.py"]                 
        env:
          - name: WORKFLOW
            value: '{{workflow.name}}'
          - name: LATEST_COMMIT
            value: '{{workflow.parameters.latest-commit}}'
          - name: STATUS
            value: '{{inputs.parameters.status}}'
        envFrom:
        - secretRef:
            name: dev-secret-ci
        resources:
          requests:
            cpu: '1'
            memory: 1Gi
    - name: ci-make-lint-template
      inputs:
        artifacts:
        - name: argo-source
          path: /src
          git:
            repo: XXX
            revision: "{{workflow.parameters.latest-commit}}"
            usernameSecret:
              name: dev-secret-ci
              key: GIT_USERNAME
            passwordSecret:
              name: dev-secret-ci
              key: GIT_PASSWORD
      metadata:
        labels:
          app: ci
          commit: '{{workflow.parameters.latest-commit}}'
          stage: '{{workflow.name}}-lint-test'
          workflow: '{{workflow.name}}' 
      container:
        image: XXX
        command: ["bash", "-c"]
        args: ["pip3 install -r src/test_requirements.txt --quiet && make lint"]
        workingDir: /src
        resources:
          requests:
            cpu: '1'
            memory: 1Gi                    
    - name: ci-make-unit-test-template
      inputs:
        artifacts:
        - name: argo-source
          path: /src
          git:
            repo: XXX
            revision: "{{workflow.parameters.latest-commit}}"
            usernameSecret:
              name: dev-secret-ci
              key: GIT_USERNAME
            passwordSecret:
              name: dev-secret-ci
              key: GIT_PASSWORD
      metadata:
        labels:
          app: ci
          commit: '{{workflow.parameters.latest-commit}}'
          stage: '{{workflow.name}}-unit-test'
          workflow: '{{workflow.name}}'                             
      container:
        image: XXXX
        command: ["bash", "-c"]
        args: ["pip3 install -r src/test_requirements.txt --quiet && make unit_test"]
        workingDir: /src
        resources:
          requests:
            cpu: '8'
            memory: 25Gi 
    - name: ci-make-integration-test-template
      inputs:
        artifacts:
        - name: argo-source
          path: /src
          git:
            repo: XXX
            revision: "{{workflow.parameters.latest-commit}}"
            usernameSecret:
              name: dev-secret-ci
              key: GIT_USERNAME
            passwordSecret:
              name: dev-secret-ci
              key: GIT_PASSWORD
      metadata:
        labels:
          app: ci
          commit: '{{workflow.parameters.latest-commit}}'
          stage: '{{workflow.name}}-integration-test'
          workflow: '{{workflow.name}}' 
      container:
        image: XXXX
        command: ["bash", "-c"]
        args: ["pip3 install -r src/test_requirements.txt --quiet && make integration_test"]
        workingDir: /src
        resources:
          requests:
            cpu: '8'
            memory: 25Gi
    - name: docker-build-template
      inputs:
        artifacts:
        - name: argo-source
          path: /src
          git:
            repo: XXX
            revision: "{{workflow.parameters.latest-commit}}"
            usernameSecret:
              name: dev-secret-ci
              key: GIT_USERNAME
            passwordSecret:
              name: dev-secret-ci
              key: GIT_PASSWORD
      retryStrategy:
        limit: 2
      container:
        image: gcr.io/kaniko-project/executor:debug
        args: ["XX"]
        workingDir: /src
        resources:
          requests:
            cpu: '2'
            memory: 4Gi
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
      volumes:  
      - name: kaniko-secret
        secret:
          secretName: XX
          items:
            - key: ".dockerconfigjson"
              path: config.json
    - name: cd-trigger-template
      metadata:
        labels:
          app: ci
          commit: '{{workflow.parameters.latest-commit}}'
          stage: '{{workflow.name}}-cd-argo-trigger'
          workflow: '{{workflow.name}}' 
      container:
        image: XXX
        command: ["bash", "-c"]
        args: ["ops/scripts/cd-trigger.sh"]
        resources:
          requests:
            cpu: '1'
            memory: 1Gi
        env:
          - name: BRANCH
            value: "{{workflow.parameters.branch}}"
          - name: REFID
            value: "{{workflow.parameters.refid}}"
          - name: LATEST_COMMIT
            value: "{{workflow.parameters.latest-commit}}"
          - name: CHANGE_TYPE
            value: "{{workflow.parameters.change_type}}"
          - name: USER_SLUG
            value: "{{workflow.parameters.user_slug}}"
        envFrom:
          - secretRef:
              name: dev-secret-ci
```
