### ISSUE TITLE
Argo linting does not respect namespace of declared resource

### ISSUE THREAD

**Issue by ericandrewmeadows** [argoproj/argo#3667]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
Declared a `CronWorkflow` that had the namespace in the declaration.  When running `argo cron lint <cronWorkflowJsonFile>`, it said the template did not exist.

**What you expected to happen**:
Namespace to be respected w.r.t. the declared CronWorkflow.

**How to reproduce it (as minimally and precisely as possible)**:
Create & apply any template with the namespace in its declaration.  Then, create any CronWorkflow with the same namespace, and run `argo cron lint` - it fails every time.

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
2.8.0
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-12-11T12:42:56Z"
  compiler: gc
  gitCommit: 6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4
  gitTreeState: clean
  gitVersion: v1.15.7
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-06-01T22:20:10Z"
  compiler: gc
  gitCommit: fb7add51f767aae42655d39972210dc1c5dbd4b3
  gitTreeState: clean
  gitVersion: v1.15.12-gke.2
  goVersion: go1.12.17b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- example CronWorkflow
```
{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "CronWorkflow",
  "metadata": {
    "name": "foo",
    "namespace": "eric-meadows",
    "labels": {
      "workflows.argoproj.io/controller-instanceid": "build-controller"
    }
  },
  "spec": {
    "schedule": "5 * * * *",
    "concurrencyPolicy": "Replace",
    "startingDeadlineSeconds": 0,
    "suspend": true,
    "workflowSpec": {
      "entrypoint": "run",
      "templates": [
        {
          "name": "run",
          "dag": {
            "tasks": [
              {
                "name": "a",
                "dependencies": null,
                "templateRef": {
                  "name": "existingWorkflowTemplate",
                  "template": "existingTemplateInExistingWorkflowTemplate"
                },
                "arguments": {
                  "parameters": []
                }
              }
            ]
          }
        }
      ]
    }
  }
}

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
