### ISSUE TITLE
Argo lint outputs are inconsistent between `argo cron lint` and `argo template lint`

### ISSUE THREAD

**Issue by ericandrewmeadows** [argoproj/argo#3668]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
Ran `argo template lint` and `argo cron lint` for `WorkflowTemplate` and `CronWorkflow` files, respectively, and their outputs were quite different.
```
WorkflowTemplate manifests validated
```
vs
```
./json-to-validate.json is valid
Cron workflow manifests validated
```

**What you expected to happen**:
I expected the outputs to be, roughly, the same (could include file validated, or not, but these should be the same).
```
WorkflowTemplate manifests validated
```
vs
```
CronWorkflow manifests validated
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
v2.8.0
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-12-11T12:42:56Z"
  compiler: gc
  gitCommit: 6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4
  gitTreeState: clean
  gitVersion: v1.15.7
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-06-01T22:20:10Z"
  compiler: gc
  gitCommit: fb7add51f767aae42655d39972210dc1c5dbd4b3
  gitTreeState: clean
  gitVersion: v1.15.12-gke.2
  goVersion: go1.12.17b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
