### ISSUE TITLE
The Tolerations are invalid with Template of steps

### ISSUE THREAD

**Issue by leileiwan** [argoproj/argo#3707]
# The Tolerations are invalid with Template of steps
# 1.Problem
I set the tolerations in Template of steps  , but it's invalid.
Then I set the Workflow.Spec.Tolerations, it useful. It seems very strange.

Then I found dag had the same problem. 

* set for Template
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "1s"
    tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value2"
      effect: "NoSchedule"
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [sleep]
      args: ["{{inputs.parameters.message}}"]
```

```
kubectl describe pod steps-tcztw-3119333882 
Name:           steps-tcztw-3119333882
Namespace:      default
Priority:       0
Node:          10.224.4.196/10.224.4.196
Start Time:     Fri, 07 Aug 2020 20:45:36 +0800
Labels:         workflows.argoproj.io/completed=false
                workflows.argoproj.io/workflow=steps-tcztw
Annotations:    workflows.argoproj.io/node-name: steps-tcztw[0].hello1
                workflows.argoproj.io/template:
                  {"name":"whalesay","arguments":{},"inputs":{"parameters":[{"name":"message","value":"1s"}]},"outputs":{},"metadata":{},"container":{"name"...
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Workflow/steps-tcztw
Containers:
  wait:
    Container ID:  
    Image:         argoproj/argoexec:v2.9.3
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:  steps-tcztw-3119333882 (v1:metadata.name)
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /var/run/docker.sock from docker-sock (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hrm5j (ro)
  main:
    Container ID:  
    Image:         docker/whalesay
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
    Args:
      1s
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hrm5j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  podmetadata:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations -> annotations
  docker-sock:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  Socket
  default-token-hrm5j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hrm5j
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                                  Message
  ----    ------     ----  ----                                  -------

```
* set for workflow Spec
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1  
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "1s"
    - - name: hello2b
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "10s"
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [sleep]
      args: ["{{inputs.parameters.message}}"]
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value2"
    effect: "NoSchedule"
```
```
Name:           steps-wnth4-700877309
Namespace:      default
Priority:       0
Node:          10.224.4.195/10.224.4.195
Start Time:     Sun, 09 Aug 2020 15:28:48 +0800
Labels:         workflows.argoproj.io/completed=false
                workflows.argoproj.io/workflow=steps-wnth4
Annotations:    workflows.argoproj.io/node-name: steps-wnth4[0].hello1
                workflows.argoproj.io/outputs: {"exitCode":"0"}
                workflows.argoproj.io/template:
                  {"name":"whalesay","arguments":{},"inputs":{"parameters":[{"name":"message","value":"1s"}]},"outputs":{},"metadata":{},"container":{"name"...
Status:         Succeeded
IP:             172.20.13.183
IPs:            <none>
Controlled By:  Workflow/steps-wnth4
Containers:
  wait:
    Container ID:  docker://43baf9495882556a6d15a7b8e7e73f4068802788f5e087564e2a8368b33c3d37
    Image:         argoproj/argoexec:v2.9.3
    Image ID:      docker-pullable://argoproj/argoexec@sha256:a25cbe11d210b67e9621fecd4505e3438d0dd3ce8fc5e8d3dea1bbc2adb853f6
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 09 Aug 2020 15:28:49 +0800
      Finished:     Sun, 09 Aug 2020 15:29:00 +0800
    Ready:          False
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:  steps-wnth4-700877309 (v1:metadata.name)
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /var/run/docker.sock from docker-sock (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hrm5j (ro)
  main:
    Container ID:  docker://fb8ed24f9eb8e7a47b42ad108c91d2992a71a6a3d2c4d096d46c67209134d074
    Image:         docker/whalesay
    Image ID:      docker-pullable://docker/whalesay@sha256:178598e51a26abbc958b8a2e48825c90bc22e641de3d31e18aaf55f3258ba93b
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
    Args:
      1s
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 09 Aug 2020 15:28:59 +0800
      Finished:     Sun, 09 Aug 2020 15:29:00 +0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hrm5j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  podmetadata:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations -> annotations
  docker-sock:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  Socket
  default-token-hrm5j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hrm5j
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     key1=value2:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```
# 2 analysis code
It will add tmpl.Tolerations or wfSpec.Tolerations before it create pod, so I understand the second case.

But why the tmpl.Tolerations is nil which expected has toleration key1 
```
//operate-->executeTemplate-->executeContainer-->createWorkflowPod-->addSchedulingConstraints
// addSchedulingConstraints applies any node selectors or affinity rules to the pod, either set in the workflow or the template
func addSchedulingConstraints(pod *apiv1.Pod, wfSpec *wfv1.WorkflowSpec, tmpl *wfv1.Template) {
	...
	// Set tolerations (if specified)
	if len(tmpl.Tolerations) > 0 {
		pod.Spec.Tolerations = tmpl.Tolerations
	} else if len(wfSpec.Tolerations) > 0 {
		pod.Spec.Tolerations = wfSpec.Tolerations
	}
    ...
}
```

father Template use func resolveTemplateImpl just finds the son Template, it discards some father's field, such as tolerations、Volumes、NodeSelectors and so on.
so when we create the pod of step, it lost the tolerations  seted by steps Template.
```
func (ctx *Context) resolveTemplateImpl(tmplHolder wfv1.TemplateReferenceHolder, depth int) (*Context, *wfv1.Template, bool, error) {
...
	var tmpl *wfv1.Template
...
	if tmpl != nil {
		ctx.log.Debug("Found stored template")
	} else {
		// Find newly appeared template.
		newTmpl, err := ctx.GetTemplate(tmplHolder)
		if err != nil {
			return nil, nil, false, err
		}
...
		tmpl = newTmpl
	}

	// Update the template base of the context.
	newTmplCtx, err := ctx.WithTemplateHolder(tmplHolder)
	if err != nil {
		return nil, nil, false, err
	}

	// Return a concrete template without digging into it.
	if tmpl.GetType() != wfv1.TemplateTypeUnknown {
		return newTmplCtx, tmpl, templateStored, nil
	}

	// Dig into nested references with new template base.
	finalTmplCtx, resolvedTmpl, templateStoredInCall, err := newTmplCtx.resolveTemplateImpl(tmpl, depth+1)
	if err != nil {
		return nil, nil, false, err
	}
	...
	// Merge the referred template into the original.
	mergedTmpl, err := common.MergeReferredTemplate(tmpl, resolvedTmpl)
	if err != nil {
		return nil, nil, false, err
	}

	return finalTmplCtx, mergedTmpl, templateStored, nil
}
```

I suggest add some father Template's fields before return son Template.

**Comment by alexec** [comment]
Can I play this back so I can see if I understand. Do you expect that a pod's tolerations should be inherited from their parent step or DAG? But that is not the case?

**Comment by leileiwan** [comment]
Yes，if we have many steps，all the steps have different tolerations but the same container. Now, we can only create may different container Template，because the tolerations  seted for steps Template is unuseful.

**Comment by leileiwan** [comment]
@alexec what's your suggestion

**Comment by alexec** [comment]
Ok. Labelling as `enhancement` .

**Comment by alexec** [comment]
@sarabala1979 thinks he has a way to solve this without making code changes. He will comment shortly.

**Comment by leileiwan** [comment]
@sarabala1979 Could show your suggestions？

**Comment by sarabala1979** [comment]
@leileiwan  Sorry for the delay, you can use `podspecpatch` to pass the parameter to pod spec

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: effect
            value: "NoSchedule"
          - name: key
            value: "key1"
          - name: operator
            value: "Equal"
          - name: value
            value: "value1"

      - name: hello2a
        template: whalesay
        arguments:
          parameters:
          - name: effect
            value: "NoSchedule"
          - name: key
            value: "key2"
          - name: operator
            value: "Equal"
          - name: value
            value: "value2"
      - name: hello2b
        template: whalesay
        arguments:
          parameters:
          - name: effect
            value: "NoSchedule"
          - name: key
            value: "key3"
          - name: operator
            value: "Equal"
          - name: value
            value: "value3"

  - name: whalesay
    podSpecPatch: '{"tolerations":[{"effect":"{{inputs.parameters.effect}}","key":"{{inputs.parameters.key}}","operator":"{{inputs.parameters.operator}}","value":"{{inputs.parameters.value}}"}]}'
#    podSpecPatch:
    inputs:
      parameters:
      - name: effect
      - name: key
      - name: operator
      - name: value
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.effect}}"]
```
