### ISSUE TITLE
Argo OnExit does not work properly when using step template in a dag

### ISSUE THREAD

**Issue by sh-tatsuno** [argoproj/argo#3710]
## Summary 

Argo OnExit does not work properly when using step template in a dag

## Diagnostics

Argo version: v2.9.4

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-primay-branch-
spec:
  entrypoint: statis
  templates:
  - name: a
    container:
      image:  docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
  - name: exit
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["exit!"]
  - name: steps
    steps:
      - - name: step-a
          template: a
  - name: statis
    dag:
      tasks:
      - name: A
        onExit: exit
        template: steps # <--- if change "a", it works!!
```

In above case, exit will never be called.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
