### ISSUE TITLE
Submit raw workflow to the REST api

### ISSUE THREAD

**Issue by laymain** [argoproj/argo#3712]
# Summary

Can we send directly raw yaml workflows to the REST api?  
It seems that it is possible using K8s API but it is not documented anymore: #1163 and #1757.

# Motivation

I would appreciate to describe my workflows in YAML and submit them directly to the API,  
without the need to convert them into the [OpenAPI format](https://argoproj.github.io/argo/swagger/).

**Comment by alexec** [comment]
In short - no. You must use the Open API format as described. However, you can submit YAML and that YAML contains the workflow itself:

https://argoproj.github.io/argo/swagger/#post_2

**Comment by laymain** [comment]
If I follow the documentation of the [POST /api/v1/workflows/{namespace}](https://argoproj.github.io/argo/swagger/#post_7) endpoint, I have to submit a [io.argoproj.workflow.v1alpha1.WorkflowCreateRequest](https://argoproj.github.io/argo/swagger/#ioargoprojworkflowv1alpha1workflowcreaterequest) that indeed contains the workflow.

Something like that should work:

```yaml
curl --location --request POST 'http://localhost:2746/api/v1/workflows/argo' \
--header 'Content-Type: application/yaml' \
--data-raw 'workflow:
  apiVersion: argoproj.io/v1alpha1
  kind: Workflow
  metadata:
    generateName: hello-world-
    labels:
      workflows.argoproj.io/archive-strategy: "false"
  spec:
    entrypoint: whalesay
    templates:
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
'
```

But I get

```json
{
  "error":"invalid character 'w' looking for beginning of value",
  "code":3,
  "message":"invalid character 'w' looking for beginning of value"
}
```

Since when does the API supports YAML? Or am I just using the wrong `Content-Type`?
