### ISSUE TITLE
OnExit handler overrides logs from main containers

### ISSUE THREAD

**Issue by rmgpinto** [argoproj/argo#3732]
## Summary 

What happened/what you expected to happen?
OnExit handler is overriding logs from main containers

## Diagnostics

What version of Argo Workflows are you running?
2.9.5 and tried with 2.10.0-rc6 as well.

```yaml
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-08-11T02:00:10Z"
  generateName: crunchbase-
  generation: 22
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/cron-workflow: crunchbase
    workflows.argoproj.io/phase: Succeeded
  name: crunchbase-skqjd
  namespace: argo
spec:
  arguments: {}
  entrypoint: crunchbase-dag
  onExit: exit-handler
  templates:
  - arguments: {}
    dag:
      tasks:
      - arguments: {}
        name: crunchbase-fetch
        template: ""
        templateRef:
          name: crunchbase-fetch-template
          template: crunchbase-fetch
      - arguments: {}
        dependencies:
        - crunchbase-fetch
        name: crunchbase-ingestion
        template: ""
        templateRef:
          name: crunchbase-ingestion-template
          template: crunchbase-ingestion
      - arguments: {}
        dependencies:
        - crunchbase-fetch
        name: crunchbase-delete-timestamp-tables
        template: ""
        templateRef:
          name: crunchbase-delete-timestamp-tables-template
          template: crunchbase-delete-timestamp-tables
    inputs: {}
    metadata: {}
    name: crunchbase-dag
    outputs: {}
  - arguments: {}
    inputs: {}
    metadata: {}
    name: exit-handler
    outputs: {}
    steps:
    - - arguments: {}
        name: slack-notify
        templateRef:
          name: slack-notify-template
          template: slack-notify
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-08-11T02:17:04Z"
  nodes:
    crunchbase-skqjd:
      children:
      - crunchbase-skqjd-967124738
      displayName: crunchbase-skqjd
      finishedAt: "2020-08-11T02:16:55Z"
      id: crunchbase-skqjd
      name: crunchbase-skqjd
      outboundNodes:
      - crunchbase-skqjd-2112004410
      - crunchbase-skqjd-3615769241
      phase: Succeeded
      startedAt: "2020-08-11T02:00:21Z"
      templateName: crunchbase-dag
      templateScope: local/crunchbase-skqjd
      type: DAG
    crunchbase-skqjd-1076882:
      children:
      - crunchbase-skqjd-867507988
      displayName: crunchbase-skqjd.onExit
      finishedAt: "2020-08-11T02:17:04Z"
      id: crunchbase-skqjd-1076882
      name: crunchbase-skqjd.onExit
      outboundNodes:
      - crunchbase-skqjd-2622408395
      phase: Succeeded
      startedAt: "2020-08-11T02:16:55Z"
      templateName: exit-handler
      templateScope: local/crunchbase-skqjd
      type: Steps
    crunchbase-skqjd-867507988:
      boundaryID: crunchbase-skqjd-1076882
      children:
      - crunchbase-skqjd-2072922104
      displayName: '[0]'
      finishedAt: "2020-08-11T02:17:04Z"
      id: crunchbase-skqjd-867507988
      name: crunchbase-skqjd.onExit[0]
      phase: Succeeded
      startedAt: "2020-08-11T02:16:55Z"
      templateName: exit-handler
      templateScope: local/crunchbase-skqjd
      type: StepGroup
    crunchbase-skqjd-967124738:
      boundaryID: crunchbase-skqjd
      children:
      - crunchbase-skqjd-4071112825
      displayName: crunchbase-fetch
      finishedAt: "2020-08-11T02:11:33Z"
      id: crunchbase-skqjd-967124738
      name: crunchbase-skqjd.crunchbase-fetch
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "0"
      phase: Succeeded
      startedAt: "2020-08-11T02:00:21Z"
      templateRef:
        name: crunchbase-fetch-template
        template: crunchbase-fetch
      templateScope: local/crunchbase-skqjd
      type: Retry
    crunchbase-skqjd-1105969212:
      boundaryID: crunchbase-skqjd
      children:
      - crunchbase-skqjd-1507863031
      - crunchbase-skqjd-2112004410
      displayName: crunchbase-ingestion
      finishedAt: "2020-08-11T02:16:55Z"
      id: crunchbase-skqjd-1105969212
      name: crunchbase-skqjd.crunchbase-ingestion
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "0"
      phase: Succeeded
      startedAt: "2020-08-11T02:11:33Z"
      templateRef:
        name: crunchbase-ingestion-template
        template: crunchbase-ingestion
      templateScope: local/crunchbase-skqjd
      type: Retry
    crunchbase-skqjd-1507863031:
      boundaryID: crunchbase-skqjd
      displayName: crunchbase-ingestion(0)
      finishedAt: "2020-08-11T02:12:45Z"
      hostNodeName: ip-10-1-10-6.eu-west-1.compute.internal
      id: crunchbase-skqjd-1507863031
      message: failed with exit code 255
      name: crunchbase-skqjd.crunchbase-ingestion(0)
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "255"
      phase: Failed
      resourcesDuration:
        cpu: 111
        memory: 111
      startedAt: "2020-08-11T02:11:33Z"
      templateRef:
        name: crunchbase-ingestion-template
        template: crunchbase-ingestion
      templateScope: local/crunchbase-skqjd
      type: Pod
    crunchbase-skqjd-2072922104:
      boundaryID: crunchbase-skqjd-1076882
      children:
      - crunchbase-skqjd-2622408395
      displayName: slack-notify
      finishedAt: "2020-08-11T02:17:04Z"
      id: crunchbase-skqjd-2072922104
      name: crunchbase-skqjd.onExit[0].slack-notify
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "0"
      phase: Succeeded
      startedAt: "2020-08-11T02:16:55Z"
      templateRef:
        name: slack-notify-template
        template: slack-notify
      templateScope: local/crunchbase-skqjd
      type: Retry
    crunchbase-skqjd-2112004410:
      boundaryID: crunchbase-skqjd
      displayName: crunchbase-ingestion(1)
      finishedAt: "2020-08-11T02:16:54Z"
      hostNodeName: ip-10-1-20-251.eu-west-1.compute.internal
      id: crunchbase-skqjd-2112004410
      name: crunchbase-skqjd.crunchbase-ingestion(1)
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 488
        memory: 488
      startedAt: "2020-08-11T02:12:46Z"
      templateRef:
        name: crunchbase-ingestion-template
        template: crunchbase-ingestion
      templateScope: local/crunchbase-skqjd
      type: Pod
    crunchbase-skqjd-2622408395:
      boundaryID: crunchbase-skqjd-1076882
      displayName: slack-notify(0)
      finishedAt: "2020-08-11T02:17:03Z"
      hostNodeName: ip-10-1-10-232.eu-west-1.compute.internal
      id: crunchbase-skqjd-2622408395
      name: crunchbase-skqjd.onExit[0].slack-notify(0)
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 6
        memory: 6
      startedAt: "2020-08-11T02:16:55Z"
      templateRef:
        name: slack-notify-template
        template: slack-notify
      templateScope: local/crunchbase-skqjd
      type: Pod
    crunchbase-skqjd-3615769241:
      boundaryID: crunchbase-skqjd
      displayName: crunchbase-delete-timestamp-tables(0)
      finishedAt: "2020-08-11T02:11:50Z"
      hostNodeName: ip-10-1-30-111.eu-west-1.compute.internal
      id: crunchbase-skqjd-3615769241
      name: crunchbase-skqjd.crunchbase-delete-timestamp-tables(0)
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 27
        memory: 27
      startedAt: "2020-08-11T02:11:33Z"
      templateRef:
        name: crunchbase-delete-timestamp-tables-template
        template: crunchbase-delete-timestamp-tables
      templateScope: local/crunchbase-skqjd
      type: Pod
    crunchbase-skqjd-3679545890:
      boundaryID: crunchbase-skqjd
      children:
      - crunchbase-skqjd-3615769241
      displayName: crunchbase-delete-timestamp-tables
      finishedAt: "2020-08-11T02:11:52Z"
      id: crunchbase-skqjd-3679545890
      name: crunchbase-skqjd.crunchbase-delete-timestamp-tables
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "0"
      phase: Succeeded
      startedAt: "2020-08-11T02:11:33Z"
      templateRef:
        name: crunchbase-delete-timestamp-tables-template
        template: crunchbase-delete-timestamp-tables
      templateScope: local/crunchbase-skqjd
      type: Retry
    crunchbase-skqjd-4071112825:
      boundaryID: crunchbase-skqjd
      children:
      - crunchbase-skqjd-3679545890
      - crunchbase-skqjd-1105969212
      displayName: crunchbase-fetch(0)
      finishedAt: "2020-08-11T02:11:31Z"
      hostNodeName: ip-10-1-20-182.eu-west-1.compute.internal
      id: crunchbase-skqjd-4071112825
      name: crunchbase-skqjd.crunchbase-fetch(0)
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log
            region: eu-west-1
            secretKeySecret:
              key: ""
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1043
        memory: 10860
      startedAt: "2020-08-11T02:00:21Z"
      templateRef:
        name: crunchbase-fetch-template
        template: crunchbase-fetch
      templateScope: local/crunchbase-skqjd
      type: Pod
  phase: Succeeded
  resourcesDuration:
    cpu: 1675
    memory: 11492
  startedAt: "2020-08-11T02:00:17Z"
  storedTemplates:
    namespaced/crunchbase-delete-timestamp-tables-template/crunchbase-delete-timestamp-tables:
      arguments: {}
      container:
        command:
        - python3
        - /maintenance/delete_timestamp_tables.py
        env:
        - name: AWS_DEFAULT_REGION
          value: eu-west-1
        - name: ENVIRONMENT
          value: prod
        - name: DAG
          value: crunchbase
        image: 860825859229.dkr.ecr.eu-west-1.amazonaws.com/prod-maintenance:latest
        imagePullPolicy: Always
        name: ""
        resources: {}
      initContainers:
      - command:
        - /bin/sh
        - -c
        - apk add curl && while [ `curl -s -o /prod/null -w "%{http_code}" 'http://169.254.169.254/latest/meta-data/iam/security-credentials/prod-argo-iam-role'`
          != '200' ]; do sleep 5; done
        image: alpine:latest
        name: init
        resources: {}
      inputs: {}
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          iam.amazonaws.com/role: prod-argo-iam-role
      name: crunchbase-delete-timestamp-tables
      nodeSelector:
        component: fetch
        service: data-pipelines
      outputs: {}
      retryStrategy:
        limit: 3
    namespaced/crunchbase-fetch-template/crunchbase-fetch:
      arguments: {}
      container:
        env:
        - name: AWS_DEFAULT_REGION
          value: eu-west-1
        - name: ENVIRONMENT
          value: prod
        image: 860825859229.dkr.ecr.eu-west-1.amazonaws.com/prod-crunchbase:latest
        imagePullPolicy: Always
        name: ""
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
      initContainers:
      - command:
        - /bin/sh
        - -c
        - apk add curl && while [ `curl -s -o /prod/null -w "%{http_code}" 'http://169.254.169.254/latest/meta-data/iam/security-credentials/prod-argo-iam-role'`
          != '200' ]; do sleep 5; done
        image: alpine:latest
        name: init
        resources: {}
      inputs: {}
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          iam.amazonaws.com/role: prod-argo-iam-role
      name: crunchbase-fetch
      nodeSelector:
        component: fetch
        service: data-pipelines
      outputs: {}
      retryStrategy:
        limit: 3
    namespaced/crunchbase-ingestion-template/crunchbase-ingestion:
      arguments: {}
      container:
        env:
        - name: AWS_DEFAULT_REGION
          value: eu-west-1
        - name: ENVIRONMENT
          value: prod
        - name: DAG
          value: crunchbase
        - name: ECR_IMAGE
          value: 860825859229.dkr.ecr.eu-west-1.amazonaws.com/prod-ingestion:latest
        - name: SPARK_EXECUTOR_INSTANCES
          value: "4"
        - name: SPARK_EXECUTOR_CPU
          value: 850m
        - name: SPARK_DRIVER_MEMORY
          value: 4g
        - name: SPARK_EXECUTOR_MEMORY
          value: 2g
        image: 860825859229.dkr.ecr.eu-west-1.amazonaws.com/prod-ingestion:latest
        imagePullPolicy: Always
        name: ""
        resources: {}
        volumeMounts:
        - mountPath: /opt/spark/jars/hive-site.xml
          name: hive-metastore-config
          subPath: hive-site.xml
      initContainers:
      - command:
        - /bin/sh
        - -c
        - apk add curl && while [ `curl -s -o /prod/null -w "%{http_code}" 'http://169.254.169.254/latest/meta-data/iam/security-credentials/prod-argo-iam-role'`
          != '200' ]; do sleep 5; done
        image: alpine:latest
        name: init
        resources: {}
      inputs: {}
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          iam.amazonaws.com/role: prod-argo-iam-role
      name: crunchbase-ingestion
      nodeSelector:
        component: ingestion
        service: data-pipelines
      outputs: {}
      retryStrategy:
        limit: 3
      volumes:
      - configMap:
          name: hive-metastore-config
        name: hive-metastore-config
    namespaced/slack-notify-template/slack-notify:
      arguments: {}
      container:
        env:
        - name: AWS_DEFAULT_REGION
          value: eu-west-1
        - name: ENVIRONMENT
          value: prod
        - name: WORKFLOW_NAME
          value: '{{workflow.name}}'
        - name: WORKFLOW_STATUS
          value: '{{workflow.status}}'
        - name: WORKFLOW_FAILURES
          value: '{{workflow.failures}}'
        - name: WORKFLOW_CREATION_TIMESTAMP
          value: '{{workflow.creationTimestamp}}'
        image: 860825859229.dkr.ecr.eu-west-1.amazonaws.com/prod-slack-notify:latest
        imagePullPolicy: Always
        name: ""
        resources: {}
      initContainers:
      - command:
        - /bin/sh
        - -c
        - apk add curl && while [ `curl -s -o /prod/null -w "%{http_code}" 'http://169.254.169.254/latest/meta-data/iam/security-credentials/prod-argo-iam-role'`
          != '200' ]; do sleep 5; done
        image: alpine:latest
        name: init
        resources: {}
      inputs: {}
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          iam.amazonaws.com/role: prod-argo-iam-role
      name: slack-notify
      nodeSelector:
        service: cluster-management
      outputs: {}
      retryStrategy:
        limit: 3
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

time="2020-08-11T15:20:19Z" level=warning msg="Workflow 'crunchbase-skqjd' from CronWorkflow 'crunchbase' completed"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Will take a look

**Comment by simster7** [comment]
It seems like all your outputs have the same `key`:

```yaml
artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: ""
            bucket: backups-prod
            endpoint: s3.amazonaws.com
            insecure: false
            key: argo-logs/main.log    # <- they all share this key!
            region: eu-west-1
            secretKeySecret:
              key: ""
```

So they are likely overwriting each other. Have you set a `keyFormat` as in [this example](https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md#s3-compatible-artifact-repository-bucket-such-as-aws-gcs-minio-and-alibaba-cloud-oss)?
