### ISSUE TITLE
Access Properties of JSON Output Individually

### ISSUE THREAD

**Issue by moorepatrick** [argoproj/argo#3733]
# Summary

I would like to know if it is possible to to access the properties of a JSON output directly.

# Motivation

Instead of creating multiple outputs, I would like to save a single json file and access the contained properties as needed. Using `withParams` and `item` is close, but using that multiple times in series appears to be blocked by https://github.com/argoproj/argo/issues/3182.

Example usage with a modified https://github.com/argoproj/argo/blob/master/examples/pod-spec-from-previous-step.yaml

See `setup-resources-tmpl.podSpecPatch`

```apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pod-spec-from-previous-step-
spec:
  entrypoint: workflow
  templates:
  - name: workflow
    dag:
      tasks:
      - name: parse-resources
        template: parse-resources-tmpl
      - name: setup-resources
        dependencies: [parse-resources]
        template: setup-resources-tmpl
        arguments:
          parameters:
            - name: resources
              value: "{{tasks.parse-resources.outputs.parameters.resources}}"

  - name: parse-resources-tmpl
    outputs:
      parameters:
        - name: resources
          valueFrom:
            path: /tmp/resources.json
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo '{"memory": "10Gi", "cpu": "2000m"}' > /tmp/resources.json && cat /tmp/resources.json

  - name: setup-resources-tmpl
    inputs:
      parameters:
      - name: resources
    podSpecPatch: '{"containers":[{"name":"main", "resources":{"limits": {"memory": {{inputs.parameters.resources.memory}}, "cpu": {{inputs.parameters.resources.cpu}}}, "requests": {"memory": {{inputs.parameters.resources.memory}}, "cpu": {{inputs.parameters.resources.cpu}}}'
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo {{inputs.parameters.resources}}
```

**Comment by sarabala1979** [comment]
@moorepatrick  I am trying to understand your question. Are you asking JSON input parameter can be accessed by its elements instead of the whole JSON? if yes, It won't support as first-class support in argo. The current parameter will support multiple data types. In your case container or script needs to parse the JSON or add an intermediate step to parse and output it as output parameters. 
Here the example:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: json-parsing-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: json
        template: json-parsing
        arguments:
          parameters:
          - name: json
            value: '{"memory": "10Gi", "cpu": "2000m"}'
    - - name: print
        template: print
        arguments:
          parameters:
            - name: memory
              value: "{{steps.json.outputs.parameters.memory}}"
            - name: cpu
              value: "{{steps.json.outputs.parameters.cpu}}"
  - name: print
    inputs:
      parameters:
        - name: memory
        - name: cpu
    script:
      image: debian:9.4
      command: [bash]
      source: |
        echo {{inputs.parameters.memory}} {{inputs.parameters.cpu}}

  - name: json-parsing
    inputs:
      parameters:
      - name: json
      artifacts:
      - name: message
        path: test.json
        raw:
          data: |
            {{inputs.parameters.json}}
    outputs:
      parameters:
        - name: memory
          valueFrom:
            path: mem.txt
        - name: cpu
          valueFrom:
            path: cpu.txt
    container:
      image: stedolan/jq
      command: [sh, -c]
      args: [" jq <  test.json '.memory' > mem.txt | jq <  test.json '.cpu' > cpu.txt  "]

```
