### ISSUE TITLE
Small correction to workflow template dag example

### ISSUE THREAD

**Issue by dynamicmindset** [argoproj/argo#3735]
# Summary

What change needs making?

[dag example](https://github.com/argoproj/argo/blob/master/examples/workflow-template/dag.yaml) passes arguments to a `DagTemplate` ref that [does not have inputs](https://github.com/argoproj/argo/blob/master/examples/workflow-template/templates.yaml#L92).

```
      - name: C
        dependencies: [A]
        templateRef:
          name: workflow-template-inner-dag
          template: inner-diamond
        arguments:
          parameters:
          - name: message
            value: C
```
This can be confusing for a newcomer.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
