### ISSUE TITLE
Output artifacts are uploaded even when the container failed

### ISSUE THREAD

**Issue by fangpenlin** [argoproj/argo#3761]
## Summary 

Output artifacts are uploaded even when the container failed.

Artifacts shouldn't be uploaded if the container failed.

Not sure is this a feature by design or a bug, but as it's very surprising to me, and took me very long time to debug, so I would report it as a bug. The background, I have a process keeps writing data to a file, and I add the file to artifacts to be uploaded once it finished. I also set a livenessProbe to ensure that worker is healthy. Sometimes, the process got killed and the process exited with code 137. And I realize the output file is uploaded anyway. I have an upfront skipping check for the existence of the file in my GCP bucket. The side effect of uploading the artifacts even when container failed is to have an incomplete file in the cloud storage and my retry task will think it's done already and skip.

I tried my best to find an option for turning off uploading artifacts no matter what, but cannot find any so far. I think in many cases uploading artifacts when container fails still make sense, like keep the error log in the cloud storage. It's very easy to workaround, I can just upload the file with a command line in the container script, but just wonder maybe it would be nice to have an option to disable it? So that I can still utilize the benefits of artifact output. I think it could be something like a `when` keyword for a task but for artifacts instead?

## Diagnostics

What version of Argo Workflows are you running?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: reproduce-bug-
spec:
  entrypoint: upload 
  templates:
  - name: upload
    script:
      image: python:3
      command: [bash]
      source: |
        set -e
        echo "hi" > /var/my-file
        sleep 10
        exit 1
      resources:
        requests:
          cpu: 250m
    outputs:
      artifacts:
      - name: my-file
        path: /var/my-file
        optional: true
        archive:
          none: {}
        s3:
          endpoint: storage.googleapis.com
          bucket: my-bucket-data
          key: _tmp/my-file
          accessKeySecret:
            name: argo-secrets
            key: gcs.s3.access.key
          secretKeySecret:
            name: argo-secrets
            key: gcs.s3.secret.key

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
