### ISSUE TITLE
artifacts/parameters between workflows

### ISSUE THREAD

**Issue by BIGBALLON** [argoproj/argo#3796]
Hi, all:

There are two workflow templates ``ta`` and ``tb``, 

```bash
argo template create ta.yaml 
argo template create tb.yaml 
```

and I want to use ``workflowTemplateRef`` to trigger them
(We are using Argo Workflow v 2.9.5).

But I want to use workflow ``ta``'s output(parameters or artifacts) in workflow ``tb``, which means I want send ``ta``'s output to ``tb``, Is there any way to do that?

Thanks a lot!!!

**Comment by sarabala1979** [comment]
you can pass `parameters and artifacts` from one template to another template using `arguments`
Here the example.  Please refer `workflow-template-inner-steps`
https://github.com/argoproj/argo/blob/master/examples/workflow-template/templates.yaml

**Comment by BIGBALLON** [comment]
@sarabala1979 thanks for your reply, 

I still have a question, for the following WorkflowTemplate ``ta``, how can I send the parameter ``hello-param`` to another template(e.g. ``tb``)
 
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-outputs
spec:
  entrypoint: whalesay-outputs
  templates:
  - name: whalesay-outputs
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; echo -n hello world > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello-param
        valueFrom:
          default: "Foobar"   # Default value to use if retrieving valueFrom fails. If not provided workflow will fail instead
          path: /tmp/hello_world.txt
```

**Comment by sarabala1979** [comment]
just you can refer `{{steps.<name>.output.parameters.<name>}}'
Here the examble
```
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-outputs
spec:
  entrypoint: step
  templates:
  - name: step
    steps:
    - - name: generate
        template: whalesay-outputs
    - - name: pass-to-wft
        templateRef:
          name: workflow-template-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
            - name: message
              value: "{{steps.generate.outputs.parameters.hello-param}}"
  - name: whalesay-outputs
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; echo -n hello world > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello-param
        valueFrom:
          default: "Foobar"   # Default value to use if retrieving valueFrom fails. If not provided workflow will fail instead
          path: /tmp/hello_world.txt
```
