### ISSUE TITLE
Better YAML validation for template inputs

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#38]
YAML validator is allowing some user errors to slip through by allowing

```
inputs:
  artifacts:
    CODE:
      from: "%%asdf%%"
      path: /src
```
Where `%%asdf%%` is not resolvable.
