### ISSUE TITLE
WorkflowEventBinding not working

### ISSUE THREAD

**Issue by simonfrey** [argoproj/argo#3817]
If I try to apply the example workflow event binding:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-consumer
  namespace: argo
spec:
  event:
    selector: payload.message != "" && metadata["x-argo"] == ["true"] && discriminator == "my-discriminator"
  submit:
    workflowTemplateRef:
      name: workflow-template-submittable
    arguments:
      parameters:
        - name: message
          valueFrom:
            event: payload.message
```
I get following error:
```
error: unable to recognize "event_workflow.yml": no matches for kind "WorkflowEventBinding" in version "argoproj.io/v1alpha1"
```

---

In the [documentation is noted](https://argoproj.github.io/argo/events/) that events are available from version 2.11 on and dockerhub offers tags [up to 2.10](https://hub.docker.com/r/argoproj/workflow-controller/tags).

How can I pull and use events for my argo workflows as even github shows only releases up to 2.10? Does that mean they are not available yet? If yes when will they be?
