### ISSUE TITLE
successfulJobsHistoryLimit, failedJobsHistoryLimit with cron workflow is not working

### ISSUE THREAD

**Issue by prateekkhera** [argoproj/argo#3833]
## Summary 

The successfulJobsHistoryLimit, failedJobsHistoryLimit with cron workflow is not working for us. I tested with simple cron workflows and works fine. But, in our cron, we are calling workflow templates using templateRef which in turn calls for another workflow template using templateRef that has the container definition. Could this nesting be causing the issue? Here's the snippet for cron:

![image](https://user-images.githubusercontent.com/22524153/90785966-9f57a000-e320-11ea-9209-ff35e833e975.png)

What happened/what you expected to happen?

Completed workflows should be deleted as per their status and parameters successfulJobsHistoryLimit, failedJobsHistoryLimit 

What version of Argo Workflows are you running?

2.9.5. Similar, issue was there with 2.9.3 too, which we're using

**Comment by simster7** [comment]
> Could this nesting be causing the issue?

Not likely. If it works for one CronWorkflow, it should work for the rest. Can you dig through your `workflow-controller` logs and see if you find something relevant for this? Searching for this string will help: `Enforcing history limit for '<CWF_NAME>'`

**Comment by prateekkhera** [comment]
Thanks @simster7 for commenting, I can see still issue despite seeing the string you mentioned in the workflow controller logs. Closing the issue as don't have time right now to dig more, will re-open if I get to see again in future

**Comment by alanyu9857** [comment]
it still not working in 3.3.10

**Comment by layoaster** [comment]
I can confirm this is not working on 3.4.3. I'm also using a CronWorkflow that calls WorkflowTemplate like the OP.

In my case I have two different cronjobs: 
* Hourly ( with a history of the last 24 jobs)
* Daily (with a history of the last 7 jobs)

I can only see the workflow of the last executed job in the case of the hourly jobs, I don't get any workflow of the daily jobs.

* Hourly 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dremel-druid-cron-hourly-historical-reindex-prod
  labels:
    project: dremel
    app: druid
    env: production
spec:

  schedule: "1 * * * *"
  suspend: false
  # Allowed to start within the next 58 minutes
  startingDeadlineSeconds: 3480
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 24
  failedJobsHistoryLimit: 24

  workflowMetadata:
    labels:
      project: dremel
      app: druid
      pipeline-type: cron
      env: production

  workflowSpec:

    archiveLogs: true

    ttlStrategy:
      secondsAfterCompletion: 86400  # 24 hours
      secondsAfterSuccess: 86400     # 24 hours
      secondsAfterFailure: 86400     # 24 hours

    arguments:
      parameters:
        # Repo
        - name: target_env
          value: "production"
        # Docker image
        - name: docker_image
          value: ""
        # Docker version tag
        - name: docker_tag
          value: "4.1.1"

    workflowTemplateRef:
      name: dremel-druid-cron-hourly-historical-data-reindex
      clusterScope: false
```

* Daily (pretty much the same)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dremel-druid-cron-daily-historical-reindex-prod
  labels:
    project: dremel
    app: druid
    env: production
spec:

  schedule: "0 2 * * *"
  suspend: false
  # Allowed to start within the next 20 hours
  startingDeadlineSeconds: 72000
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7

  workflowMetadata:
    labels:
      project: dremel
      app: druid
      pipeline-type: cron
      env: production

  workflowSpec:

    archiveLogs: true

    ttlStrategy:
      secondsAfterCompletion: 604800 # 7 days
      secondsAfterSuccess: 604800    # 7 days
      secondsAfterFailure: 604800    # 7 days

    arguments:
      parameters:
        # Repo
        - name: target_env
          value: "production"
        # Docker image
        - name: docker_image
          value: ""
        # Docker version tag
        - name: docker_tag
          value: "4.1.1"

    workflowTemplateRef:
      name: dremel-druid-cron-daily-historical-data-reindex
      clusterScope: false

```
