### ISSUE TITLE
Possible to reference artifact repo by name?

### ISSUE THREAD

**Issue by westonplatter** [argoproj/argo#3845]
# Summary

Is it possible to reference artifact configurations by name?

# Motivation

For the argo deployment we have, we'd like to use multiple artifact repositories since some are faster than others (eg, storing 2-3mb files on Google Cloud Storage vs a NAS). Ideally, I'd like to not have to pass around all connection / credentials each time I read/write to/from a repo.

Does argo have something reference-able like `repoName`?

For example, 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: default
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      repoName: MyArtifactRepo
      bucket: my-bucket
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
      keyFormat: tmp
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generatename: artifact-selection-
  namespace: default
spec:
  entrypoint: select-files-test
  templates:
    - name: select-files-test
      dag:
        tasks:
          - name: make-list
            template: make-list
          - name: create-files
            template: create-files
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
            withParam: "{{tasks.make-list.outputs.result}}"
            dependencies: [make-list]
          - name: save-aggregate-stats
            template: save-aggregate-stats
            dependencies: [create-files]
          - name: needs-file-and-stats
            template: needs-file-and-stats
            arguments:
              parameters:
                - name: prod-id
                  value: "{{item}}"
            withParam: "{{tasks.make-list.outputs.result}}"
            dependencies: [save-aggregate-stats]
    - name: make-list
      container:
        image: alpine:3.7
        command:
         - echo
         - '["M1103401840LE", "M1103401840RE", "M1105737674LE", "M1105737674RE"]'

    - name: create-files
      inputs:
        parameters:
          - name: prod-id
      script:
        image: alpine:3.7
        command: [sh]
        source: |
          head -c 1000 < /dev/urandom > /tmp/{{inputs.parameters.prod-id}}.txt
      outputs:
        artifacts:
          - name: test-file
            path: /tmp/{{inputs.parameters.prod-id}}.txt
            archive:
              none: {}

    - name: save-aggregate-stats
      inputs:
        artifacts:
          - name: created-files
            path: /tmp/
            repoName: MyArtifactRepo
      script:
        image: alpine:3.7
        command: [sh]
        source: |
          ls /tmp > /tmp/list.txt
      outputs:
        artifacts:
          - name: filelist
            path: /tmp/list.txt
            archive:
              none: {}
            repoName: MyArtifactRepo

    - name: needs-file-and-stats
      inputs:
        parameters:
          - name: prod-id
        artifacts:
          - name: created-files
            path: /tmp/{{inputs.parameters.prod-id}}.txt
            repoName: MyArtifactRepo

      script:
        image: alpine:3.7
        command: [sh]
        source: |
          echo /tmp/{{inputs.parameters.prod-id}}.txt
```
