### ISSUE TITLE
Sharing files between Workflow and WorkflowTemplates using volumes

### ISSUE THREAD

**Issue by ramanNarasimhan77** [argoproj/argo#3874]
# Summary

I am trying to define a volume in a `Workflow` and have the same volume accessible in a step that references a `WorkflowTemplate`

# Motivation

Consider I have a workflow with 3 steps. 

```text
Step1: Reads file from s3 and mounts on a pvc

Step2: Ingests data from the file and writes back to pvc

Step3: Processes ingested data and writes result to pvc
```

`Step1` is very generic and I want to write a `WorkflowTemplate` for this functionality so that it can be used by multiple workflows

However I am not clear how `Workflow` and `WorkflowTemplates` can share the same PVC. 
Should the `volumeClaimTemplates` and `volumeMounts` be defined in both Workflow and WorkflowTemplate?

**Comment by sarabala1979** [comment]
Here the example for passing files from template to workflow template

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-steps-
spec:
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        templateRef:
          name: workflow-template-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a
        template: print-message

  - name: print-message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo getting message from volume; find /mnt/vol; cat /mnt/vol/hello_world.txt"]
      volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
```

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo generating message in volume; cowsay hello world | tee /mnt/vol/hello_world.txt"]
      volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
```
