### ISSUE TITLE
Allow passing a variable amount of values for one input parameter into `args` and `command`.

### ISSUE THREAD

**Issue by bartcode** [argoproj/argo#3887]
# Summary

Support input parameters that are lists. Subsequently, allow them to be appended to the `args` or `command` values (see example in `Use Cases`).

# Use Cases
The example below shows what I'd like to use. Be aware how these values are added to the `args` list requires some discussion. I just wrote `|unpack` now, which is a bit of a Pythonic way to similarly add items to a list (`["--numbers", *values]`).

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-
spec:
  entrypoint: do-something
  templates:
    - name: something
      inputs:
        parameters:
          - name: values
      container:
        image: some-image
        args: ["--numbers", "{{inputs.parameters.values|unpack}}"]  # This should somehow become ["--numbers", "1", "3", "6", "9"].

    - name: do-something
      dag:
        tasks:
          - name: do-it
            template: something
            arguments:
              parameters:
                - name: values
                  value: ["1", "3", "6", "9"]  # This is not possible at the moment. It can only be a single value.
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
will it work for you? 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-
spec:
  entrypoint: do-something
  templates:
    - name: something
      inputs:
        parameters:
          - name: values
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo {{inputs.parameters.values}}"]  # This should somehow become ["--numbers", "1", "3", "6", "9"].

    - name: do-something
      dag:
        tasks:
          - name: do-it
            template: something
            arguments:
              parameters:
                - name: values
                  value: '["1", "3", "6", "9"]'
```

**Comment by bartcode** [comment]
Wouldn't say so, no. Because then `["1", "3", "6", "9"]` is still parsed as a single argument instead of multiple.

**Comment by sarabala1979** [comment]
I would recommend adding one more step which will remove the `[]` from string and output `"1", "3", "6", "9"` or if your step is a script template, you can parse it before pass it.  In Argo, all parameters are string. If you want to iterate the JSON array, you can use `withParam`. This will pass each element from arrar to given template

**Comment by bartcode** [comment]
Thanks for your recommendation. I understand your suggestion is a valid workaround. I can imagine it doesn't have any real priority now, but I just think it'd be more convenient in this use case to be able to use lists in parameters as well.

I see this is labelled as `more-information-needed` now. How can I help with that?

**Comment by sarabala1979** [comment]
Thanks for confirming. I will close the issue.   `more-information-needed` is mainly for the user to reply.

**Comment by cal-pratt** [comment]
Is there a more preferred way to post feature requests? Can this be re-opended? This is a big pain for me as well. 

Wrapping the arguments in `sh -c` doesn't seems like the ideal solution to what must be a common issue _(although I wouldn't say I know a better way to implement such a feature)_.

I have a similar thought where I would like to be able to pass a list to my script, and also be able to conditionally set a flag.  e.g.

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: script-templates
spec:
  templates:
    - name: my-cool-script-template
      inputs:
        parameters:
          - name: url_args
          - name: use_flag_args
      container:
        image: some-image
        command: ['/usr/bin/my-cool-script']
        args: [
          "--url-endpoints", 
          "{{ < unpack url_args ?? > }}",
          "{{ < set --use-flag if use_flag arg is true, otherwise nothing ?? > }}",
        ]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: my-cool-script
  namespace: distroflow
spec:
  entrypoint: my-cool-script-template
  arguments:
    parameters:
      - name: url_args
        value: ["href1", "href2"]
      - name: use_flag_args
        value: True
  workflowTemplateRef:
    name: script-templates
```

The application in the container would be invoked like: `/usr/bin/my-cool-script --url-endpoints href1 href2 --use-flag`
