### ISSUE TITLE
Workflow fails to terminate. Possible proxy issue? ("Failed to get pod").

### ISSUE THREAD

**Issue by jdkhong** [argoproj/argo#3893]
## Summary 

I'm setting up a new GKE cluster with Argo v2.9.4 and ran into some issues when running a hello-world workflow test. I'm using the helm charts to build. I'm relatively new to Argo and Kubernetes, so I might be missing something. Also, I am under a corporate proxy. Please let me know if there's additional information that might be helpful in resolving this issue 

**What happened:**

I got `Failed to get pod 'hello-world-b2868': Get https://10.56.9.1:881/api/v1/namespaces/argoproj/pods/hello-world-b2868: proxyconnect tcp: EOF` when running the hello-world workflow from the Getting Started page.

**What you expected to happen:**

I expected the hello-world workflow to complete successfully.

## Diagnostics

What version of Argo Workflows are you running?

```
Environment: 
argo: v2.9.4+20d2ace.dirty
BuildDate: 2020-07-25T08:30:49Z
GitCommit: 20d2ace3d5344db68ce1bc2a250bbb1ba9862613
GitTreeState: dirty
GitTag: v2.9.4
GoVersion: go1.14.5
Compiler: gc
Platform: darwin/amd64
```

kubectl version -o yaml

```
clientVersion:
  buildDate: "2020-07-15T16:58:53Z"
  compiler: gc
  gitCommit: dff82dc0de47299ab66c83c626e08b245ab19037
  gitTreeState: clean
  gitVersion: v1.18.6
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-06-25T22:55:26Z"
  compiler: gc
  gitCommit: baccd25d44f1a0d06ad3190eb508784efbb990a5
  gitTreeState: clean
  gitVersion: v1.16.11-gke.5
  goVersion: go1.13.9b4
  major: "1"
  minor: 16+
  platform: linux/amd64

```

```
Container ID:  docker://8cd85972a4c389239102048f4b50f35fb6e12121
Image:         argo-workflow-argoexec:0.1
Image ID:      docker-pullable:argo-workflow-argoexec@sha256
Port:          <none>
Host Port:     <none>
Command:
    argoexec
    wait
State:          Terminated
    Reason:       Error
    Message:      Failed to establish pod watch: Get https://10.56.9.1:881/api/v1/namespaces/default/pods?fieldSelector=metadata.name%3Dhello-world-6vkjw&watch=true: proxyconnect tcp: EOF
    Exit Code:    1
    Started:      Fri, 28 Aug 2020 16:00:28 +0000
    Finished:     Fri, 28 Aug 2020 16:00:35 +0000
Ready:          False
Restart Count:  0
Requests:
```
