### ISSUE TITLE
Pass artifacts from a dag in a workflow to a dag in a  WorkflowTemplate

### ISSUE THREAD

**Issue by sahil-sawhney** [argoproj/argo#3912]
# Summary

Is there a way by which we can pass artifacts from a task of a dag in a workflow to a task of a dag in a  WorkflowTemplate? Following is an example snippet for the same.

> kind: workflow
> metadata:
>   name: main-workflow
> spec:
>  templates:
>    - name: main-template
>      dag:
>        tasks:
>        - name: A			**_### Task A Generates output artifact named "A-out-artifact"_**
>          template: template-A
>        - name: B
>          templateRef:
>            name: sub-workflow
>            template: sub-template
>          arguments:
>            artifacts:
>            - name: A-out-artifact
>              from: "{{tasks.A.outputs.artifacts.A-out-artifact}}"
> 
> kind: workflowTemplate
> metadata:
>   name: sub-workflow
> spec:
>   templates:
>    - name: sub-template
>      dag:
>        tasks:
>        - name: C
>          template: template-C
>          arguments:
>            artifacts:
>            - name: source-repo
>              from: "{{something.my-artifact}}"

Here what should be the correct value of **{{something.my-artifact}}**?
# Motivation

It would make the passing of artifacts from one dag to another  (in a different workflow template) easy.

**Comment by alexec** [comment]
try "inputs:" rather than "arguments:"?

**Comment by sahil-sawhney** [comment]
@alexec I don't think we can use inputs in DagTasks. Ref -> https://argoproj.github.io/argo/fields/#dagtask

**Comment by sarabala1979** [comment]
@sahil-sawhney yes you can pass the artifacts from DAG to workflowtemplate
Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    dag:
     tasks:
     - name: generate-artifact
       template: whalesay
     - name: consume-artifact
       dependencies: [generate-artifact]
       templateRef:
         name: workflow-template-whalesay-template
         template: print-message
       arguments:
         artifacts:
         - name: message
           from: "{{tasks.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
```

WorkflowTemplate:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: print-message
    inputs:
      artifacts:
        - name: message
          path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```
