### ISSUE TITLE
Realtime Prometheus metrics when status is Successful

### ISSUE THREAD

**Issue by adinhodovic** [argoproj/argo#3925]
# Summary

What do you want to know about this project?

When I create a realtime metric that is only emitted when status is `successful`/`failure` it is automatically converted to `pending`. E.g
```yaml
when: '{{status}} == Succeeded'
gauge:
  realtime: true
  value: '{{workflow.creationTimestamp}}'
```

Gets converted into:
```yaml
when: Pending == Succeeded
gauge:
    value: '{{workflow.creationTimestamp}}'
    realtime: true
```

Argo v2.10.0, is this behaviour intentional?

# Motivation

Why do you need to know this, any examples or use cases you could include?

I'd like to track when the last successful cronjob ran, obv `completionTimestamp` would be better than `creationTimestamp` but the offset of minutes the cronjob ran is ok.
