### ISSUE TITLE
Support interpolated mutex names

### ISSUE THREAD

**Issue by shmargum** [argoproj/argo#3955]
# Summary

It would be useful to be able to use arguments (workflow or even template) in the name field of the `mutex` synchronization.

# Use Cases

This is useful when you have a workflow with many parellielizable steps that may be combined sequentially (regardless of completion order) after completion. There are also other general cases where this is useful.

example:
```yaml
- name: stepx
  synchronization:
    mutex:
      name: "stepx-{{workflow.parameters.paramy}}"
```

+-
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Fixed by #3957

**Comment by geoff-maddock** [comment]
Does this work currently?  I'm in 3.2 but I find that variables are not interpolating in mutex name:

```
    - name: deploy
      synchronization:
        mutex:
          name: "{{input.parameters.host-inventory}}legacy-app"
```

I get an error such as when running two workflows back to back:
```
MESSAGE
Waiting for default/Mutex/{{input.parameters.host-inventory}}legacy-app lock. Lock status: 0/1
```
