### ISSUE TITLE
Kubernetes KIND failing to complete any workflow

### ISSUE THREAD

**Issue by ewassef** [argoproj/argo#3958]
# Summary

When running in Kubernetes KIND with extra volume mounts to the host machines docker sock, the following error occurs in the executor pod every time (Error response from daemon: No such container:). This causes failure even if the other pod succeeds. 

If no extra mount is added, the pods eventually fail with no logs, however, there is an event saying: MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file

# Motivation

All development is conducted on KIND clusters. We are attempting to wrap Argo workflow in our Operators to standardize our CI process

**Comment by ewassef** [comment]
Got an answer in the Slack channel. Posting the answer here in case someone is searching the web for something similar:
Change your `containerRuntimeExecutor` to `pns` in your configmap. This will get it to work with containerd vs dockerd based installations. Thank you Daniel Herman

**Comment by gosoon** [comment]
> Got an answer in the Slack channel. Posting the answer here in case someone is searching the web for something similar:
> Change your `containerRuntimeExecutor` to `pns` in your configmap. This will get it to work with containerd vs dockerd based installations. Thank you Daniel Herman

Can you show the configuration in ConfigMap? There is no default configuration in my ConfigMap.
```
kubectl get cm workflow-controller-configmap -n argo -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"workflow-controller-configmap","namespace":"argo"}}
  creationTimestamp: "2020-09-08T03:47:13Z"
  name: workflow-controller-configmap
  namespace: argo
  resourceVersion: "701849"
  selfLink: /api/v1/namespaces/argo/configmaps/workflow-controller-configmap
  uid: 64a9089e-4fbe-49d5-8b28-c2bb2a99be7e
```

**Comment by ewassef** [comment]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-workflow-controller-configmap
  labels:
    chart: argo-0.10.2
    release: argo
    heritage: Helm
data:
  config: |
    instanceID: INSTANCEID
    containerRuntimeExecutor: docker #change this to pns if on kind
    artifactRepository:
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-minio
        secretKeySecret:
          key: secretkey
          name: argo-minio
        bucket: argo-artifacts
        endpoint: argo-minio:9000
        insecure: true
```
