### ISSUE TITLE
Same workflow executes fine via CLI buit fails via web UI

### ISSUE THREAD

**Issue by zewelor** [argoproj/argo#3959]
## Summary 

What happened/what you expected to happen?

Same yaml works fine when executing via argo cli, but fails to start when uploaded via www UI. Error I'm getting:

```
HTTP 400
{
  "error": "json: cannot unmarshal number into Go struct field EnvVar.workflow.spec.templates.container.env.value of type string",
  "code": 3,
  "message": "json: cannot unmarshal number into Go struct field EnvVar.workflow.spec.templates.container.env.value of type string"
}
```

## Diagnostics

What version of Argo Workflows are you running?
2.10.1

```yaml
    - name: reprocess-single-tfrecords
      container:
        image: image
        env:
        - name: S3_USE_HTTPS
          value: 0
```

I can fix it by quoting '0'. Then it works fine. It works via CLI without quoting. Also it validates via CLI, using ```argo lint``` command.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
