### ISSUE TITLE
How to give integer value to ActiveDeadlineSeconds via parameters

### ISSUE THREAD

**Issue by PranjaliSoni** [argoproj/argo#3970]
I'm trying the following piece of workflow where we pass the value to ActiveDeadlineSeconds(timeout in scripts)via parameters  in arguments in Steps.(have put this piece of code in bolds)

**I'm getting the following error in:**
HTTP 400
{
  "error": "json: cannot unmarshal string into Go struct field Template.workflow.spec.templates.activeDeadlineSeconds of type int64",
  "code": 3,
  "message": "json: cannot unmarshal string into Go struct field Template.workflow.spec.templates.activeDeadlineSeconds of type int64"
}

**How to pass and access integer value via parameters?** 

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: whalesay
  arguments:
    parameters:
    - name: dur
      value: 10
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: dur       # parameter declaration
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo sleeping for 1m; sleep 60; echo done"]
    activeDeadlineSeconds: {{inputs.parameters.dur}}
```
