### ISSUE TITLE
Workflow level retry strategy

### ISSUE THREAD

**Issue by PranjaliSoni** [argoproj/argo#3971]
I have try a piece of code with various steps and dags and retry at each step and have to write the retry piece of code everytime . Can there be a modification where it can be given at one place and used at different places?

For reference: 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamon-coinflip-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
        - name: A
          template: coinflip
          retryStrategy:
            limit: 10
            backoff:
              duration: "1" 
              factor: 2
              maxDuration:  "1d"
        - name: B
          dependencies: [A]
          template: coinflip
          retryStrategy:
            limit: 10
            backoff:
              duration: "1" 
              factor: 2
              maxDuration:  "1d"
        - name: C
          dependencies: [A]
          template: coinflip
          retryStrategy:
            limit: 10
            backoff:
              duration: "1" 
              factor: 2
              maxDuration:  "1d"
        - name: D
          dependencies: [B, C]
          template: coinflip
  - name: coinflip
    steps:
      - - name: flip-coin
          template: flip-coin
          retryStrategy:
            limit: 10
            backoff:
              duration: "1" 
              factor: 2
              maxDuration:  "1d"
      - - name: heads
          template: found-heads
          when: "{{steps.flip-coin.outputs.result}} == heads"
        - name: tails
          template: coinflip
          when: "{{steps.flip-coin.outputs.result}} == tails"
  - name: flip-coin
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)
  - name: found-heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]
```

**Comment by simster7** [comment]
> Can there be a modification where it can be given at one place and used at different places?

Currently not possible. Let me think and see if there is a good way to do this

**Comment by alexec** [comment]
v2.12

**Comment by erhhung** [comment]
If by
> have to write the retry piece of code everytime

you mean you're having to repeat this block of YAML, then it looks like native **YAML anchors and aliases** should help. No special support from Argo itself should be necessary.

```yaml
retryStrategy:
  limit: 10
  backoff:
  duration: "1" 
  factor: 2
  maxDuration:  "1d"
```
