### ISSUE TITLE
Allow HTTP artifacts to set request header(s)

### ISSUE THREAD

**Issue by mecampbellsoup** [argoproj/argo#3980]
# Summary

Currently an HTTP artifact can only specify a URL parameter:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: render-blender
spec:
  templates:
    - name: render
      inputs:
        artifacts:
          - name: foo
            path: /foo.py
            http:
              url: "{{workflow.parameters.api_url}}/files/foo.py"
```

This proposal is to add an additional attribute, e.g. `headers JSON` (or `headers[]`), to be included with the request's headers data:

```yaml
        artifacts:
          - name: secret-script
            path: /secret-script.py
            http:
              url: "{{workflow.parameters.api_url}}/files/secret-script.py"
              headers:
                - name: API_KEY
                  value: "{{workflow.parameters.api_key}}"
```

# Use Cases

When fetching HTTP artifacts from an API that requires authentication and/or authorization.

This way the workflow submitting service, typically the backend API, would be able to send the value for `API_KEY` as a workflow parameter in order to keep this HTTP endpoint protected from the forces of evil.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by goock** [comment]
@mecampbellsoup I have tests in c4d repo and I would like to keep it there. Will this feature allow to download artifacts in CI and let me run tests as usual, before we moved the plugin to backend.

**Comment by alexec** [comment]
This is a good idea. Would you like to submit a PR to add this feature?

**Comment by mecampbellsoup** [comment]
> This is a good idea. Would you like to submit a PR to add this feature?

Yep, will do.

**Comment by mecampbellsoup** [comment]
@alexec I have modified the `HTTPArtifact` type definition to include an optional `headers` map, but I can't seem to locate where the actual HTTP _request_ takes place - could you point me in the right direction?

Here's the change I have made so far:

```go
// HTTPArtifact allows an file served on HTTP to be placed as an input artifact in a container
type HTTPArtifact struct {
	// URL of the artifact
	URL string `json:"url" protobuf:"bytes,1,opt,name=url"`

	// Optional headers to include with the HTTP request for the artifact.
	Headers map[string]string `json:"headers,omitempty" protobuf:"bytes,2,opt,name=headers"`
}
```

**Comment by alexec** [comment]
Search for where curl is called.

**Comment by mecampbellsoup** [comment]
Thanks @alexec that was pretty straightforward to find after all... 😅 

One more thing - will the workflow YAML parsing logic require any changes such that it can make sense of e.g.:

```yaml
inputs:
  artifacts:
    - name: foo
      path: /foo.py
      http:
        url: "{{workflow.parameters.api_url}}/files/foo.py"
        headers:
          - API_KEY: my-secret-api-key-header-value
```
?
