### ISSUE TITLE
Cannot create WorkflowTemplate if using `{{workflow.labels.*}}`

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#3989]
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: test-foobar-
  labels:
    testLabel: foobar
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      resubmitPendingPods: true
      container:
        image: docker/whalesay
      metrics:
        prometheus:
          - name: intuit_data_persistplat_dppselfservice_workflow_test_duration
            help: Duration of workflow
            labels:
              - key: label
                value: "{{workflow.labels.testLabel}}"
            gauge:
              realtime: true
              value: "{{duration}}"
```
Gives
```
Failed to create workflow template: templates.whalesay: failed to resolve {{workflow.labels.testLabel}}
```
