### ISSUE TITLE
Repo information is not populated when workflows are accessed directly

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#40]
Steps to repro:

1. Create a template that does not have the COMMIT as a parameter and commit it into the .argo directory.
```
---
type: container
version: 1
name: my-test-checkout
description: Checks out a source repository to /src
resources:
  mem_mib: 500
  cpu_cores: 0.1
image: argoproj/argoscm:v2.0
command: ["axscm"]
args: ["clone", "%%inputs.parameters.REPO%%", "/src"]
inputs:
  parameters:
    REPO:
      default: "%%session.repo%%"
outputs:
  artifacts:
    CODE:
      path: /src
```

2. Since, this workflow does not have a COMMIT param, it doesn't show up when the user clicks on a commit and then clicks "Create new job". The only way to access this is to go directly to the "Templates" option on the left side panel.

3. Click on the Templates and select the one just created above.

4. Click on the "+" sign to go to the "Review workflow parameters" page.

5. Notice that the repo information is not populated. It continues to show %%session.repo%%. If the workflow is run, it fails because there is no such repo as %%session.repo%%.
