### ISSUE TITLE
`argo logs` errors out with `rpc error: code = PermissionDenied desc = unknown (get pods)` 

### ISSUE THREAD

**Issue by ozooxo** [argoproj/argo#4026]
## Summary 

`argo logs` errors out with `rpc error: code = PermissionDenied desc = unknown (get pods)`. It should return logs from the corresponding Kubernetes pod.

## Diagnostics

What version of Argo Workflows are you running?

Client

```
$ argo version
argo: v2.10.0+195c6d8.dirty
  BuildDate: 2020-08-18T23:05:49Z
  GitCommit: 195c6d8310a70b07043b9df5c988d5a62dafe00d
  GitTreeState: dirty
  GitTag: v2.10.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

Server

```
$ kubectl exec -it argo-server-***** -- argo version
argo: v2.10.0
  BuildDate: 2020-08-18T23:15:20Z
  GitCommit: 195c6d8310a70b07043b9df5c988d5a62dafe00d
  GitTreeState: clean
  GitTag: v2.10.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

I can get the logs from `kubectl`, `argo logs` from the server, but got RPC error when I call it from the client.

```
$ kubectl logs my-wf-***** -c main
{"asctime": ....

$ kubectl exec -it argo-server-***** -- argo logs my-wf-*****
{"asctime": ....

$ argo -v logs my-wf-*****
DEBU[0000] CLI version                                   version="{v2.10.0+195c6d8.dirty 2020-08-18T23:05:49Z 195c6d8310a70b07043b9df5c988d5a62dafe00d v2.10.0 dirty go1.13.4 gc linux/amd64}"
DEBU[0000] Client options                                opts="{{argo-server:2746 true true}  0x17081a0 <nil> 0x17081f0}"
FATA[0000] rpc error: code = PermissionDenied desc = unknown (get pods)
```

Here is my rbac, I have added logs into it but that doesn't help

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-server-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
      - logs
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - pods/log
    verbs:
      - get
      - list
      - logs
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
    verbs:
      - create
      - get
      - list
      - logs
      - watch
      - update
      - patch
      - delete
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Your role looks correct to me. Can you please share the argo-server logs for the request?

**Comment by ozooxo** [comment]
@alexec 

`argo list` (which is a successful call, so rule out networking issues):

```
time="2020-09-16T15:11:29Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-09-16T15:11:29Z" grpc.time_ms=68.264 span.kind=server system=grpc
```

`argo logs` which raises the `rpc error: code = PermissionDenied desc = unknown (get pods)` error:

```
time="2020-09-16T15:12:00Z" level=warning msg="finished streaming call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = unknown (get pods)" grpc.code=PermissionDenied grpc.method=PodLogs grpc.service=workflow.WorkflowService grpc.start_time="2020-09-16T15:12:00Z" grpc.time_ms=17.42 span.kind=server system=grpc
```

**Comment by alexec** [comment]
Duplicate of #3913.

**Comment by alexec** [comment]
@ozooxo could I please ask you to look at #3913 and see if you agreed (I'm not sure myself).

**Comment by ozooxo** [comment]
Hi @alexec ,

I checked https://github.com/argoproj/argo/issues/3913

Yes we have the auth mode enabled, and we setup the JWT token as (client side) `ARGO_TOKEN` environment variable where the argo-cli commands can access. The token we are using is for a `jenkins` service account, which is different to the token you can get from `kubectl exec argo-server-***** -- argo auth token`.

```
        - args:
            - server
            - --auth-mode
            - client
            - --auth-mode
            - sso
            - --secure
            - --namespaced
```

It is the same log command, and the same behavior that other commands (tried get/list/submit) are working fine but `argo logs` raises error. However, the actual error content we have is different from https://github.com/argoproj/argo/issues/3913.

----

I try to use the `kubectl exec argo-server-***** -- argo auth token` instead, and actually the log can be seen successfully. Log:

```
time="2020-09-17T13:51:10Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=PodLogs grpc.service=workflow.WorkflowService grpc.start_time="2020-09-17T13:51:10Z" grpc.time_ms=66.973 span.kind=server system=grpc
```

The service account and JWT token are generated from https://argoproj.github.io/argo/access-token/ . So maybe it is a bug on the service account/service account setup?

**Comment by ozooxo** [comment]
FYI, this is my `argo-role` (I previously passed you the `argo-server-role` setup):

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - get
  - list
  - logs
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
  - logs
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - logs
  - watch
  - update
  - patch
  - delete
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs:
  - get
  - list
  - logs
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - logs
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
    - "policy"
  resources:
    - poddisruptionbudgets
  verbs:
    - create
    - get
    - delete
```

I kind of add `logs` everywhere but it doesn't help.

**Comment by alexec** [comment]
@ozooxo the role show in https://argoproj.github.io/argo/access-token/ is only enough permission to submit a workflow. You need add more to tail logs.

You can change this as follows:

```
kubectl edit role jenkins
```

**Comment by ozooxo** [comment]
Hi @alexec ,

So our Jenkins role is something like this. And we added the `logs` verb to it (see comment inside of YAML. However, after that we are still seeing the same permission error.

Could you provide more detail where exactly we should be adding/modified? Thanks!

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{*******},"rules":[{"apiGroups":["argoproj.io"],"resources":["workflows"],"verbs":["get","list","watch","update","patch","delete","create"]},{"apiGroups":["argoproj.io"],"resources":["workflowtemplates"],"verbs":["get","list","watch"]},{"apiGroups":["argoproj.io"],"resources":["cronworkflows"],"verbs":["get","list","watch","update","patch","delete"]}]}
  creationTimestamp: "2020-08-28T13:45:38Z"
  labels:
    app.kubernetes.io/instance: *******
  name: *******
  namespace: *******
  resourceVersion: "1117840331"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/*******
  uid: *******
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
  - logs               # <-------------------------- This is newly added.
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
```

**Comment by alexec** [comment]
You need `pods/logs` as per https://argoproj.github.io/argo/workflow-rbac/ for tailing logs.

**Comment by alexec** [comment]
There are several roles mentioned in the issue, to be very clear

* `argo-server` role is used by the Argo Server. This should either (a) be left unmodified or (b) restricted to ready-only permissions.
* `workflow` role (sometime just `argo`) is used by your workflow and should be give these permissions: https://argoproj.github.io/argo/workflow-rbac/
* `jenkins` role used by third-party APIs for the API or CLI. This should be given permission appropriate to the work it need to do: https://argoproj.github.io/argo/access-token/

**Comment by ozooxo** [comment]
Yup. So we added this on the jenkins role and `argo logs` works again.

```
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
```

Wonder what that default service account role comes from? Can this step be codified (so we only need to manually `kubectl create role jenkins-or-some-other-service-account --verb=list,update --resource=workflows.argoproj.io` to create a role, instead to need to manually create it and manually modified it)? Thanks!
