### ISSUE TITLE
steps.STEP_NAME.startedAt causes failed to resolve

### ISSUE THREAD

**Issue by Asaf-m** [argoproj/argo#4034]
## Summary 

> What happened/what you expected to happen?
I have this workflow (partial code) which is also argocd `postSync` hook.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ...
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  entrypoint: my-flow
  templates:
    - name: my-flow
      steps:
        - - name: step-1
            templateRef:
              name: my-workflow-template-1
              template: my-template-2

        - - name: step-2
            when: "{{steps.step-1.exitCode}} == 0"
            templateRef:
              name: my-workflow-template-2
              template: my-template-2
            arguments:
              parameters:
                - name: my-parameter
                  value: "{{steps.step-1.startedAt}}"
```
When I sync it I get `invalid spec: templates.my-flow.steps failed to resolve {{steps.step-1.startedAt}}`.
I'm sure that the spec is indeed valid, when I'm retrying the workflow it runs perfectly.
## Diagnostics

> What version of Argo Workflows are you running?

v2.9.5

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```
```
time="2020-09-15T11:13:50Z" level=info msg="Processing workflow" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:13:50Z" level=info msg="Updated phase  -> Running" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:13:50Z" level=info msg="Updated phase Running -> Failed" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:13:50Z" level=info msg="Updated message  -> invalid spec: templates.savers-staging-deployment-verification.steps failed to resolve {{steps.negative-keywords-saver.startedAt}}" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:13:50Z" level=info msg="Marking workflow completed" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:13:50Z" level=info msg="Checking daemoned children of " namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:13:50Z" level=info msg="Workflow update successful" namespace=staging phase=Failed 
```
At this point I retried the workflow.
```
resourceVersion=93048647 workflow=savers-staging-deployment-verification
time="2020-09-15T11:23:54Z" level=info msg="Processing workflow" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:23:54Z" level=info msg="Retry node savers-staging-deployment-verification initialized Running" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:23:54Z" level=info msg="Steps node savers-staging-deployment-verification-3316037919 initialized Running" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:23:54Z" level=info msg="StepGroup node savers-staging-deployment-verification-1005670539 initialized Running" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:23:54Z" level=info msg="Pod node savers-staging-deployment-verification-1234352735 initialized Pending" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:23:54Z" level=info msg="Created pod: savers-staging-deployment-verification(0)[0].negative-keywords-saver (savers-staging-deployment-verification-1234352735)" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:23:54Z" level=info msg="Workflow step group node savers-staging-deployment-verification-1005670539 not yet completed" namespace=staging workflow=savers-staging-deployment-verification
time="2020-09-15T11:23:54Z" level=info msg="Workflow update successful" namespace=staging phase=Running resourceVersion=93051872 workflow=savers-staging-deployment-verification
...
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
