### ISSUE TITLE
Mount a script from a ConfigMap

### ISSUE THREAD

**Issue by aceeric** [argoproj/argo#4038]
This is just a question. Looking through the documentation, it did not appear that there is a way to accomplish this but I thought I would ask anyway:

We're looking at Argo Workflow for some unattended processes. One of the processes is a lengthy bash script (about 300 lines). It seems a little too long to inline in the Argo task in the `command` or `source` fields. Ideally we would place this script into the cluster as a ConfigMap, and then mount the ConfigMap into the task, and invoke the script from the mount point. Is there a way to do this?

Thank you

**Comment by simster7** [comment]
You could do so using a `WorkflowTempalte`? Otherwise you could do so using a `ConfigMap` and accessing it using a `resource` template in your workflow.

More info: https://github.com/argoproj/argo/blob/master/docs/workflow-templates.md

**Comment by alexec** [comment]
Could you mount your config-map as a volume on a pod?

**Comment by aceeric** [comment]
As I read the docs, a `resource` task action "can be any kubectl action (e.g. create, delete, apply, patch)" but I didn't see a way to "kubectl get" an external resource and map it into the Task... And `WorkFlowTemplate` - as it looks to me - all the examples are inlined and I'm looking for a way not to inline 300+ lines of bash script.

**Comment by aceeric** [comment]
@alexec I guess I could have the task start a Job, and have the Job YAML mount the configmap holding the script... I was envisioning something along the lines of the following:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: my-task
spec:
  volumes:
  - name: my-scripts
    configMap:
      name: my-script-cm
  entrypoint:   entrypoint
  templates:
  - name:   entrypoint
    steps:
    - - name: do
        template: do

  - name: do
    volumeMounts:
    - name: my-scripts
      mountPath: /tmp/scripts
    script:
      image: debian:9.4
      command: [bash]
      source: |
        /tmp/scripts/run-my-long-script
```

**Comment by alexec** [comment]
I think you could event do this:


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: my-task
spec:
  entrypoint:   entrypoint
  templates:
  - name:   entrypoint
    steps:
    - - name: do
        template: do
  - name: do
    # not quite sure of the syntax
    volumes:
     - name: my-scripts
        path: /tmp/scripts/
        configMap:
          name: my-script-cm
    script:
      image: debian:9.4
      command: [bash]
      source: |
        /tmp/scripts/run-my-long-script
```
