### ISSUE TITLE
Workflow created from Workflowtemplate doesn't respect the activeDeadlineSeconds defined the Workflowtemplate

### ISSUE THREAD

**Issue by ediezh** [argoproj/argo#4044]
## Summary 

- Define a workflowtemplate with a activeDeadlineSeconds: 36000

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-test
  namespace: argo
spec:
  activeDeadlineSeconds: 36000
 ...
```

- Submit a workflow from this workflowtemplate
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-test-
spec:
  workflowTemplateRef:
    name: workflow-template-test
...
```

- Expect the workflow has activeDeadlineSeconds: 36000

- But instead, the workflow has activeDeadlineSeconds: 86400 which is from the controller workflow defaults
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
...
  generateName: workflow-test-
  namespace: argo
spec:
  activeDeadlineSeconds: 86400
...
```

## Diagnostics

What version of Argo Workflows are you running?

Client: 
```yaml
argo: v2.10.0-rc4+8d6dae6.dirty
  BuildDate: 2020-07-28T22:59:40Z
  GitCommit: 8d6dae6128074445d9bd0222c449643053568db8
  GitTreeState: dirty
  GitTag: v2.10.0-rc4
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
Server:
```
argo: v2.10.0-rc7
  BuildDate: 2020-08-14T00:51:56Z
  GitCommit: 267da535b66ed1dab8bcc90410260b7cf4b80e2c
  GitTreeState: clean
  GitTag: v2.10.0-rc7
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
