### ISSUE TITLE
How to pass non-default artifact repositories via the artifact arguments?

### ISSUE THREAD

**Issue by Jane85** [argoproj/argo#4050]
Hi,

I am trying to run the following workflow and it does not work. The error that I got is 
```controller is not configured with a default archive location```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: b3309624-5665-46a1-a6fb-121ae9b670a7
  namespace: test
spec:
  entrypoint: artifact-example
  serviceAccountName: workflow
  arguments:
    artifacts:
      - name: hello-art
        s3:
          accessKeySecret:
            key: accessKey
            name: some-secret
          bucket: some-bucket
          endpoint: s3.amazonaws.com
          key: hello.txt
          secretKeySecret:
            key: secretKey
            name: some-secret

  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          # bind message to the hello-art artifact
          # generated by the generate-artifact step
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]

    outputs:
      artifacts:
      # generate hello-art artifact from /tmp/hello_world.txt
      # artifacts can be directories as well as files
      - name: hello-art
        path: /tmp/hello_world.txt

  - name: print-message
    inputs:
      artifacts:
      # unpack the message input artifact
      # and put it at /tmp/message
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```

It seems that the s3 configuration in the artifact argument does not take any effect.  However, if i move the s3 configuration into the output artifact, then it works.  Does this mean it is not possible to pass non-default artifact repository via the arguments?
