### ISSUE TITLE
`runtimeResolution` Does not appear to work

### ISSUE THREAD

**Issue by endzyme** [argoproj/argo#4102]
## Summary 

I am trying to understand when to use `runtimeResolution` in the `templateRef` configuration. It would appear that this would allow you to provide `{{inputs.parameters.workflowtemplate-ref}}` as the `name: ""` of the `templateRef`, and skip validation (which currently breaks, due to either placeholder or interpolation issues). When I set `runtimeResolution: true`, I get a panic exit on the CLI.

## Diagnostics

What version of Argo Workflows are you running? (tried in 2.4.3, 2.8.0 and 2.10.0)

This produces a panic:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-templateref-
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      steps:
        - - name: generate
            template: generate
        - - name: dynamic
            templateRef:
              name: "{{steps.generate.outputs.result}}"
              runtimeResolution: true
              template: entrypoint
    - name: generate
      script:
        image: alpine
        command: 
          - "echo"
          - "someworkflowtemplateref"
```
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x10ab4f8]

goroutine 1 [running]:
github.com/argoproj/argo/workflow/validate.(*templateValidationCtx).addOutputsToScope(0xc00066a908, 0x0, 0xc0003b3360, 0xd, 0xc0005a5170, 0xc0003b0000)
	/go/src/github.com/argoproj/argo/workflow/validate/validate.go:631 +0x78
github.com/argoproj/argo/workflow/validate.(*templateValidationCtx).validateSteps(0xc00066a908, 0xc0005a5170, 0xc0005a8140, 0xc0004c1d40, 0xc0005b6548, 0x1)
	/go/src/github.com/argoproj/argo/workflow/validate/validate.go:577 +0xa04
github.com/argoproj/argo/workflow/validate.(*templateValidationCtx).validateTemplate(0xc00066a908, 0xc0004c0d80, 0xc0005a8140, 0x1683a40, 0xc0004492c8, 0xc00066a8d8, 0x0, 0x218)
	/go/src/github.com/argoproj/argo/workflow/validate/validate.go:223 +0x821
github.com/argoproj/argo/workflow/validate.(*templateValidationCtx).validateTemplateHolder(0xc00066a908, 0x168c3c0, 0xc0004c0000, 0xc0005a8080, 0x1683a40, 0xc0004492c8, 0xc00066a8d8, 0x0, 0x0, 0x0)
	/go/src/github.com/argoproj/argo/workflow/validate/validate.go:296 +0x350
github.com/argoproj/argo/workflow/validate.ValidateWorkflow(0x167ede0, 0xc000274dc0, 0xc000449180, 0x16ad700, 0x0, 0x0, 0xc00043ae00, 0xc000598000)
	/go/src/github.com/argoproj/argo/workflow/validate/validate.go:129 +0x724
github.com/argoproj/argo/workflow/util.SubmitWorkflow(0x16ad840, 0xc0003a5ea0, 0x1683bc0, 0xc000237e40, 0x7fffb548da27, 0x4, 0xc000449180, 0xc0001e4280, 0xc0003c6820, 0xc00066b7d0, ...)
	/go/src/github.com/argoproj/argo/workflow/util/util.go:257 +0x557
github.com/argoproj/argo/cmd/argo/commands.SubmitWorkflows(0xc0003e2c60, 0x1, 0x6, 0xc0001e4280, 0xc0002f8880)
	/go/src/github.com/argoproj/argo/cmd/argo/commands/submit.go:162 +0x587
github.com/argoproj/argo/cmd/argo/commands.NewSubmitCommand.func1(0xc000204280, 0xc0003e2c60, 0x1, 0x6)
	/go/src/github.com/argoproj/argo/cmd/argo/commands/submit.go:45 +0xc5
github.com/spf13/cobra.(*Command).execute(0xc000204280, 0xc0003e2ba0, 0x6, 0x6, 0xc000204280, 0xc0003e2ba0)
	/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001fcc80, 0xc0000df680, 0xc0000df400, 0xc0000df180)
	/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0001fcc80, 0x0, 0xc0001d1ec0)
	/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/argoproj/argo/cmd/argo/main.go:17 +0x27
```

If you remove the `runtimeResolution: true` you get:
```text
2020/09/22 14:38:54 Failed to submit workflow: templates.entrypoint.steps[1].dynamic template reference {{steps.generate.outputs.result}}.entrypoint not found
```

Alternatively I've tried the following:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-templateref-
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      steps:
        - - name: generate
            template: generate
        - - name: run
            arguments:
              parameters:
                - name: "workflowtemplate"
                  value: "{{steps.generate.outputs.result}}"
            template: run
    - name: run
      inputs:
        parameters:
          - name: workflowtemplate
            value: "somethinghere"
      steps:
        - - name: dynamic
            templateRef:
              name: "{{inputs.parameters.workflowtemplate}}"
              template: entrypoint
    - name: generate
      script:
        image: alpine
        command: 
          - "echo"
          - "someworkflowtemplateref"
```
and get the message below:
```text
2020/09/22 14:43:30 Failed to submit workflow: templates.entrypoint.steps[1].run templates.run.steps[0].dynamic template reference placeholder.entrypoint not found
```

I would like to be able to submit a job that determines the WorkflowTemplate ref based on some step's output. Is this possible?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
