### ISSUE TITLE
How do you specify a step that takes as input the output artifacts from a variable number of previous steps?

### ISSUE THREAD

**Issue by mark-grimes** [argoproj/argo#4120]
# Summary

How do I specify many input artifacts to a step, when the artifacts (and names) are generated as the output from previous steps?

# Motivation

In a diamond style workflow,
```
   A
  /|   \
 / |    \
B  C ... X
 \ |    /
  \|   /
   Z
```
`A` creates steps `B` to `X` using `withParam:`.  Each of these steps creates an output artifact.  I now need step `Z` to process all of these artifacts.  I have tried passing a JSON array as the `key` to `Z`, but the step gets stuck on pod creation. Is this possible?  I can find no examples that do this.

I don't think I can work around this with persistent volumes, because `B` to `X` will be running on different nodes and (as far as I'm aware) GKE doesn't support ReadWriteMany.

My particular use case is that `A` checks an external source for videos, if there are any it downloads them and publishes them as artifacts, and creates `B` to `X` to perform object detection on each video.  Step `Z` then needs to take as input all of the results, decide on a highlight range from all videos, and create a single output with clips from all input videos.  Everything up to step `Z` works great.

**Comment by sarabala1979** [comment]
@mark-grimes Here the example for aggergate artifacts.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aggregate-artifacts-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: generate
        template: gen-number-list
    - - name: generate-artifacts
        template: whalesay
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"
    - - name: collect-files
        template: collect-files

  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([i for i in range(20, 24)], sys.stdout)

  - name: whalesay
    inputs:
      parameters:
        - name: seconds
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
        - name: hello-art-{{inputs.parameters.seconds}}
          path: /tmp/hello_world.txt
          s3:
            bucket: my-bucket
            endpoint: minio:9000
            insecure: true
            key: test-{{workflow.name}}/hello_world-{{inputs.parameters.seconds}}.txt
            accessKeySecret:
              name: my-minio-cred
              key: accesskey
            secretKeySecret:
              name: my-minio-cred
              key: secretkey

  - name: collect-files
    inputs:
      artifacts:
        - name: hello-art-files
          path: /tmp
          s3:
            bucket: my-bucket
            endpoint: minio:9000
            insecure: true
            key: test-{{workflow.name}}
            accessKeySecret:
              name: my-minio-cred
              key: accesskey
            secretKeySecret:
              name: my-minio-cred
              key: secretkey
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["ls /tmp"]

```
