### ISSUE TITLE
`duration` variable can't be resolved in metrics

### ISSUE THREAD

**Issue by YourPsychiatrist** [argoproj/argo#4121]
## Summary 

I want to record some metrics including a step duration.

I tried both of the following metric specs:

real-time:
```yaml
- name: "step_duration"
  help: "Step duration"
  labels:
    - # ...
  gauge:
    value: "{{ duration }}"
    realtime: true
```

non-realtime:
```yaml
- name: "step_duration"
  help: "Step duration"
  labels:
    - # ...
  gauge:
    value: "{{ duration }}"
```

Other metrics in the same section of `metrics.prometheus` are recorded correctly so I am positive that the position of the spec within the workflow yaml is valid.

I expected this to work the way the docs describe it. [[1](https://argoproj.github.io/argo/variables/#realtime-metrics)] [[2](https://argoproj.github.io/argo/metrics/)]

## Diagnostics

Running version v2.11.0

Because this is a business-related project I cannot share the workflow. But we generate our workflows and the specs consist of multiple thousand lines. The remaining workflow, including other metrics in the list, are verified to work.

Error message:

```
unable to substitute parameters for metric 'step_duration': failed to resolve {{ duration }}"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
