### ISSUE TITLE
UI - hide input parameter value that is a secret 

### ISSUE THREAD

**Issue by tvalasek** [argoproj/argo#4173]
# Summary

Hide input parameter value in Argo UI that is a secret type. 

# Use Cases

Some input parameters may be secrets and thus their values not desired to be displayed.

# Proposal

In template that consumes inputs.parameters, add spec defining inputs.parameters.type. When Argo UI sees that, it will display REDACTED (or something similar) instead of true value.

```
      inputs:
        parameters:
        - name: MY_SECRET
          type: secret
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
