### ISSUE TITLE
Not all parameters are passed to step

### ISSUE THREAD

**Issue by simonfrey** [argoproj/argo#4176]
I have the following step which is a loop over an array of strings:
```
          - name: current1
            dependencies: [previous2]
            template: current1
            arguments:
                parameters: [ { name: "timeout", value: "10m" },
                              { name: "dry_run", value: "false" },
                              { name: "file_path", value: "{{item}}" } ]
              artifacts:
                - name: k8s_ymls
                  from: "{{tasks.previous1.outputs.artifacts.k8s_ymls}}"
            withParam: "{{tasks.previous2.outputs.result}}"
````
The problem is, when I execute the workflow this certain step only gets a single parameter `file_path` the other two parameters are not passed into the step as of why the step fails.

Version v2.11.1
![DeepinScreenshot_select-area_20200930181035](https://user-images.githubusercontent.com/24354822/94711326-4714b480-0348-11eb-8204-a33bf5af16cf.png)

**Comment by simster7** [comment]
Could you please include a sample workflow to reproduce this issue?

**Comment by simonfrey** [comment]
Damn with a simpler example it works :confused: 

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
  namespace: argo
spec:
  entrypoint: loop-example
  templates:
  - name: loop-example
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: "second"
            value: "hey"
          - name: message
            value: "{{item}}"
        withItems:              # invoke whalesay once for each item in parallel
        - hello world           # item 1
        - goodbye world         # item 2

  - name: whalesay
    inputs:
      parameters:
      - name: message
      - name: second
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.second}}: {{inputs.parameters.message}}"]
```
