### ISSUE TITLE
Workflow controller crashes on infinite loop of nested workflows

### ISSUE THREAD

**Issue by pkosiec** [argoproj/argo#4180]
## Summary 

When there is an infinite loop of nested workflows, Workflow Controller crashes with reason Error and exit code 137.

```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
```

I didn't notice any errors in the Workflow Controller logs, apart from trying to visit nested template until there are no other references. I couldn't find root cause in Minikube logs, but the Pod was definitely not OOMKilled.

Two times I managed to get error for the infinite loop workflow:
```yaml
  message: 'Request entity too large: limit is 3145728'
  phase: Error
```
Basically Workflow controller tried to access nested templates and resolve them. The depth was constantly 0. 
<details><summary>See partial logs with debug mode</summary>
<p>

```
time="2020-10-01T12:55:02Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=loop)" depth=0 tmpl="*v1alpha1.NodeStatus (nested-level2)"
time="2020-10-01T12:55:02Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=loop)" depth=0 tmpl="*v1alpha1.NodeStatus (nested-level2)"
time="2020-10-01T12:55:02Z" level=debug msg="Initializing node loop[1].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested: template: *v1alpha1.WorkflowStep (nested-level1), boundaryID: loop-3671090580" namespace=argo workflow=loop
time="2020-10-01T12:55:02Z" level=info msg="Steps node loop-3028185083 initialized Running" namespace=argo workflow=loop
time="2020-10-01T12:55:02Z" level=debug msg="Initializing node loop[1].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0]: template: *v1alpha1.Template (nested-level1), boundaryID: loop-3028185083" namespace=argo workflow=loop
time="2020-10-01T12:55:02Z" level=info msg="StepGroup node loop-2947515351 initialized Running" namespace=argo workflow=loop
time="2020-10-01T12:55:02Z" level=debug msg="Evaluating node loop[1].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested[0].nested: template: *v1alpha1.WorkflowStep (nested-level2), boundaryID: loop-3028185083" namespace=argo workflow=loop
time="2020-10-01T12:55:02Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=argo,name=loop)" depth=0 tmpl="*v1alpha1.WorkflowStep (nested-level2)"
time="2020-10-01T12:55:02Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=argo,name=loop)" depth=0 tmpl="*v1alpha1.WorkflowStep (nested-level2)"
time="2020-10-01T12:55:02Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=argo,name=loop)" depth=0 tmpl="*v1alpha1.WorkflowStep (nested-level2)"
```
</p>
</details>

I would expect that Argo detects the infinite loop and fails the Workflow fast.

## Reproduce the issue

1. Run minikube
2. Run
    ```bash
    kubectl create ns argo
    ```
3. Install Argo from stable version
   ```bash
   kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/quick-start-minimal.yaml
   ```
4. Run workflow
```bash
cat <<EOF | kubectl apply -f -
  apiVersion: argoproj.io/v1alpha1
  kind: Workflow
  metadata:
    name: loop
  spec:
    entrypoint: loop
    templates:
      - name: loop
        steps:
          - - name: generate
              template: generate1
          - - name: nested
              template: nested-level1
              arguments:
                parameters:
                  - name: nested-in-parameter
                    value: "{{steps.generate.outputs.parameters.out-parameter}}"
                artifacts:
                  - name: nested-in-artifact
                    from: "{{steps.generate.outputs.artifacts.out-artifact}}"
          - - name: consume
              template: consume
              arguments:
                parameters:
                  - name: in-parameter
                    value: "{{steps.nested.outputs.parameters.nested-out-parameter}}"
                artifacts:
                  - name: in-artifact
                    from: "{{steps.nested.outputs.artifacts.nested-out-artifact}}"
  
  
  
      # container template which generates an output parameter and artifact
      - name: generate1
        container:
          image: docker/whalesay:latest
          command: [sh, -c]
          args: ["
          cowsay hello world 1 | tee /tmp/my-output-artifact.txt &&
          echo 'my-output-paramete1' > /tmp/my-output-parameter.txt
        "]
        outputs:
          parameters:
            - name: out-parameter
              valueFrom:
                path: /tmp/my-output-parameter.txt
          artifacts:
            - name: out-artifact
              path: /tmp/my-output-artifact.txt
  
      - name: generate3
        container:
          image: docker/whalesay:latest
          command: [sh, -c]
          args: ["
          cowsay hello world 3 | tee /tmp/my-output-artifact.txt &&
          echo 'my-output-parameter3' > /tmp/my-output-parameter.txt
        "]
        outputs:
          parameters:
            - name: out-parameter3
              valueFrom:
                path: /tmp/my-output-parameter.txt
          artifacts:
            - name: out-artifact3
              path: /tmp/my-output-artifact.txt
  
  
  
      # steps template which consumes an input artifact and also produces
      # its own output parameters and artifacts taken from one of its steps.
      - name: nested-level1
        inputs:
          parameters:
            - name: nested-in-parameter
          artifacts:
            - name: nested-in-artifact
        steps:
          - - name: nested
              template: nested-level2
              arguments:
                parameters:
                  - name: nested-in-parameter
                    value: "{{inputs.parameters.nested-in-parameter}}"
                artifacts:
                  - name: nested-in-artifact
                    from: "{{inputs.artifacts.nested-in-artifact}}"
        outputs:
          parameters:
            - name: nested-out-parameter
              valueFrom:
                parameter: "{{steps.nested.outputs.parameters.nested-out-parameter}}"
          artifacts:
            - name: nested-out-artifact
              from: "{{steps.nested.outputs.artifacts.nested-out-artifact}}"
  
      - name: nested-level2
        inputs:
          parameters:
              - name: nested-in-parameter
          artifacts:
            - name: nested-in-artifact
        steps:
          - - name: nested
              template: nested-level1
              arguments:
                parameters:
                  - name: nested-in-parameter
                    value: "{{inputs.parameters.nested-in-parameter}}"
                artifacts:
                  - name: nested-in-artifact
                    from: "{{inputs.artifacts.nested-in-artifact}}"
        outputs:
          parameters:
            - name: nested-out-parameter
              valueFrom:
                parameter: "{{steps.nested.outputs.parameters.nested-out-parameter}}"
          artifacts:
            - name: nested-out-artifact
              from: "{{steps.nested.outputs.artifacts.nested-out-artifact}}"
  
  
      # container template which consumes an input parameter and artifact
      - name: consume
        inputs:
          parameters:
            - name: in-parameter
          artifacts:
            - name: in-artifact
              path: /tmp/art
        container:
          image: alpine:3.7
          command: [sh, -c]
          args: ["
          echo 'input parameter value: {{inputs.parameters.in-parameter}}' &&
          echo 'input artifact contents:' &&
          cat /tmp/art
        "]
EOF
```
## Diagnostics

Argo Workflows version: 2.10.0 (installed from https://raw.githubusercontent.com/argoproj/argo/stable/manifests/quick-start-minimal.yaml)
Environment: Minikube 1.12.3

Workflow:
<details><summary>See full YAML</summary>
<p>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    workflows.argoproj.io/phase: Running
  name: loop
  namespace: argo
spec:
  arguments: {}
  entrypoint: loop
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: loop
    outputs: {}
    steps:
    - - arguments: {}
        name: generate
        template: generate1
    - - arguments:
          artifacts:
          - from: '{{steps.generate.outputs.artifacts.out-artifact}}'
            name: nested-in-artifact
          parameters:
          - name: nested-in-parameter
            value: '{{steps.generate.outputs.parameters.out-parameter}}'
        name: nested
        template: nested-level1
    - - arguments:
          artifacts:
          - from: '{{steps.nested.outputs.artifacts.nested-out-artifact}}'
            name: in-artifact
          parameters:
          - name: in-parameter
            value: '{{steps.nested.outputs.parameters.nested-out-parameter}}'
        name: consume
        template: consume
  - arguments: {}
    container:
      args:
      - ' cowsay hello world 1 | tee /tmp/my-output-artifact.txt && echo ''my-output-paramete1''
        > /tmp/my-output-parameter.txt '
      command:
      - sh
      - -c
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: generate1
    outputs:
      artifacts:
      - name: out-artifact
        path: /tmp/my-output-artifact.txt
      parameters:
      - name: out-parameter
        valueFrom:
          path: /tmp/my-output-parameter.txt
  - arguments: {}
    container:
      args:
      - ' cowsay hello world 3 | tee /tmp/my-output-artifact.txt && echo ''my-output-parameter3''
        > /tmp/my-output-parameter.txt '
      command:
      - sh
      - -c
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: generate3
    outputs:
      artifacts:
      - name: out-artifact3
        path: /tmp/my-output-artifact.txt
      parameters:
      - name: out-parameter3
        valueFrom:
          path: /tmp/my-output-parameter.txt
  - arguments: {}
    inputs:
      artifacts:
      - name: nested-in-artifact
      parameters:
      - name: nested-in-parameter
    metadata: {}
    name: nested-level1
    outputs:
      artifacts:
      - from: '{{steps.nested.outputs.artifacts.nested-out-artifact}}'
        name: nested-out-artifact
      parameters:
      - name: nested-out-parameter
        valueFrom:
          parameter: '{{steps.nested.outputs.parameters.nested-out-parameter}}'
    steps:
    - - arguments:
          artifacts:
          - from: '{{inputs.artifacts.nested-in-artifact}}'
            name: nested-in-artifact
          parameters:
          - name: nested-in-parameter
            value: '{{inputs.parameters.nested-in-parameter}}'
        name: nested
        template: nested-level2
  - arguments: {}
    inputs:
      artifacts:
      - name: nested-in-artifact
      parameters:
      - name: nested-in-parameter
    metadata: {}
    name: nested-level2
    outputs:
      artifacts:
      - from: '{{steps.nested.outputs.artifacts.nested-out-artifact}}'
        name: nested-out-artifact
      parameters:
      - name: nested-out-parameter
        valueFrom:
          parameter: '{{steps.nested.outputs.parameters.nested-out-parameter}}'
    steps:
    - - arguments:
          artifacts:
          - from: '{{inputs.artifacts.nested-in-artifact}}'
            name: nested-in-artifact
          parameters:
          - name: nested-in-parameter
            value: '{{inputs.parameters.nested-in-parameter}}'
        name: nested
        template: nested-level1
  - arguments: {}
    container:
      args:
      - ' echo ''input parameter value: {{inputs.parameters.in-parameter}}'' && echo
        ''input artifact contents:'' && cat /tmp/art '
      command:
      - sh
      - -c
      image: alpine:3.7
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: in-artifact
        path: /tmp/art
      parameters:
      - name: in-parameter
    metadata: {}
    name: consume
    outputs: {}
status:
  finishedAt: null
  nodes:
    loop:
      children:
      - loop-215688583
      displayName: loop
      finishedAt: null
      id: loop
      name: loop
      phase: Running
      startedAt: "2020-09-30T11:44:45Z"
      templateName: loop
      templateScope: local/loop
      type: Steps
    loop-215688583:
      boundaryID: loop
      children:
      - loop-2309907940
      displayName: '[0]'
      finishedAt: null
      id: loop-215688583
      name: loop[0]
      phase: Running
      startedAt: "2020-09-30T11:44:45Z"
      templateName: loop
      templateScope: local/loop
      type: StepGroup
    loop-2309907940:
      boundaryID: loop
      displayName: generate
      finishedAt: null
      hostNodeName: minikube
      id: loop-2309907940
      name: loop[0].generate
      outputs:
        artifacts:
        - name: out-artifact
          path: /tmp/my-output-artifact.txt
          s3:
            accessKeySecret:
              key: accesskey
              name: my-minio-cred
            bucket: my-bucket
            endpoint: minio:9000
            insecure: true
            key: loop/loop-2309907940/out-artifact.tgz
            secretKeySecret:
              key: secretkey
              name: my-minio-cred
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: accesskey
              name: my-minio-cred
            bucket: my-bucket
            endpoint: minio:9000
            insecure: true
            key: loop/loop-2309907940/main.log
            secretKeySecret:
              key: secretkey
              name: my-minio-cred
        exitCode: "0"
        parameters:
        - name: out-parameter
          value: my-output-paramete1
          valueFrom:
            path: /tmp/my-output-parameter.txt
      phase: Running
      startedAt: "2020-09-30T11:44:45Z"
      templateName: generate1
      templateScope: local/loop
      type: Pod
  phase: Running
  startedAt: "2020-09-30T11:44:45Z"
```
</p>
</details>

Workflow Controller logs when it crashed: [workflow-controller.log](https://github.com/argoproj/argo/files/5309853/workflow-controller.log) 
Minikube logs: [minikube.log](https://github.com/argoproj/argo/files/5309959/minikube.log)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
