### ISSUE TITLE
Argo CLI 2.11 does not support integers for parameter values 

### ISSUE THREAD

**Issue by cscetbon** [argoproj/argo#4191]
## Summary 

What happened/what you expected to happen?
Upgrading my CLI to 2.11 (brew did the update) it breaks argo who can't get query my workflows anymore.
It breaks if any workflow uses an integer and not a string as a parameter value (see example below)

```
argo list    
FATA[0000] v1alpha1.WorkflowList.Items: v1alpha1.Workflows: v1alpha1.Workflow.Spec: 
v1alpha1.WorkflowSpec.Arguments: v1alpha1.Arguments.Parameters: []v1alpha1.Parameter: 
v1alpha1.Parameter.Value: ReadString: expects " or n, but found 1, error found in #10 byte of ...|,
"value":10}]},"entr|..., bigger context ...|uments":{"parameters":[{"name":"message","value":10}]},
"entrypoint":"whalesay","templates":[{"contai|...
```

## Diagnostics

What Kubernetes provider are you using? 
EKS

What version of Argo Workflows are you running? 
2.10

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: arguments-parameters
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: 10

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
