### ISSUE TITLE
Provide enum type parameters for Argo workflows

### ISSUE THREAD

**Issue by basanthjenuhb** [argoproj/argo#4192]
# Summary
This is an enhancement to provide choice parameters as provided by Jenkins
Jenkins Example:
```
choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
```

A similar input parameter type could be provided for workflows. Something in the lines of
```
arguments:
    parameters:
    - name: choice
      defaultValue: one
      valueFrom:
           choices:
               - one
               - two
               - three
```
# Use Cases

When would you use this?

Anyone who is submitting a workflow template from UI, would be able to specify arguments from the dropdown which has values from the `choices` array

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@jessesuen @basanthjenuhb want to work on this as part of hacktoberfest. I think we need to come up with a suitable way to specify the options, I'd lean more towards:

```yaml
arguments:
    parameters:
    - name: choice
      defaultValue: one
      enum:
               - one
               - two
               - three
```
