### ISSUE TITLE
Cannot submit workflow from workflow template with input artifact argument

### ISSUE THREAD

**Issue by istepura** [argoproj/argo#4296]
## Summary 
I've converted https://github.com/argoproj/argo/blob/master/examples/arguments-artifacts.yaml to workflow template:
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: arguments-artifacts
spec:
  entrypoint: kubectl-input-artifact
  arguments:
    artifacts:
    - name: kubectl
      http:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl

  templates:
  - name: kubectl-input-artifact
    inputs:
      artifacts:
      - name: kubectl
        path: /usr/local/bin/kubectl
        mode: 0755
    container:
      image: debian:9.4
      command: [sh, -c]
      args: ["kubectl version"]
```
 But when I try and submit any workflow using this template, submission fails
```
❯ argo  submit --from workflowtemplate/arguments-artifacts
2020/10/15 16:46:00 Failed to submit workflow: templates.kubectl-input-artifact inputs.artifacts.kubectl was not supplied
```

## Server/CLI version
2.11.3

**Comment by alexec** [comment]
Interesting. You're expecting the workflow to use the arguments. Have you tried this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: arguments-artifacts
spec:
  entrypoint: kubectl-input-artifact

  templates:
  - name: kubectl-input-artifact
    inputs:
      artifacts:
      - name: kubectl
        path: /usr/local/bin/kubectl
        mode: 0755
        http:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl
    container:
      image: debian:9.4
      command: [sh, -c]
      args: ["kubectl version"]
```
