### ISSUE TITLE
Input Parameters for Annotations not working

### ISSUE THREAD

**Issue by arctiqtim** [argoproj/argo#4304]
## Summary 

I am currently able to pass workflow parameters as variable input to pod annotations in a template, however I cannot pass input parameters.  Specifically for the use case of Vault Injector this limits the ability to use repeatable templates, while passing different values in steps in the workflow.

## Diagnostics

What Kubernetes provider are you using? - v1.16.13-gke.401

What version of Argo Workflows are you running? v2.11.3

Here is a working example with workflow params:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  serviceAccountName: argo-gcs
  arguments:
    parameters:
    - name: annotation
      value: "test-annotation"
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
    metadata:
      annotations:
        iam.amazonaws.com/role: "{{workflow.parameters.annotation}}"
      labels:
        app: whalesay
        tier: demo
```
Running this workflow, the pod annotations look good:

```yaml
Name:         steps-snfvz-2811357971
Namespace:    argo
Priority:     0
Start Time:   Fri, 16 Oct 2020 09:50:23 -0400
Labels:       app=whalesay
              tier=demo
              workflows.argoproj.io/completed=true
              workflows.argoproj.io/workflow=steps-snfvz
Annotations:  cni.projectcalico.org/podIP: 10.16.1.130/32
              **iam.amazonaws.com/role: test-annotation**
              workflows.argoproj.io/node-name: steps-snfvz[0].hello1
              workflows.argoproj.io/outputs: {"exitCode":"0"}
              workflows.argoproj.io/template:
                {"name":"whalesay","arguments":{},"inputs":{"parameters":[{"name":"message","value":"hello1"}]},"outputs":{},"metadata":{"annotations":{"i...
```

However if I try to do the same with input parameters in a workflow step like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  serviceAccountName: argo-gcs
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
          - name: annotation
            value: "test-annotation"

  - name: whalesay
    inputs:
      parameters:
      - name: message
      - name: annotation
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
    metadata:
      annotations:
        iam.amazonaws.com/role: "{{input.parameters.annotation}}"
      labels:
        app: whalesay
        tier: demo
```
The resulting pod annotation doesn't have the variable populated properly:

```yaml
Name:         steps-lf2vd-495017184
Namespace:    argo
Priority:     0
Start Time:   Fri, 16 Oct 2020 09:51:03 -0400
Labels:       app=whalesay
              tier=demo
              workflows.argoproj.io/completed=true
              workflows.argoproj.io/workflow=steps-lf2vd
Annotations:  cni.projectcalico.org/podIP: 10.16.1.131/32
              **iam.amazonaws.com/role: {{input.parameters.annotation}}**
              workflows.argoproj.io/node-name: steps-lf2vd[0].hello1
              workflows.argoproj.io/outputs: {"exitCode":"0"}
              workflows.argoproj.io/template:
                {"name":"whalesay","arguments":{},"inputs":{"parameters":[{"name":"message","value":"hello1"},{"name":"annotation","value":"test-annotatio...
```

The biggest issue with this is that for use cases to integrate with Hashicorp Vault I would still like to use repeatable Argo templates and call them with input parameters at each step.  This way you could use different secrets/paths/etc for different workflow steps.

Cheers

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Does podSpecPatch work for you?

**Comment by arctiqtim** [comment]
Haven't tried that I'll give it a go now

**Comment by arctiqtim** [comment]
I tried the following:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  serviceAccountName: argo-gcs
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
          - name: annotation
            value: "test-annotation"

  - name: whalesay
    inputs:
      parameters:
      - name: message
      - name: annotation
    podSpecPatch: '{"metadata":{"annotations":{"iam.amazonaws.com/role":"{{input.parameters.annotation}}"}}}'
    # podSpecPatch: '{"op":"add","path":"/metadata/annotations/test","value": "{{input.parameters.annotation}}"}'
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
    metadata:
      annotations:
        vault.hashicorp.com/secret-volume-path: "/opt/ssh"
      labels:
        app: whalesay
        tier: demo
```

But it doesn't want to patch the annotation ... perhaps the podSpecPatch doesn't support annotation patching?

This is what comes through:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.16.1.139/32
    vault.hashicorp.com/secret-volume-path: /opt/ssh
    workflows.argoproj.io/node-name: steps-w2kw5[0].hello1
    workflows.argoproj.io/outputs: '{"exitCode":"0"}'
    workflows.argoproj.io/template: '{"name":"whalesay","arguments":{},"inputs":{"parameters":[{"name":"message","value":"hello1"},{"name":"annotation","value":"test-annotation"}]},"outputs":{},"metadata":{"annotations":{"vault.hashicorp.com/secret-volume-path":"/opt/ssh"},"labels":{"app":"whalesay","tier":"demo"}},"container":{"name":"","image":"docker/whalesay","command":["cowsay"],"args":["hello1"],"resources":{}},"podSpecPatch":"{\"metadata\":{\"annotations\":{\"iam.amazonaws.com/role\":\"{{input.parameters.annotation}}\"}}}"}'
```
