### ISSUE TITLE
Changes to workflow semaphore seems not to trigger reload semaphore state in workflow-controller

### ISSUE THREAD

**Issue by tse77** [argoproj/argo#4327]
I'm not sure this is a bug or not but I got some feedback when asking on stackoverflow to submit an issue.

I'm learning about semaphores in the Argo project workflows to avoid concurrent workflows using the same resource.

My use case is that I have several external resources which only one workflow can use one at a time. So far so good, but sometimes the resource needs some maintenance and during that period I don't want to Argo to start any workflow.

This is my example semaphore configMap:
sempaphore
``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: testsystem-sync
data:
  darksow: "1"
```

This is my example workflow using the claiming the semaphore:

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: counter-    # name of the workflow spec
  Labels:
spec:
  serviceAccountName: fke-sa
  entrypoint: counter          # invoke the whalesay template
  synchronization:
    semaphore:
      configMapKeyRef:
        name: testsystem-sync
        key: darksow
  templates:
  - name: counter              # name of the template
    container:
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "n=0; while [ $n -lt 60 ]; do echo $n; sleep 1; n=$((n+1));done" ]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
```
When submit some of these Argo will only execute one at the time as expected. Let's say I want to do some maintenance on the resource I would like to block argo from starting any new workflow so I do a:

``` sh
kubectl edit configmap ...
```

and set the semphore to value 0 (in the future I would do that programatically through Kube-api but this will do for testing). So I then submit a new job but Argo start the workflow even if I changed the configmap.

If I cycle the workflow pod it sometimes work and when I restore the configmap again with the value 1 it wont start any workflow until I cycle the workflow-controller pod again.

So it seems that the argo workflow-controller pod does not reload the semaphore state when the configmap changes.

Related question on stackoverflow is [here](https://stackoverflow.com/questions/64427258/argo-workflows-semaphore-with-value-0)

Kubernetes 1.17
Argo 2.11.6
