### ISSUE TITLE
Infinite creation of new Workflows.

### ISSUE THREAD

**Issue by nemanjasymphony** [argoproj/argo#4328]
## Summary 

When we start Argo Workflows it works ok, but in some moment (let's say two or three hours later) it starts creating new workflows and it never stops. This is huge issue for us, because this is basically an infinite loop - new workflows are constantly creating. It affects our resources a lot.

Note: We are triggering workflows via AMQP sensor.

## Diagnostics

What Kubernetes provider are you using?
- EKS

What version of Argo Workflows are you running?
2.7.6

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: amqp
  namespace: argo-events
spec:
  template:
    serviceAccountName: events
  dependencies:
    - name: test-dep
      eventSourceName: amqp
      eventName: example
  triggers:
    - template:
        name: amqp-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: argo-workflows
                generateName: sync-by-id-
              spec:
                entrypoint: sync
                arguments:
                  parameters:
                    - name: id
                      value: "123"
                    - name: image
                      value: "aaa"
                serviceAccountName: workflow
                templates:
                  - name: step
                  inputs: 
                    parameters: 
                      - name: id
                        value: "123"
                      - name: image
                        value: "aaa"
                  container:
                    image: "{{`{{inputs.parameters.image}}`}}"
                    args: ["{{`{{inputs.parameters.id}}`}}"]
                  - name: sync
                    dag:
                      tasks:
                        - name: first-step
                          template: step
                          arguments:
                            parameters: [
                              {name: id, value: "{{`{{workflow.parameters.id}}`}}"},
                              {name: image, value: "first-step-image:tag"}
                            ]
                        - name: second-step
                          dependencies: [first-step]
                          template: step
                          arguments:
                            parameters: [
                              {name: id, value: "{{`{{workflow.parameters.id}}`}}"},
                              {name: image, value: "second-step-image:tag"}
                            ]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.id
              dest: spec.arguments.parameters.0.value
```

Status regarding the workflows: It works ok for some time, and then it starts creating new workflows that are in pending state.

Here is the link to the video we've recorded, so you can see what's showing on the UI: https://gofile.io/d/cauAUQ

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
