### ISSUE TITLE
goofy syntax issue in examples/README.md

### ISSUE THREAD

**Issue by dllehr81** [argoproj/argo#4330]
## Summary 

In the https://github.com/argoproj/argo/blob/master/examples/README.md#volumes example for creating a pvc on the fly, the 
`resource` section is under `inputs` when I believe it should be one level up.

## Diagnostics

What Kubernetes provider are you using? 
Openshift 4.3
What version of Argo Workflows are you running? 
2.10.1
```yaml
  - name: generate-volume
    inputs:
      parameters:
        - name: pvc-size
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            generateName: pvc-example-
          spec:
            accessModes: ['ReadWriteOnce', 'ReadOnlyMany']
            resources:
              requests:
                storage: '{{inputs.parameters.pvc-size}}'
      outputs:
        parameters:
          - name: pvc-name
            valueFrom:
              jsonPath: '{.metadata.name}'
```

should be 
```yaml
  - name: generate-volume
    inputs:
      parameters:
        - name: pvc-size
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          generateName: pvc-example-
        spec:
          accessModes: ['ReadWriteOnce', 'ReadOnlyMany']
          resources:
            requests:
              storage: '{{inputs.parameters.pvc-size}}'
      outputs:
        parameters:
          - name: pvc-name
            valueFrom:
              jsonPath: '{.metadata.name}'
```

I can submit a PR but don't want to muddy the waters if this is something someone else wants to suck up into one of their upcoming works?

Bonus points:
This action requires `get/create/delete` access to the `persistentvolumeclaims` resource.  That's not on by default for the `default` serviceaccount.  Not sure if that's an issue or if you expect users to manage that expectation on their own?

Either way, thanks for your time!
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
