### ISSUE TITLE
in comparator does not work when there is only one value inside the parenthesis

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo#4356]
## Summary 
"in" is now supported in conditionals but I am getting an error when trying to use it with only one value inside the parenthesis

Here is the error I got:
```
Failed to evaluate 'when' expresion 'a in (a)': Value 'a' cannot be used with the comparator 'in', it is not a number
```
However if I use `when: "a in (a,b)"` then it works.
## Diagnostics

What Kubernetes provider are you using? 
Kubernetes in IBM cloud

What version of Argo Workflows are you running? 
v2.11.6

Here's an example of a workflow that fails
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-bash-
spec:
  entrypoint: bash-script-example
  templates:
  - name: bash-script-example
    steps:
    - - name: schedule
        template: schedule
    - - name: a
        template: print-message
        when: "a in {{steps.schedule.outputs.result}}"
        arguments:
          parameters:
          - name: message
            value: "I am step A"
      - name: b
        template: print-message
        when: "b in {{steps.schedule.outputs.result}}"
        arguments:
          parameters:
          - name: message
            value: "I am step B"
      - name: c
        template: print-message
        when: "c in {{steps.schedule.outputs.result}}"
        arguments:
          parameters:
          - name: message
            value: "I am step C"

  - name: schedule
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo '(a)'"] # replacing '(a)' with '(a,b)' works
  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.message}}"]
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
