### ISSUE TITLE
mount a volume on the wait container does not work

### ISSUE THREAD

**Issue by omerfsen** [argoproj/argo#4366]
## Summary 

Trying to mount Volumes to wait pod on executor does not work.

## Diagnostics

AKS 1.16.13 , EKS 1.17 , Kind 1.17

v2.11.6

I am trying to mount a volume from a secret on wait node because our minio is SSL enabled by default even from inside kubernetes cluster but this SSL is signed by an Internal CA.

So my purpose is to change CA so internal CA cert can be used and minio does not get inside **wait** pod which is inside executor and responsible for getting outputs and save it to minio as defined at **archiveLogs**

```bash
x509: certificate signed by unknown authority error
```

I have tried: (after every change i have restarted all pods via kubectl rollout restart deployment -n argo so ALL pods restarted)

```yaml
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: docker
    executor:
      volumeMounts:
        - mountPath: /etc/ssl/certs/
          name: ssl-certs
          readOnly: true
      volumes:
        - name: ssl-certs
          secret:
            items:
            - key: tls.crt
              path: ca-certificates.crt
            secretName: ingress-tls
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-minio
        secretKeySecret:
          key: secretkey
          name: argo-minio
        bucket: argo-artifacts
        endpoint: services.domain.com:9000
        insecure: false
kind: ConfigMap
```

or

```yaml
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: docker
    executor:
      volumeMounts:
      - name: ssl-certs
        mountPath: /etc/ssl/certs/
        readOnly: true
    workflowDefaults:
      spec:
        volumes:
        - name: ssl-certs
          secret:
            items:
            - key: tls.crt
              path: ca-certificates.crt
            secretName: ingress-tls
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-minio
        secretKeySecret:
          key: secretkey
          name: argo-minio
        bucket: argo-artifacts
        endpoint: services.domain.com:9000
        insecure: false
kind: ConfigMap
```

or

```yaml
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: docker
    executor:
    workflowDefaults:
      spec:
        volumes:
        - name: ssl-certs
          secret:
            items:
            - key: tls.crt
              path: ca-certificates.crt
            secretName: ingress-tls
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs/
          readOnly: true
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-minio
        secretKeySecret:
          key: secretkey
          name: argo-minio
        bucket: argo-artifacts
        endpoint: services.domain.com:9000
        insecure: false
kind: ConfigMap
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
