### ISSUE TITLE
K8Sapi fails on first try and succeds on second

### ISSUE THREAD

**Issue by juliusvonkohout** [argoproj/argo#4367]
## Summary 
The example fails once and finishes after second try.

## Diagnostics

Kubernetes 1.18
argoexec 2.11.6
workflow-controller v2.3.0

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sum-pipeline
  generateName: sum-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.4, pipelines.kubeflow.org/pipeline_compilation_time: '2020-10-24T17:15:11.808285',
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "100000", "name":
      "count", "optional": true, "type": "Integer"}], "name": "Sum pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.4}
spec:
  entrypoint: sum-pipeline
  templates:
  - name: sum-pipeline
    dag:
      tasks:
      - {name: volume-creation, template: volume-creation}
  - name: volume-creation
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.name}}-mypvc'
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
    outputs:
      parameters:
      - name: volume-creation-manifest
        valueFrom: {jsonPath: '{}'}
      - name: volume-creation-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: volume-creation-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
  arguments:
    parameters:
    - {name: count, value: '100000'}
  serviceAccountName: pipeline-runner
```

```
time="2020-10-24T15:29:40Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\n{\nexecutorImage: argoproj/argoexec:v2.3.0,\ncontainerRuntimeExecutor: k8sapi,\nmetricsConfig: \n{\n    enabled: true,\n    path: /metrics,\n    port: 8080\n},\ntelemetryConfig:\n{\n   enabled: true,\n   path: /metrics,\n   port: 8081\n},\nartifactRepository:\n{\n    s3: {\n        bucket: mlpipeline,\n        keyPrefix: artifacts,\n        endpoint: minio-service.kubeflow:9000,\n        insecure: true,\n        accessKeySecret: {\n            name: mlpipeline-minio-artifact,\n            key: accesskey\n        },\n        secretKeySecret: {\n            name: mlpipeline-minio-artifact,\n            key: secretkey\n        }\n    }\n}\n}\n"
time="2020-10-24T15:29:40Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2020-10-24T15:29:40Z" level=info msg="Workflow Controller (version: v2.3.0) starting"
time="2020-10-24T15:29:40Z" level=info msg="Workers: workflow: 8, pod: 8"
time="2020-10-24T15:29:40Z" level=info msg="Watch Workflow controller config map updates"
time="2020-10-24T15:29:40Z" level=info msg="Starting prometheus metrics server at 0.0.0.0:8080/metrics"
time="2020-10-24T15:29:40Z" level=info msg="Starting prometheus metrics server at 0.0.0.0:8081/metrics"
time="2020-10-24T15:29:40Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2020-10-24T15:29:40Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\n{\nexecutorImage: argoproj/argoexec:v2.3.0,\ncontainerRuntimeExecutor: k8sapi,\nmetricsConfig: \n{\n    enabled: true,\n    path: /metrics,\n    port: 8080\n},\ntelemetryConfig:\n{\n   enabled: true,\n   path: /metrics,\n   port: 8081\n},\nartifactRepository:\n{\n    s3: {\n        bucket: mlpipeline,\n        keyPrefix: artifacts,\n        endpoint: minio-service.kubeflow:9000,\n        insecure: true,\n        accessKeySecret: {\n            name: mlpipeline-minio-artifact,\n            key: accesskey\n        },\n        secretKeySecret: {\n            name: mlpipeline-minio-artifact,\n            key: secretkey\n        }\n    }\n}\n}\n"
time="2020-10-24T15:29:40Z" level=info msg="Started workflow TTL worker"
time="2020-10-24T15:32:16Z" level=info msg="Processing workflow" namespace=kubeflow workflow=sum-pipeline
time="2020-10-24T15:32:16Z" level=info msg="Updated phase  -> Running" namespace=kubeflow workflow=sum-pipeline
time="2020-10-24T15:32:16Z" level=info msg="Updated phase Running -> Failed" namespace=kubeflow workflow=sum-pipeline
time="2020-10-24T15:32:16Z" level=info msg="Updated message  -> invalid spec: templates.volume-creation.outputs.parameters.volume-creation-manifest: k8sapi executor does not support outputs from base image layer. must use emptyDir" namespace=kubeflow workflow=sum-pipeline
time="2020-10-24T15:32:16Z" level=info msg="Marking workflow completed" namespace=kubeflow workflow=sum-pipeline
time="2020-10-24T15:32:16Z" level=info msg="Checking daemoned children of " namespace=kubeflow workflow=sum-pipeline
time="2020-10-24T15:32:16Z" level=info msg="Workflow update successful" namespace=kubeflow workflow=sum-pipeline
```

```
status:
  finishedAt: "2020-10-24T15:32:16Z"
  message: 'invalid spec: templates.volume-creation.outputs.parameters.volume-creation-manifest:
    k8sapi executor does not support outputs from base image layer. must use emptyDir'
  phase: Failed
  startedAt: "2020-10-24T15:32:16Z"
```

```
[julius@localhost ~]$ argo -n kubeflow get sum-pipeline
Name:                sum-pipeline
Namespace:           kubeflow
ServiceAccount:      pipeline-runner
Status:              Failed
Message:             invalid spec: templates.volume-creation.outputs.parameters.volume-creation-manifest: k8sapi executor does not support outputs from base image layer. must use emptyDir
Created:             Sat Oct 24 17:32:16 +0200 (7 minutes ago)
Started:             Sat Oct 24 17:32:16 +0200 (7 minutes ago)
Finished:            Sat Oct 24 17:32:16 +0200 (7 minutes ago)
Duration:            0 seconds
Parameters:          
  count:             100000
```

```
[julius@localhost ~]$ argo -n kubeflow retry sum-pipeline
Name:                sum-pipeline
Namespace:           kubeflow
ServiceAccount:      pipeline-runner
Status:              Running
Conditions:          
 Completed           False
Created:             Sat Oct 24 17:32:16 +0200 (8 minutes ago)
Started:             Sat Oct 24 17:32:16 +0200 (8 minutes ago)
Duration:            8 minutes 25 seconds
Parameters:          
  count:             100000
```

```
[julius@localhost ~]$ argo -n kubeflow get sum-pipeline
Name:                sum-pipeline
Namespace:           kubeflow
ServiceAccount:      pipeline-runner
Status:              Succeeded
Created:             Sat Oct 24 17:32:16 +0200 (8 minutes ago)
Started:             Sat Oct 24 17:32:16 +0200 (8 minutes ago)
Finished:            Sat Oct 24 17:40:45 +0200 (20 seconds ago)
Duration:            8 minutes 29 seconds
Parameters:          
  count:             100000

STEP                  TEMPLATE         PODNAME                DURATION  MESSAGE
 ✔ sum-pipeline       sum-pipeline                                        
 └-✔ volume-creation  volume-creation  sum-pipeline-39308471  4s      
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
