### ISSUE TITLE
Template metrics not working from within WorkflowTemplate

### ISSUE THREAD

**Issue by dbseel** [argoproj/argo#4381]
## Summary 

I have a WorkflowTemplate that contains a list of steps, each of which calls a template. Within this step template is a metric with labels based on the parameter passed in. When I check prometheus after running the workflow, I only see results labelled against the first parameter passed in for each metric, but the number of results lines up with how many times the template was called.

If I run the exact same flow from a workflow directly instead of calling a workflowtemplate, everything seems to work correctly.

## Diagnostics

What Kubernetes provider are you using?
docker-desktop, eks

What version of Argo Workflows are you running? 
v2.11.6

This workflowtemplate reproduces the issue (2 step_counter_status results, both labelled with name 'first'):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
spec:
  entrypoint: steps
  templates:
    - name: steps
      steps:
        - - name: random-int1
            template: random-int
            arguments:
              parameters:
              - name: name
                value: first
        - - name: random-int2
            template: random-int
            arguments:
              parameters:
              - name: name
                value: second
    - name: random-int
      inputs:
        parameters:
        - name: name
      metrics:
        prometheus:
        - name: step_counter_status
          help: "Count of step by name and status"
          labels:
            - key: name
              value: "{{inputs.parameters.name}}"
            - key: status
              value: "{{status}}"
          counter:
            value: "1"
      container:
        image: python:alpine3.6
        command: ["python", -v]
```

This workflow works fine (2 step_counter_status results, one labelled with name 'first', one with 'second'):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: steps
  templates:
    - name: steps
      steps:
        - - name: random-int1
            template: random-int
            arguments:
              parameters:
              - name: name
                value: first
        - - name: random-int2
            template: random-int
            arguments:
              parameters:
              - name: name
                value: second
    - name: random-int
      inputs:
        parameters:
        - name: name
      metrics:
        prometheus:
        - name: step_counter_status
          help: "Count of step by name and status"
          labels:
            - key: name
              value: "{{inputs.parameters.name}}"
            - key: status
              value: "{{status}}"
          counter:
            value: "1"
      container:
        image: python:alpine3.6
        command: ["python", -v]
```

```
time="2020-10-26T18:04:04Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="DAG node hello-world-nr2m5 initialized Running" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="All of node hello-world-nr2m5.random-int1 dependencies [] completed" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="Pod node hello-world-nr2m5-3993440999 initialized Pending" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="Created pod: hello-world-nr2m5.random-int1 (hello-world-nr2m5-3993440999)" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="All of node hello-world-nr2m5.random-int2 dependencies [] completed" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="Pod node hello-world-nr2m5-4010218618 initialized Pending" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="Created pod: hello-world-nr2m5.random-int2 (hello-world-nr2m5-4010218618)" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:04Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=2397028 workflow=hello-world-nr2m5
time="2020-10-26T18:04:05Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:05Z" level=info msg="Updating node hello-world-nr2m5-4010218618 message: ContainerCreating"
time="2020-10-26T18:04:05Z" level=info msg="Updating node hello-world-nr2m5-3993440999 message: ContainerCreating"
time="2020-10-26T18:04:05Z" level=info msg="Skipped pod hello-world-nr2m5.random-int1 (hello-world-nr2m5-3993440999) creation: already exists" namespace=argo podPhase=Pending workflow=hello-world-nr2m5
time="2020-10-26T18:04:05Z" level=info msg="Skipped pod hello-world-nr2m5.random-int2 (hello-world-nr2m5-4010218618) creation: already exists" namespace=argo podPhase=Pending workflow=hello-world-nr2m5
time="2020-10-26T18:04:05Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=2397036 workflow=hello-world-nr2m5
time="2020-10-26T18:04:06Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:06Z" level=info msg="Skipped pod hello-world-nr2m5.random-int1 (hello-world-nr2m5-3993440999) creation: already exists" namespace=argo podPhase=Pending workflow=hello-world-nr2m5
time="2020-10-26T18:04:06Z" level=info msg="Skipped pod hello-world-nr2m5.random-int2 (hello-world-nr2m5-4010218618) creation: already exists" namespace=argo podPhase=Pending workflow=hello-world-nr2m5
time="2020-10-26T18:04:08Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:08Z" level=info msg="Updating node hello-world-nr2m5-4010218618 status Pending -> Running"
time="2020-10-26T18:04:08Z" level=info msg="Updating node hello-world-nr2m5-3993440999 status Pending -> Running"
time="2020-10-26T18:04:08Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=2397056 workflow=hello-world-nr2m5
time="2020-10-26T18:04:09Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:09Z" level=info msg="Setting node hello-world-nr2m5-4010218618 outputs"
time="2020-10-26T18:04:09Z" level=info msg="Setting node hello-world-nr2m5-3993440999 outputs"
time="2020-10-26T18:04:09Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=2397064 workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="Updating node hello-world-nr2m5-4010218618 status Running -> Succeeded"
time="2020-10-26T18:04:10Z" level=info msg="Updating node hello-world-nr2m5-3993440999 status Running -> Succeeded"
time="2020-10-26T18:04:10Z" level=info msg="Outbound nodes of hello-world-nr2m5 set to [hello-world-nr2m5-3993440999 hello-world-nr2m5-4010218618]" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="node hello-world-nr2m5 phase Running -> Succeeded" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="node hello-world-nr2m5 finished: 2020-10-26 18:04:10.265576867 +0000 UTC" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="Checking daemoned children of hello-world-nr2m5" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-nr2m5
time="2020-10-26T18:04:10Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=2397069 workflow=hello-world-nr2m5
time="2020-10-26T18:04:11Z" level=info msg="Labeled pod completed" namespace=argo pod=hello-world-nr2m5-4010218618
time="2020-10-26T18:04:11Z" level=info msg="Labeled pod completed" namespace=argo pod=hello-world-nr2m5-3993440999
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Will take a look

**Comment by simster7** [comment]
@dbseel How are you submitting the `WorkflowTemplate`?

**Comment by dbseel** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  workflowTemplateRef:
    name: hello-world
```
