### ISSUE TITLE
The SSO does not work, there is a link with the secret SSO in k8s

### ISSUE THREAD

**Issue by Amauche** [argoproj/argo#4395]
## Summary 

I have enabled and configured SSO authentication but I have problems with an "sso" secret in k8s.

The "sso" secret didn't exist so I created it empty thinking that Argo server would provision it but it didn't.
So I get this error message in the "argo-server" pod.

I would be grateful if you had a suggestion.

## Diagnostics

Argo is deployed on **GKE v1.14.10-gke.36** .

Here is the configuration of SSO in configmap.
```yaml
sso:
      issuer: https://accounts.google.com
      clientId:
        name: argo-client-sso
        key: client-id-key
      clientSecret:
        name: argo-client-sso
        key: client-secret-key
      redirectUrl: https://argo.mydomain.com/oauth2/callback
```

Here argo-server deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        - --auth-mode 
        - sso
        - --namespaced
        image: argoproj/argocli:latest
        name: argo-server
        ports:
        - containerPort: 2746
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: argo-server
```  
here my secret file:
```yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: argo
  name: argo-client-sso
type: Opaque
data:
  client-id-key: TmljZSB0cnkgOykK
  client-secret-key: TmljZSB0cnkgYWdhaW4gOykK
```

The logs from the server :
```level=fatal msg="failed to parse private key: asn1: syntax error: sequence truncated"```
```

Thank you in advance and if you need more information, ask me. ;)
---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
