### ISSUE TITLE
Can't export ResourcesDuration metrics to Prometheus

### ISSUE THREAD

**Issue by tomgoren** [argoproj/argo#4402]
## Summary 

According to the [docs](https://argoproj.github.io/argo/variables/#metrics), step level resource consumption metrics are available via resourcesDuration.[cpu|memory].
However, these metrics are exposed as strings, in a Golang `time.Duration` format, which makes them incompatible with the Prometheus expectations.

## Diagnostics

What Kubernetes provider are you using? `v1.17.9-eks-4c6976`

What version of Argo Workflows are you running? `v2.11.6`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo-workflows
  generateName: testing-workflow-
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: [cowsay]
      metrics:
        prometheus:
          - name: "resource_duration_cpu"
            help: "Resource Duration CPU"
            gauge:
              value: "{{resourcesDuration.cpu}}"
```

```
❯ argo -n argo-workflows get testing-workflow-t5rb6
Name:                testing-workflow-t5rb6
Namespace:           argo-workflows
ServiceAccount:      default
Status:              Succeeded
Conditions:
✖ MetricsError could not construct metric 'resource_duration_cpu': strconv.ParseFloat: parsing "2s": invalid syntax
 Completed           True
Created:             Wed Oct 21 08:13:54 -0400 (20 seconds ago)
Started:             Wed Oct 21 08:13:54 -0400 (20 seconds ago)
Finished:            Wed Oct 21 08:13:58 -0400 (16 seconds ago)
Duration:            4 seconds
ResourcesDuration:   2s*(1 cpu),2s*(100Mi memory)
STEP                       TEMPLATE  PODNAME                 DURATION  MESSAGE
 ✔ testing-workflow-t5rb6  whalesay  testing-workflow-t5rb6  3s
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
