### ISSUE TITLE
exitCode grabbing not working for PNS executor

### ISSUE THREAD

**Issue by nbren12** [argoproj/argo#4406]
## Summary 

Referring to the exit code in a `when` clause fails for the PNS executor with a microk8s installation.

### MCVE

When I run the workflow below with the k8sapi executor and then show the logs, I see
```
conditional-sdzl5-1989971332: exit code of last process was 0
```
as expected. With the pns executor, these are logs:
```
conditional-d2hcc-789778176: exit code of last process was {{steps.print-hello.exitCode}}
```
The exitCode is not being de-referenced. Interestingly, this only occurs when sleeping for at least 5 seconds. 

## Diagnostics

What Kubernetes provider are you using?  microk8s on ubuntu.

What version of Argo Workflows are you running?  Happens on v2.11.6 and v2.10.2

```yaml
Paste a workflow that reproduces the bug, including status:
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-
spec:
  entrypoint: conditional-example
  arguments:
    parameters:
    - name: should-print
      value: "true"

  templates:
  - name: conditional-example
    inputs:
      parameters:
      - name: should-print
    steps:
    - - name: print-hello
        template: whalesay
        continueOn:
          failed: true
        when: "{{inputs.parameters.should-print}} == true"
    - - name: print-hello1
        template: whalesay1
        arguments:
            parameters:
                - name: exitcode
                  value: "{{steps.print-hello.exitCode}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [bash, -c]
      args: ["sleep 5"]

  - name: whalesay1
    inputs:
        parameters:
            - name: exitcode
    container:
      image: docker/whalesay:latest
      command: ["echo", "{{inputs.parameters.exitcode}}"]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
