### ISSUE TITLE
Log artifact not annotated to the pod when an output artifact fails

### ISSUE THREAD

**Issue by hadim** [argoproj/argo#4439]
## Setup

- K8s provider: GCP running 1.17.9-gke.6300
- Argo version: 2.10.2:
  - I also tried with `argoproj/argocli:latest` and observe the same bug.
  - I **haven't tried** with `argoproj/workflow-controller:latest`.

## What happen

When a folder of an output artifact in the container does not exist, upon termination, argo can't upload it (which seems obvious). But **in consequence** the pod **does not get annotated** with the **log artifact** which has been correctly uploaded.

Is that possible to annotate the pod even if one or more output artifacts has failed?

## Reproduce

- **Working example:** here `/data/outputs` is created and so upon termination the `log` and `outputs` artifacts get uploaded. The last line of the `main` logs shows `level=info msg="Annotating pod with output"`.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bug-log-argo-will-succeed-
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      script:
        image: alpine
        command: [sh]
        source: |
          set -e
          echo "Write outputs"
          mkdir -p /data/outputs
          echo "result" > /data/outputs/results.csv
      outputs:
        artifacts:
          - name: input-data
            path: /data/outputs/
            s3:
              key: tests/outputs/
              bucket: xxxxx-data
              endpoint: s3.amazonaws.com
              accessKeySecret:
                name: xxx-secrets
                key: xxxxxxx
              secretKeySecret:
                name: xxx-secrets
                key: xxxxxxx
            archive:
              none: {}
```

- **Failing example:** here `/data/outputs` is not created during the workflow (for example the workflow failed during its execution) and so upon termination the `log` artifact get uploaded but the not the `outputs` one. In consequence the pod **is not annotated** and so the associated archived workflow cannot display the logs. **But** the logs can be accessed by browsing the bucket we are using to store the logs.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bug-log-argo-will-fail-
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      script:
        image: alpine
        command: [sh]
        source: |
          set -e
          echo "Do not write outputs"

          # random command so it fails
          fdsfsdfsdf
      outputs:
        artifacts:
          - name: input-data
            path: /data/outputs/
            s3:
              key: tests/outputs/
              bucket: xxxx-data
              endpoint: s3.amazonaws.com
              accessKeySecret:
                name: xx-secrets
                key: xxxx
              secretKeySecret:
                name: xxx-secrets
                key: xxxx
            archive:
              none: {}
```

- **Working example without output artifact:** same setup as above but without an output artifact. In that case the pod get correctly annotated with the `log` artifact. All good even when the workflow fails.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bug-log-argo-will-fail-
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      script:
        image: alpine
        command: [sh]
        source: |
          set -e
          echo "Do not write outputs"

          # random command so it fails
          fdsfsdfsdf
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
