### ISSUE TITLE
IntOrString not accepting variables

### ISSUE THREAD

**Issue by josephmcgovern-wf** [argoproj/argo#4442]
## Summary 

I would expect to be able to provide an input variable to an `activeDeadlineSeconds` field on a template. However, I receive validation errors when attempting to do this. 

I would expect to be able to submit a workflow that specifies `activeDeadlineSecond` via a variable and have its value properly populated.

## Diagnostics

> What Kubernetes provider are you using? 

EKS, but that's N/A for this scenario.

> What version of Argo Workflows are you running? 

```
> argo version

argo: v2.11.3
  BuildDate: 2020-10-07T22:51:05Z
  GitCommit: a00a8f141c221f50e397aea8f86a54171441e395
  GitTreeState: clean
  GitTag: v2.11.3
  GoVersion: go1.13.15
  Compiler: gc
  Platform: darwin/amd64
```

Here is my workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: timeout-bug-
spec:
  entrypoint: main

  templates:
    - name: main
      dag:
        tasks:
          - name: print-timeout
            template: print-timeout
          - name: use-timeout
            template: use-timeout
            dependencies: [print-timeout]
            arguments:
              parameters:
                - name: timeout
                  value: "{{tasks.print-timeout.outputs.result}}"

    - name: print-timeout
      container:
        image: alpine
        command: [sh, -c]
        args: ['echo 5']

    - name: use-timeout
      inputs:
        parameters:
          - name: timeout
      activeDeadlineSeconds: {{inputs.parameters.timeout}}
      container:
        image: alpine
        command: [sh, -c]
        args: ["echo sleeping for 1m; sleep 60; echo done"]
```

If I submit this workflow, I get an error:
```
argo submit -n argo --watch workflow-example.yaml

Failed to parse workflow: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"inputs.parameters.timeout":interface {}(nil)}
```

If I wrap the variable in quotes, replacing the line `{{inputs.parameters.timeout}}` with `"{{inputs.parameters.timeout}}"`, and re-submit the workflow, I get a different error:

```
argo submit -n argo --watch workflow-example.yaml

Failed to submit workflow: templates.main.tasks.use-timeout templates.use-timeout.activeDeadlineSeconds must be a positive integer > 0 or an argo variable
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
