### ISSUE TITLE
TemplateRef metrics not working from within WorkflowTemplate

### ISSUE THREAD

**Issue by dbseel** [argoproj/argo#4443]
## Summary 

I have a WorkflowTemplate that contains a list of steps, each of which calls a dag template. This dag template calls other common step templates, and within this step template is a metric with labels based on the parameter passed in. When I check prometheus after running the workflow, I only see results labelled against the first parameter passed in for each metric, but the number of results lines up with how many times the template was called.

This was found verifying https://github.com/argoproj/argo/issues/4381
Looks like my original example was not close enough to our actual workflow setup.

## Diagnostics

What Kubernetes provider are you using? 
docker-desktop, eks

What version of Argo Workflows are you running? 
v2.11.7

Use these workflow templates to reproduce the issue (2 step_counter_status results, both labelled with name "first"):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-with-ref
spec:
  entrypoint: steps
  templates:
    - name: steps
      steps:
        - - name: random-int1
            templateRef:
              name: hello-world-common
              template: dagsteps
            arguments:
              parameters:
              - name: name
                value: first
        - - name: random-int2
            templateRef:
              name: hello-world-common
              template: dagsteps
            arguments:
              parameters:
              - name: name
                value: second
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-common
spec:
  entrypoint: steps
  templates:
  - name: dagsteps
    inputs:
      parameters:
      - name: name
    dag:
      tasks:
        - name: random
          template: random-int
          arguments:
            parameters:
            - name: name
              value: "{{inputs.parameters.name}}"
  - name: random-int
    inputs:
      parameters:
      - name: name
    metrics:
      prometheus:
      - name: step_counter_status
        help: "Count of step by name and status"
        labels:
          - key: name
            value: "{{inputs.parameters.name}}"
          - key: status
            value: "{{status}}"
        counter:
          value: "1"
    container:
      image: python:alpine3.6
      command: ["python", -v]
```

Reproduce with 'argo -n argo submit metricworkflow.yaml --watch'

Where metricworkflow.yaml is:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  workflowTemplateRef:
    name: hello-world-with-ref
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
