### ISSUE TITLE
feature request - submit workflow templates

### ISSUE THREAD

**Issue by Boolman** [argoproj/argo#4483]
# Summary

the "Submit Workflow" mode on the webui, I would like to have a option to select a template from a set of example workflows

For example: 
click on "submit workflow", click on the dropdown, choose "Packer"

It fills out this in the form:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: packer-
spec:
  entrypoint: build
  arguments:
    parameters:
      - name: repo
        value: "REQUIRED"
      - name: env
        value: "REQUIRED"
  workflowTemplateRef:
    name: packer
```
And the user fills out the required values and submit the workflow

# Use 

I believe this would make it easier for team members

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
