### ISSUE TITLE
[bug] workflow stuck in running when daemon pod missing

### ISSUE THREAD

**Issue by lonsdale8734** [argoproj/argo#4521]
## Summary 

What happened/what you expected to happen?

**Workflow stuck in running phase when daemon pod missing.**

## Diagnostics

What version of Argo Workflows are you running? 

I had tests based on v2.7.1, v2.10.2 and v2.11.7.

`argo submit -p error=0 daemon-miss.yaml` work as expected.
`argo submit -p error=1 daemon-miss.yaml` stuck at v2.7.1.
`argo submit  -p error=2 daemon-miss.yaml` stuck at v2.10.2 and v2.11.7.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-missing-
spec:
  arguments:
    parameters:
    - name: error
      value: "0"

  activeDeadlineSeconds: 150
  entrypoint: dag
  onExit: exit
  templates:
  - name: dag
    dag:
      tasks:
      - name: daemon
        template: daemon
      - name: sleep
        template: sleep
        dependencies: [daemon]
        arguments:
          parameters:
          - name: ip
            value: "{{tasks.daemon.ip}}"

  - name: daemon
    daemon: true
    script:
      workingDir: /tmp/
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        echo "{{pod.name}}" > name
        test "{{workflow.parameters.error}}" = "1" && kubectl -n "{{workflow.namespace}}" delete po "{{pod.name}}" || true
        sleep 30
      volumeMounts:
      - name: shared
        mountPath: /tmp/
      readinessProbe:
        exec:
          command:
          - sleep
          - 2s
        initialDelaySeconds: 5
        timeoutSeconds: 2
    sidecars:
    - name: name
      workingDir: /tmp/
      image: python:3.7.5-alpine3.10
      command: [python, -m, http.server]
      ports:
      - containerPort: 8000
      volumeMounts:
      - name: shared
        mountPath: /tmp/
    volumes:
    - name: shared
      emptyDir: {}

  - name: sleep
    inputs:
      parameters:
      - name: ip
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        name=$(wget -qO- http://"{{inputs.parameters.ip}}":8000/name)
        echo $name
        test "{{workflow.parameters.error}}" = "2" && kubectl -n "{{workflow.namespace}}" delete po $name || true
        sleep 10s

  - name: exit
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        sleep 10s
        echo "exit"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.ss

**Comment by sarabala1979** [comment]
I will take a look

**Comment by sarabala1979** [comment]
@lonsdale8734 I tried to reproduce this issue on my local. I couldn't reproduce it. Am I missing anything?

Workflow:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-missing-
spec:
  arguments:
    parameters:
    - name: error
      value: "0"

#  activeDeadlineSeconds: 150
  entrypoint: dag
  onExit: exit
  templates:
  - name: dag
    dag:
      tasks:
      - name: daemon
        template: daemon
      - name: sleep
        template: sleep
        dependencies: [daemon]
        arguments:
          parameters:
          - name: ip
            value: "{{tasks.daemon.ip}}"

  - name: daemon
    daemon: true
    script:
      workingDir: /tmp/
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        echo "{{pod.name}}"
        kubectl -n argo delete po "{{pod.name}}"
        sleep 30
      volumeMounts:
      - name: shared
        mountPath: /tmp/
      readinessProbe:
        exec:
          command:
          - sleep
          - 2s
        initialDelaySeconds: 5
        timeoutSeconds: 2
    sidecars:
    - name: name
      workingDir: /tmp/
      image: python:3.7.5-alpine3.10
      command: [python, -m, http.server]
      ports:
      - containerPort: 8000
      volumeMounts:
      - name: shared
        mountPath: /tmp/
    volumes:
    - name: shared
      emptyDir: {}

  - name: sleep
    inputs:
      parameters:
      - name: ip
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        name=$(wget -qO- http://"{{inputs.parameters.ip}}":8000/name)
        echo $name
        test "{{workflow.parameters.error}}" = "2" && kubectl -n "{{workflow.namespace}}" delete po $name || true
        sleep 10s

  - name: exit
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        sleep 10s
        echo "exit"

```




Output :

```
Namespace:           argo
ServiceAccount:      default
Status:              Error
Conditions:          
 Completed           True
Created:             Thu Nov 12 10:51:10 -0800 (19 seconds ago)
Started:             Thu Nov 12 10:51:10 -0800 (19 seconds ago)
Finished:            Thu Nov 12 10:51:29 -0800 (now)
Duration:            19 seconds
ResourcesDuration:   20s*(1 cpu),16s*(100Mi memory)
Parameters:          
  error:             0

STEP                            TEMPLATE  PODNAME                          DURATION  MESSAGE
 ⚠ daemon-missing-d5dk9         dag                                                               
 ├-⚠ daemon                     daemon    daemon-missing-d5dk9-1555427502  19s       pod deleted  
                                                                                                           
 ✔ daemon-missing-d5dk9.onExit  exit      daemon-missing-d5dk9-1417079043  14s 
```

**Comment by sarabala1979** [comment]
@lonsdale8734 I tried to reproduce this issue on my local. I couldn't reproduce it. Am I missing anything?

Workflow:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-missing-
spec:
  arguments:
    parameters:
    - name: error
      value: "0"

#  activeDeadlineSeconds: 150
  entrypoint: dag
  onExit: exit
  templates:
  - name: dag
    dag:
      tasks:
      - name: daemon
        template: daemon
      - name: sleep
        template: sleep
        dependencies: [daemon]
        arguments:
          parameters:
          - name: ip
            value: "{{tasks.daemon.ip}}"

  - name: daemon
    daemon: true
    script:
      workingDir: /tmp/
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        echo "{{pod.name}}"
        kubectl -n argo delete po "{{pod.name}}"
        sleep 30
      volumeMounts:
      - name: shared
        mountPath: /tmp/
      readinessProbe:
        exec:
          command:
          - sleep
          - 2s
        initialDelaySeconds: 5
        timeoutSeconds: 2
    sidecars:
    - name: name
      workingDir: /tmp/
      image: python:3.7.5-alpine3.10
      command: [python, -m, http.server]
      ports:
      - containerPort: 8000
      volumeMounts:
      - name: shared
        mountPath: /tmp/
    volumes:
    - name: shared
      emptyDir: {}

  - name: sleep
    inputs:
      parameters:
      - name: ip
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        name=$(wget -qO- http://"{{inputs.parameters.ip}}":8000/name)
        echo $name
        test "{{workflow.parameters.error}}" = "2" && kubectl -n "{{workflow.namespace}}" delete po $name || true
        sleep 10s

  - name: exit
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        sleep 10s
        echo "exit"

```




Output :

```
Namespace:           argo
ServiceAccount:      default
Status:              Error
Conditions:          
 Completed           True
Created:             Thu Nov 12 10:51:10 -0800 (19 seconds ago)
Started:             Thu Nov 12 10:51:10 -0800 (19 seconds ago)
Finished:            Thu Nov 12 10:51:29 -0800 (now)
Duration:            19 seconds
ResourcesDuration:   20s*(1 cpu),16s*(100Mi memory)
Parameters:          
  error:             0

STEP                            TEMPLATE  PODNAME                          DURATION  MESSAGE
 ⚠ daemon-missing-d5dk9         dag                                                               
 ├-⚠ daemon                     daemon    daemon-missing-d5dk9-1555427502  19s       pod deleted  
                                                                                                           
 ✔ daemon-missing-d5dk9.onExit  exit      daemon-missing-d5dk9-1417079043  14s 
```

**Comment by lonsdale8734** [comment]
@sarabala1979 This is the simplified workflow for v2.7.1

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-missing-
spec:
  activeDeadlineSeconds: 150
  entrypoint: dag
  onExit: exit
  templates:
  - name: dag
    dag:
      tasks:
      - name: daemon
        template: daemon
      - name: sleep
        template: sleep
        dependencies: [daemon]

  - name: daemon
    daemon: true
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        echo "{{pod.name}}"
        kubectl -n "{{workflow.namespace}}" delete po "{{pod.name}}"
        sleep 30
      readinessProbe:
        exec:
          command:
          - sleep
          - 10s
        initialDelaySeconds: 15
        timeoutSeconds: 2

  - name: sleep
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        echo "sleep"
        sleep 10s

  - name: exit
    script:
      image: bitnami/kubectl:1.15
      command: [sh]
      source: |
        set -e
        echo "exit"
        sleep 10s
```
