### ISSUE TITLE
sso secretname on configmap is not respected and defaults to sso as secretname

### ISSUE THREAD

**Issue by omerfsen** [argoproj/argo#4526]
## Summary 

sso secret name on --configmap=argo-workflow-controller-configmap is not respected and defaults to "sso" as the secret name even we define secret on  argo-workflow-controller-configmap configmap. This is working fine on v2.11.17 but not on v2.12.0-rc2

## Diagnostics

AKS 1.16.15

Argo 2.12.0-rc2

Argo-Server pods:

```yaml
kubectl logs -n argowf argo-server-b754b67fc-9qmjw 
time="2020-11-13T14:12:39Z" level=info authModes="[sso]" baseHRef=/workflow/ managedNamespace= namespace=argowf secure=false
time="2020-11-13T14:12:39Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo/tls/"
time="2020-11-13T14:12:39Z" level=info msg="config map" name=argo-workflow-controller-configmap
time="2020-11-13T14:12:40Z" level=fatal msg="failed to read secret: secrets \"sso\" not found"
```

configmap (containing argo-server-sso as sso section)

```yaml
    sso:
      clientId:
        key: client-id
        name: argo-server-sso
      clientSecret:
        key: client-secret
        name: argo-server-sso
      issuer: xxx.com
      redirectUrl: https://xxx.com/workflow/oauth2/callback
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
