### ISSUE TITLE
Failed to establish pod watch: timed out waiting for the condition

### ISSUE THREAD

**Issue by YasukeXXX** [argoproj/argo#4534]
## Summary 

Workflow is never success.
The command itself completed successfully, but Workflow returns an error `failed to save outputs: Failed to establish pod watch: timed out waiting for the condition`.

## Diagnostics

What Kubernetes provider are you using? 
EKS

What version of Argo Workflows are you running? 
v2.12.0-rc2 and v2.11.7
(install via Kustomize cluster-install)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-11-16T01:09:00Z"
  generation: 6
  labels:
    example: "true"
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
    workflows.argoproj.io/phase: Error
  name: delightful-octopus
  namespace: default
spec:
  arguments:
    parameters:
    - name: message
      value: hello argo
  entrypoint: argosay
  podGC:
    strategy: OnPodCompletion
  templates:
  - arguments: {}
    container:
      args:
      - echo
      - '{{inputs.parameters.message}}'
      command:
      - /argosay
      image: argoproj/argosay:v2
      name: main
      resources: {}
    inputs:
      parameters:
      - name: message
        value: '{{workflow.parameters.message}}'
    metadata: {}
    name: argosay
    outputs: {}
  ttlStrategy:
    secondsAfterCompletion: 300
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-11-16T01:09:48Z"
  message: 'failed to save outputs: Failed to establish pod watch: timed out waiting
    for the condition'
  nodes:
    delightful-octopus:
      displayName: delightful-octopus
      finishedAt: "2020-11-16T01:09:46Z"
      hostNodeName: ip-10-1-4-62.ap-northeast-1.compute.internal
      id: delightful-octopus
      inputs:
        parameters:
        - name: message
          value: hello argo
      message: 'failed to save outputs: Failed to establish pod watch: timed out waiting
        for the condition'
      name: delightful-octopus
      phase: Error
      progress: 1/1
      resourcesDuration:
        cpu: 34
        memory: 34
      startedAt: "2020-11-16T01:09:00Z"
      templateName: argosay
      templateScope: local/delightful-octopus
      type: Pod
  phase: Error
  progress: 1/1
  resourcesDuration:
    cpu: 34
    memory: 34
  startedAt: "2020-11-16T01:09:00Z"
```

```
time="2020-11-16T01:09:00Z" level=info msg="Processing workflow" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:00Z" level=info msg="Updated phase  -> Running" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:00Z" level=info msg="Pod node delightful-octopus initialized Pending" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:00Z" level=info msg="Created pod: delightful-octopus (delightful-octopus)" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:00Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=200504176 workflow=delightful-octopus
time="2020-11-16T01:09:00Z" level=info msg="Processing workflow" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:00Z" level=info msg="Skipped pod delightful-octopus (delightful-octopus) creation: already exists" namespace=default podPhase=Pending workflow=delightful-octopus
time="2020-11-16T01:09:00Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=200504179 workflow=delightful-octopus
time="2020-11-16T01:09:01Z" level=info msg="Processing workflow" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:01Z" level=info msg="Updating node delightful-octopus message: ContainerCreating"
time="2020-11-16T01:09:01Z" level=info msg="Skipped pod delightful-octopus (delightful-octopus) creation: already exists" namespace=default podPhase=Pending workflow=delightful-octopus
time="2020-11-16T01:09:01Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=200504189 workflow=delightful-octopus
time="2020-11-16T01:09:01Z" level=info msg="Processing workflow" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:01Z" level=info msg="Skipped pod delightful-octopus (delightful-octopus) creation: already exists" namespace=default podPhase=Pending workflow=delightful-octopus
time="2020-11-16T01:09:17Z" level=info msg="Processing workflow" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:17Z" level=info msg="Updating node delightful-octopus status Pending -> Running"
time="2020-11-16T01:09:17Z" level=info msg="Skipped pod delightful-octopus (delightful-octopus) creation: already exists" namespace=default podPhase=Running workflow=delightful-octopus
time="2020-11-16T01:09:17Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=200504349 workflow=delightful-octopus
time="2020-11-16T01:09:48Z" level=info msg="Processing workflow" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:48Z" level=info msg="Pod failed" displayName=delightful-octopus namespace=default pod=delightful-octopus templateName=argosay workflow=delightful-octopus
time="2020-11-16T01:09:48Z" level=info msg="Updating node delightful-octopus status Running -> Error"
time="2020-11-16T01:09:48Z" level=info msg="Updating node delightful-octopus message: failed to save outputs: Failed to establish pod watch: timed out waiting for the condition"
time="2020-11-16T01:09:48Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:48Z" level=info msg="Updated message  -> failed to save outputs: Failed to establish pod watch: timed out waiting for the condition" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:48Z" level=info msg="Marking workflow completed" namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:48Z" level=info msg="Checking daemoned children of " namespace=default workflow=delightful-octopus
time="2020-11-16T01:09:48Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=200504550 workflow=delightful-octopus
time="2020-11-16T01:09:48Z" level=info msg="Found Workflow default/delightful-octopus set expire at 2020-11-16 01:14:48 +0000 UTC (4m59.44526214s from now)"
time="2020-11-16T01:09:48Z" level=info msg="Queueing workflow default/delightful-octopus for delete in 4m59.44526214s"
time="2020-11-16T01:09:48Z" level=info msg="Found Workflow default/delightful-octopus set expire at 2020-11-16 01:14:48 +0000 UTC (4m59.444934473s from now)"
time="2020-11-16T01:09:48Z" level=info msg="Queueing workflow default/delightful-octopus for delete in 4m59.444934473s"
time="2020-11-16T01:09:48Z" level=info msg="Delete pod for gc successfully" namespace=default pod=delightful-octopus
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
