### ISSUE TITLE
Add workflow variable support for non-string fields

### ISSUE THREAD

**Issue by iven** [argoproj/argo#4571]
# Summary

What change needs making?

Currently workflow variables can only be used in string fields(#3041), we should add support for non-string fields.

# Use Cases

When would you use this?

For example, `activeDeadlineSeconds` is an int64 field in Argo. If I want to set the value from a parameter:

```
  templates:
  - name: apply-manifest
    inputs:
      parameters:
      - name: manifest
      - name: timeout
    resource:
      action: apply
      manifest: "{{inputs.parameters.manifest}}"
    activeDeadlineSeconds: "{{inputs.parameters.timeout}}"
```

, a validation error will be raised:

```
activeDeadlineSeconds must be a positive integer > 0 or an argo variable
```

Using yaml's type cast is also not possible:

```
    activeDeadlineSeconds: !!int "{{inputs.parameters.timeout}}"
```

, because the yaml parser tries to convert the string `"{{inputs.parameters.timeout}}"` as int first.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
