### ISSUE TITLE
How can I get sub workflow steps/tasks output?

### ISSUE THREAD

**Issue by zen-xu** [argoproj/argo#4573]
# Use Cases

When would you use this?

I created a cluster workflow template, which will do some tasks.
when I ref this template, I don't know how can I get the output from cluster workflow task/step.

For example

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
        tasks:
        - name: generate-params
          templateRef:
            name: generate-params
            template: job
            clusterScope: true
        - name: handle-params
          templateRef:
            name: calculate
            template: calculate
            clusterScope: true
          arguments:
            parameters:
            - name: params
              value: "{{tasks.generate-params.steps.gen.outputs.result}}"   // not work
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
