### ISSUE TITLE
Pod Annotations do not work on Workflow Templates

### ISSUE THREAD

**Issue by ericandrewmeadows** [argoproj/argo#4578]
## Summary 

I attempted to add `annotations` to a WorkflowTemplate Step, but only `labels` works.

Whenever `annotations` is added, neither labels nor annotations are populated on the pod itself.

## Diagnostics

What Kubernetes provider are you using?  `GKE`, v1.16

What version of Argo Workflows are you running?  `v2.12.0-rc2`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: github
  namespace: argo-events
  labels:
    workflows.argoproj.io/controller-instanceid: ci-cd
spec:
  templates:
  - name: report-status
    inputs:
      parameters:
      - name: state
      - name: context
      - name: github-status-url
    metadata:
      annotations:
        foo: bar
      labels:
        foobar: foo
```

```
time="2020-11-20T19:48:50Z" level=info msg="Processing workflow" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:50Z" level=info msg="Updated phase  -> Running" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:50Z" level=info msg="Steps node foo-build-jfqrl initialized Running" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:50Z" level=info msg="StepGroup node foo-build-jfqrl-679441083 initialized Running" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:50Z" level=info msg="Pod node foo-build-jfqrl-906143765 initialized Pending" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:50Z" level=info msg="Created pod: foo-build-jfqrl[0].git-initial-status (foo-build-jfqrl-906143765)" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:50Z" level=info msg="Workflow step group node foo-build-jfqrl-679441083 not yet completed" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:50Z" level=info msg="Workflow update successful" namespace=argo-events phase=Running resourceVersion=13627535 workflow=foo-build-jfqrl
time="2020-11-20T19:48:51Z" level=info msg="Processing workflow" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:51Z" level=info msg="Updating node foo-build-jfqrl-906143765 message: PodInitializing"
time="2020-11-20T19:48:51Z" level=info msg="Skipped pod foo-build-jfqrl[0].git-initial-status (foo-build-jfqrl-906143765) creation: already exists" namespace=argo-events podPhase=Pending workflow=foo-build-jfqrl
time="2020-11-20T19:48:51Z" level=info msg="Workflow step group node foo-build-jfqrl-679441083 not yet completed" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:51Z" level=info msg="Workflow update successful" namespace=argo-events phase=Running resourceVersion=13627548 workflow=foo-build-jfqrl
time="2020-11-20T19:48:53Z" level=info msg="Processing workflow" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:53Z" level=info msg="Skipped pod foo-build-jfqrl[0].git-initial-status (foo-build-jfqrl-906143765) creation: already exists" namespace=argo-events podPhase=Pending workflow=foo-build-jfqrl
time="2020-11-20T19:48:53Z" level=info msg="Workflow step group node foo-build-jfqrl-679441083 not yet completed" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:54Z" level=info msg="Processing workflow" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:54Z" level=info msg="Setting node foo-build-jfqrl-906143765 outputs"
time="2020-11-20T19:48:54Z" level=info msg="Updating node foo-build-jfqrl-906143765 status Pending -> Running"
time="2020-11-20T19:48:54Z" level=info msg="Workflow step group node foo-build-jfqrl-679441083 not yet completed" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:54Z" level=info msg="Workflow update successful" namespace=argo-events phase=Running resourceVersion=13627581 workflow=foo-build-jfqrl
time="2020-11-20T19:48:55Z" level=info msg="Processing workflow" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:55Z" level=info msg="Updating node foo-build-jfqrl-906143765 status Running -> Succeeded"
time="2020-11-20T19:48:55Z" level=info msg="Step group node foo-build-jfqrl-679441083 successful" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:55Z" level=info msg="node foo-build-jfqrl-679441083 phase Running -> Succeeded" namespace=argo-events workflow=foo-build-jfqrl
time="2020-11-20T19:48:55Z" level=info msg="node foo-build-jfqrl-679441083 finished: 2020-11-20 19:48:55.693913273 +0000 UTC" namespace=argo-events workflow=foo-build-jfqrl```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@ericandrewmeadows  I couldn't able to reproduce the above example.  Label and Annotations are updated on pod spec.

WorkflowTemplate
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  entrypoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      metadata:
        annotations:
          foo: bar
        labels:
          foobar: foo
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

workflow:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
      - - name: call-whalesay-template
          templateRef:
            name: workflow-template-submittable
            template: whalesay-template
          arguments:
            parameters:
            - name: message
              value: "hello world"
```



```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    foo: bar
    workflows.argoproj.io/node-name: workflow-template-hello-world-gvnf2[0].call-whalesay-template
    workflows.argoproj.io/template: '{"name":"whalesay-template","arguments":{},"inputs":{"parameters":[{"name":"message","value":"hello
      world"}]},"outputs":{},"metadata":{"annotations":{"foo":"bar"},"labels":{"foobar":"foo"}},"container":{"name":"","image":"docker/whalesay","command":["cowsay"],"args":["hello
      world"],"resources":{}},"archiveLocation":{"archiveLogs":true,"s3":{"endpoint":"minio:9000","bucket":"my-bucket","insecure":true,"accessKeySecret":{"name":"my-minio-cred","key":"accesskey"},"secretKeySecret":{"name":"my-minio-cred","key":"secretkey"},"key":"workflow-template-hello-world-gvnf2/workflow-template-hello-world-gvnf2-931789941"}}}'
  creationTimestamp: "2020-11-30T17:48:43Z"
  labels:
    foobar: foo
    workflows.argoproj.io/completed: "false"
```
