### ISSUE TITLE
UI live view hang on retryStrategy

### ISSUE THREAD

**Issue by sylock** [argoproj/argo#4597]
## Summary 

When defining a step where the template have a retryStrategy (without maxDuration defined), the last step is hanging when looking its live progression through the UI (the step is running forever from the UI point of view). 

Workaround: force a refresh of the browser with SHIFT+refresh button. Then you see that the workflow has passed and continued through its further steps.

```yml
retryStrategy:
    limit: 5
    backoff:
        duration: "5"
        factor: 2
        # maxDuration: "30s"
```
## Diagnostics

I'm using argo v2.11.7 on a pure kubernetes installed on-premise.

### View hanging
![2020-11-25_16h46_25](https://user-images.githubusercontent.com/2362405/100250331-d8199d80-2f3d-11eb-8388-18ab5048181e.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
