### ISSUE TITLE
Argo is not respecting container default entry point

### ISSUE THREAD

**Issue by simonfrey** [argoproj/argo#4627]
## Summary 

I want argo to choose the default entry point of a container. It does not.

```
      container:
        image:workflow-step-XXX:e72b5997
        args: ["{{inputs.parameters}}"]
```
fails and the following works:
```
      container:
        image:workflow-step-XXX:e72b5997
        args: ["{{inputs.parameters}}"]
        command: ["/check-preconditions"]
```
When I directly docker run the container the entry point works as expected 

### What Kubernetes provider are you using? 

GCE

### What version of Argo Workflows are you running? 

v2.11.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
