### ISSUE TITLE
synchronization semaphore lost on delete

### ISSUE THREAD

**Issue by abuckenheimer** [argoproj/argo#4632]
## Summary 

I had a large number of pending workflows (~50-100) stuck behind my synchronization semaphore (~20) and decided to shed load by deleting all workflows. I expected this to free up slots in the semaphore but it seems like deleting the workflows did not release those slots.

## Diagnostics

What Kubernetes provider are you using? 
running on EKS
```
$ kubectl --version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

What version of Argo Workflows are you running? 
v2.11.7

## Reproduction
```yaml
# example_lock.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  workflow: "3"
```

```yaml
# example_workflow.yml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
spec:
  entrypoint: whalesay
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        key: workflow
  templates:
    - name: whalesay
      container:
        image: alpine:latest
        command: [sh, -c, "sleep 5; echo hi"]
        imagePullPolicy: "IfNotPresent"

```

```bash
kubectl apply -f example_lock.yml -n argo
# do the below a few times:
# run workflow with some concurrency
argo submit example_workflow.yml -n argo & argo submit example_workflow.yml -n argo & argo submit example_workflow.yml -n argo & argo submit example_workflow.yml -n argo & argo submit exam
ple_workflow.yml -n argo
# delete running containers
argo delete --all -n argo
```

Paste the logs from the workflow controller:
```
time="2020-12-02T19:53:50Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/synchronization-wf-level-hwm2l message="Waiting for argo/ConfigMap/my-config/workflow lock. Lock status: 0/3 "
time="2020-12-02T19:53:50Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/synchronization-wf-level-94zjm message="Waiting for argo/ConfigMap/my-config/workflow lock. Lock status: 0/3 "
time="2020-12-02T19:53:51Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/synchronization-wf-level-hwm2l message="Waiting for argo/ConfigMap/my-config/workflow lock. Lock status: 0/3 "
time="2020-12-02T19:53:51Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/synchronization-wf-level-94zjm message="Waiting for argo/ConfigMap/my-config/workflow lock. Lock status: 0/3 "
time="2020-12-02T19:53:52Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/synchronization-wf-level-hwm2l message="Waiting for argo/ConfigMap/my-config/workflow lock. Lock status: 0/3 "
time="2020-12-02T19:53:57Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/synchronization-wf-level-94zjm message="Waiting for argo/ConfigMap/my-config/workflow lock. Lock status: 0/3 "
time="2020-12-02T19:53:59Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/synchronization-wf-level-5wsrz message="Waiting for argo/ConfigMap/my-config/workflow lock. Lock status: 3/3 "
time="2020-12-02T19:53:59Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" key=argo/synchronization-wf-level-lkx7p message="Waiting for argo/ConfigMap/my-config/workflow lock. Lock status: 3/3 "
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
