### ISSUE TITLE
Allow custom name in workflow started from event

### ISSUE THREAD

**Issue by michaeljohnalbers** [argoproj/argo#4640]
# Summary

It would be very useful to set the workflow name when it is started from an event.

# Use Cases

My team is using Argo to build our software when a webhook is received from Bitbucket. We use a single workflow template to build all of our various repos. So when a new workflow is kicked off from the webhook, the workflow name is always "common-workflow-&lt;generated stuff>". It makes it difficult to know which repo is being built. What I'd like to see is the ability to set the workflow name based off of data from the webhook. Or thinking it through a bit more, maybe update the generate-name value from data from the webhook (for easy name uniqueness).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Check the labels to see which workflow template was used.

**Comment by michaeljohnalbers** [comment]
> Check the labels to see which workflow template was used.

I know which template was used. We only use one. What I'm looking for is a usability enhancement. In the UI all of the workflows show up with the same(-ish) name.

For instance, suppose two builds get started for two different repos, cool-repo and bad-repo. Because both workflows will have been started from the same template, with the same generate-name value, the workflows just show up as "common-workflow-abcdef" and "common-workflow-rstlne". It would be handy if we could change that so the workflows were named "cool-repo-abcdef" and "bad-repo-rstlne". That information is only available, as far as I know, from the payload on the webhook which triggered the workflows.

 We have a fair number of workflows which run and being able to easily differentiate them would make life easier.

**Comment by alexec** [comment]
Is this UI or CLI issue? What about displaying the parameters in the workflow list?

**Comment by michaeljohnalbers** [comment]
Both, I suppose. You'd obviously see the same names if you look in the UI or run `argo list`.

Displaying the parameters might make things too cluttered. But I shouldn't be married to a specific way to fix this. Giving the ability to set the name seemed like the most straight-foward approach. And the capability is already in the CLI.

**Comment by alexec** [comment]
How do you create these from templates?

**Comment by michaeljohnalbers** [comment]
We have our Bitbucket send a webhook on a push. That is handled by a workflow event binding. Here's the binding:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: back-end-push-event
spec:
  event:
    selector: payload.eventKey == "repo:refs_changed" && discriminator == "back-end" && payload.changes[0].refId == "refs/heads/master"
  submit:
    workflowTemplateRef:
      name: common-workflow
    arguments:
      parameters:
      - name: project
        valueFrom:
          event: payload.repository.name
      - name: git-url
        valueFrom:
          event: filter(payload.repository.links.clone, {.name == "ssh"})[0].href
      - name: commit
        valueFrom:
          event: payload.changes[0].toHash
      - name: payload
        valueFrom:
          event: payload
```

**Comment by alexec** [comment]
So you need something like a new templatable field for the name?

**Comment by michaeljohnalbers** [comment]
The name of the resulting workflow, yes. I personally don't have a need to template which workflow template ref to use (and it seems like if you need to use different templates then you should probably just use a different binding). Just spit-balling, something like this might work:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: back-end-push-event
spec:
  event:
    selector: payload.eventKey == "repo:refs_changed" && discriminator == "back-end" && payload.changes[0].refId == "refs/heads/master"
  submit:
    workflowTemplateRef:
      name: common-workflow
    workflowName: # Or maybe workflowGenerateName
      valueFrom:
        event: payload.repository.name
...
```

**Comment by alexec** [comment]
This seems like a good feature. Would you like to submit a PR?

**Comment by michaeljohnalbers** [comment]
The problem is that I don't know the code-base at all and my golang knowledge is very limited.

**Comment by alexec** [comment]
DCO - yes. Submitting a PR is by far the fastest way to (a) prove there is a need and (b) get it done.

**Comment by michaeljohnalbers** [comment]
Sorry, DCO?

**Comment by alexec** [comment]
DCO = contributor agreement

**Comment by michaeljohnalbers** [comment]
Where do I find this? I don't see it on https://argoproj.github.io/argo/CONTRIBUTING/

**Comment by alexec** [comment]
https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo

**Comment by michaeljohnalbers** [comment]
I could use some help. I created a PR for this, https://github.com/argoproj/argo/pull/4783, but it's failing on the CI/Codegen check. The comment in the PR submission form says that if this happens to run `make codegen`. I run that but nothing is generated that could be included on the git commit. `git status` shows no modified files.

**Comment by lawrencenika** [comment]
how come when I used
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: acolite-binding
  namespace: argo
spec:
  event:
    selector: >-
      ...
  submit:
    metadata:
      name: 'some-hardcoded-name{{even.payload.id}}'
...
```

i got error `strict decoding error: unknown field "spec.submit.metadata.name"`
