### ISSUE TITLE
Cannot use the global variable workflow.outputs.parameters.<NAME>

### ISSUE THREAD

**Issue by sylock** [argoproj/argo#4680]
## Summary 

What we need to do : from the exit handler, access the output parameter of a workflow step. We tried to do it using the global variable workflow.outputs.parameters.<NAME> as defined in your documentation: https://argoproj.github.io/argo/variables/#global

We get an error from argo saying it cannot resolve the variable.

The error:
![2020-12-09_16h25_33](https://user-images.githubusercontent.com/2362405/101650135-e8e90980-3a3b-11eb-92fb-5c8447a3a419.png)

The piece of code where we define the output:
![2020-12-09_16h26_13](https://user-images.githubusercontent.com/2362405/101650148-ec7c9080-3a3b-11eb-9e59-2f37c826e8ea.png)

## Diagnostics

* maybe there is another way of fetching a variable of the workflow from the exit handler?
* maybe we misunderstood the use of workflow.outputs.parameters (I searched in the documentation and found nothing about it except in the variables definition page)

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
To help diagnose, please can we ask for:

* What version are you running?
* Can you attach the complete YAML for the workflow?

Thank you.

**Comment by sylock** [comment]
Version of ARgo : 2.11.7

Here is the yaml (with obsfuscated URL or sensible information).
```
<OBFUSCATED>: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: node-network-loss
  namespace: openshift-odc
spec:
  serviceAccountName: openshift-odc
  entrypoint: scenario
  onExit: exit-handler
  volumes:
  - name: ssh-keys-vol
    secret:
      secretName: node-ssh-secret
      defaultMode: 0700
      items:
      - key: key
        mode: 0600
        path: key
      - key: key.pub
        mode: 0640
        path: key.pub

  templates:
  - name: scenario
    steps:
    # Check if our cluster is healthy.
    - - name: check-nodes-ready
        template: get-ready-nodes
        arguments:
          parameters:
          - name: expected_nodes
            value: 2
    # Find the node where our pod is running.
    # Its output will be passed to the next step(s).
    - - name: find-node-with-pod
        template: get-pod-info
        arguments:
          parameters:
          - name: label_selector
            value: app=helloworld
          - name: namespace
            value: resilience-tests
          - name: excluded_node # Should be empty
            value: ""
    # Simulate that the network interface that is used for cluster communication
    # goes down. Note that we stay connected via the second interface (eth1), so
    # we can still execute SSH commands.
    - - name: node-network-down
        template: set-network-link
        arguments:
          parameters:
          - name: host
            value: "{{steps.find-node-with-pod.outputs.parameters.nodename}}"
          - name: interface
            value: eth0
          - name: state
            value: down
    # After 20-30s, one of the nodes should now be in NotReady state.
    - - name: check-node-notready
        template: get-ready-nodes
        arguments:
          parameters:
          - name: expected_nodes
            value: 1
    # Check again where our pod is running. Wait until the pod is
    # redeployed on another node. Multiple retries will be needed.
    - - name: check-pod-redeployed
        template: get-pod-info
        arguments:
          parameters:
          - name: label_selector
            value: app=helloworld
          - name: namespace
            value: resilience-tests
          - name: excluded_node
            value: "{{steps.find-node-with-pod.outputs.parameters.nodename}}"
    # Restore network connectivity on the node.
    - - name: node-network-up
        template: set-network-link
        arguments:
          parameters:
          - name: host
            value: "{{steps.find-node-with-pod.outputs.parameters.nodename}}"
          - name: interface
            value: eth0
          - name: state
            value: up
    # After 20-30 seconds, the node should come up again as Ready.
    # Pods can be scheduled again on this node.
    - - name: count-ready-nodes-final
        template: get-ready-nodes
        arguments:
          parameters:
          - name: expected_nodes
            value: 2

  - name: get-ready-nodes
    inputs:
      parameters:
      - name: expected_nodes
    retryStrategy:
      limit: 5
      backoff:
        duration: "5"
        factor: 2
        maxDuration: "4m"
    script:
      image: <OBFUSCATED>/resilience/python-requests-script
      command: [python]
      env:
      - name: API_TOKEN
        valueFrom:
          secretKeyRef:
            name: openshift-secret
            key: api_token
      source: |
        import os
        import requests
        import sys
        import urllib3

        API_URL = 'https://smals-ci.paas.acc.<OBFUSCATED>'
        API_TOKEN = os.environ['API_TOKEN'].rstrip()
        TIMEOUT = 5
        EXPECTED_READY_NODES = {{inputs.parameters.expected_nodes}}

        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

        # Get node list from Openshift API
        headers = {'Authorization': f'Bearer {API_TOKEN}'}
        resp = requests.get(f'{API_URL}/api/v1/nodes', headers=headers,
                            timeout=TIMEOUT, verify=False)
        r = resp.json()

        # Filter on worker (compute) nodes
        nodes = [
            x for x in r['items']
            if x['metadata']['labels']['role'] == 'node'
        ]

        # Check if nodes are in expected ready state
        nodes_ok = 0
        for node in nodes:
            is_ready = next(
                (x for x in node['status']['conditions']
                 if x['type'] == 'Ready' and x['status'] == 'True'),
                None
            )
            if is_ready:
              nodes_ok = nodes_ok + 1

        if nodes_ok != EXPECTED_READY_NODES:
            print(
                f'get-ready-nodes: Expected {EXPECTED_READY_NODES}, '
                f'found {nodes_ok} nodes in Ready state'
            )
            sys.exit(1)

  - name: get-pod-info
    inputs:
      parameters:
      - name: label_selector
      - name: namespace
      - name: excluded_node
    retryStrategy:
      limit: 20
      backoff:
        duration: "30"
        factor: 1
    outputs:
      parameters:
      - name: nodename
        valueFrom:
          path: nodename.txt
    script:
      image: <OBFUSCATED>/resilience/python-requests-script
      command: [python]
      source: |
        import os
        import requests
        import sys
        import urllib3

        API_URL = 'https://<OBFUSCATED>-ci.paas.acc.<OBFUSCATED>'
        API_TOKEN = os.environ['API_TOKEN'].rstrip()
        APP_LABEL_SELECTOR = '{{inputs.parameters.label_selector}}'
        APP_NAMESPACE = '{{inputs.parameters.namespace}}'
        EXCLUDED_NODE = '{{inputs.parameters.excluded_node}}'
        TIMEOUT = 5

        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

        # Construct endpoint URL
        url = (
            f'{API_URL}/api/v1/namespaces/{APP_NAMESPACE}/pods/?'
            f'labelSelector={APP_LABEL_SELECTOR}'
        )

        # Get info from Openshift API
        headers = {'Authorization': f'Bearer {API_TOKEN}'}
        resp = requests.get(url, headers=headers, timeout=TIMEOUT, verify=False)
        r = resp.json()

        if EXCLUDED_NODE != '':
            # The pod cannot run on the excluded node, we expect it to be
            # deployed elsewhere.
            pods = [
                x for x in r['items']
                if x['status']['phase'] == 'Running'
                and x['spec']['nodeName'] != EXCLUDED_NODE
            ]
        else:
            pods = [x for x in r['items'] if x['status']['phase'] == 'Running']

        if len(pods) != 1:
            print(
              'get-pod-info: Did not yet find 1 running pod on the '
              'expected node'
            )
            sys.exit(1)

        pod = pods[0]
        if 'spec' in pod and 'nodeName' in pod['spec']:
            nodename = pod['spec']['nodeName']
            # Print result to stdout
            # print(nodename)
            # Write out nodename to a file for output parameter
            print(nodename, file=open('nodename.txt', 'w'))
        else:
            print('get-pod-info: Error, did not find the nodename!')
            sys.exit(1)

      env:
      - name: API_TOKEN
        valueFrom:
          secretKeyRef:
            name: openshift-secret
            key: api_token

  - name: set-network-link
    inputs:
      parameters:
      - name: host
      - name: interface
      - name: state
    script:
      image: <OBFUSCATED>/resilience/openssh-client
      command: [bash]
      volumeMounts:
      - name: ssh-keys-vol
        mountPath: "/etc/ssh_keys"
        readOnly: false
      source: |
        ssh \
          -o "StrictHostKeyChecking no" \
          -i /etc/ssh_keys/key \
          root@{{inputs.parameters.host}} \
          ip link set {{inputs.parameters.interface}} {{inputs.parameters.state}}

  - name: exit-handler
    steps:
    # On exit, if the workflow was not successful, we always make sure to
    # restore the network connectivity on the node.
    - - name: node-network-restore
        template: set-network-link
        arguments:
          parameters:
          - name: host
            value: "{{workflow.outputs.parameters.nodename}}"
          - name: interface
            value: eth0
          - name: state
            value: up
        when: "{{workflow.status}} != Succeeded"

    # Reporting
    - - name: exit-workflow
        templateRef:
          name: resilience-exit-handler-latest
          template: exit
          clusterScope: true
        arguments:
          parameters:
          - name: testStatus
            value: "{{workflow.status}}"
          - name: failures
            value: "{{workflow.failures}}"
          - name: mailTo
            value: <OBFUSCATED>
          - name: mailSendingCondition
            value: "True"
          - name: serviceDisplayName
            value: openshift-odc
          - name: serviceVersion
            value: v1.0.0
          - name: testName
            value: node-network-loss
          - name: testDescription
            value: Loss of network connectivity of worker node
```

**Comment by alexec** [comment]
I believe this error is correct. You do not specify an output parameter with "globalName" in your manifest. 

```json
"outputs": {
          "parameters": [{"name": "nodename", "globalName": "workflow.outputs.parameters.nodename","valueFrom": {"path": "mypath"}}]
        }
```

**Comment by sylock** [comment]
Hi Alex,

Almost :) Globalname must be a string without dots. Here is the exerpt of code that works.

```
outputs:
  parameters:
    - name: nodename
      globalName: nodename
      valueFrom:
        path: nodename.txt
```

By the way, I did not found any explanation or exemple of it's usage in the documentation. It would be fine to add an example.
