### ISSUE TITLE
UI crash: "Cannot convert undefined or null to object" on timeline tab for pending workflow

### ISSUE THREAD

**Issue by austinpray-mixpanel** [argoproj/argo#4686]
## Summary 

When clicking on the timeline tab for a pending workflow, the UI crashes with the following trace:

```
Stack Trace
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at t.render (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:498:22382)
    at Ei (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:396:62906)
    at Oi (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:396:62701)
    at Pi (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:396:66535)
    at Ua (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:396:90552)
    at Xa (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:396:90936)
    at Es (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:396:97823)
    at Ds (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:396:97203)
    at js (https://ui.argo.corp.mixpanel.org/main.faeb51ce0df50d13947a.js:396:98578)
Component Stack

    in t
    in div
    in div
    in div
    in div
    in div
    in Unknown
    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in n
```

### reproduce

Submit two workflows with the same mutex:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
  namespace: default
spec:
  entrypoint: whalesay
  synchronization:
    mutex:
      name: "testmutex"
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sleep]
      args: ["100"]
```

This should put the second workflow in a pending state for 100 seconds.

![Screen Shot 2020-12-09 at 11 04 52 AM](https://user-images.githubusercontent.com/71290498/101663326-32236400-3a10-11eb-84a6-aabc339dfd2a.png)

Click through to the pending workflow's single view. Click through to the timeline tab.

![image](https://user-images.githubusercontent.com/71290498/101663743-aeb64280-3a10-11eb-81d2-7b0e458d3200.png)

The UI will crash with the aforementioned trace.

![image (3)](https://user-images.githubusercontent.com/71290498/101663860-cbeb1100-3a10-11eb-8598-607e1a186d1f.png)

## Diagnostics

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 
2.11.5

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
