### ISSUE TITLE
"parallelism" field can't be added in templates referenced inside a dag 

### ISSUE THREAD

**Issue by bnoeson** [argoproj/argo#4713]
## Summary 

I am trying to create a workflow using a DAG template referencing other templates. 

```yaml
spec:  
  entrypoint: dag-template
  templates:
    - name: task-1-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: task-2-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: dag-template
      dag:
        tasks:
          - name: task-1
            template: task-1-template
          - name: task-2
            template: task-2-template
            dependencies:
              - task-1
```

In this workflow, I need to have a task (let's say task-1) that is parallelized with max 5 tasks at the same time, while another needs to be parallelized with max 10 tasks at the same time.

When I try to add `parallelism` field inside `task-1-template`, I get the following error:
```
Internal Server Error: templates.dag-template.tasks.task-1 templates.task-1-template.parallelism is only valid for steps and dag templates
```

When looking at the [documentation](https://argoproj.github.io/argo/fields/#templateref), `parallelism` is an attribute of a template object. Furthermore, it is called from a dag, and so fits with the `dag template` description. I would then expect that my use case is possible.

## Diagnostics

What Kubernetes provider are you using? Rancher (k8s v1.16.8)

What version of Argo Workflows are you running? v2.11.6

To reproduce the behavior : 

```yaml
spec:  
  entrypoint: dag-template
  templates:
    - name: task-1-template
      parallelism: 1
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: task-2-template
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: dag-template
      dag:
        tasks:
          - name: task-1
            template: task-1-template
          - name: task-2
            template: task-2-template
            dependencies:
              - task-1
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
try:

```yaml
spec:  
  parallelism: 1
  entrypoint: dag-template
```

**Comment by bnoeson** [comment]
This doesn't match my use case. I would like to have different parallelism values for the 2 tasks. For now I didn't find a way to have that.

Example:

```
spec:  
  entrypoint: dag-template
  templates:
    - name: task-1-template
      parallelism: 1
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: task-2-template
      parallelism: 10
      container:
        image: 'python:alpine3.6'
        command:
          - echo
          - performing...
    - name: dag-template
      dag:
        tasks:
          - name: task-1
            template: task-1-template
          - name: task-2
            template: task-2-template
            dependencies:
              - task-1
```

**Comment by jessesuen** [comment]
```yaml
  templates:
    - name: task-1-template
      parallelism: 1
      container:
        image: 'python:alpine3.6'
```

As the error message indicates, parallelism is valid on dag or steps. You are attempting to put it on a single container template which by definition, cannot have parallelism.

I think you want this:

```yaml
    - name: dag-template
      dag:
        parallelism: 10
        tasks:
          - name: task-1
            template: task-1-template
          - name: task-2
            template: task-2-template
            dependencies:
              - task-1
```
