### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined When trying to inspect WF containers in UI

### ISSUE THREAD

**Issue by avifried1** [argoproj/argo#4745]
## Summary 
Happens only for specific workflow (regardless of exit status). Reproduce in dashboard:
- Go to workflow.
- Press running pod.
- Go to `Containers` section.

Console throws: 

```
TypeError: Cannot read property 'find' of undefined
    at Object.t.getResolvedTemplates (template-resolution.ts:19)
    at n.render (workflow-node-info.tsx:240)
    at Oi (react-dom.production.min.js:173)
    at Ti (react-dom.production.min.js:172)
    at Ni (react-dom.production.min.js:180)
    at Ua (react-dom.production.min.js:232)
    at Xa (react-dom.production.min.js:233)
    at Os (react-dom.production.min.js:249)
    at Cs (react-dom.production.min.js:248)
    at Ps (react-dom.production.min.js:251)
```

Component stack:

```
Component Stack

    in n
    in div
    in div
    in t
    in div
    in Unknown
    in div
    in div
    in div
    in div
    in div
    in Unknown
    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in n
```

## Diagnostics

What version of Argo Workflows are you running? **2.12.0-rc5**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: graph-template
  labels:
    job-name: graph
spec:
  entrypoint: graph
  arguments:
    parameters:
      - name: date
        value: ""
      - name: range
        value: ""
      - name: debug
        value: "false"
  workflowMetadata:
    labels:
      app-group: general
  ttlStrategy:
    secondsAfterSuccess: 1209600
    secondsAfterFailure: 604800
  activeDeadlineSeconds: 86400

  templates:
  - name: graph
    volumes:
      - name: graph-config-volume
        configMap:
          name: graph-config-map
          items:
            - key: config-as-json
              path: configApp.json
    inputs:
      parameters:
      - name: date
      - name: range
      - name: debug
        default: "false"
    container:
      image: "11111111.dkr.ecr.us-east-1.amazonaws.com/image-name:latest"
      args:
        - "--date"
        - "{{inputs.parameters.date}}"
        - "--range"
        - "{{inputs.parameters.range}}"
      imagePullPolicy: Always
      env:
        - name: ENV
          value: prod
      volumeMounts:
        - name: graph-config-volume
          mountPath: /etc/config
```

No controller log errors

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
