### ISSUE TITLE
Support external link annotation

### ISSUE THREAD

**Issue by kenchan0130** [argoproj/argo#4752]
# Summary

Like https://github.com/argoproj/argo-cd/pull/4380, we may want to put external links to workflow templates and workflow execution results as well.

# Use Cases

- Check the specifications for workflow.
- Check logs and performance of workflow execution results

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
A feature to add links exists: https://argoproj.github.io/argo/links/
If we had a standard annotation we could modify the code to allow you to link that too. Would you like to submit a PR?

**Comment by kenchan0130** [comment]
> A feature to add links exists: https://argoproj.github.io/argo/links/

This is to provide a link to the argo server, and I am aware that it is not possible to provide a link for individual workflows.

> If we had a standard annotation we could modify the code to allow you to link that too. Would you like to submit a PR?

I don't know what the policy is for modifications, so please let me know.

Are you assuming that you don't add any processing on the server side, but modify the front end (probably [around here](https://github.com/argoproj/argo/blob/master/ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx))?

**Comment by alexec** [comment]
```yaml
links:
      - name: Example Workflow Link
        scope: workflow
        url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
      - name: Example Pod Link
        scope: pod
        url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
```

I thinking new formatting things could be added:

```yaml
links:
      - name: Example Workflow Link
        scope: workflow
        URL: "${metadata.annotations[''workflows.argoproj.io/external-link"]}'
```

You'd need to modify this func to support it:

https://github.com/argoproj/argo/blob/master/ui/src/app/workflows/components/workflow-details/workflow-details.tsx#L350
