### ISSUE TITLE
prepending ExecutorScriptSourcePath breaks using script with args without command

### ISSUE THREAD

**Issue by MrFreezeex** [argoproj/argo#4782]
## Summary 

We use a script with an `args` with `sh` (and not a `command`). Our image has an entrypoint and exec the rest of the arguments with something like `exec "$@"`.
The PR https://github.com/argoproj/argo/pull/4492 breaks these types of workflows (see the example below).

I don't know what should be the right behavior but executing the entrypoint before a script is pretty convenient. For instance, we use it to do some privileged actions and then we drop privileges before executing the workflow's script.

## Diagnostics

What Kubernetes provider are you using? Baremetal

What version of Argo Workflows are you running? v2.12.2

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-args-script
spec:
  entrypoint: test
  templates:
  - name: test
    script:
      image: mrfreezeex/test-argow-script:v1
      args: [sh]
      source: |
        echo "This message won't be shown!"
```

My test image is built using these files :

Dockerfile :
```
FROM alpine

COPY entrypoint.sh entrypoint.sh

ENTRYPOINT entrypoint.sh
CMD echo hello
```

entrypoint.sh :
```
#!/bin/sh

exec "$@"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
