### ISSUE TITLE
Can't submit workflow: failed to resolve {{workflow.namespace}}

### ISSUE THREAD

**Issue by Seanny123** [argoproj/argo#4805]
## Summary 

When trying to submit a workflow, the submission fails due to:
```
ServiceAccount:      argo
Status:              Failed
Message:             failed to resolve {{workflow.namespace}}
Conditions:          
 Completed           True
Created:             Mon Dec 28 18:20:23 -0500 (1 second ago)
Started:             Mon Dec 28 18:20:23 -0500 (1 second ago)
Finished:            Mon Dec 28 18:20:23 -0500 (1 second ago)
Duration:            0 seconds
Progress:            0/0
Parameters:          
  project:           {{workflow.namespace}}
  input-s3-bucket:   the-proj-{{workflow.parameters.project}}
  nstructs:          3
```

## Diagnostics

Argo version
```
argo: v2.12.2
  BuildDate: 2020-12-18T18:00:03Z
  GitCommit: 7868e723704bcfe1b943bc076c2e0b83777d6267
  GitTreeState: clean
  GitTag: v2.12.2
  GoVersion: go1.13.15
  Compiler: gc
  Platform: linux/amd64
```

Minimal workflow to reproduce
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: filter-flop-
spec:
  serviceAccountName: argo
  hostNetwork: true
  podDisruptionBudget:
    minAvailable: 99999
  podGC:
    strategy: OnPodSuccess

  arguments:
    parameters:
      - name: project
        value: "{{workflow.namespace}}"
      - name: input-s3-bucket
        value: "the-proj-{{workflow.parameters.project}}"
      # these sample values should be overridden by a parameter file 
      - name: nstructs
        value: "3"

  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: sequence-count
            template: echo
            withSequence:
              count: "{{workflow.parameters.nstructs}}"
            arguments:
              parameters:
                - name: str-to-echo
                  value: "{{workflow.parameters.input-s3-bucket}}"

    - name: echo
      inputs:
        parameters:
          - name: str-to-echo
      script:
        image: fedora:32
        command: [bash]
        source: |
          #!/bin/bash

          set -xe

          echo "Processed {{inputs.parameters.str-to-echo}}"
```

If I change the parameter `str-to-echo` to:
```
- name: str-to-echo
  value: "{{workflow.namespace}}"
```

There is no error and the workflow is submitted and run successfully. So there's something about the parameter `input-s3-bucket` that's causing this problem, but I can't figure out what it is. Even if the cause of the error isn't a bug, there should probably be a better error message?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
