### ISSUE TITLE
Unable to submit the following yaml through argo2 cli (works with kubectl create)

### ISSUE THREAD

**Issue by gaganapplatix** [argoproj/argo#481]
I get the error:
```
2017/11/20 16:16:39 Get /Users/gagan/Develop/workspace/workflows/logging-cleanup-workflow.yaml: unsupported protocol scheme ""
```
But running same yaml through kubectl create -f works and gives desired results.
```
apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: logging-workflow-
spec:
  entrypoint: sock-shop-logging

  templates:
  - name: sock-shop-logging
    steps:
    - - name: deploy
        template: logging-deploy

  - name: logging-deploy
    inputs:
      artifacts:
      - name: logging-manifests
        path: /src
        git:
          repo: https://github.com/argoproj/example-cd.git
          revision: "master"
      - name: kubectl
        path: /usr/local/bin/kubectl
        http:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.8.3/bin/linux/amd64/kubectl
        mode: 755
    container:
      image: docker.io/debian:9.2
      command: ["/bin/sh", "-c"]
      args: ['kubectl create -f "/src/example-cd/logging"']
```
