### ISSUE TITLE
argo cli generates none non-obvious error message

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo#482]
[ERR_BAD_REQUEST] influxdb-ci.yaml: template 'test-cov' steps[0]. name is not unique

```
  - name: test-cov
    inputs:
      artifacts:
      - name: source
    steps:
    - - test-cov-query:
        template: test-cov-base
        arguments:
          parameters:
          - name: package
            value: "query"
      - test-cov-tsm1:
        template: test-cov-base
        arguments:
          parameters:
          - name: package
            value: "tsdb/engine/tsm1"
```
