### ISSUE TITLE
Improve syntax checking when passing artifacts to nested workflows

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo#484]
Here, we pass an artifact to test-cov which passes the artifact to test-cov-base.
If the artifact is not explicitly specified or specified with a missing 'from: "{{inputs.artifacts.source}}" statement, the workflow can be submitted but the controller complains with: "time="2017-11-21T00:47:14Z" level=error msg="influxdb-ci-9xzcn error: [ERR_BAD_REQUEST] arguments.artifacts.source missing location information"
```
  - name: test-cov
    inputs:
      artifacts:
      - name: source
    steps:
    - - name: test-cov-query
        template: test-cov-base
        arguments:
          parameters:
          - name: package
            value: "query"
```
