### ISSUE TITLE
Semaphores not working

### ISSUE THREAD

**Issue by indiejames** [argoproj/argo#4874]
## Summary 

What happened/what you expected to happen?

Running the semaphore example in the documentation (https://argoproj.github.io/argo/synchronization/) fails when tryring to look up the synchronization concurrency value from the provided configmap. The error message is 
```
Failed to acquire the synchronization lock. Sync configuration key 'workflow' not found in ConfigMap
```

It should run without failure and use the value from the configmap to limit concurrency of the workflow execution. 

## Diagnostics

What Kubernetes provider are you using? 

Docker Desktop Mac

What version of Argo Workflows are you running? 

v2.11.5

For the configmap (kubectl -n argo create configmap my-config --from-file=my-config.yaml)
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: my-config
data:
  workflow: "1"  # Only one workflow can run at given time in particular namespace
  template: "2"  # Two instance of template can run at a given time in particular namespace 
```
For the workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
spec:
  entrypoint: whalesay
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        key: workflow
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

```
time="2021-01-13T18:22:38Z" level=warning msg="Failed to acquire the lock" error="Sync configuration key 'workflow' not found in ConfigMap" key=argo/synchronization-wf-level-jscns
time="2021-01-13T18:22:38Z" level=info msg="Updated phase  -> Failed" namespace=argo workflow=synchronization-wf-level-jscns
time="2021-01-13T18:22:38Z" level=info msg="Updated message  -> Failed to acquire the synchronization lock. Sync configuration key 'workflow' not found in ConfigMap" namespace=argo workflow=synchronization-wf-level-jscns
time="2021-01-13T18:22:38Z" level=info msg="Marking workflow completed" namespace=argo workflow=synchronization-wf-level-jscns
time="2021-01-13T18:22:38Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=5164561 workflow=synchronization-wf-level-jscns
time="2021-01-13T18:23:46Z" level=warning msg="Failed to acquire the lock" error="Sync configuration key 'workflow' not found in ConfigMap" key=argo/synchronization-wf-level-24fv8
time="2021-01-13T18:23:46Z" level=info msg="Updated phase  -> Failed" namespace=argo workflow=synchronization-wf-level-24fv8
time="2021-01-13T18:23:46Z" level=info msg="Updated message  -> Failed to acquire the synchronization lock. Sync configuration key 'workflow' not found in ConfigMap" namespace=argo workflow=synchronization-wf-level-24fv8
time="2021-01-13T18:23:46Z" level=info msg="Marking workflow completed" namespace=argo workflow=synchronization-wf-level-24fv8
time="2021-01-13T18:23:46Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=5164682 workflow=synchronization-wf-level-24fv8
time="2021-01-13T18:24:16Z" level=warning msg="Failed to acquire the lock" error="Sync configuration key 'workflow' not found in ConfigMap" key=argo/synchronization-wf-level-th45v
time="2021-01-13T18:24:16Z" level=info msg="Updated phase  -> Failed" namespace=argo workflow=synchronization-wf-level-th45v
time="2021-01-13T18:24:16Z" level=info msg="Updated message  -> Failed to acquire the synchronization lock. Sync configuration key 'workflow' not found in ConfigMap" namespace=argo workflow=synchronization-wf-level-th45v
time="2021-01-13T18:24:16Z" level=info msg="Marking workflow completed" namespace=argo workflow=synchronization-wf-level-th45v
time="2021-01-13T18:24:16Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=5164737 workflow=synchronization-wf-level-th45v
time="2021-01-13T18:56:49Z" level=warning msg="Failed to acquire the lock" error="Sync configuration key 'workflow' not found in ConfigMap" key=argo/synchronization-wf-level-hkh89
time="2021-01-13T18:56:49Z" level=info msg="Updated phase  -> Failed" namespace=argo workflow=synchronization-wf-level-hkh89
time="2021-01-13T18:56:49Z" level=info msg="Updated message  -> Failed to acquire the synchronization lock. Sync configuration key 'workflow' not found in ConfigMap" namespace=argo workflow=synchronization-wf-level-hkh89
time="2021-01-13T18:56:49Z" level=info msg="Marking workflow completed" namespace=argo workflow=synchronization-wf-level-hkh89
time="2021-01-13T18:56:49Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=5168627 workflow=synchronization-wf-level-hkh89
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@sarabala1979 should people be testing with v2.12.4?

**Comment by indiejames** [comment]
> @sarabala1979 should people be testing with v2.12.4?

Just tested with v2.12.4 and it fails the same way. Perhaps an issue with Docker Desktop on Mac?

**Comment by indiejames** [comment]
FWIW I can use see the configmap with kubectl and it has the right values
```
kubectl -n argo describe configmap my-config                                 
Name:         my-config
Namespace:    argo
Labels:       <none>
Annotations:  <none>

Data
====
semaphore.yaml:
----
apiVersion: v1
kind: ConfigMap
metadata:
 name: my-config
data:
  workflow: "1"  # Only one workflow can run at given time in particular namespace
  template: "2"  # Two instance of template can run at a given time in particular namespace
Events:  <none>
```

**Comment by sarabala1979** [comment]
@indiejames are you submitting the in the same namespace?  can you provide the problem workflow  yaml using `kubectl get wf <name> -o yaml`?

**Comment by indiejames** [comment]
Yes, it's the same namespace. The yam is this
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2021-01-13T21:58:42Z"
  generateName: synchronization-wf-level-
  generation: 2
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
    workflows.argoproj.io/phase: Failed
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:workflows.argoproj.io/creator: {}
      f:spec:
        .: {}
        f:arguments: {}
        f:entrypoint: {}
        f:synchronization:
          .: {}
          f:semaphore:
            .: {}
            f:configMapKeyRef:
              .: {}
              f:key: {}
              f:name: {}
        f:templates: {}
      f:status: {}
    manager: argo
    operation: Update
    time: "2021-01-13T21:58:42Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:workflows.argoproj.io/completed: {}
          f:workflows.argoproj.io/phase: {}
      f:status:
        f:conditions: {}
        f:finishedAt: {}
        f:message: {}
        f:phase: {}
        f:startedAt: {}
    manager: workflow-controller
    operation: Update
    time: "2021-01-13T21:58:42Z"
  name: synchronization-wf-level-zn5l8
  namespace: argo
  resourceVersion: "5187844"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/synchronization-wf-level-zn5l8
  uid: 56719f50-e648-4af2-8e60-1a4a0386ac03
spec:
  arguments: {}
  entrypoint: whalesay
  synchronization:
    semaphore:
      configMapKeyRef:
        key: workflow
        name: my-config
  templates:
  - arguments: {}
    container:
      args:
      - hello world
      command:
      - cowsay
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: whalesay
    outputs: {}
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2021-01-13T21:58:42Z"
  message: Failed to acquire the synchronization lock. Sync configuration key 'workflow'
    not found in ConfigMap
  phase: Failed
  startedAt: "2021-01-13T21:58:42Z"
```

**Comment by sarabala1979** [comment]
it looks like your env problem. I am able to run the workflow with the above CM and WF.
```
Name:                synchronization-wf-level-zn797
Namespace:           argo
ServiceAccount:      default
Status:              Succeeded
Conditions:          
 Completed           True
Created:             Wed Jan 13 17:46:12 -0800 (7 seconds ago)
Started:             Wed Jan 13 17:46:12 -0800 (7 seconds ago)
Finished:            Wed Jan 13 17:46:19 -0800 (now)
Duration:            7 seconds
ResourcesDuration:   4s*(1 cpu),2s*(100Mi memory)

STEP                               TEMPLATE  PODNAME                         DURATION  MESSAGE
 ✔ synchronization-wf-level-zn797  whalesay  synchronization-wf-level-zn797  5s    
```

**Comment by chris-durbin** [comment]
I repeated the instructions from the description and submitted a workflow via the UI and saw the same error.

This is in AWS using EKS with Argo version 2.11.5.

**Comment by indiejames** [comment]
Tried v2.12.5 and still seeing the same behavior.

**Comment by sarabala1979** [comment]
> I repeated the instructions from the description and submitted a workflow via the UI and saw the same error.
> 
> This is in AWS using EKS with Argo version 2.11.5.

@chris-durbin Please make sure you are submitting to the same namespace from UI.

**Comment by sarabala1979** [comment]
>time="2021-01-13T18:22:38Z" level=info msg="Updated message  -> Failed to acquire the synchronization lock. Sync configuration key 'workflow' not found in ConfigMap" namespace=argo workflow=synchronization-wf-level-jscns
time="2021-01-13T18:22:38Z" level=info msg="Marking workflow completed" namespace=argo workflow=synchronization-wf-level-jscns

Based above log, controller able to find `configmap` but it doesn't find the `workflow`.  Can you provide live configmap using `kubectl get cm my-config -o yaml`

**Comment by chris-durbin** [comment]
Tested again with the same error message.

I'm using the 'argo' namespace when I create the ConfigMap and the same 'argo' namespace when I submit the workflow.

**Comment by sarabala1979** [comment]
@chris-durbin can you provide the output of `kubectl get cm my-config -o yaml -n argo`?  This feature is working as expected in locally and in our environment also. Can we have a quick zoom call?

**Comment by sarabala1979** [comment]
@indiejames @chris-durbin  thanks for the support. Found the issue configmap creation in @indiejames env and fix it.
Entire configamp yaml add as the value in this configmap.

Not working  Configmap:
```yaml
apiVersion: v1
data:
  my-config.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
     namespace: argo
     name: my-config
    data:
      workflow: "1"  # Only one workflow can run at given time in particular namespace
      template: "2"  # Two instance of template can run at a given time in particular namespace
kind: ConfigMap
```

Working Configmap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: my-config
 namespace: argo
data:
  workflow: "1"  # Only one workflow can run at given time in particular namespace
  template: "3"
```
