### ISSUE TITLE
argo cron submit

### ISSUE THREAD

**Issue by seddonm1** [argoproj/argo#4882]
# Summary

Currently the `argo cron` CLI does not make it easy to execute an Argo `CronWorkflow` a single time as a validation that the workflow works without scheduling the job.

My proposal is we add an `argo cron submit` or modify the `argo submit` command to accept a `CronWorkflow`, unwrap the `workflowSpec` and run it a single time as per any other `argo submit`.

I can submit a PR if this proposal is accepted and the `argo cron submit` vs `argo submit` is decided (or another option).

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["🕓 hello world"]
```
# Use Cases

This would allow CICD testing of the workflow contained within the CRON job without having to deploy the CRON job.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
