### ISSUE TITLE
default template spec on workflow-controller-configmap

### ISSUE THREAD

**Issue by krrrr38** [argoproj/argo#5042]
# Summary

1.Add `templateDefaults` into workflow-controller-configmap like https://argoproj.github.io/argo/default-workflow-specs/
2. execute workflow expanding templates using `templateDefaults`

# Use Cases

Currently we can collect all workflow metrics using `workflowDefaults` easily.
Template-level metrics also can be collected like https://argoproj.github.io/argo/metrics/#metric-spec. But there is no settings for `templateDefaults`. To collect all template level metrics easily, I suggest to add it.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Out of curiosity: what metric would be you be interested in capturing for all templates?

**Comment by krrrr38** [comment]
I want to collect `exec_duration` for each steps.

**Comment by krrrr38** [comment]
I wrote the yaml expand example here.

<details>
<summary>templateDefaults expands workflow example</summary>

1. setup configmap with `templateDefaults`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  templateDefaults: |
    metrics:
      prometheus:
      - name: exec_template_duration_gauge
        labels:
          - key: name
            value: model_a
        help: "Duration gauge by name"
        gauge:
          value: "{{duration}}"
```

2. prepare WorkflowTemplate using `templates`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: steps-
spec:
  entrypoint: hello1
  templates:
  - name: hello1
    steps:
    - - name: hello1-step1
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello1"}]
  - name: hello2
    - - name: hello2-step1
        templateRef:
          name: someWorkflowTemplate
          template: entrypoint
```

then expand workflow like following.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello
  templates:
  - name: hello1
    steps:
    - - name: hello1-step1
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello1"}]
            metrics:
        prometheus:
        - name: exec_template_duration_gauge
          labels:
            - key: name
              value: model_a
          help: "Duration gauge by name"
          gauge:
            value: "{{duration}}"
  - name: hello2
    - - name: hello2-step1
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello2"}]
            metrics:
        prometheus:
        - name: exec_template_duration_gauge
          labels:
            - key: name
              value: model_a
          help: "Duration gauge by name"
          gauge:
            value: "{{duration}}"
```
</details>

----

But, I know that [there is template duration metrics, but not exists step duration metrics currently](https://argoproj.github.io/argo/variables/#metrics).
Probably I might collect step metrics as pod duration and so on. I will investigate more and open issue again, when clearing the solution.
