### ISSUE TITLE
Runtime error while submitting a workflow

### ISSUE THREAD

**Issue by hibnico** [argoproj/argo#5051]
## Summary 

I am trying to use workflow template. I have submitted my first try at it, so probably the workflow is not well shaped, but the workflow controller is having a runtime error trying to handle the workflow.

## Diagnostics

What Kubernetes provider are you using? 

It is a self hosted one, 1.12.

What version of Argo Workflows are you running? 

I first got the error with Argo 2.12.6. I tried with the last version, 2.12.8, got the same error.

Here are the submitted resources:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft1
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: values
        value: "{\"n\":1}"
  templates:
    - name: main
      dag:
        tasks:
          - name: task1
            template: job
            arguments:
              parameters:
                - name: values
                  value: "{{inputs.parameters.values}}"
                - name: name
                  value: "wft1.task1"
          - name: task2
            depends: task1.Succeeded
            template: job
            arguments:
              parameters:
                - name: values
                  value: "{{tasks.task1.outputs.parameters.values}}"
                - name: name
                  value: "wft1.task2"
      outputs:
        parameters:
          - name: values
            valueFrom:
              parameter: "{{tasks.task2.outputs.parameters.values}}"
    - name: job
      inputs:
        parameters:
          - name: values
          - name: name
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"Job {{inputs.parameters.name}}\" && echo '{{inputs.parameters.values}}' > /mnt/out/values.json"]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      metadata:
        labels:
          "io.saagie/job-execution-id": "wft1-argonla-test-job-id"
      volumes:
        - name: out
          emptyDir: { }
      outputs:
        parameters:
          - name: values
            valueFrom:
              path: /mnt/out/values.json

  outputs:
    parameters:
      - name: values
        value: "{{tasks.main.outputs.parameters.values}}"

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wft2
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: values
      - name: name
  templates:
    - name: main
      dag:
        tasks:
          - name: task1
            template: job
            arguments:
              parameters:
                - name: values
                  value: "{{inputs.parameters.values}}"
                - name: name
                  value: "{{inputs.parameters.name}}.task1"
          - name: task2
            depends: task1.Succeeded
            template: job
            arguments:
              parameters:
                - name: values
                  value: "{{tasks.task1.outputs.parameters.values}}"
                - name: name
                  value: "{{inputs.parameters.name}}.task2"
      outputs:
        parameters:
          - name: values
            valueFrom:
              parameter: "{{tasks.task2.outputs.parameters.values}}"
    - name: job
      inputs:
        parameters:
          - name: values
          - name: name
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"Job {{inputs.parameters.name}}\" && echo '{{inputs.parameters.values}}' > /mnt/out/values.json"]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      metadata:
        labels:
          "io.saagie/job-execution-id": "wft2-argonla-test-job-id"
      volumes:
        - name: out
          emptyDir: { }
      outputs:
        parameters:
          - name: values
            valueFrom:
              path: /mnt/out/values.json

  outputs:
    parameters:
      - name: values
        value: "{{tasks.main.outputs.parameters.values}}"



---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wfinwf-
  labels:
    io.saagie/pipeline-id: "wfinwf-test"
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: values
  templates:
    - name: main
      dag:
        tasks:
          - name: task1
            templateRef:
              name: wft1
              template: main
            arguments:
              parameters:
                - name: values
                  value: "{{workflow.parameters.values}}"

          - name: condition-eval1
            depends: task1.Succeeded
            template: condition-eval
            arguments:
              parameters:
                - name: values
                  value: "{{tasks.task1.outputs.parameters.values}}"
                - name: condition
                  value: "values[\"n\"] > 0"
          - name: condition-when1
            depends: condition-eval1.Succeeded
            template: nop
            when: "{{tasks.condition-eval1.outputs.parameters.condition}}"
          - name: task2
            depends: condition-when1.Succeeded
            templateRef:
              name: wft2
              template: main
            arguments:
              parameters:
                - name: values
                  value: "{{tasks.condition-eval1.outputs.parameters.values}}"
                - name: name
                  value: "main.task2"

          - name: condition-eval2
            depends: task1.Succeeded
            template: condition-eval
            arguments:
              parameters:
                - name: values
                  value: "{{tasks.task1.outputs.parameters.values}}"
                - name: condition
                  value: "values[\"n\"] < 0"
          - name: condition-when2
            depends: condition-eval2.Succeeded
            template: nop
            when: "{{tasks.condition-eval2.outputs.parameters.condition}}"
          - name: task3
            depends: condition-when2.Succeeded
            templateRef:
              name: wft2
              template: main
            arguments:
              parameters:
                - name: values
                  value: "{{tasks.condition-eval2.outputs.parameters.values}}"
                - name: name
                  value: "main.task3"

          - name: task4
            depends: task2.Succeeded || task3.Succeeded
            template: job
            arguments:
              parameters:
                - name: values
                  value: "{}"
                - name: name
                  value: "task4"

    - name: bootstrap
      inputs:
        parameters:
          - name: "n"
      container:
        image: alpine:3.6
        command: [ sh, -c ]
        args: [ "echo -n '{\"n\": {{inputs.parameters.n}}}' > /mnt/out/values.json" ]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      volumes:
        - name: out
          emptyDir: { }
      outputs:
        parameters:
          - name: values
            valueFrom:
              path: /mnt/out/values.json

    - name: wf1
      inputs:
        parameters:
          - name: values
      dag:
        tasks:
          - name: task1
            template: job
            arguments:
              parameters:
                - name: values
                  value: "{{inputs.parameters.values}}"
                - name: name
                  value: "wf1.task1"
          - name: task2
            depends: task1.Succeeded
            template: job
            arguments:
              parameters:
                  - name: values
                    value: "{{tasks.task1.outputs.parameters.values}}"
                  - name: name
                    value: "wf1.task2"
      outputs:
        parameters:
          - name: values
            valueFrom:
              parameter: "{{tasks.task2.outputs.parameters.values}}"

    - name: wf2
      inputs:
        parameters:
          - name: name
          - name: values
      dag:
        tasks:
          - name: task1
            template: job
            arguments:
              parameters:
                - name: values
                  value: "{{inputs.parameters.values}}"
                - name: name
                  value: "{{inputs.parameters.name}}.task1"
          - name: task2
            depends: task1.Succeeded
            template: job
            arguments:
              parameters:
                - name: values
                  value: "{{tasks.task1.outputs.parameters.values}}"
                - name: name
                  value: "{{inputs.parameters.name}}.task2"

    - name: job
      inputs:
        parameters:
          - name: values
          - name: name
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"Job {{inputs.parameters.name}}\" && echo '{{inputs.parameters.values}}' > /mnt/out/values.json"]
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      metadata:
        labels:
          "io.saagie/job-execution-id": "argonla-test-job-id"
      volumes:
        - name: out
          emptyDir: { }
      outputs:
        parameters:
          - name: values
            valueFrom:
              path: /mnt/out/values.json

    - name: condition-eval
      inputs:
        parameters:
          - name: values
          - name: condition
      script:
        image: python:alpine3.6
        command: [python]
        args: ["{{inputs.parameters.values}}"]
        source: |
          import json
          import sys
          values = json.loads(sys.argv[1])
          condition = {{inputs.parameters.condition}}
          with open("/mnt/out/condition.txt", "wt") as f:
              f.write("true" if condition else "false")
          with open("/mnt/out/values.json", "wt") as f:
              f.write(sys.argv[1])
        volumeMounts:
          - name: out
            mountPath: /mnt/out
      volumes:
        - name: out
          emptyDir: { }
      outputs:
        parameters:
          - name: condition
            valueFrom:
              path: /mnt/out/condition.txt
          - name: values
            valueFrom:
              path: /mnt/out/values.json
    - name: nop
      script:
        image: python:alpine3.6
        command: [python]
        source: ""
```

Here are the logs from the controller:

```
time="2021-02-09T09:09:26.267Z" level=info msg="Processing workflow" namespace=argonla workflow=wfinwf-sjn6m
time="2021-02-09T09:09:26.267Z" level=error msg="Recovered from panic" namespace=argonla r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 201 [running]:\nruntime/debug.Stack(0xc0968fab6a, 0x180bdc0, 0x29f3e30)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).operate.func2(0xc000151140)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:184 +0xbe\npanic(0x180bdc0, 0x29f3e30)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).setGlobalParameters(0xc000151140, 0xc0002abd10, 0x1, 0x1, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:476 +0x66e\ngithub.com/argoproj/argo/v2/workflow/controller.(*wfOperationCtx).operate(0xc000151140)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:229 +0x480\ngithub.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).processNextItem(0xc0001c4e00, 0xa0f120b10334400)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:574 +0x828\ngithub.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).runWorker(0xc0001c4e00)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:496 +0x2b\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000ae2b50)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:152 +0x5e\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ae2b50, 0x3b9aca00, 0x0, 0x1, 0xc00073c960)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:153 +0xf8\nk8s.io/apimachinery/pkg/util/wait.Until(0xc000ae2b50, 0x3b9aca00, 0xc00073c960)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:88 +0x4d\ncreated by github.com/argoproj/argo/v2/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:215 +0xa5d\n" workflow=wfinwf-sjn6m
time="2021-02-09T09:09:26.267Z" level=info msg="Updated phase  -> Error" namespace=argonla workflow=wfinwf-sjn6m
time="2021-02-09T09:09:26.267Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=argonla workflow=wfinwf-sjn6m
time="2021-02-09T09:09:26.267Z" level=info msg="Marking workflow completed" namespace=argonla workflow=wfinwf-sjn6m
time="2021-02-09T09:09:26.267Z" level=info msg="Checking daemoned children of " namespace=argonla workflow=wfinwf-sjn6m
time="2021-02-09T09:09:26.293Z" level=info msg="Workflow update successful" namespace=argonla phase=Error resourceVersion=50554430 workflow=wfinwf-sjn6m
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
