### ISSUE TITLE
Workflows with fixed names don't get marked completed

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#554]
A workflow with a fixed name (as against a "generateName") doesn't get marked completed. It remains in Running state forever, even when the pods comprising that workflow complete.

The following workflow stays in Running state forever:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    name: my-test
spec:
    entrypoint: run-workflow
    templates:
    - name: run-workflow
      container:
        image: alpine:3.6
        command: ["sleep", "5"]
```

Simply changing the same workflow to have "generateName" works correctly:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    generateName: my-test-
spec:
    entrypoint: run-workflow
    templates:
    - name: run-workflow
      container:
        image: alpine:3.6
        command: ["sleep", "5"]
```
