### ISSUE TITLE
Support for GPU resources

### ISSUE THREAD

**Issue by dvavili** [argoproj/argo#577]
For Machine learning workflows we would require to schedule jobs/pods on nodes with GPU resources. Need support to mention GPU resources in workflow spec.

**Comment by edlee2121** [comment]
@jessesuen Need to document how to schedule pods on GPU nodes.

**Comment by jessesuen** [comment]
Hi @dvavili, are you referring to kubernetes' Accelerators feature to allow support for having GPU limits and requests? https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

If so, this should be supported already. You simply need to add the request and/or limit field to the `resources` field in the container spec. See example below:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      resources:
        limits: 
          alpha.kubernetes.io/nvidia-gpu: 2
```

The container and it's fields are passed through when argo constructs the pod spec so these resource requests should be preserved.
