### ISSUE TITLE
Support for emptyDir

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#593]
Argo v2 workflow templates do not support emptyDir. There are several cases where using emptyDir as some sort of scratch space is useful (e.g. DinD).

**Comment by jessesuen** [comment]
This should be supported through normal volume declarations in the spec.volumes section.

**Comment by shrinandj** [comment]
My attempts at using the `volumeClaimTemplates` failed when I used the emptyDir. But I found that the right way to do it was to use `volumes` instead of `volumeClaimTemplates`.

This example worked just fine.

```
# This example demonstrates the ability for a workflow to use an
# emptyDir volume.
#
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: volumes-emptydir-
spec:
  entrypoint: volumes-emptydir-example
  volumes:
  - name: workdir
    emptyDir: {}

  templates:
  - name: volumes-emptydir-example
    container:
      image: debian:latest
      command: ["/bin/bash", "-c"]
      args: ["
        vol_found=`mount | grep /mnt/vol` && \
        if [[ -n $vol_found ]]; then echo \"Volume mounted and found\"; else echo \"Not found\"; fi
      "]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
```

I'll add this to the examples dir.

**Comment by jessesuen** [comment]
Example added.

**Comment by David-Development** [comment]
@jessesuen Maybe the following example is worth adding to the examples as well (maybe as a comment). 

In case anyone wondering how to use tmpfs with Argo (https://kubernetes.io/docs/concepts/storage/volumes/#emptydir):

```
# This example demonstrates the ability for a workflow to use an
# emptyDir volume using tmpfs (RAM-backed filesystem).
#
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: volumes-emptydir-
spec:
  entrypoint: volumes-emptydir-example
  volumes:
  - name: tmpfs
    emptyDir:
      medium: Memory
      sizeLimit: "50Gi"
...
```

Important note (kubernetes docs): 

> While tmpfs is very fast, be aware that unlike disks, tmpfs is cleared on node reboot and any files you write will count against your Container’s memory limit
