### ISSUE TITLE
Git artifact driver needs credentials support

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#626]
The git artifact driver does not do anything with the usernameSecret and passwordSecret making it impossible to clone private registries. This needs to be fixed.

**Comment by jessesuen** [comment]
This is how a YAML would look referencing the k8s secret. In lieu of username/password, we should also support ssh keys.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-git-
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: https://github.com/argoproj/argo.git
          revision: "master"
          usernameSecret:
            name: my-github-credentials
            key: username
          passwordSecret:
            name: my-github-credentials
            key: password

    container:
      image: golang:1.8
      command: [sh, -c]
      args: ["cd /src && git status && ls -l"]
```
