### ISSUE TITLE
Failed to list *v1.Workflow: the server could not find the requested resource (get workflows.argoproj.io)

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#630]
I'm trying to convert the Argo installation into a ksonnet config. My manifests are below. I've created the CRD but the workflow-controller is showing the following error

```
ERROR: logging before flag.Parse: E1228 05:50:42.630074       1 reflector.go:205] github.com/argoproj/argo/workflow/controller/controller.go:211: Failed to list *v1.Workflow: the server could not find the requested resource (get workflows.argoproj.io)
```
Any idea what could be causing this?

Here are the manifests for all the resources I'm deploying.

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    shortNames:
    - wf
    singular: workflow
  scope: Namespaced
  version: v1alpha1
---
apiVersion: v1
data:
  config: 'executorImage: argoproj/argoexec:latest'
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: kubeflow-test-infra
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: workflow-controller-deployment
  namespace: kubeflow-test-infra
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        command:
        - /bin/workflow-controller
        env:
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: IN_CLUSTER
          value: "true"
        image: argoproj/workflow-controller:latest
        name: workflow-controller
      serviceAccount: argo
      serviceAccountName: argo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: argo-ui
  name: argo-ui
  namespace: kubeflow-test-infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: argo-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: argo-ui
    spec:
      containers:
      - env:
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: IN_CLUSTER
          value: "true"
        image: argoproj/argoui:v2.0.0-alpha2
        imagePullPolicy: IfNotPresent
        name: argo-ui
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: argo
      serviceAccountName: argo
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-ui
  name: argo-ui
  namespace: kubeflow-test-infra
spec:
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: argo-ui
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: kubeflow-test-infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-cluster-role
  namespace: kubeflow-test-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: argo
  namespace: kubeflow-test-infra
```

**Comment by jlewi** [comment]
I was using the wrong docker image for the workflow controller; I wasn't using the v2 image. 

Here are working manifests.

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    shortNames:
    - wf
    singular: workflow
  scope: Namespaced
  version: v1alpha1
---
apiVersion: v1
data:
  config: 'executorImage: argoproj/argoexec:latest'
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: kubeflow-test-infra
---
apiVersion: extensions/v1beta1
kind: Deployment
labels:
  app: workflow-controller
metadata:
  name: workflow-controller
  namespace: kubeflow-test-infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: workflow-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        command:
        - workflow-controller
        env:
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: argoproj/workflow-controller:v2.0.0-alpha2
        imagePullPolicy: IfNotPresent
        name: workflow-controller
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: argo
      serviceAccountName: argo
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: argo-ui
  name: argo-ui
  namespace: kubeflow-test-infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: argo-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: argo-ui
    spec:
      containers:
      - env:
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: IN_CLUSTER
          value: "true"
        image: argoproj/argoui:v2.0.0-alpha2
        imagePullPolicy: IfNotPresent
        name: argo-ui
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: argo
      serviceAccountName: argo
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-ui
  name: argo-ui
  namespace: kubeflow-test-infra
spec:
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: argo-ui
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: kubeflow-test-infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-cluster-role
  namespace: kubeflow-test-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: argo
  namespace: kubeflow-test-infra
```
