### ISSUE TITLE
Impossible to submit json as a CLI parameter

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#646]
A use case is to pass a JSON string as a parameter. It doesn't seem possible to do this from the command line. No matter what combination of quoting/escaping I try to do, I get some form of the following error:

```
argo submit examples/arguments-parameters.yaml -p json='{"hello":"world"}'
Error: invalid argument "json={\"hello\":\"world\"}" for "-p, --parameter" flag: line 1, column 6: bare " in non-quoted-field
```

**Comment by jessesuen** [comment]
Here is the example manifest we need to get working from command line:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pass-json-
spec:
  entrypoint: parsejson
  templates:
  - name: parsejson
    inputs:
      parameters:
      - name: json
    container:
      image: jessesuen/argoexec:latest
      command: [sh, -c]
      args: ["echo '{{inputs.parameters.json}}' | jq"]
```
