### ISSUE TITLE
Proposal: raw contents as a new input artifact type

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#648]
I would like to introduce a new input artifact type, called `raw`, which would take the literal value from a "contents" sub field and place it in the specified path as a file. Example below:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-raw-
spec:
  entrypoint: raw-contents
  templates:
  - name: raw-contents
    inputs:
      artifacts:
      - name: myfile
        path: /tmp/file
        raw:
          contents: |
            this is
            the raw file
            contents
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/file"]
```

The use case is to be able to take small pieces of data (json, yaml, diff files) and provide some convenience to the user by not having to do things like echo strings into files, worry about shell escaping, etc...

**Comment by jessesuen** [comment]
We should also be able to do something like:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-raw-
spec:
  entrypoint: raw-contents
  templates:
  - name: raw-contents
    inputs:
      parameters:
      - name: contents  
      artifacts:
      - name: raw
        path: /tmp/file
        raw:
          contents: "{{inputs.parameters.contents}}"
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/file"]
```
