### ISSUE TITLE
Executor momentarily identified main container with a different containerID

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#691]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
The wait container identified the main container with a particular container ID. However a subsequent `docker wait` resulted in the container not existing, and thereby erroring with the log:
```
time="2018-01-17T00:38:59Z" level=error msg="`docker wait 351d8db2d99bc819d64f68d39cfc576958b0368ebec19d5e1441e20e603db70e` failed: Error response from daemon: No such container: 351d8db2d99bc819d64f68d39cfc576958b0368ebec19d5e1441e20e603db70e\n"
```
This caused the executor wait logic to error prematurely

**What you expected to happen**:
Executor should properly identify the main container.

**How to reproduce it (as minimally and precisely as possible)**:
Seen only once in an argo-ci job

**Environment**:
- Argo version: v2.0.0+2c35971

- Kubernetes version :
```
serverVersion:
  buildDate: 2017-12-19T20:05:45Z
  compiler: gc
  gitCommit: 2c2a807131fa8708abc92f3513fe167126c8cce5
  gitTreeState: clean
  gitVersion: v1.8.5-gke.0
  goVersion: go1.8.3b4
  major: "1"
  minor: 8+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get argo-ci-cgn4n -o wide
Name:             argo-ci-cgn4n
Namespace:        default
ServiceAccount:   default
Status:           Running
Created:          Tue Jan 16 16:33:20 -0800 (5 hours ago)
Started:          Tue Jan 16 16:33:20 -0800 (5 hours ago)
Duration:         5 hours 17 minutes 56 seconds
Parameters:
  revision:       a3707ca82c71fbbc42583dbd1bb20191d076a268
  repo:           https://github.com/jessesuen/argo.git

STEP                                               PODNAME                   DURATION  ARTIFACTS  MESSAGE
 ● argo-ci-cgn4n                                                             5h
 └-·-✔ ci(make controller-image)                   argo-ci-cgn4n-1293435445  8m
   ├-✔ ci(make executor-image)                     argo-ci-cgn4n-1334237054  7m
   ├-✔ ci(make cli-linux)                          argo-ci-cgn4n-1043663010  3m
   ├-✔ ci(make cli-darwin)                         argo-ci-cgn4n-489834203   9m
   ├-✔ ci(make ui-image)                           argo-ci-cgn4n-1171340199  9m
   ├-● ci(dep ensure && make lint)                 argo-ci-cgn4n-2875348619  5h
   ├-✔ ci(dep ensure && make test)                 argo-ci-cgn4n-2431488616  4m
   └-✔ ci(dep ensure && ./hack/verify-codegen.sh)  argo-ci-cgn4n-1551545145  1m
```
- executor logs:

Here we see executor identified the main container to be: 351d8db2d99bc819d64f68d39cfc576958b0368ebec19d5e1441e20e603db70e
```
$ kubectl logs argo-ci-cgn4n-2875348619 -c wait
time="2018-01-17T00:38:59Z" level=info msg="Executor (version: v2.0.0+2c35971) initialized with template:\narchiveLocation:\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: argoci-minio-user\n    bucket: argo-artifacts\n    endpoint: argoci-minio-svc:9000\n    insecure: true\n    key: argo-ci-cgn4n/argo-ci-cgn4n-2875348619\n    secretKeySecret:\n      key: secretkey\n      name: argoci-minio-user\ncontainer:\n  args:\n  - until docker ps; do sleep 3; done; cd /go/src/github.com/argoproj/argo && dep\n    ensure && make lint\n  command:\n  - sh\n  - -c\n  env:\n  - name: DOCKER_HOST\n    value: 127.0.0.1\n  image: argoproj/argo-ci-builder:1.0\n  name: \"\"\n  resources: {}\ninputs:\n  artifacts:\n  - git:\n      repo: https://github.com/jessesuen/argo.git\n      revision: a3707ca82c71fbbc42583dbd1bb20191d076a268\n    name: code\n    path: /go/src/github.com/argoproj/argo\n  parameters:\n  - name: cmd\n    value: dep ensure && make lint\nname: ci-builder\noutputs: {}\nsidecars:\n- image: docker:17.10-dind\n  mirrorVolumeMounts: true\n  name: dind\n  resources: {}\n  securityContext:\n    privileged: true\n"
time="2018-01-17T00:38:59Z" level=info msg="Waiting on main container"
time="2018-01-17T00:38:59Z" level=info msg="main container started with container ID: 351d8db2d99bc819d64f68d39cfc576958b0368ebec19d5e1441e20e603db70e"
time="2018-01-17T00:38:59Z" level=info msg="Starting annotations monitor"
time="2018-01-17T00:38:59Z" level=info msg="Starting deadline monitor"
time="2018-01-17T00:38:59Z" level=info msg="docker wait 351d8db2d99bc819d64f68d39cfc576958b0368ebec19d5e1441e20e603db70e"
time="2018-01-17T00:38:59Z" level=error msg="`docker wait 351d8db2d99bc819d64f68d39cfc576958b0368ebec19d5e1441e20e603db70e` failed: Error response from daemon: No such container: 351d8db2d99bc819d64f68d39cfc576958b0368ebec19d5e1441e20e603db70e\n"
time="2018-01-17T00:38:59Z" level=info msg="Annotations monitor stopped"
time="2018-01-17T00:38:59Z" level=error msg="Error waiting on main container to be ready, Error response from daemon: No such container: 351d8db2d99bc819d64f68d39cfc576958b0368ebec19d5e1441e20e603db70e\ngithub.com/argoproj/argo/errors.New\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:48\ngithub.com/argoproj/argo/errors.InternalError\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:59\ngithub.com/argoproj/argo/workflow/common.RunCommand\n\t/root/go/src/github.com/argoproj/argo/workflow/common/util.go:254\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).Wait\n\t/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:479\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:24\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:750\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:831\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:784\nmain.main\n\t/root/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:15\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:185\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337"
time="2018-01-17T00:38:59Z" level=info msg="No output artifacts"
time="2018-01-17T00:38:59Z" level=info msg="No output parameters"

```

But here is what k8s shows as the main container:
```
  - containerID: docker://296b7acd6022ff709afd05cd43718e21535cf55b6693e52d89c3b0b459108d5d
    image: argoproj/argo-ci-builder:1.0
    imageID: docker-pullable://argoproj/argo-ci-builder@sha256:9bf9e56742a5bb992a4b59d8fd8b8f2714ee6dc5bf87732ae84181f6d5e33544
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://296b7acd6022ff709afd05cd43718e21535cf55b6693e52d89c3b0b459108d5d
        exitCode: 0
        finishedAt: 2018-01-17T00:40:26Z
        reason: Completed
        startedAt: 2018-01-17T00:38:58Z
```
