### ISSUE TITLE
[BUG] resource can not be passes as parameter

### ISSUE THREAD

**Issue by dmonakhov** [argoproj/argo#703]
I try to pass container resources (cpu in my case) as workflow parameter( see workflow below)
But argo cli validation failed like follows:
```
$ argo  submit resource-param.yaml 
2018/01/26 19:00:54 resource-param.yaml failed to parse: error unmarshaling JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```
AFAIU this is happens because expression was not actually substituted.

WORKFLOW
```
# Try to pass cpu resource as an argument                                                                                                   
#                                                                                                                                           
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: resource-param-
spec:
  arguments:
    parameters:
    - name: nrcpu
      value: 4
  entrypoint: stress-ng
  templates:
  - name: stress-ng
    inputs:
      parameters:
      - name: nrcpu
    container:
      image: lorel/docker-stress-ng
      args: [ "--cpu", "{{workflow.parameters.nrcpu}}", "--timeout", "15s", "--metrics-brief" ]
      resources:
        requests:
          memory: 1Gi
          #cpu: 4                                                                                                                           
          cpu: "{{workflow.parameters.nrcpu}}"

```

**Comment by jessesuen** [comment]
K8s has custom unmarshal/marshal functions for the container.resources field. Need to find a way to workaround this.

**Comment by jessesuen** [comment]
This is going to be a tricky one to fix. Since we reuse the Container data structure from the k8s API types (among others), we inherit all of logic that comes with marshaling and unmarshaling of the various types. This includes the custom unmarshalling functions deeply nested any of their sub fields (in this case resource/quantity.go Quantity). We definitely do not want to move away from reusing Container data type since we need to keep in-line with k8s. Our only option it appears is to implement custom unmarshalling at the template level. I'm also very weary of doing that since that is always tricky to get right.

**Comment by dmonakhov** [comment]
@jessesuen  Thank you for explanation.
May be there is workaround for this I'm not an exert in k8s API.
My scenario: 
a CI job which want to compile. So I want complete it ASAP, for that reason I use 
'make -j $NRCPU', where NRCPU is  $(numcpu-1) on kube-nodes.  It is obvious that hardcoding NRCPU is bad for portability because it NRCPU varies from cluster to cluster 

It it possible to define resource via generic kubernetes API? Via configMap or other config?

**Comment by dmonakhov** [comment]
Yeah. It seems that  'kind: LimitRange'  resource does exactly what I need.   https://kubernetes.io/docs/tasks/administer-cluster/cpu-constraint-namespace .
Since workaround exists this issue can be moved to  enhancement section.

**Comment by jessesuen** [comment]
Thanks for the legwork on the workaround. Yes, container.resources obtained from parameters is a use case we should support, so eventually this is something I'd fixed. The right way to go about doing it, escapes me at the moment.

**Comment by discordianfish** [comment]
Is there a workaround for this? This is almost a show-stopper for the usecase here. We have several tasks that have vastely different resource requirements, which forces us to create many templates.

**Comment by epa095** [comment]
A bit of brainstorming on this.
Would it maybe make sense to be able to define a "patch" to a workflow step, which could override parts of the yaml definition of the step. I am thinking something similar to overlays in [kustomize.
](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/glossary.md#overlay) This could take in exactly the same parameters as the step itself, and be applied to the workflow step right before execution. This would allow you to still use the k8s API types for the workflow step, but people would be "on their own" in regard to what they write in the patch/overlay step.

**Comment by igor47** [comment]
also got bitten by this issue and am unsure of workarounds. 

future people, to limit "me too" comments, feel free to leave a :+1: reaction on this comment.

**Comment by elsonrodriguez** [comment]
As a workaround for this I ended up using a resource to create a Job. Messy but workable.

Food for thought: A killer use case for this would be in combination with GKE's node auto-provisioner, especially for compute-heavy jobs. This way memory/cpu/gpu could be defined as a parameter, and eventually it will just run.

**Comment by Snapple49** [comment]
@elsonrodriguez Hi, would you mind explaining your workaround please? Not sure if I follow, but I'm interested in solutions to this problem as well

**Comment by elsonrodriguez** [comment]
@Snapple49  Basically I just use this pattern:

https://github.com/argoproj/argo/blob/baf37052976458401a6c0e44d06f30dc8d819680/examples/k8s-jobs.yaml

The `manifest` portion is fully template compatible, so you can swap out anything for a variable, including resource allocation.

For example:
````
                resources:
                  limits:
                    memory: "{{inputs.parameters.memory}}"
                    cpu: "{{inputs.parameters.cpu}}"
```

The downside is that logs won't show up directly associated with the workflow, it's less readable, and more complex.
