### ISSUE TITLE
Make output parameters easily accessible from code

### ISSUE THREAD

**Issue by 0xdevalias** [argoproj/argo#718]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What you expected to happen**:

I've been playing around with running argo workflows from my own golang code, and have been pondering the best way to 'extract data' from the workflow.

This lead to me looking at a few options, including:

* the 'artifact' features (likely too heavyweight/overengineered for my needs)
* parsing logs (hacky)
* [using a shared volume](https://github.com/argoproj/argo/blob/master/examples/volumes-existing.yaml) between my code and the workflow (potential)
* [output parameters](https://github.com/argoproj/argo/blob/master/examples/output-parameter.yaml)

The output parameters seemed of particular interest, but when I raised the question on Slack, @jessesuen implied that it might be annoying to parse them from the 'result json' in its current form:

> output parameters might work for you — the value will be stored in the workflow resource object (JSON) for a consumer to parse. The problem is that the outputs would be nested into some arbitrary node’s outputs which is not obvious to parse and extract the value. There is a case to be made for having workflow outputs as a first class citizen. Then the workflow’s outputs could be extracted via the json field: myworkflow.outputs.parameters.myparam Can you file a feature request and we can take the discussion there?

As mentioned above, if these outputs were treated as 'first class citizens', then we could access them in a format similar to `myworkflow.outputs.parameters.myparam`, which would be nice.

Opening here for discussion.

**Environment**:
- Argo version:
```
$ argo version
  argo: v2.0.0-beta1
  BuildDate: 2018-01-18T22:04:00Z
  GitCommit: 549870c1ee08138b20b8a4b0c026569cf1e6c19a
  GitTreeState: clean
  GitTag: v2.0.0-beta1
  GoVersion: go1.9.1
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-01-18T21:11:08Z
  compiler: gc
  gitCommit: 5fa2db2bd46ac79e5e00a4e6ed24191080aa463b
  gitTreeState: clean
  gitVersion: v1.9.2
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-01-26T19:04:38Z
  compiler: gc
  gitCommit: 925c127ec6b946659ad0fd596fa959be43f0cc05
  gitTreeState: clean
  gitVersion: v1.9.0
  goVersion: go1.9.1
  major: ""
  minor: ""
  platform: linux/amd64
```

**Comment by 0xdevalias** [comment]
Hacked together some PoC code for my usecase:

```
func GetOutputParams(wf *wfv1.Workflow) (map[string]wfv1.Parameter, error) {
	if wf.Status.FinishedAt.IsZero() {
		return nil, errors.New("Workflow not finished")
	} else if wf.Status.Phase != wfv1.NodeSucceeded {
		return nil, errors.New("Workflow not Succeeded")
	}

	outputParams := make(map[string]wfv1.Parameter)

	for _, node := range wf.Status.Nodes {
		for _, p := range node.Outputs.Parameters {
			// TODO: This will overwrite 'clashing' keys, find a better solution
			outputParams[p.Name] = p
		}
	}
	return outputParams, nil
}
```

**Comment by jessesuen** [comment]
Any suggestions on syntax? I'm thinking something like:

```
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo -n hello world > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello-param
        valueFrom:
          path: /tmp/hello_world.txt
        globalOutputName: my-wf-output
```
Which would result in:
```
status:
  outputs:
    parameters:
    - name: my-wf-output
      value: hello world
```

**Comment by 0xdevalias** [comment]
No strong feels on syntax, but wondering if there is a need to have a difference between `name: hello-param` and `globalOutputName: my-wf-output`

Would make more logical sense to me for them to be the same name.

If `globalOutputName` is there to mark things that will be output globally (with the default being not to), then maybe just have `global: true` or similar?

**Comment by jessesuen** [comment]
I started my thinking with `global: true`, but felt it might be limiting. I'm not sure if there is a real use-case of having the global output name be different than just the output name, or if I'm just overthinking this. I do like the simplicity of just having `global: true`. Let me get some opinions from folks here, as well as the slack channel.

**Comment by jessesuen** [comment]
OK, I now remember why I went this route, and why `global: true` would be too limiting. I feel it is important to support something like this
```
    outputs:
      parameters:
      - name: hello-param
        valueFrom:
          path: /tmp/hello_world.txt
        globalOutputName: "{{inputs.parameters.someval}}"
```
This keeps the template composable, but enables it to produce different global outputs with different names. With `global: true`, it would not be possible.

**Comment by 0xdevalias** [comment]
Would that not also be possible with the following?

```
    outputs:
      parameters:
      - name: "{{inputs.parameters.someval}}"
        valueFrom:
          path: /tmp/hello_world.txt
        global: "true"
```

Or by composable, do you mean internally other things could refer to it by`hello-param` (in your example), and externally I can define whatever I want? If so, I can see the logic.. but wonder if there is much benefit over adding a few more template params around the place. 

Ultimately I don't think it makes a huge distinction either way, so happy to go with consensus.
