### ISSUE TITLE
GCS Invalid Header

### ISSUE THREAD

**Issue by rossedman** [argoproj/argo#726]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**: When using GCS with Interoperability enabled artifact storage fails. It appears the secret key isn't decoded properly based on the output

**What you expected to happen**: Artifacts to be stored in GCS

**How to reproduce it (as minimally and precisely as possible)**: Create a GCS bucket, enable interoperability, place keys in workflow config, run workflow that contains artifact outputs.

**Anything else we need to know?**:

The secret key in the output is not the base64 encoded version I provided to the workflow config. 

```
invalid header field value "AWS <ACCESS_KEY>\n:zqkz4avmI3UNWwkSxIm0MOOTrtU=" for key Authorization
```

**Environment**:
- Argo version: v2.0.0
- Kubernetes version : 
```
clientVersion:
  buildDate: 2018-01-18T10:09:24Z
  compiler: gc
  gitCommit: 5fa2db2bd46ac79e5e00a4e6ed24191080aa463b
  gitTreeState: clean
  gitVersion: v1.9.2
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-01-18T09:42:01Z
  compiler: gc
  gitCommit: 5fa2db2bd46ac79e5e00a4e6ed24191080aa463b
  gitTreeState: clean
  gitVersion: v1.9.2
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow-controller logs:
```
time="2018-02-09T18:10:19Z" level=info msg="Processing workflow" namespace=default workflow=pg-service-bootstrap-6gk98
time="2018-02-09T18:10:19Z" level=info msg="Updating node pg-service-bootstrap-6gk98[0].checkout (pg-service-bootstrap-6gk98-3493805669) message: failed to save outputs: Get https://storage.googleapis.com/pg-deploy/?location=: net/http: invalid header field value \"AWS <ACCESS_KEY>\\n:zqkz4avmI3UNWwkSxIm0MOOTrtU=\" for key Authorization"
time="2018-02-09T18:10:19Z" level=info msg="Updating node pg-service-bootstrap-6gk98[0].checkout (pg-service-bootstrap-6gk98-3493805669) status Running -> Error"
time="2018-02-09T18:10:19Z" level=info msg="Step group node pg-service-bootstrap-6gk98[0].checkout (pg-service-bootstrap-6gk98-3493805669) deemed failed: child 'pg-service-bootstrap-6gk98-3493805669' failed" namespace=default workflow=pg-service-bootstrap-6gk98
time="2018-02-09T18:10:19Z" level=info msg="step group pg-service-bootstrap-6gk98[0] was unsuccessful" namespace=default workflow=pg-service-bootstrap-6gk98
```
