### ISSUE TITLE
PersistentVolumeClaim name as a parameter

### ISSUE THREAD

**Issue by vreon** [argoproj/argo#749]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature request

**What happened**:

I'd like to point a Workflow at an existing PersistentVolumeClaim whose name is specified by a parameter. Some options I explored:

- Workflows support a `volumes` field, but it exists outside of any template so the `claimName` must be hard-coded
- It's possible to mount an arbitrary PVC using a `resource` template that creates a Job... but it's not possible to pass input artifacts to that Job because it (understandably) lacks the argoexec plumbing:

  ```
  2018/02/16 14:57:14 Workflow manifest resourcevoltest.yaml failed submission: template 'restore' 
  inputs.artifacts.source.path only valid in container/script templates
  ```

- I could use `resource` to mount the PVC on a Pod that sleeps (or runs `rsyncd`), then copy the artifact data over from an Argo `container`, but whoa

- A `persistentVolumeClaim` input artifact might be cool, if it's not too confusing to users:

  ```yaml
  - name: restore
    inputs:
      parameters:
      - name: destClaimName
      - name: sourceS3Key
      artifacts:
      - name: source
        path: /source
        s3:
          key: '{{inputs.parameters.sourceS3Key}}'
          # [...]
      - name: dest
        path: /dest
        persistentVolumeClaim:
          claimName: '{{inputs.parameters.destClaimName}}'
    container:
      image: busybox
      command: ['cp', '-a', '/source/.', '/dest']
  ```

**Environment**:
- Argo version:
```
argo: v2.0.0
  BuildDate: 2018-02-06T21:39:43Z
  GitCommit: 0978b9c61cb7435d31ef8d252b80e03708a70adc
  GitTreeState: clean
  GitTag: v2.0.0
  GoVersion: go1.9.1
  Compiler: gc
  Platform: linux/amd64
```
