### ISSUE TITLE
Output parameters should trim newline character

### ISSUE THREAD

**Issue by adamresson** [argoproj/argo#758]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
Output parameter have trailing \n character

**What you expected to happen**:
Trailing new line characters in outputs should be removed

**How to reproduce it (as minimally and precisely as possible)**:

I have a file that contains a trailing newline character, which isn't uncommon for linux files. I know I could have a separate step that 'trims' the file, but in my mind, this should be the default behaviour. I have another program outputting the file (which is why it's not as easy as adding a `echo -n` as below, but this is an example of how I'd generate a similar file.
```
echo 36.0 > /mnt/data/filename
```

My workflow template is as follows:
```
  - name: parse-metric
    inputs:
      parameters:
        - name: filename
    container:
      image: debian:9.1
      command: [ "cat", "/mnt/data/{{inputs.parameters.filename}}" ]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/data
    outputs:
      parameters:
      - name: metric
        valueFrom:
          path: /mnt/data/{{inputs.parameters.filename}}
```

Upon executing and inspection of the output annotation, there is a trailing newline character:

```
    workflows.argoproj.io/outputs: '{"parameters":[{"name":"metric","value":"36.0\n","valueFrom":{"path":"/mnt/data/output.txt"}}]}'
```

Then when I try to insert the output as a input to another container, I get some weird behaviour.

Workflow:
```
    container:
      image: <redacted>
      args: 
        - "./script-run"
        - "--metric"
        - "{{inputs.parameters.value}}"
```

`k get pod <name> -o yaml` contains:

```
spec:
  containers:
  - args:
    - ./script-run
    - --metric
    - |
      36.0
```
which essentially ends up add a new line in the middle of my command and then the arguments doesn't get parsed properly.

Any suggestions on workarounds and/or if this is expected behaviour?

**Environment**:
- Argo version:
```
argo: v2.0.0
```

**Comment by adamresson** [comment]
Looks like this might be similar to #751, or atleast a similar fix might work.

**Comment by jessesuen** [comment]
I think trimming off *all* newlines at the end of the file, might close the door on a use case where newlines are meaningful. But chopping off a single newline (if exists) might be a good compromise between addressing the needs of the 95% of users but leave the door open in case trailing newlines are desired. WDYT?

**Comment by adamresson** [comment]
I think that’s a great compromise. Typical a single lined file is likely a single “value” that would be output, whereas a multi line file would want to respect the new line. Either that or have a flag you can set on the output parameter where you could toggle the trim on or off. @jessesuen how do you feel about that?

**Comment by jessesuen** [comment]
> or have a flag you can set on the output parameter where you could toggle the trim on or off

I don't think we should introduce more knobs for this since after implementing this, I doubt that people really need this level of control over trimming. Let's just go with trimming a single trailing newline at the end of the output.

**Comment by adamresson** [comment]
If anyone's looking for a temporary workaround for this, here's what I came up with
```
  - name: parse-metric
    inputs:
      parameters:
        - name: filename
    container:
      image: debian:9.1
      command: [sh, -c]
      args: ["
        perl -pi -e 'chomp if eof' /mnt/data/{{inputs.parameters.filename}}
      "]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/data
    outputs:
      parameters:
      - name: metric
        valueFrom:
          path: /mnt/data/{{inputs.parameters.filename}}
```
which edits the file inline
