### ISSUE TITLE
Add submodule support for git artifacts

### ISSUE THREAD

**Issue by decarboxy** [argoproj/argo#778]
Currently git artifacts can clone a specified version of a repository.  We should extend the git artifact to optionally support submodules.  Specifically, a boolean flag `submodules` should be added to the git artifact configuration.  When this flag is set to true, `submodule init` and `submodule update` should be run.  

The new artifact spec would look something like this:

```yaml
            git:
              repo: "{{inputs.parameters.repository}}"
              revision: "{{inputs.parameters.revision}}"
              submodules: true
              usernameSecret:
                name: github-pull-creds
                key: username
              passwordSecret:
                name: github-pull-creds
                key: password
```
