### ISSUE TITLE
Support for user defined pod metadata (labels/annotations)

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#781]
**FEATURE REQUEST?**:

I'd like to be able to easily identify the pod(s) corresponding to a particular step in my workflow. 

So I'd like step names to be included in pod labels. 

Currently the node name is stored as an annotation but not a label. An annotation isn't as convenient for querying e.g. via kubectl.

For example here's the annotations and labels for my pod

```
  annotations:
    workflows.argoproj.io/node-name: jlewi-tf-serving-release-v20180303-pr339-72bc7b1-98f7-98f7.build-tf-serving-cpu
    workflows.argoproj.io/template: '{"name":"build-tf-serving-cpu","inputs":{},"outputs":{},"container":{"name":"","image":"gcr.io/mlkube-testing/test-worker:latest","command":["/bin/bash","-c","/mnt/test-data-volume/jlewi-tf-serving-release-v20180303-pr339-72bc7b1-98f7-98f7/src/kubeflow/kubeflow/components/k8s-model-server/images/build_image.sh
      /mnt/test-data-volume/jlewi-tf-serving-release-v20180303-pr339-72bc7b1-98f7-98f7/src/kubeflow/kubeflow/components/k8s-model-server/images/Dockerfile.cpu
      gcr.io/mlkube-testing/tf-model-server-cpu:latest"],"env":[{"name":"PYTHONPATH","value":"/mnt/test-data-volume/jlewi-tf-serving-release-v20180303-pr339-72bc7b1-98f7-98f7/src/kubeflow/kubeflow:/mnt/test-data-volume/jlewi-tf-serving-release-v20180303-pr339-72bc7b1-98f7-98f7/src/kubeflow/testing/py"},{"name":"GOOGLE_APPLICATION_CREDENTIALS","value":"/secret/gcp-credentials/key.json"},{"name":"GITHUB_TOKEN","valueFrom":{"secretKeyRef":{"name":"github-token","key":"github_token"}}},{"name":"JOB_NAME","value":"tf-serving-release"},{"name":"JOB_TYPE","value":"presubmit"},{"name":"REPO_NAME","value":"kubeflow"},{"name":"REPO_OWNER","value":"kubeflow"},{"name":"BUILD_NUMBER","value":"98f7"},{"name":"PULL_NUMBER","value":"339"},{"name":"PULL_PULL_SHA","value":"72bc7b1"},{"name":"DOCKER_HOST","value":"127.0.0.1"}],"resources":{},"volumeMounts":[{"name":"kubeflow-test-volume","mountPath":"/mnt/test-data-volume"},{"name":"github-token","mountPath":"/secret/github-token"},{"name":"gcp-credentials","mountPath":"/secret/gcp-credentials"}]},"sidecars":[{"name":"dind","image":"docker:17.10-dind","resources":{},"securityContext":{"privileged":true},"mirrorVolumeMounts":true}],"archiveLocation":{}}'
  creationTimestamp: 2018-03-04T03:02:15Z
  labels:
    workflows.argoproj.io/completed: "false"
    workflows.argoproj.io/workflow: jlewi-tf-serving-release-v20180303-pr339-72bc7b1-98f7-98f7
```
It would be great if node-name was also a label
I suspect we might need to drop the workflow name to meet the label requirements.

**Comment by jessesuen** [comment]
Kubernetes has restrictions on what characters can be in a label, so the node name (which is the human "readable" unique identifier of a node in a workflow), would not be allowed as kubernetes label unless we change the formula of what constitutes a node name. For example, in the following example, `dag-diamond-coinflip-zswx9.D[1].tails[1].tails[1].tails` is the node name.

```
    dag-diamond-coinflip-zswx9-1978891959:
      boundaryID: dag-diamond-coinflip-zswx9-2772668011
      displayName: tails
      finishedAt: 2018-03-05T10:16:26Z
      id: dag-diamond-coinflip-zswx9-1978891959
      message: when 'heads == tails' evaluated false
      name: dag-diamond-coinflip-zswx9.D[1].tails[1].tails[1].tails
      phase: Skipped
      startedAt: 2018-03-05T10:16:26Z
      type: Skipped
```

Kubernetes rejects the request with the message: "a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character"

Step names, which is the user-defined local reference of a step within a template boundary, faces a similar problem because of the formula that we use when constructing the name when `withItems` is specified. For example, the step name `test-linux(3:image:ubuntu,tag:17.10)` would still be rejected:

```
    loops-maps-gx4hb-2924864200:
      boundaryID: loops-maps-gx4hb
      displayName: test-linux(3:image:ubuntu,tag:17.10)
      finishedAt: 2018-03-06T00:39:48Z
      id: loops-maps-gx4hb-2924864200
      inputs:
        parameters:
        - name: image
          value: ubuntu
        - name: tag
          value: "17.10"
      name: loops-maps-gx4hb[0].test-linux(3:image:ubuntu,tag:17.10)
      phase: Succeeded
      startedAt: 2018-03-06T00:34:33Z
      templateName: cat-os-release
```

I think if we want to allow labels for steps in a pod, we may need first class support of this in a new `template.metadata.labels` field, rather than trying to fit the node or step name as an automatic label. Thoughts?
