### ISSUE TITLE
Support SSH authentication for git artifacts

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#793]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

HTTPS and password authentication might be disabled. Argo should support authentication using ssh key.

**What you expected to happen**:

It should be possible to define git artifact using 'git@' url and ssh key secret:

```
        git:
          repo: "git@github.com:argoproj/argo.git"
          revision: "master"
          sshKeySecret: 'argo-github-ssh'
```
