### ISSUE TITLE
Common pattern for reusable snippet of workflow template

### ISSUE THREAD

**Issue by mumoshu** [argoproj/argo#799]
**This is a enhancement request** to probably the documentation.
Sorry if the doc already covers this kind of use-case with enough details!

## Context

This is a successor of #795, especially based on [my thought on how we should address the use-case](https://github.com/argoproj/argo/issues/795#issuecomment-373973589).

As an Argo user wanting to write a concise, declarative, secure workflow definition, and also a potential Argo developer who wants to contribute the project, I'd like to define so-called `macros` in workflow spec. So that Argo can focus on high-level things like [`steps`, `template`, `dag`, `suspend` and `container`](https://github.com/argoproj/argo/blob/a45bf1b7558b3eb60ec65d02c166c306e7797a79/workflow/controller/operator.go#L863-L872), while an Argo user can write a concise workflow spec without repeating instances of these high-level concepts.

## What won't work

Again, a macro runner must be as scalable and secure as Argo's other runners exist today. It should:

- not consume too much resources in Argo controller/worker and
- not require a direct access to "secrets" from Argo controller

So for example, a "`http` template type processed directly in Argo controller"(#795) for prupose of maximizing conciseness of your workflow declaration wouldn't be a solution.

## How I would achieve it today

For example, if I as an Argo user wanted to integrate [Brigade](https://github.com/Azure/brigade) with Argo, I would write something like the below for maximum reusability of my snippet(invoking a single brigade workflow) based on the [arguments-parameters example](https://github.com/argoproj/argo/blob/master/examples/arguments-parameters.yaml) and [global-parameters example](https://github.com/argoproj/argo/blob/master/examples/global-parameters.yaml):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: brigade-ci-cd-pipeline
spec:
  entrypoint: my-brigade-ci-cd-pipeline
  # Usage
  # $ argo submit my-brigade-ci-cd-pipeline.yaml -p project=$BRIGADE_PROJECT_PER_GIT_REPO -p commit=$GIT_COMMIT_SHA1
  arguments:
    parameters:
    - name: commit
    - name: project
  templates:
  - name: ci-pipeline
    dag:
      tasks:
      # Parallelly run 4 tasks
      - name: unit-test
        template: brig-run
        arguments:
          parameters: [{event: "unit-test"}]
      - name: integration-test
        template: brig-run
        arguments:
          parameters: [{event: "integration-test"}]
      - name: docker-build
        template: brig-run
        arguments:
          parameters: [{event: "docker-build"}]
      - name: lint-chart
        template: brig-run
        arguments:
          parameters: [{event: "lint-chart"}]
      # And finally deploy the helm chart along with the latest docker image
      - name: deploy
        template: brig-run
        arguments:
          parameters: [{event: "deploy"}]
        dependencies: [unit-test, integration-test, docker-build, lint-chart]
  # Macro: brig-run
  # synchronously run a brigade event handler for the event specified via the "event" arg
  - name: brig-run
    inputs:
      # `commit` and `project` comes from global parameters
      parameters:
      - name: event
    container:
      image: mumoshu/brig:latest
      command: ["brig"]
      args: ["run", "{{workflow.parameters.project}}", "-e", "{{inputs.parameters.event}}", "-c", "{{workflow.parameters.commit}}"]
```

For use-cases other than mine, not involving Brigade at all, you can rewrite `brig-run` macro in the above example freely to choose any "backend" to offload your actual task to anything other than a raw command in a docker image.

## Issue

So, what's the issue actually?

I guess this is a documentation issue at this point, because "I" couldn't figure out how I would write a "macro" in this way.

WDYT? Any input is welcomed! Thanks.

## Extra, potential question

What is the performance(latency/throughput) implication by implementing "macros" this way?

Back to #795, one of my expectations was that executing `http` templates directly within Argo controller would have a potential for achieving:

- higher throughput
- lower latency
- lower cpu/memory consumption

than running it this way(=nested workflow processing and at least one k8s pod creation per macro call).

Would this question makes sense? Can we just forget about these performance/resource consumption issue in practice?

Thanks!
