### ISSUE TITLE
Feature Request: unify --install-namespace and --namespace flags

### ISSUE THREAD

**Issue by Fitzse** [argoproj/argo#812]
**FEATURE REQUEST**

**What happened**:
A number of times while setting up argo in a cluster I have forgotten about the `--install-namespace` flag. In normal usage (once argo is setup) one always uses the `-n` flag to point to argo in a separate namespace, however, when _installing_  you must remember to use the `--install-namespace` flag instead. This has led me to install argo in a separate namespace than intended a number of times. I wonder if the `--install-namespace` flag is needed at all? Can we just use the global `--namespace` flag instead then there is no change of confusion/error?

Is there ever a case for using _both_ at once where they are different?

**Environment**:
- Argo version:
```
argo: v2.1.0-beta2
  BuildDate: 2018-03-29T20:49:33Z
  GitCommit: fe23c2f651a61a2d7aa877a86edff9802d7b5b47
  GitTreeState: clean
  GitTag: v2.1.0-beta2
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```

- Kubernetes version :
```
clientVersion:
  buildDate: 2018-01-18T21:11:08Z
  compiler: gc
  gitCommit: 5fa2db2bd46ac79e5e00a4e6ed24191080aa463b
  gitTreeState: clean
  gitVersion: v1.9.2
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2017-11-20T05:17:43Z
  compiler: gc
  gitCommit: 9befc2b8928a9426501d3bf62f72849d5cbcd5a3
  gitTreeState: clean
  gitVersion: v1.8.4
  goVersion: go1.8.3
  major: "1"
  minor: "8"
  platform: linux/amd64
```
