### ISSUE TITLE
Input parameters on a steps template prevent daemon pods from terminating

### ISSUE THREAD

**Issue by adampearse** [argoproj/argo#830]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:

Adding an input parameter to a steps template prevents daemon pods from terminating, despite the workflow completing successfully

**What you expected to happen**:

Daemon pods would terminate when the step template completes

**How to reproduce it (as minimally and precisely as possible)**:

Update the [daemon-nginx](https://github.com/argoproj/argo/blob/master/examples/daemon-nginx.yaml) example to include an input parameter on the step template:

```
  - name: daemon-nginx-example
    inputs:
      parameters:
      - name: foo
        value: bar
```

**Anything else we need to know?**:

This is caused by `executeSteps` not updating the `node` variable after [calling](https://github.com/argoproj/argo/blob/73990c787b08f2ce72f65b8169e9f1653b5b6877/workflow/controller/steps.go#L52) `addChildNode`. The node returned from `executeSteps` doesn't have `Children` populated so, if the step has input parameters, `executeTemplate` [replaces](https://github.com/argoproj/argo/blob/73990c787b08f2ce72f65b8169e9f1653b5b6877/workflow/controller/operator.go#L881) the node with children set with the childless one.

When `killDeamonedChildren` (sic) runs, no reference to the child step group exists. Daemoned grandchild pods are not killed and continue running after the workflow has succeeded.

**Environment**:
- Argo version:
```
  BuildDate: 2018-03-29T20:49:33Z
  GitCommit: fe23c2f651a61a2d7aa877a86edff9802d7b5b47
  GitTreeState: clean
  GitTag: v2.1.0-beta2
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-04-13T22:29:03Z
  compiler: gc
  gitCommit: d4ab47518836c750f9949b9e0d387f20fb92260b
  gitTreeState: clean
  gitVersion: v1.10.1
  goVersion: go1.9.5
  major: "1"
  minor: "10"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-04-12T14:14:26Z
  compiler: gc
  gitCommit: d4ab47518836c750f9949b9e0d387f20fb92260b
  gitTreeState: clean
  gitVersion: v1.10.1
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo list
NAME                 STATUS      AGE    DURATION
daemon-nginx-g9qq8   Succeeded   36s    17s

$ kubectl get pods
NAME                            READY     STATUS      RESTARTS   AGE
daemon-nginx-g9qq8-1987695171   2/2       Running     0          42s
daemon-nginx-g9qq8-4146491224   0/2       Completed   0          34s
```
