### ISSUE TITLE
Simplifying Argo YAML specification when templates are not needed

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo#847]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

Templates are great when the same containers are being reused within a workflow. 

But in the case where containers are not being reused within a workflow, they make the YAML spec longer and more difficult to understand, particularly in the case where many parameters need to be passed around. 

Would it be possible to modify the definition of a WorkflowStep so that it can directly specify the content of a template instead of having to refer to a template? 

As an example, the following code: 

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  templates:
  - name: loop-example
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems:
        - hello world
        - goodbye world

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

Would become something like this: 

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  steps:
  - name: print-message
    image: docker/whalesay:latest
    parameters:
    - name: message
      value: "{{item}}"
    withItems:
    - hello world
    - goodbye world
```
