### ISSUE TITLE
A good pattern for aggregating results from parallel stages

### ISSUE THREAD

**Issue by decarboxy** [argoproj/argo#854]
**FEATURE REQUEST**:

Argo already has a good pattern for executing an arbitrary number of steps in parallel using a loop (https://github.com/argoproj/argo/blob/master/examples/loops-param-result.yaml). This pattern is really useful if you're running a stochastic algorithm and want to generate a collection of results from independent runs. 

What's missing is a good way of aggregating the results.  You can run a database as a "daemon" container and aggregate the results for analysis in future steps and this works fine, but it adds a bit of complexity to the workflow and makes it harder to reason about. A more built-in pattern for handling this kind of situation would be helpful.

There are probably many ways of accomplishing this, but one thing we could do instead is extend the concept of an artifact to allow for "collection" artifacts.  A collection artifact would be referenced with a template variable name like a normal file artifact, but could contain the output from multiple stages. 

When used as an input artifact, the collection would be mounted as a directory. 

In a workflow spec, you could imagine writing an output to a collection artifact like this: 

```yaml
  - name: whalesay
    inputs:
      parameters: 
      - name: index
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world-{{inputs.parameters.index}}.txt"]
    outputs:
      collection-artifacts:
      - name: hello-collection
        path: /tmp/hello_world-{{inputs.parameters.index}}.txt
```

and using it as an input like this:
```yaml
  - name: print-message
    inputs:
      collection-artifacts:
      - name: hello-collection
        path: /tmp/hello-collection
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["ls /tmp/hello-collection"]
```

This approach ought to be compatible with any of the currently supported artifact back ends.
