### ISSUE TITLE
A failed step in a template with parallelism will not complete

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#868]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:

The following workflow will never complete:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallelism-failed-step-
spec:
  entrypoint: parallelism-failed-step
  templates:
  - name: parallelism-failed-step
    parallelism: 2
    steps:
    - - name: sleep
        template: sleep
        arguments:
          parameters:
          - name: exit-code
            value: "{{item}}"
        withItems:
        - 0
        - 1
        - 0

  - name: sleep
    inputs:
      parameters:
      - name: exit-code
    container:
      image: alpine:latest
      command: [sh, -c, "exit {{inputs.parameters.exit-code}}"]
```

Somehow the controller is skipping the re-evaluation of the object even when restarted.

**Environment**:
- Argo version: v2.1.0

**Comment by jessesuen** [comment]
Does not seem to affect dag templates. This behaves expectedly:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallelism-failed-dag-
spec:
  entrypoint: parallelism-failed-dag
  templates:
  - name: parallelism-failed-dag
    parallelism: 2
    dag:
      tasks:
      - name: A
        template: pass
      - name: B
        dependencies: [A]
        template: pass
      - name: C
        dependencies: [A]
        template: pass
      - name: D
        dependencies: [A]
        template: fail
      - name: E
        dependencies: [A]
        template: pass
      - name: F
        dependencies: [B, C, D, E]
        template: pass

  - name: pass
    container:
      image: alpine:3.7
      command: [sh, -c, exit 0]

  - name: fail
    container:
      image: alpine:3.7
      command: [sh, -c, exit 1]
```
