### ISSUE TITLE
Workflow step doesn't exit when sidecar container is running

### ISSUE THREAD

**Issue by pdilyard** [argoproj/argo#879]
**Bug report**

**What happened**: I have some tests that rely on a running Postgres container that I started as a sidecar. The tests complete successfully, but the workflow step does not stop (it just infinitely says "Running"). If I take away the Postgres sidecar, the tests fail but the step exits and argo works correctly.

**What you expected to happen**: When the command passed to the main container exits, the sidecar should terminate.

**How to reproduce it (as minimally and precisely as possible)**: 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-bug-
spec:
  entrypoint: hello

  templates:
  - name: hello
    steps:
    - - name: demo
        template: demo
    - - name: should-run-but-doesnt
        template: should-run-but-doesnt

  - name: demo
    container:
      image: ubuntu:18.04
      command: [/bin/bash, -c]
      args: [ "echo 'Complete, workflow should now move on from this step'" ]
    sidecars:
    - name: postgres
      image: postgres:9.6

  - name: should-run-but-doesnt
    container:
      image: ubuntu
      command: [/bin/bash, -c]
      args: [" echo 'This workflow step should run once the previous one is complete, but it does not.' "]
```

Submit this workflow, note that Argo never gets to the `should-run-but-doesnt` step. Comment out the `sidecars:` part, and the entire thing completes as expected.

**Environment**:
- Argo version:
```
argo: v2.1.0
  BuildDate: 2018-05-01T20:03:06Z
  GitCommit: 9379638189cc194f1b34ff7295f0832eac1c1651
  GitTreeState: clean
  GitTag: v2.1.0
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-04-13T22:27:55Z
  compiler: gc
  gitCommit: d4ab47518836c750f9949b9e0d387f20fb92260b
  gitTreeState: clean
  gitVersion: v1.10.1
  goVersion: go1.9.5
  major: "1"
  minor: "10"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-02-16T18:26:58Z
  compiler: gc
  gitCommit: 6e5b33a290a99c067003632e0fd6be0ead48b233
  gitTreeState: clean
  gitVersion: v1.8.8-gke.0
  goVersion: go1.8.3b4
  major: "1"
  minor: 8+
  platform: linux/amd64
```
