### ISSUE TITLE
Does Argo support Ceph as Artifactory? 

### ISSUE THREAD

**Issue by StAugust** [argoproj/argo#884]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
No documents on how to configure Ceph as Artifactory. 
**What you expected to happen**:
Tutorials on how to configure Ceph as Artifactory.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version: 
```
  argo: v2.1.1
  BuildDate: 2018-05-29T20:39:36Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
clientVersion:
  buildDate: 2018-04-19T00:05:56Z
  compiler: gc
  gitCommit: dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92
  gitTreeState: clean
  gitVersion: v1.9.7
  goVersion: go1.9.3
  major: "1"
  minor: "9"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-04-18T23:58:35Z
  compiler: gc
  gitCommit: dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92
  gitTreeState: clean
  gitVersion: v1.9.7
  goVersion: go1.9.3
  major: "1"
  minor: "9"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                artifact-passing-6pvtz
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             child 'artifact-passing-6pvtz-4259257710' failed
Created:             Tue Jun 12 02:38:34 +0000 (14 seconds ago)
Started:             Tue Jun 12 02:38:35 +0000 (13 seconds ago)
Finished:            Tue Jun 12 02:38:35 +0000 (13 seconds ago)
Duration:            0 seconds

STEP                       PODNAME                            DURATION  MESSAGE
 ✖ artifact-passing-6pvtz                                               child 'artifact-passing-6pvtz-4259257710' failed
 └---⚠ generate-artifact   artifact-passing-6pvtz-4259257710  0s        controller is not configured with a default archive location
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```
