### ISSUE TITLE
Deleted pods in k8s needs to be handled in argo.

### ISSUE THREAD

**Issue by VenkataKarthikP** [argoproj/argo#893]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG Report
**What happened**:

When underlying pod is deleted in k8s. Argo retry node is not spawning new node even if re-try attempts are left.

**What you expected to happen**:

Controller should treat deleted pods as errors and continue with either creating new pod or mark retry node as error appropriately. 

**How to reproduce it (as minimally and precisely as possible)**:
Delete pod in retry node manually in k8s.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```

- Kubernetes version :
```
kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-22T05:40:13Z
  compiler: gc
  gitCommit: 32ac1c9073b132b8ba18aa830f46b77dcceb0723
  gitTreeState: clean
  gitVersion: v1.10.5
  goVersion: go1.9.7
  major: "1"
  minor: "10"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-02-07T11:55:20Z
  compiler: gc
  gitCommit: d2835416544f298c919e2ead3be3d0864b52323b
  gitTreeState: clean
  gitVersion: v1.9.3
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:

```
~$ argo get cmg-1529802060
Name:                cmg-1529802060
Namespace:           ml-prod
ServiceAccount:      default
Status:              Running
Created:             Sat Jun 23 18:01:22 -0700 (1 day ago)
Started:             Sat Jun 23 18:01:22 -0700 (1 day ago)
Duration:            1 days 18 hours 37 minutes 52 seconds
STEP                                            PODNAME                                          DURATION  MESSAGE
 ● cmg-1529802060
 ├---✔ model-gen-prep
 |   ├-✖ model-gen-prep(0)                      cmg-1529802060-3308568300  16m       failed with exit code 1
 |   └-✔ model-gen-prep(1)                      cmg-1529802060-1630659305  58m
 └-·-✖ model-gen-training(0:demo:f18_34)                                                                   No more retries left
   | ├-✖ model-gen-training(0:demo:f18_34)(0)   cmg-1529802060-2253993419  10m       failed with exit code 1
   | ├-✖ model-gen-training(0:demo:f18_34)(1)   cmg-1529802060-2858134798  53m       failed with exit code 1
   | ├-✖ model-gen-training(0:demo:f18_34)(2)   cmg-1529802060-2455619037  13s       failed with exit code 1
   | ├-✖ model-gen-training(0:demo:f18_34)(3)   cmg-1529802060-2791318512  7m        failed with exit code 1
   | ├-⚠ model-gen-training(0:demo:f18_34)(4)   cmg-1529802060-241370687   1d        pod deleted
   | ├-✖ model-gen-training(0:demo:f18_34)(5)   cmg-1529802060-845512066   11m       failed with exit code 1
   | ├-✖ model-gen-training(0:demo:f18_34)(6)   cmg-1529802060-711438209   2m        failed with exit code 1
   | ├-✖ model-gen-training(0:demo:f18_34)(7)   cmg-1529802060-2389347204  14m       failed with exit code 1
   | ├-✖ model-gen-training(0:demo:f18_34)(8)   cmg-1529802060-2792157155  15m       failed with exit code 1
   | ├-✖ model-gen-training(0:demo:f18_34)(9)   cmg-1529802060-2322530918  13s       failed with exit code 1
   | └-✖ model-gen-training(0:demo:f18_34)(10)  cmg-1529802060-3910701520  10m       failed with exit code 1
   ├-✔ model-gen-training(10:demo:f21_49)(0)    cmg-1529802060-1436784580  1h
   ├-✔ model-gen-training(11:demo:f21_99)(0)    cmg-1529802060-1954071774  1h
   ├-● model-gen-training(1:demo:f18_49)
   | ├-✖ model-gen-training(1:demo:f18_49)(0)   cmg-1529802060-3705857692  11m       failed with exit code 1
   | └-⚠ model-gen-training(1:demo:f18_49)(1)   cmg-1529802060-3101716313  1d        pod deleted
   ├-✔ model-gen-training(2:demo:f18_99)(0)     cmg-1529802060-485286116   1h
   ├-✔ model-gen-training(3:demo:m18_34)(0)     cmg-1529802060-3915130641  1h
   ├-✔ model-gen-training(4:demo:m18_49)(0)     cmg-1529802060-3246018548  1h

```

<img width="471" alt="screen shot 2018-06-25 at 10 02 17 am" src="https://user-images.githubusercontent.com/11186040/41892104-cfbda0f8-78cb-11e8-8228-6b230841c276.png">
