### ISSUE TITLE
[Request] Adding Exit handler on step level

### ISSUE THREAD

**Issue by hongkunyoo** [argoproj/argo#910]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

**What happened**:
In document, [exit-handler](https://github.com/argoproj/argo/blob/master/examples/README.md#exit-handlers) provides the ability to check *workflow level* status.

Is it possible to check *step level (or DAG)* status after finishing each steps?

For example,
```yaml
 templates:
  - name: workflow-name
    steps:
    - - name: generate
        template: whalesay
        onExit: exit-handler  # adding Exit handler on step (DAG) level
    - - name: print
        template: print-message
```

If there is an alternative way to accomplish this feature, please let me know.
