### ISSUE TITLE
[Feature Request] global artifacts accessibility

### ISSUE THREAD

**Issue by godleon** [argoproj/argo#931]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature request

**What happened**:
Global artifacts cannot be used in a template which is referenced in a `step` template.

**What you expected to happen**:
Global artifacts can be used just like the parameter does.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:39:36Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-06T08:13:03Z
  compiler: gc
  gitCommit: 5ca598b4ba5abb89bb773071ce452e33fb66339d
  gitTreeState: clean
  gitVersion: v1.10.4
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-06-06T08:00:59Z
  compiler: gc
  gitCommit: 5ca598b4ba5abb89bb773071ce452e33fb66339d
  gitTreeState: clean
  gitVersion: v1.10.4
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Comment by jessesuen** [comment]
Duping this to issue #931

**Comment by gaetansnl** [comment]
@jessesuen Is it possible to have an example ? I can't make it work
```yaml
spec:
  entrypoint: ci
  arguments:
    artifacts:
      - name: repository
        git: ...
```
When I try to use it
```yaml
  templates:
    - name: ci
      steps:
        - - name: build
            template: build

    - name: build
      inputs:
        artifacts:
          - name: repository
            path: /repository
```
I get `invalid spec: templates.build inputs.artifacts.repository was not supplied"`. But I can't find a way to supply it via `from` or by another way
