### ISSUE TITLE
Cannot use Global Parameters

### ISSUE THREAD

**Issue by bappr** [argoproj/argo#940]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

**What happened**:
Following this example: https://github.com/argoproj/argo/blob/master/examples/global-parameters.yaml, I am not able to retrieve the global parameter.
When running `argo submit`, I get the following error ```2018/08/09 11:55:30 ./gcp-pv-snapshot.yaml failed to parse: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"workflow.parameters.REGISTRYSECRET":interface {}(nil)}```

**What you expected to happen**:
I should not get the error.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gcp-pv-snapshot-
spec:
  entrypoint: snapshot
  arguments:
    parameters:
      - name: REGISTRYSECRET
        value: regsecret
  imagePullSecrets:
    - name: {{workflow.parameters.REGISTRYSECRET}}
  templates:
  - name: snapshot
    steps:
    - - name: exec-snapshot
        template: exec-snapshot
  - name: exec-snapshot
    inputs:
      parameters:
      - name: IMAGETAG
        value: ac2a4d2b4
    container:
      image: kintocloud.azurecr.io/gcp-pv-snapshot:{{inputs.parameters.IMAGETAG}}
```

**Anything else we need to know?**:
Quoting `{{workflow.parameters.REGISTRYSECRET}}` does not work as well.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd6
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-27T22:29:25Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-05-31T18:32:23Z
  compiler: gc
  gitCommit: 9b5b719c5f295c99de68ffb5b63101b0e0175376
  gitTreeState: clean
  gitVersion: v1.9.7-gke.3
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```
