### ISSUE TITLE
Step level memoization

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo#944]
FEATURE REQUEST:

When using Argo for ML, data caching would be an very useful feature. 

For instance: 
- Workflow 1 starts
- Workflow 1 executes container image 5 as its 10th step. 
- Argo somehow would be able to figure out whether container image 5 already executed with the exact same inputs previously. (It could have been as part of another workfow).  
- If the same image was already executed with the same inputs, the output of the previous execution would be reused, the image would not be re-executed. 
- If the container is storing data in an artifact repository, the old data would somehow be associated with the old (completed) as well as the new (bypassed) execution. 

Is this something that Argo would support? 

If not, would you have suggestions/ideas on whether it would be possible to support this use case? Would need necessarily require big changes to Argo? Or do you think there is a way to support this with the current implementation?

**Comment by DSchmidtDev** [comment]
@vicaire It's an interesting feature but I'm not sure if thats something Argo will offer.
But if you need the feature in near future you could have a look at [Pachyderm](https://github.com/pachyderm/pachyderm) which tries to improve the processing with caching and special data management.

**Comment by vicaire** [comment]
DSchmidtDev@, ideally, we would like something that is integrated with Argo. We would also like the caching logic to be separate from the containers that handle the ML computations.

**Comment by chartinmarrel** [comment]
+1. We use Luigi and consider migrating to Argo.
Luigi is "able to figure out whether container image 5 already executed with the exact same inputs previously. (It could have been as part of another workfow)" and it would be great if Argo provides it as well.

**Comment by alexec** [comment]
What is the goal please - to execute workflows faster by not running steps that have already been computed?

**Comment by antoniomo** [comment]
While the goal to execute faster is part of it, it also involves better resource usage and the ability to use Argo as a generic ETL/Data/ML workflow engine. Some workflows might be really costly in time and money, say workflows that require GPU and big CPU/RAM requirements, and might take several hours to compute.

**Comment by andrewgeller** [comment]
Would you consider calling this feature _[memoization](https://en.wikipedia.org/wiki/Memoization)_ instead of _data caching_?

**Comment by alexec** [comment]
Can I propose a new name for this issue - "step memoizing"? I think it captures the problem and potential solution in a way that makes it easy to to understand. 

E.g. "Reduce cost and workflow execution time by memoizing previously run steps"?

This is a large feature as we'd need a data store to memoize the results.

**Comment by terrytangyuan** [comment]
+1 to step memoizing

**Comment by ecurtin2** [comment]
This is something I've been manually implementing in the container's logic itself. For ML workflows in particular, I've been resorting to checking if the output dataset exists then exit early. Wonder if a simple solution to some of this problem is something like

```
mytask:
   - name: data-stuff
     when:
        - pathNotExists:
             - s3://mybucket/key1
             - s3://mybucket/key2
```
For example, it'd be really lovely to do stuff like this to check for the existence of spark's `_SUCCESS` files for big ETL job caching

**Comment by alexec** [comment]
See #1054

**Comment by foobarbecue** [comment]
@ecurtin2 I'm doing the same, on an NFS share volume. Manually checking at each step whether the output exists and skipping the step if it does. It would be great to have a solution built-in to Argo.

**Comment by alexec** [comment]
See #3066

**Comment by jessesuen** [comment]
Had some discussion about this. This is how we propose this feature will will work:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: memoize-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: hello world

  templates:
  - name: whalesay
    memoize:
      maxAge: 3d
      cache:
        configMapName: whalesay-cache
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 10; cowsay {{inputs.parameters.message}} > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello
        valueFrom:
          path: /tmp/hello_world.txt

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: whalesay-cache
data:
  # cache key would be hash combination of:
  # - template definition
  # - inputs
  # allows cache to be invalidated if template changes or inputs change
  whalesay.abc123def4567890: |
    {
      "exipiresAt":"2020-06-18T17:11:05Z",
      "nodeID":"memoize-abx4124-123129321123", # do we need this?
      "outputs":
        {
          "parameters":
            [
              {
                "name":"hello",
                "value":"hello world"
              }
            ]
        }
    }
```

**Comment by jessesuen** [comment]
Future improvements would include:

1. syntax to allow this to happen for all steps of the workflow (i.e. spec.memoize)
2. ability to control what inputs can control the cache key (e.g. allowing only some of the N inputs to affect the cache key, and ignore others)
3. ability to use other stores as a cache (other than a ConfigMap), e.g. redis

**Comment by ecurtin2** [comment]
I'd like to comment that I think being able to use an artifact-like store for this is particularly useful for me. We are often doing ETL + ML tasks that are long-lived and in namespaced deployments of workflows, and every once in a while depend on external tasks. If there was a way to maybe do some sort of cache key as a file artifact I think it could really help. 


In your example I'm thinking of something like 


```yaml
  - name: whalesay
    memoize:
      cache:
        key: "{{memoize.template}}-{{memoize.params}}" 
        ~OR~
        key: ""   # Spark does empty _SUCCESS files so we can skip in that circumstance
        artifact:
          s3:
            endpoint: aws.whateveritis.com
            bucket: my-bucket-name
            key: path/in/bucket

```

I am not familiar with the internals of Argo so am not sure if this is hard for some reason I don't understand.
