### ISSUE TITLE
Default Artifact Repository and Unique Name

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo#953]
FEATURE REQUEST:

We would like to use the default artifact repository when running an Argo workflow but unfortunately the path used for each workflow is not unique (workflow.name/pod.name) because K8 only guarantees unique names for resources that are currently managed by K8.

Would it be possible to have the option to change the path to {{workflow.uid}}/{{pod.uid}} or {{workflow.uid}}/{{pod.name}} to avoid collisions?

**Comment by jessesuen** [comment]
You're right, workflow name/pod name is not unique enough. I think we should introduce a config in the configmap for this, letting the user to decide other fields to incorporate into the artifact path.  {{workflow.name}} should also be available. There already exists a field keyPrefix in the configmap which allows users to use a sub path. We just need to allow variables to be used there. For example:

```
    artifactRepository:
      s3:
        bucket: my-bucket
        endpoint: argo-artifacts-minio.default:9000
        keyPrefix: my-argo-artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}
```
