### ISSUE TITLE
Cannot download artifacts from S3 using argo ui

### ISSUE THREAD

**Issue by max-radin** [argoproj/argo#955]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:
When clicking on the download button for an artifact in the Argo UI, nothing happened.

**What you expected to happen**:
I expected the artifact to be downloaded.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a workflow that saves an artifact to S3 using an AWS IAM role for authentication.
2. Click on the button to download the artifact in the Argo UI.

**Anything else we need to know?**:
Looking at [app.ts](https://github.com/argoproj/argo-ui/blob/master/src/api/app.ts#L101), I suspect the problem is related to the Argo UI trying to get S3 access credentials from a kubernetes secret. My cluster uses AWS IAM roles rather than secret keys for accessing S3.

**Environment**:
- Argo version:
```
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-05-21T09:17:39Z
  compiler: gc
  gitCommit: 2bba0127d85d5a46ab4b778548be28623b32d0b0
  gitTreeState: clean
  gitVersion: v1.10.3
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-05-28T20:13:43Z
  compiler: gc
  gitCommit: 2bba0127d85d5a46ab4b778548be28623b32d0b0
  gitTreeState: clean
  gitVersion: v1.10.3
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

Every time I click on the download button, a line like this one is printed to the argo-ui logs:

    (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 30): TypeError: Cannot read property '' of undefined
