### ISSUE TITLE
Workflow RBAC aggregation to admin/edit/view cluster roles

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#960]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

Today, when installing argo, a namespace admin cannot do anything on a workflow object. To allow a namespace admin the ability to manage custom resources, we need to aggregate upwards to the admin, edit, and view roles. This is done using the `rbac.authorization.k8s.io/aggregate-to-XXX` label. For example:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
```
