### ISSUE TITLE
cannot set directory input artifact to be 0777

### ISSUE THREAD

**Issue by wanghong230** [argoproj/argo#972]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened**:
The artifact(directory) loaded  from S3, the permission is not set properly

```
    inputs:
      artifacts:
      - name: kops-state-tar
        path: /home/iks/kops
        mode: 0777
      - name: iks-state-tar
        path: /home/iks/iks
        mode: 0777
      - name: kube-admin-config
        path: /home/iks/kubeconfig
        mode: 0777
```

```
~ $ ls -lh
total 8
drw-rw-rw-    2 104      nobody        52 Aug 29 03:56 iks
drw-rw-rw-    6 104      nobody       101 Aug 29 03:56 kops
-rw-rw-rw-    1 104      nobody      5.7K Aug 29 03:49 kubeconfig
```

The artifact is set with permission with 0777 in the workflow definition, however, the directory is set to be 0666. Without x in the directory, we cannot access anything from the directory.

One thing I notice is the argo logic actually set the permission to be 438(0666).

```artifacts:\n  - mode: 438\n```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```
