### ISSUE TITLE
[Script] failed to save outputs: verify serviceaccount default:default has necessary privileges

### ISSUE THREAD

**Issue by bappr** [argoproj/argo#983]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REQUEST

**What happened**:
Got an error when trying to use `script` in my workflow.
```
Name:                scriptmm2nm
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             child 'scriptmm2nm-2223370800' failed
Created:             Thu Sep 06 10:46:47 +0800 (13 seconds ago)
Started:             Thu Sep 06 10:46:47 +0800 (13 seconds ago)
Finished:            Thu Sep 06 10:46:51 +0800 (9 seconds ago)
Duration:            4 seconds

STEP            PODNAME                 DURATION  MESSAGE
 ✖ scriptmm2nm                                    child 'scriptmm2nm-2223370800' failed
 └---⚠ script   scriptmm2nm-2223370800  3s        failed to save outputs: verify serviceaccount default:default has necessary privileges
```

**What you expected to happen**:
Should run the script without error.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: script
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: script
        template: script
  - name: script
    script:
      image: alpine:latest
      command: ["sh"]
      source: |
        echo test
    metadata:
      labels:
        workflowId: test
```
`argo submit`

**Anything else we need to know?**:
I even assign role `cluster-admin` to `default` service-account.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-27T22:29:25Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-08-02T23:42:40Z
  compiler: gc
  gitCommit: 9b635efce81582e1da13b35a7aa539c0ccb32987
  gitTreeState: clean
  gitVersion: v1.9.7-gke.5
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```

**Comment by David-Development** [comment]
Any updates on this? I'm encountering the same issue on a brand new bare mental kubernetes (rke) cluster. It looks like that this issue might be related to #982 

As mentioned in #982 the following workaround works (on RKE)
```bash
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default
```

**Comment by mysteryHJJ** [comment]
I have the same issue，but it looks like 
```
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default
```
doesn't work

**Comment by jessesuen** [comment]
Here are a set of minimal privileges needed by a workflow pod:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
```

Issue https://github.com/argoproj/argo/issues/1072 has been filed to eliminate `get secrets` as a required rule.

**Comment by smartnose** [comment]
I am hitting a similar issue, although I'm not entirely sure whether I've granted enough permission for Argo worker. Here is the output log from the workflow pod:

```
$ kubectl logs dom-backtestingnccw2-1662167784 -c wait
time="2018-12-27T22:31:26Z" level=info msg="Creating a docker executor"
time="2018-12-27T22:31:26Z" level=info msg="Executor (version: v2.2.0, build_date: 2018-08-30T08:52:54Z) initialized with template:\narchiveLocation: {}\ninputs:\n  parameters:\n  - name: task-id\n    value: 5349f7c0fc57485eb1e1ba3bae5b0e67\nmetadata: {}\nname: task-tpl\noutputs: {}\nscript:\n  command:\n  - sh\n  image: 551896635143.dkr.ecr.us-west-2.amazonaws.com/zoml/zmlflow:weil-workflow\n  imagePullPolicy: Always\n  name: \"\"\n  resources: {}\n  source: |\n    /opt/program/argo_entry 5349f7c0fc57485eb1e1ba3bae5b0e67\n"
time="2018-12-27T22:31:26Z" level=info msg="Waiting on main container"
time="2018-12-27T22:31:26Z" level=warning msg="Failed to get pod 'dom-backtestingnccw2-1662167784': pods \"dom-backtestingnccw2-1662167784\" is forbidden: User \"system:serviceaccount:default:default\" cannot get pods in the namespace \"default\""
time="2018-12-27T22:31:26Z" level=info msg="No sidecars"
time="2018-12-27T22:31:26Z" level=info msg="No output artifacts"
time="2018-12-27T22:31:26Z" level=info msg="No output parameters"
time="2018-12-27T22:31:26Z" level=info msg="Capturing script output"
time="2018-12-27T22:31:26Z" level=warning msg="Failed to get pod 'dom-backtestingnccw2-1662167784': pods \"dom-backtestingnccw2-1662167784\" is forbidden: User \"system:serviceaccount:default:default\" cannot get pods in the namespace \"default\""
time="2018-12-27T22:31:26Z" level=info msg="Alloc=3511 TotalAlloc=9747 Sys=9030 NumGC=3 Goroutines=5"
time="2018-12-27T22:31:26Z" level=fatal msg="pods \"dom-backtestingnccw2-1662167784\" is forbidden: User \"system:serviceaccount:default:default\" cannot get pods in the namespace \"default\"\ngithub.com/argoproj/argo/errors.Wrap\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:87\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:70\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).getPod\n\t/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:504\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).GetMainContainerStatus\n\t/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:546\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).GetMainContainerID\n\t/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:563
```

**Comment by cameronbraid** [comment]
> check the wait container logs to see what the issue really is.

Thanks for this hint.

My issue was that a hostPath volume couldn't be mounted.

**Comment by jessesuen** [comment]
Will use this bug to improve error message.

**Comment by kevinpauli** [comment]
@jessesuen I created that `workflow-role` yaml you posted:

```$ kubectl apply -f workflow-role.yaml 
role.rbac.authorization.k8s.io/workflow-role created```

But `artifact-passing` still fails with the same error message... what else do I need to do?

**Comment by jdclarke5** [comment]
I saw a similar message arising from a pod running in a non-default namespace (call it `mynamespace`). The error message was therefore accurate and the default service account needs to be given the appropriate role. The role binding is given below (since google brought me here it might be useful to somebody else).

```yaml
# Argo artifacts require the mynamespace default user to have appropriate privileges
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: artifact-role
  namespace: mynamespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: artifact-role-binding
  namespace: mynamespace
roleRef:
  kind: Role
  name: artifact-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: training
```
