### ISSUE TITLE
[Script] Does not work if command has multiple values

### ISSUE THREAD

**Issue by bappr** [argoproj/argo#986]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
Template below does not work.
`sh: /argo/staging/script: Permission denied`

**What you expected to happen**:
It should work.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-bash-
spec:
  entrypoint: main
  serviceAccountName: default
  templates:
  - name: main
    steps:
    - - name: generate
        template: generate
    - - name: print
        template: print
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate.outputs.result}}"
  - name: generate
    script:
      image: alpine:latest
      command:
      - "sh"
      - "-c"
      source: |
        cat /dev/urandom | od -N2 -An -i | awk -v f=1 -v r=100 '{printf "%i\\n", f + r * $1 / 65536}'
  - name: print
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command:
      - "sh"
      - "-c"
      args:
      - "echo result was: {{inputs.parameters.message}}"
```

`argo submit`

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-27T22:29:25Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-08-02T23:42:40Z
  compiler: gc
  gitCommit: 9b635efce81582e1da13b35a7aa539c0ccb32987
  gitTreeState: clean
  gitVersion: v1.9.7-gke.5
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```
